samseg-long. Added lesion options

diff --git a/samseg/samseg-long b/samseg/samseg-long
--- a/samseg/samseg-long
+++ b/samseg/samseg-long
@@ -23,6 +23,9 @@ set Resample = 1;
 set Interp = cubic
 set preprocdir = longpreproc
 set OptionsFile = ()
+set Lesion = 0
+set LesionMaskPattern = ()
+set LesionMaskStructure = ()
 set KeepHistory = 0
 
 # These are preprocessing options
@@ -119,6 +122,9 @@ if(! $Resample) then
 endif
 if($SaveWarp) set cmd = ($cmd --save-warp)
 if($SavePosteriors) set cmd = ($cmd --save-posteriors)
+if($Lesion)               set cmd = ($cmd --lesion)
+if($#LesionMaskStructure) set cmd = ($cmd --lesion-mask-structure $LesionMaskStructure)
+if($#LesionMaskPattern)   set cmd = ($cmd --lesion-mask-pattern   $LesionMaskPattern)
 if($#OptionsFile) set cmd = ($cmd --options $OptionsFile)
 set tmpstr = `printf %03d $#tplist`
 set tst = $outdir/tp$tmpstr/samseg.csv
@@ -394,6 +400,34 @@ while( $#argv != 0 )
       exit 0
       breaksw
 
+    case "--lesion":
+      set Lesion = 1
+      breaksw
+
+    case "--lesion-mask-structure":
+      if($#argv < 1) goto arg1err;
+      set LesionMaskStructure = $argv[1]; shift;
+      set Lesion = 1
+      breaksw
+
+    case "--lesion-mask-pattern":
+      if($#argv < 1) goto arg1err;
+      set mlist = ()
+      while(1)
+        set mlist = ($mlist $argv[1]); shift;
+        if($#argv == 0) break;
+        set dd = `echo $argv[1] | cut -c1-2`
+        if("$dd" == "--") break;
+      end
+      if($nmodes == 0) set nmodes = $#mlist
+      if($#mlist != $nmodes) then
+        echo "ERROR: lesion mask pattern has $#mlist items, expecting $nmodes"
+        exit 1;
+      endif
+      set LesionMaskPattern = ($mlist)
+      set Lesion = 1
+      breaksw
+
     # These options below are for preprocessing
     case "--i":
       if($#argv < 1) goto arg1err;
@@ -576,6 +610,12 @@ if($#basemodenames) then
   set umodenames = ($basemodenames)
 endif
 
+if($#LesionMaskPattern) then
+  if($#LesionMaskPattern != $#umodenames) then
+    echo "ERROR: lesion mask pattern has $#LesionMaskPattern but there are $#umodenames modes"
+    exit 1
+  endif
+endif
 
 goto check_params_return;
 ############--------------##################
