Added --long option to do longitudinal analysis

diff --git a/samseg/samseg b/samseg/samseg
--- a/samseg/samseg
+++ b/samseg/samseg
@@ -37,6 +37,9 @@ set UseFLAIR = 0;
 set modenamelist = ()
 set refmodename = ();
 set SaveMesh = 0
+set optionsfile = ()
+set longitudinal = 0;
+set basedir = ()
 
 set inputargs = ($argv);
 set PrintHelp = 0;
@@ -118,9 +121,25 @@ if($DoImport) then
 endif
 
 #========================================================
+if($longitudinal) then
+  set regmat = $basedir/template_coregistrationMatrices.mat
+  set optionsfile = $outdir/long.options
+  echo '{\
+    "modelSpecifications": {\
+        "atlasFileName": "meshpath"\
+    },\
+    "optimizationOptions": {\
+        "multiResolutionSpecification": [{\
+            "atlasFileName": "meshpath",\
+            "targetDownsampledVoxelSpacing": 1.0\
+        }]\
+    }\
+   }' | sed "s@meshpath@$meshpath@g" > $optionsfile
+endif
 
 set cmd0 = (run_samseg -o $outdir --threads $threads)
 if($SaveMesh) set cmd0 = ($cmd0 --save-mesh)
+if($#optionsfile) set cmd0 = ($cmd0 --options $optionsfile)
 if($#regmat)  set cmd0 = ($cmd0 --reg-mat $regmat)
 if($#initlta) set cmd0 = ($cmd0 --init-lta $initlta)
 if($regonly) set cmd0 = ($cmd0 --reg-only);
@@ -436,6 +455,29 @@ while( $#argv != 0 )
       set DoDecimate = 0; # for recon-all
       breaksw
 
+    case "--options":
+      if($#argv < 1) goto arg1err;
+      set optionsfile = $argv[1]; shift;
+      if(! -e $optionsfile) then
+        echo "ERROR: cannot find $optionsfile"
+        exit 1;
+      endif
+      breaksw
+
+    case "--long":
+      if($#argv < 1) goto arg1err;
+      set basedir = $argv[1]; shift;
+      set meshpath = $basedir/mesh.txt.gz
+      if(! -e $meshpath) then
+        echo "ERROR: cannot find $meshpath"
+        exit 1;
+      endif
+      pushd $basedir > /dev/null
+      set basedir = `pwd`;
+      popd > /dev/null
+      set longitudinal = 1;
+      breaksw
+
     case "--log":
       if($#argv < 1) goto arg1err;
       set LF = $argv[1]; shift;
@@ -575,6 +617,17 @@ else
   set coregdir  = $outdir/coreg
 endif
 
+if($longitudinal) then
+  if($#optionsfile) then 
+    echo "ERROR: cannot specify --options with --long"
+    exit 1;
+  endif
+  if($#regmat) then 
+    echo "ERROR: cannot specify --regmat with --long"
+    exit 1;
+  endif
+endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -614,6 +667,8 @@ usage_exit:
   echo " --stiffness K : mesh stiffness ($stiffness)"
   echo " --ssdd SAMSEG_DATA_DIR : where the atlas is located"
   echo " --save-mesh : save the mesh (probably for longitudinal analysis)"
+  echo " --options optionsfile : to pass to run_samseg"
+  echo " --long basedir : base for longitudinal analysis (base must have mesh)"
   echo ""
 
   if(! $PrintHelp) exit 1;
