now if SKIP_MRIS_SPHERE_1CPU_TEST is defined, then it skip the run using 1 cpu, and just runs the 8 cpu test, which is quicker and suitable for sw development

diff --git a/mris_sphere/test_mris_sphere b/mris_sphere/test_mris_sphere
--- a/mris_sphere/test_mris_sphere
+++ b/mris_sphere/test_mris_sphere
@@ -8,8 +8,8 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2014/11/03 23:13:35 $
-#    $Revision: 1.2 $
+#    $Date: 2014/11/04 18:52:06 $
+#    $Revision: 1.3 $
 #
 # Copyright © 2014 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -24,7 +24,7 @@
 # General inquiries: freesurfer@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mris_sphere,v 1.2 2014/11/03 23:13:35 nicks Exp $'
+set VERSION='$Id: test_mris_sphere,v 1.3 2014/11/04 18:52:06 nicks Exp $'
 
 umask 002
 
@@ -43,23 +43,21 @@ cd testdata
 set log = (../test_mris_sphere.log)
 if (-e $log) rm -f $log
 
-setenv OMP_NUM_THREADS 1
-set cmd=(../mris_sphere -seed 1234 rh.inflated rh.1cpu.sphere)
-echo "\n\n $cmd \n\n" |& tee -a $log
-$cmd |& tee -a $log
-if ($status != 0) then
-  echo "mris_sphere FAILED" |& tee -a $log
-  exit 1
-endif
+set threads = ( 1 8 )
+if ($?SKIP_MRIS_SPHERE_1CPU_TEST) set threads = ( 8 )
 
-setenv OMP_NUM_THREADS 8
-set cmd=(../mris_sphere -seed 1234 rh.inflated rh.8cpu.sphere)
-echo "\n\n $cmd \n\n" |& tee -a $log
-$cmd |& tee -a $log
-if ($status != 0) then
-  echo "mris_sphere FAILED" |& tee -a $log
-  exit 1
-endif
+foreach num ($threads)
+
+    setenv OMP_NUM_THREADS $num
+    set cmd=(../mris_sphere -seed 1234 rh.inflated rh.${num}cpu.sphere)
+    echo "\n\n $cmd \n\n" |& tee -a $log
+    $cmd |& tee -a $log
+    if ($status != 0) then
+        echo "mris_sphere FAILED" |& tee -a $log
+        exit 1
+    endif
+
+end
 
 echo "" |& tee -a $log
 echo "" |& tee -a $log
@@ -69,9 +67,10 @@ echo "" |& tee -a $log
 # compare expected results with actual (produced) results
 #
 
-set TEST_FILES=( rh.1cpu.sphere rh.8cpu.sphere )
-foreach tstf ($TEST_FILES)
-  set cmd=(../../mris_diff/mris_diff --debug rh.sphere $tstf);
+foreach num ($threads)
+
+  set cmd=(../../mris_diff/mris_diff \
+        --debug rh.sphere rh.${num}cpu.sphere);
   echo "\n\n $cmd \n\n" |& tee -a $log
   $cmd |& tee -a $log
   set diff_status=$status
@@ -79,6 +78,7 @@ foreach tstf ($TEST_FILES)
     echo "$cmd FAILED (exit status=$diff_status)" |& tee -a $log
     exit 1
   endif
+
 end
 
 #
