now if SKIP_MRI_EMREG_1CPU_TEST is defined, then it skip the run using 1 cpu, and just runs the 8 cpu test, which is quicker and suitable for sw development

diff --git a/mri_em_register/test_mri_em_register b/mri_em_register/test_mri_em_register
--- a/mri_em_register/test_mri_em_register
+++ b/mri_em_register/test_mri_em_register
@@ -8,8 +8,8 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2014/11/03 21:38:35 $
-#    $Revision: 1.3 $
+#    $Date: 2014/11/04 18:38:37 $
+#    $Revision: 1.4 $
 #
 # Copyright © 2014 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -24,7 +24,7 @@
 # General inquiries: freesurfer@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mri_em_register,v 1.3 2014/11/03 21:38:35 nicks Exp $'
+set VERSION='$Id: test_mri_em_register,v 1.4 2014/11/04 18:38:37 nicks Exp $'
 
 umask 002
 
@@ -43,33 +43,26 @@ cd testdata
 set log = (../test_mri_em_register.log)
 if (-e $log) rm -f $log 
 
-setenv OMP_NUM_THREADS 1
-set cmd=(../mri_em_register \
-    -uns 3 \
-    -mask brainmask.mgz \
-    nu.mgz \
-    ../../distribution/average/RB_all_2014-08-21.gca \
-    talairach.1cpu.lta)
-echo "\n\n $cmd \n\n" |& tee -a $log
-$cmd |& tee -a $log
-if ($status != 0) then
-  echo "mri_em_register FAILED" |& tee -a $log
-  exit 1
-endif
+set threads=( 1 8 )
+if ($?SKIP_MRI_EMREG_1CPU_TEST) set threads=( 8 )
 
-setenv OMP_NUM_THREADS 8
-set cmd=(../mri_em_register \
-    -uns 3 \
-    -mask brainmask.mgz \
-    nu.mgz \
-    ../../distribution/average/RB_all_2014-08-21.gca \
-    talairach.8cpu.lta)
-echo "\n\n $cmd \n\n" |& tee -a $log
-$cmd |& tee -a $log
-if ($status != 0) then
-  echo "mri_em_register FAILED" |& tee -a $log
-  exit 1
-endif
+foreach num ($threads)
+
+    setenv OMP_NUM_THREADS $num
+    set cmd=(../mri_em_register \
+        -uns 3 \
+        -mask brainmask.mgz \
+        nu.mgz \
+        ../../distribution/average/RB_all_2014-08-21.gca \
+        talairach.${num}cpu.lta)
+    echo "\n\n $cmd \n\n" |& tee -a $log
+    $cmd |& tee -a $log
+    if ($status != 0) then
+        echo "mri_em_register FAILED" |& tee -a $log
+    exit 1
+    endif
+
+end
 
 echo "" |& tee -a $log
 echo "" |& tee -a $log
@@ -79,15 +72,17 @@ echo "" |& tee -a $log
 # compare expected results with actual (produced) results
 #
 
-set TEST_FILES=( talairach.1cpu.lta talairach.8cpu.lta )
-foreach tstf ($TEST_FILES)
-  set cmd=(../../mri_robust_register/lta_diff talairach.lta $tstf);
+foreach num ($threads)
+
+  set cmd=(../../mri_robust_register/lta_diff \
+    talairach.lta talairach.${num}cpu.lta);
   echo "\n\n $cmd \n\n" |& tee -a $log
   set result = (`$cmd |& tee -a $log`)
   if ($result != 0) then
     echo "$cmd FAILED (RMS=$result)" |& tee -a $log
     exit 1
   endif
+
 end
 
 #
