new unit test of subject data (OAS1_0353_MR1) known to fail hash table search around slice 111

diff --git a/mri_aparc2aseg/test_mri_aparc2aseg b/mri_aparc2aseg/test_mri_aparc2aseg
--- a/mri_aparc2aseg/test_mri_aparc2aseg
+++ b/mri_aparc2aseg/test_mri_aparc2aseg
@@ -8,8 +8,8 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2007/02/22 00:57:42 $
-#    $Revision: 1.4 $
+#    $Date: 2007/07/03 18:50:32 $
+#    $Revision: 1.5 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -24,7 +24,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mri_aparc2aseg,v 1.4 2007/02/22 00:57:42 nicks Exp $'
+set VERSION='$Id: test_mri_aparc2aseg,v 1.5 2007/07/03 18:50:32 nicks Exp $'
 
 umask 002
 
@@ -41,8 +41,8 @@ gunzip -c testdata.tar.gz | tar xvf -
 set cmd=(./mri_aparc2aseg --s testdata --ribbon)
 echo ""
 echo $cmd
-echo "Output is directed to file 'mri_aparc2aseg.out.txt'..."
-$cmd > mri_aparc2aseg.out.txt
+echo "Output is directed to file 'test_mri_aparc2aseg.out.txt'..."
+$cmd >& test_mri_aparc2aseg.out.txt
 if ($status != 0) then
   echo "test_mri_aparc2aseg FAILED"
   exit 1
@@ -53,8 +53,8 @@ foreach tstvol ($TEST_FILES)
   # now compare expected with observed data
   set REF_VOL  = testdata/mri/reference_aparc+aseg.mgz
   set TST_VOL  = testdata/mri/$tstvol
-  set DIFF_VOL = $PWD/mri_diff-$tstvol
-  set MRIDIFFF = $PWD/mri_diff-$tstvol.txt
+  set DIFF_VOL = testdata/mri/mri_diff-$tstvol
+  set MRIDIFFF = testdata/mri/mri_diff-$tstvol.txt
   set cmd=(../mri_diff/mri_diff --debug \
             --thresh 0.0 \
             --log $MRIDIFFF \
@@ -69,11 +69,57 @@ foreach tstvol ($TEST_FILES)
   endif
 end
 
+####################################################################
+# this test is known to fail on when mri_aparc2aseg is built against
+# utils/mrishash.c v1.30-v1.33, it exits mri_aparc2aseg with ERROR msg
+#
+test2:
+if ( -e testdata2) then
+  echo "rm -Rf testdata2"
+  rm -Rf testdata2
+endif
+
+echo "gunzip -c testdata2.tar.gz | tar xvf -"
+gunzip -c testdata2.tar.gz | tar xvf -
+
+set cmd=( ./mri_aparc2aseg --s testdata2 \
+            --labelwm \
+            --hypo-as-wm \
+            --rip-unknown \
+            --o $SUBJECTS_DIR/testdata2/mri/wmparc.mgz )
+echo ""
+echo $cmd
+echo "Output is directed to file 'test_mri_aparc2aseg.out.txt'..."
+$cmd >>& test_mri_aparc2aseg.out.txt
+if ($status != 0) then
+  echo "test_mri_aparc2aseg FAILED"
+  exit 1
+endif
+
+test2diff:
+# now compare expected with observed data
+set REF_VOL  = testdata2/mri/reference_wmparc.mgz
+set TST_VOL  = testdata2/mri/wmparc.mgz
+set DIFF_VOL = testdata2/mri/mri_diff-wmparc.mgz
+set MRIDIFFF = testdata2/mri/mri_diff-wmparc.mgz.txt
+set cmd=(../mri_diff/mri_diff --debug \
+          --thresh 0.0 \
+          --log $MRIDIFFF \
+          $REF_VOL $TST_VOL --diff $DIFF_VOL);
+echo ""
+echo $cmd
+$cmd
+set diff_status=$status
+if ($diff_status != 0) then
+  echo "test_aparc2aseg $cmd FAILED (exit status=$diff_status)"
+  exit 1
+endif
+
 #
 # cleanup
 #
 cd ..
-rm -Rf testdata
+rm -Rf testdata testdata2 
 
 echo ""
 echo "test_mri_aparc2aseg passed all tests"
