added /usr/pubsw/bin to path

diff --git a/distribution/nmr-std-env b/distribution/nmr-std-env
--- a/distribution/nmr-std-env
+++ b/distribution/nmr-std-env
@@ -4,13 +4,13 @@
 #          stream: unpacking, functional, structural, and visualization.
 # Usage:   source nmr-std-env
 #
-# $Id: nmr-std-env,v 1.3 2005/03/01 23:05:14 kteich Exp $
+# $Id: nmr-std-env,v 1.4 2005/03/16 17:45:37 kteich Exp $
 #
 # NOTE: this file is under version control. Make sure to use the
 # proper check-out/check-in procedures when modifying it!
 #############################################################################
 
-set NSE_VERSION = '$Id: nmr-std-env,v 1.3 2005/03/01 23:05:14 kteich Exp $';
+set NSE_VERSION = '$Id: nmr-std-env,v 1.4 2005/03/16 17:45:37 kteich Exp $';
 echo $NSE_VERSION
 
 ## Turn on verboseness if desired ##
@@ -19,7 +19,7 @@ if($?NMR_STD_VERBOSE) then
   set verbose
 endif
 
-set VERSION = '$Id: nmr-std-env,v 1.3 2005/03/01 23:05:14 kteich Exp $';
+set VERSION = '$Id: nmr-std-env,v 1.4 2005/03/16 17:45:37 kteich Exp $';
 
 
 
@@ -50,6 +50,15 @@ endif
 
 source $FS_ENV_FILE
 
+# Source the FreeDiffusion Environment File
+set FD_ENV_FILE =  $FREESURFER_HOME/SetUpFreeDiffusion.csh
+if(! -e $FD_ENV_FILE) then
+  echo "ERROR: cannot find $FD_ENV_FILE"
+  exit 1;
+endif
+
+source $FD_ENV_FILE
+
 set this_shell    = `basename $SHELL`;
 set this_hostname = `hostname` 
 set this_host     = `basename $this_hostname .nmr.mgh.harvard.edu`
@@ -66,7 +75,7 @@ endif
 ### Dont leave huge cores around ###
 limit coredumpsize 0
 
-set path = ($path $FREESURFER_HOME/bin /usr/bin/X11 /usr/sbin /sbin)
+set path = ($path $FREESURFER_HOME/bin /usr/pubsw/bin /usr/bin/X11 /usr/sbin /sbin)
 
 
 if(! $?MRI_UMASK) then
