gifti tests

diff --git a/mris_convert/test_mris_convert b/mris_convert/test_mris_convert
--- a/mris_convert/test_mris_convert
+++ b/mris_convert/test_mris_convert
@@ -8,8 +8,8 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2007/07/31 17:42:11 $
-#    $Revision: 1.1 $
+#    $Date: 2008/02/29 22:01:27 $
+#    $Revision: 1.2 $
 #
 # Copyright (C) 2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -24,7 +24,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mris_convert,v 1.1 2007/07/31 17:42:11 nicks Exp $'
+set VERSION='$Id: test_mris_convert,v 1.2 2008/02/29 22:01:27 nicks Exp $'
 
 umask 002
 
@@ -34,7 +34,7 @@ umask 002
 gunzip -c ../mris_expand/testdata.tar.gz | tar xvf -
 
 #
-# run mris_convert, converting to ascii, then back to binary
+# run mris_convert, converting to ascii and gifti, then back to binary
 #
 
 set cmd=(./mris_convert lh.white lh.white.asc)
@@ -49,6 +49,28 @@ if ($status != 0) then
 endif
 
 set cmd=(./mris_convert lh.white.asc lh.new-white)
+echo ""
+echo $cmd
+echo $cmd >& test_mris_convert.log
+echo ""
+$cmd >>& test_mris_convert.log
+if ($status != 0) then
+  echo "mris_convert FAILED"
+  exit 1
+endif
+
+set cmd=(./mris_convert lh.white lh.white.gii)
+echo ""
+echo $cmd
+echo $cmd >& test_mris_convert.log
+echo ""
+$cmd >>& test_mris_convert.log
+if ($status != 0) then
+  echo "mris_convert FAILED"
+  exit 1
+endif
+
+set cmd=(./mris_convert lh.white.gii lh.gifti-white)
 echo ""
 echo $cmd
 echo $cmd >& test_mris_convert.log
@@ -98,6 +120,19 @@ endif
 
 set REF=(lh.white)
 set TST=(lh.new-white)
+set cmd=(../mris_diff/mris_diff --debug --thresh 0.0001 $REF $TST);
+echo ""
+echo $cmd
+echo $cmd >>& test_mris_convert.log
+$cmd >>& test_mris_convert.log
+set diff_status=$status
+if ($diff_status != 0) then
+  echo "$cmd FAILED (exit status=$diff_status)"
+  exit 1
+endif
+
+set REF=(lh.white)
+set TST=(lh.gifti-white)
 set cmd=(../mris_diff/mris_diff --debug --thresh 0.0001 $REF $TST);
 echo ""
 echo $cmd
