updated gifti support for functional time series data

diff --git a/mris_convert/test_gifti b/mris_convert/test_gifti
--- a/mris_convert/test_gifti
+++ b/mris_convert/test_gifti
@@ -8,8 +8,8 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2008/03/08 00:16:37 $
-#    $Revision: 1.3 $
+#    $Date: 2008/05/21 21:45:14 $
+#    $Revision: 1.4 $
 #
 # Copyright (C) 2008,
 # The General Hospital Corporation (Boston, MA). 
@@ -24,7 +24,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_gifti,v 1.3 2008/03/08 00:16:37 nicks Exp $'
+set VERSION='$Id: test_gifti,v 1.4 2008/05/21 21:45:14 nicks Exp $'
 
 umask 002
 
@@ -117,6 +117,22 @@ if ($status != 0) then
   exit 1
 endif
 
+# create freesurfer ascii functional scalar file from gifti
+set cmd=(./mris_convert \
+    -f rh.colin.func.gii \
+    rh.colin.fudicial.gii \
+    rh.colin.func.mgh)
+echo ""
+echo $cmd
+echo $cmd >& test_gifti.log
+echo ""
+$cmd >>& test_gifti.log
+if ($status != 0) then
+  echo "mris_convert FAILED"
+  exit 1
+endif
+
+
 #
 # compare expected results against each other and with expected result
 #
@@ -191,6 +207,7 @@ endif
 #
 end:
 rm -f lh.*
+rm -f rh.colin.*
 
 echo ""
 echo "test_gifti passed all tests"
