added error checking

diff --git a/mris_compute_lgi/mris_compute_lgi b/mris_compute_lgi/mris_compute_lgi
--- a/mris_compute_lgi/mris_compute_lgi
+++ b/mris_compute_lgi/mris_compute_lgi
@@ -14,8 +14,8 @@
 # Original Authors: Marie Schaer
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2007/11/17 01:25:08 $
-#    $Revision: 1.9 $
+#    $Date: 2007/11/18 00:21:53 $
+#    $Revision: 1.10 $
 #
 # Copyright (C) 2007,
 # The General Hospital Corporation (Boston, MA).
@@ -30,7 +30,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: mris_compute_lgi,v 1.9 2007/11/17 01:25:08 nicks Exp $'
+set VERSION = '$Id: mris_compute_lgi,v 1.10 2007/11/18 00:21:53 nicks Exp $'
 set PrintHelp = 0;
 set RunIt = 1;
 set cmdargs = ($argv);
@@ -55,6 +55,14 @@ check_params_return:
 # begin...
 #---------
 
+# check for matlab
+set MATLAB = `getmatlab`;
+if($status) then
+  echo "ERROR: Matlab is required to run mris_compute_lgi!"
+  exit 1;
+endif
+
+
 # temporary work files go here...
 set cmd=(rm -Rf $tmpdir)
 echo "================="
@@ -67,7 +75,9 @@ echo "$cmd"
 echo "================="
 if ($RunIt) $cmd
 
-
+#
+# mris_fill
+#
 # create a filled-volume from the input surface file...
 set cmd=(mris_fill -c -r 1 ${input} ${tmpdir}/${input}.filled.mgz)
 echo "================="
@@ -76,18 +86,31 @@ echo "================="
 if ($RunIt) $cmd
 
 
+#
+# make_outer_surface.m
+#
 # create the outer surface from the filled volume
 set MLF = /tmp/mos"_$$_".m
 set arg1 = ${tmpdir}/${input}.filled.mgz
 set arg2 = ${spheresize}
 set arg3 = ${tmpdir}/${input}-outer
+rm -f ${arg3}
 echo "make_outer_surface('${arg1}',${arg2},'${arg3}')" > $MLF
 echo "================="
 echo "`cat $MLF`"
 echo "================="
-if ($RunIt) cat $MLF | matlab -display iconic -nojvm -nosplash 
+if ($RunIt) cat $MLF | ${MATLAB} -display iconic -nojvm -nosplash
+echo ""
+rm -f ${MLF}
+if ( ! -e ${arg3} ) then
+  echo "ERROR: make_outer_surface did not create output file '${arg3}'!"
+  exit 1
+endif
 
 
+#
+# mris_smooth
+#
 # smooth this jaggy, tessellated surface
 set cmd=(mris_smooth -nw -n 3 \
     ${tmpdir}/${input}-outer \
@@ -98,6 +121,9 @@ echo "================="
 if ($RunIt) $cmd
 
 
+#
+# mris_convert
+#
 # output normals of the smoothed outer surface
 set cmd=(mris_convert -n \
     ${tmpdir}/${input}-outer-smoothed \
@@ -108,20 +134,31 @@ echo "================="
 if ($RunIt) $cmd
 
 
+#
+# find_corresponding_center_FSformat.m
+#
 # create ROI center files
 set MLF = /tmp/mrc"_$$_".m
 set arg1 = ${input}
 set arg2 = ${tmpdir}/${input}-outer-smoothed
 set arg3 = ${stepsize}
 set arg4 = ${tmpdir}
-echo "find_corresponding_center_FSformat('${arg1}','${arg2}',${arg3},'${arg4}')" \
-  > $MLF
+set arg5 = ${MLF}
+echo "find_corresponding_center_FSformat('${arg1}','${arg2}',${arg3},'${arg4}','${arg5}')" > $MLF
 echo "================="
 echo "`cat $MLF`"
 echo "================="
-if ($RunIt) cat $MLF | matlab -display iconic -nojvm -nosplash 
+if ($RunIt) cat ${MLF} | ${MATLAB} -display iconic -nojvm -nosplash 
+echo ""
+if ( -e ${MLF} ) then
+  echo "ERROR: find_corresponding_center_FSformat did not complete successfully!"
+  exit 1
+endif
 
 
+#
+# make_roi_paths.m
+#
 # create ROI path files
 set MLF = /tmp/mrp"_$$_".m
 set arg1 = ${input}
@@ -129,13 +166,22 @@ set arg2 = ${tmpdir}/${input}-outer-smoothed
 set arg3 = ${radius}
 set arg4 = ${stepsize}
 set arg5 = ${tmpdir}
-echo "make_roi_paths('${arg1}','${arg2}',${arg3},${arg4},'${arg5}')" > $MLF
+set arg6 = ${MLF}
+echo "make_roi_paths('${arg1}','${arg2}',${arg3},${arg4},'${arg5}','${arg6}')" > $MLF
 echo "================="
 echo "`cat $MLF`"
 echo "================="
-if ($RunIt) cat $MLF | matlab -display iconic -nojvm -nosplash 
+if ($RunIt) cat $MLF | ${MATLAB} -display iconic -nojvm -nosplash 
+echo ""
+if ( -e ${MLF} ) then
+  echo "ERROR:  make_roi_paths did not complete successfully!"
+  exit 1
+endif
 
 
+#
+# mri_path2label
+#
 # create ROI label files
 set vertices = `cat ${tmpdir}/${input}.center.vertices`
 foreach v ($vertices)
@@ -151,6 +197,9 @@ foreach v ($vertices)
 end
 
 
+#
+# compute_lgi.m
+#
 # finally, compute lGI measurements
 set MLF = /tmp/clgi"_$$_".m
 set arg1 = ${input}
@@ -159,14 +208,24 @@ set arg3 = ${tmpdir}/${input}-outer-smoothed-normals.asc
 set arg4 = ${stepsize}
 set arg5 = ${radius}
 set arg6 = ${tmpdir}
+rm -f ${tmpdir}/${input}_lgi_asc
 echo "compute_lgi('${arg1}','${arg2}','${arg3}',${arg4},${arg5},'${arg6}')" \
     > $MLF
 echo "================="
 echo "`cat $MLF`"
 echo "================="
-if ($RunIt) cat $MLF | matlab -display iconic -nojvm -nosplash 
+if ($RunIt) cat $MLF | ${MATLAB} -display iconic -nojvm -nosplash 
+echo ""
+rm -f ${MLF}
+if ( ! -e ${tmpdir}/${input}_lgi_asc ) then
+  echo "ERROR: compute_lgi did not create output file '${tmpdir}/${input}_lgi_asc'!"
+  exit 1
+endif
 
 
+#
+# mris_convert
+#
 # convert ascii file to scalar
 set cmd=(mris_convert -c \
     ${tmpdir}/${input}_lgi.asc \
