Put error trap for catching when the number of conditions in the paradigm file does not equal that specified in the analysis.

diff --git a/fsfast/bin/autoreg-fsl b/fsfast/bin/autoreg-fsl
--- a/fsfast/bin/autoreg-fsl
+++ b/fsfast/bin/autoreg-fsl
@@ -1,6 +1,6 @@
 #!/bin/tcsh -f
 
-set VERSION = '$Id: autoreg-fsl,v 1.1 2003/03/04 21:22:07 greve Exp $';
+set VERSION = '$Id: autoreg-fsl,v 1.2 2004/02/10 22:33:56 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -8,9 +8,11 @@ set funcstem  = ();
 set t1epistem = ();
 set subjectid = ();
 set regfile   = ();
-set corvol    = orig;
+set t1epiregfile = ();
+set corvol    = brain;
 set tmpdir    = ();
 set cleanup   = 1;
+set nobet     = 0;
 
 set PrintHelp = 0;
 
@@ -59,6 +61,31 @@ date            >> $LF
 
 set StartTime = `date`;
 
+# Create identity Matrix for t1epi->func init #
+set idreg = $tmpdir/identity.reg
+rm -f $idreg
+echo "1 0 0 0" >> $idreg
+echo "0 1 0 0" >> $idreg
+echo "0 0 1 0" >> $idreg
+echo "0 0 0 1" >> $idreg
+
+# Create initial reg matrix for t1epi->ref
+t1epi2anat.fsl
+set t1epi2anatfsl = $tmpdir/t1epi2ref.init.mat
+set t1epi2anattkr = $tmpdir/t1epi2anat.fsl.tkreg # needed for temp
+echo "----------------------------------------" |& tee -a $LF
+echo "Creating initial t1epi to anat ref matrix" |& tee -a $LF
+date |& tee -a $LF
+set cmd = (tkregister2 --targ $cordir --mov $t1epistem $t1epiext \
+     --regheader --reg $t1epi2anattkr --fslregout $t1epi2anatfsl \
+    --noedit --subject $subjectid);
+echo $cmd |& tee -a $LF
+$cmd |& tee -a $LF
+if($status) then
+  echo "ERROR: tkregister2 failed" |& tee -a $LF
+  exit 1;
+endif
+
 # Convert func to .img
 set funcimg = $tmpdir/func
 set cmd = (mri_convert $funcstem --in_type $funcext -f 0 \
@@ -102,41 +129,54 @@ if($status) then
 endif
 
 # Extract Brains
+if($nobet) echo "INFO: skipping brain extraction"
 foreach img ($funcimg $t1epiimg $corimg)
-  echo "----------------------------------------" |& tee -a $LF
-  echo "Betting $img" |& tee -a $LF
-  date |& tee -a $LF
-  set cmd = (bet $img.img $img-brain.img);
-  echo $cmd |& tee -a $LF
-  $cmd |& tee -a $LF
-  if($status) then
-    echo "ERROR: bet failed" |& tee -a $LF
-    exit 1;
+  if($nobet) then
+    cp $img.img $img-brain.img;
+    cp $img.hdr $img-brain.hdr;
+  else
+    echo "----------------------------------------" |& tee -a $LF
+    echo "Betting $img" |& tee -a $LF
+    date |& tee -a $LF
+    set cmd = (bet $img.img $img-brain.img);
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    set st = $status;
+    if($st) then
+      echo "ERROR: bet failed with status $st" |& tee -a $LF
+      exit 1;
+    endif
   endif
+  cp $img.mat $img-brain.mat # In general, not necessary
 end
 
 echo "----------------------------------------" |& tee -a $LF
 echo "Registering func to t1epi" |& tee -a $LF
 date |& tee -a $LF
-set cmd = (flirt -in $funcimg-brain.img -ref $t1epiimg-brain.img \
+set cmd = (flirt -init $idreg -in $funcimg-brain.img \
+           -ref $t1epiimg-brain.img \
            -omat $tmpdir/func2t1epi.mat -dof 7)
 echo $cmd |& tee -a $LF
 $cmd |& tee -a $LF
-if($status) then
-  echo "ERROR: flirt failed" |& tee -a $LF
+set st = $status;
+if($st) then
+  echo "ERROR: flirt failed with status $st" |& tee -a $LF
   exit 1;
 endif
 
 echo "----------------------------------------" |& tee -a $LF
 echo "Registering t1epi to anat ref" |& tee -a $LF
 date |& tee -a $LF
-# To add initialization, -init initreg.mat
-set cmd = (flirt -in $t1epiimg-brain.img -ref $corimg-brain.img \
-           -omat $tmpdir/t1epi2ref.mat -dof 12)
+#set cmd = (flirt -init $t1epi2anatfsl \
+set cmd = (flirt \
+           -in $t1epiimg-brain.img -ref $corimg-brain.img \
+           -omat $tmpdir/t1epi2ref.mat -dof 12 \
+           -searchrx -180 180 -searchry -180 180 -searchrz -180 180)
 echo $cmd |& tee -a $LF
 $cmd |& tee -a $LF
-if($status) then
-  echo "ERROR: flirt failed" |& tee -a $LF
+set st = $status;
+if($st) then
+  echo "ERROR: flirt failed with status $st" |& tee -a $LF
   exit 1;
 endif
 
@@ -153,15 +193,29 @@ if($status) then
 endif
 
 echo "----------------------------------------" |& tee -a $LF
-echo "Constructing registration file" |& tee -a $LF
-set cmd = (fslmat2register --fvol $funcimg.img \
-           --subject $subjectid --fslmat $tmpdir/func2ref.mat \
-           --o $regfile)
+echo "Constructing registration file for functional" |& tee -a $LF
+set cmd = (tkregister2 --mov $funcimg.img \
+           --subject $subjectid --fslreg $tmpdir/func2ref.mat \
+           --reg $regfile --noedit)
 echo $cmd |& tee -a $LF
 $cmd |& tee -a $LF
 if($status) then
-  echo "ERROR: fslmat2register failed" |& tee -a $LF
+  echo "ERROR: tkregister2 failed" |& tee -a $LF
   exit 1;
+endif
+
+if($#t1epiregfile != 0) then
+  echo "----------------------------------------" |& tee -a $LF
+  echo "Constructing registration file for t1epi" |& tee -a $LF
+  set cmd = (tkregister2 --mov $t1epiimg.img \
+             --subject $subjectid --fslreg $tmpdir/func2ref.mat \
+             --reg $t1epiregfile --noedit)
+  echo $cmd |& tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) then
+    echo "ERROR: tkregister2 failed" |& tee -a $LF
+    exit 1;
+  endif
 endif
 
 if($cleanup) then
@@ -174,7 +228,7 @@ set EndTime = `date`;
 echo "Started at $StartTime" |& tee -a $LF
 echo "Ended   at $EndTime"   |& tee -a $LF
 
-echo "acorfunc-sess done"
+echo "autoreg-fsl done"
 
 exit 0
 
@@ -207,8 +261,19 @@ while( $#argv != 0 )
       breaksw
 
     case "-r":
+    case "-rf":
       if ( $#argv < 1) goto arg1err;
       set regfile = $argv[1]; shift;
+      breaksw
+
+    case "-rt":
+      if ( $#argv < 1) goto arg1err;
+      set t1epiregfile = $argv[1]; shift;
+      breaksw
+
+    case "-corvol":
+      if ( $#argv < 1) goto arg1err;
+      set corvol = $argv[1]; shift;
       breaksw
 
     case "-sd":
@@ -219,6 +284,10 @@ while( $#argv != 0 )
     case "-tmpdir":
       if ( $#argv < 1) goto arg1err;
       set tmpdir = $argv[1]; shift;
+      breaksw
+
+    case "-nobet":
+      set nobet = 1;
       breaksw
 
     case "-nocleanup":
@@ -306,7 +375,7 @@ check_params:
     exit 1;
   endif
 
-  if($#tmpdir == NULL) set tmpdir = /tmp/autoreg-fsl-$$
+  if($#tmpdir == 0) set tmpdir = /tmp/autoreg-fsl-$$
   mkdir -p $tmpdir
   if( ! -e $tmpdir) then
     echo "ERROR: cannot find tmp dir $tmpdir"
@@ -342,9 +411,12 @@ usage_exit:
   echo "   -f funcstem  : functional stem"
   echo "   -t t1epistem : t1epi stem"
   echo "   -s subjectid : subject to register to"
-  echo "   -r regfile   : registration file"
+  echo "   -rf regfile   : registration file for functional"
+  echo "   -rt regfile   : registration file for t1epi"
   echo ""
   echo "More options"
+  echo "   -corvol volid : use volid instead of brain"
+  echo "   -nobet  : do not do brain extraction prior to reg"
   echo "   -sd subjectsdir : default is to use env SUBJECTS_DIR"
   echo "   -tmpdir tmpdir : set directory for temporary file"
   echo "   -nocleanup     : don't remove temporary files"
diff --git a/fsfast/bin/mkblockpar b/fsfast/bin/mkblockpar
--- a/fsfast/bin/mkblockpar
+++ b/fsfast/bin/mkblockpar
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 
-set VERSION = '$Id: mkblockpar,v 1.2 2003/04/18 22:10:34 greve Exp $';
+set VERSION = '$Id: mkblockpar,v 1.3 2004/02/10 22:33:56 greve Exp $';
 
 ##### Print out version info, if needed ####
 set n = `echo $argv | grep version | wc -l` 
@@ -13,6 +13,7 @@ set TR           = ();
 set nepochs      = ();
 set epoch_idlist = ();
 set nper_epoch   = ();
+set nper_epoch_list = ();
 set parname      = ();
 set t0 = 0;
 
@@ -37,8 +38,14 @@ touch $parname
 while($epoch <= $nepochs)
   @ code = $epoch_idlist[$epoch];
 
+  if($#nper_epoch_list != 0) then
+    set nper = $nper_epoch_list[$epoch];
+  else
+    set nper = $nper_epoch;
+  endif
+
   @ ntr = 0;
-  while($ntr < $nper_epoch)
+  while($ntr < $nper)
     printf "%6.3f  %3d\n" $t $code >> $parname
     set t = `echo "$t + $TR" | bc -l`;
     @ ntr = $ntr + 1;
@@ -93,6 +100,21 @@ while( $#argv != 0 )
       set nper_epoch = $1; shift;
       breaksw
 
+    case "-nperepochlist"
+    case "-npel"
+      if($#nepochs == 0) then
+        echo "ERROR: must specify number of epochs before id list"
+        exit 1;
+      endif
+      if ( $#argv < $nepochs) goto arg1err;
+      @ epoch = 0;
+      while($epoch < $nepochs)
+        set nper_epoch_list = ($nper_epoch_list $1); shift;
+        @ epoch = $epoch + 1;
+      end
+      breaksw
+      breaksw
+
     case "-par":
     case "-paradigm":
     case "-parname":
@@ -143,7 +165,7 @@ check_params:
     exit 1;
   endif
 
-  if($#nper_epoch == 0) then
+  if($#nper_epoch == 0 && $#nper_epoch_list == 0 ) then
     echo "ERROR: must specify number of TRs per epoch"
     exit 1;
   endif
diff --git a/fsfast/bin/preproc-sess b/fsfast/bin/preproc-sess
--- a/fsfast/bin/preproc-sess
+++ b/fsfast/bin/preproc-sess
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # preproc-sess - runs preprocessing (mc, spatsmooth, mkbrainmask, inorm)
 
-set VERSION = '$Id: preproc-sess,v 1.3 2003/10/01 21:54:43 greve Exp $';
+set VERSION = '$Id: preproc-sess,v 1.4 2004/02/10 22:33:56 greve Exp $';
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M'`"
@@ -16,6 +16,7 @@ set maskstem   = brain;
 set fwhm    = ();
 set fsd     = bold;
 set rlf     = ();
+set mcnthrun = ();
 set MCPerRun = 0;
 set DoMC     = 1;
 set DoSmooth = 1;
@@ -105,6 +106,7 @@ foreach sess ($SessList)
     set cmd = (mc-sess -fstem $mcinstem -fmcstem $mcoutstem -umask $umask);
     set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
     if($MCPerRun) set cmd = ($cmd -perrun)
+    if($#mcnthrun) set cmd = ($cmd -targnthrun $mcnthrun)
     if($#rlf != 0) set cmd = ($cmd -rlf $rlf);
     echo "$sessid MC -----------------------------" |& tee -a $LF
     date      |& tee -a $LF
@@ -198,6 +200,11 @@ while( $#argv != 0 )
     case "-mcout":
       if ( $#argv == 0) goto arg1err;
       set mcoutstem = $argv[1]; shift;
+      breaksw
+
+    case "-mcnthrun":
+      if ( $#argv == 0) goto arg1err;
+      set mcnthrun = $argv[1]; shift;
       breaksw
 
     case "-smin":
@@ -336,6 +343,11 @@ check_params:
     endif
   endif
 
+  if($MCPerRun && $#mcnthrun) then
+    echo "ERROR: cannot specify both -mcperrun and -mcnthrun"
+    exit 1;
+  endif
+
   if($#rlf != 0 && $MCPerRun) then
     echo "ERROR: cannot specify both -rlf and -mcperrun"
     exit 1;
@@ -365,6 +377,7 @@ usage_exit:
   echo "  -fsd    fsd <bold>"
   echo "  -rlf    rlf  : run list file (default all runs)"
   echo "  -mcperrun : perform motion correction on all runs separately"
+  echo "  -mcnthrun nthrun : use nthrun as reference"
   echo ""
   echo "  -nomc     : don't do motion correction"
   echo "  -nosmooth : don't do smoothing"
diff --git a/fsfast/bin/selxavg-sess b/fsfast/bin/selxavg-sess
--- a/fsfast/bin/selxavg-sess
+++ b/fsfast/bin/selxavg-sess
@@ -1,8 +1,8 @@
 #!/bin/csh -f
 # selxavg-sess
 #
-# $Id: selxavg-sess,v 1.5 2003/09/08 17:40:09 greve Exp $
-set VERSION = '$Id: selxavg-sess,v 1.5 2003/09/08 17:40:09 greve Exp $';
+# $Id: selxavg-sess,v 1.6 2004/02/10 22:33:56 greve Exp $
+set VERSION = '$Id: selxavg-sess,v 1.6 2004/02/10 22:33:56 greve Exp $';
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 set inputargs = ($argv);
@@ -71,6 +71,7 @@ set fsd       = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
 set funcstem  = `cat $infofile | awk '{if($1 == "funcstem") print $2}'`;
 set maskstem  = `cat $infofile | awk '{if($1 == "maskstem") print $2}'`;
 set parname   = `cat $infofile | awk '{if($1 == "parname") print $2}'`;
+set ncond     = `cat $infofile | awk '{if($1 == "nconditions") print $2}'`;
 set tpexclude = `cat $infofile | awk '{if($1 == "tpexclude") print $2}'`;
 set runlistfile = `cat $infofile | awk '{if($1 == "runlistfile") print $2}'`;
 set designtype = `cat $infofile | awk '{if($1 == "designtype") print $2}'`;
@@ -218,6 +219,7 @@ foreach sess ($SessList)
   set whtnmtx = ();
   foreach run ($RunList)  
     set instem = $run/$funcstem
+    set pars = ($pars $run/$parname);
 
     set tpexarg = ();
     if($#tpexclude != 0) then
@@ -233,7 +235,18 @@ foreach sess ($SessList)
     if($WhitenFlag) set whtnmtx = ($whtnmtx -whtnmtx $analysis/tcvm$run.mat)
 
     set instems = ($instems -i $instem $tpexarg);
-  end
+  end # loop over runs
+
+  # Count number of conditions, compare with analysis
+  set ncondact = `cat $pars | awk '{print $2}' | sort | uniq | wc -l`
+  @ ncondact = $ncondact - 1;
+  if($ncondact != $ncond) then
+    echo "ERROR: there are $ncondact non-null conditions in the "
+    echo "paradigm file. However, $ncond non-null conditions were"
+    echo "specified when mkanalysis was run. These must be made"
+    echo "consistent in order to run selxavg-sess."
+    exit 1;
+  endif
 
   if($new) then
     set cmd = "selxavg2"
diff --git a/fsfast/bin/tdr-rcolmat b/fsfast/bin/tdr-rcolmat
--- a/fsfast/bin/tdr-rcolmat
+++ b/fsfast/bin/tdr-rcolmat
@@ -1,11 +1,11 @@
 #!/bin/tcsh -f
-# tdr-fidmat
+# tdr-rcolmat
 
-set VERSION = '$Id: tdr-rcolmat,v 1.3 2003/12/19 21:56:21 greve Exp $';
+set VERSION = '$Id: tdr-rcolmat,v 1.4 2004/02/10 22:33:56 greve Exp $';
 
 set inputargs = ($argv);
 
-set fidmat     = ();
+set fidmatlist = ();
 set rcolmat    = ();
 set dnorm      = 1;
 set rsegthresh = 0.2;
@@ -68,7 +68,7 @@ endif
 
 #---------------------------------------------#
 tee -a > /dev/null $MLF  <<EOF
-  fidmatfile  = '$fidmat';
+  fidmatfilelist  = splitstring('$fidmatlist');
   rcolmatfile = '$rcolmat';
   dnorm = [$dnorm];
   boldweight = [$boldweight];
@@ -107,7 +107,7 @@ while( $#argv != 0 )
 
     case "--fid":
       if ( $#argv == 0) goto arg1err;
-      set fidmat = $argv[1]; shift;
+      set fidmatlist = ($fidmatlist $argv[1]); shift;
       breaksw
 
     case "--rcol":
@@ -151,6 +151,7 @@ while( $#argv != 0 )
       if ( $#argv == 0) goto arg1err;
       set MLF = $argv[1]; shift;
       set monly = 1;
+      rm -f $MLF
       breaksw
 
     case "--verbose":
@@ -181,14 +182,16 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
-  if($#fidmat == 0) then
+  if($#fidmatlist == 0) then
     echo "ERROR: must specify fidmat"
     exit 1;
   endif
-  if(! -e $fidmat ) then
-    echo "ERROR: $fidmat does not exist"
-    exit 1;
-  endif
+  foreach fidmat ($fidmatlist)
+    if(! -e $fidmat ) then
+      echo "ERROR: $fidmat does not exist"
+      exit 1;
+    endif
+  end
 
   if($#rcolmat == 0) then
     echo "ERROR: must specify rcolmat"
@@ -216,7 +219,7 @@ usage_exit:
   echo ""
   echo "USAGE: tdr-rcolmat"
   echo ""
-  echo "  --fid     fidmat"
+  echo "  --fid fidmat <--fid fidmat>"
   echo "  --rcol    rcolmat"
   echo "  --nodnorm"
   echo "  --bold"
