Added trap to check that to3d is there.

diff --git a/fsfast/bin/bvol2afni b/fsfast/bin/bvol2afni
--- a/fsfast/bin/bvol2afni
+++ b/fsfast/bin/bvol2afni
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 
-set VERSION = '$Id: bvol2afni,v 1.1 2004/02/13 21:30:42 greve Exp $'
+set VERSION = '$Id: bvol2afni,v 1.2 2004/04/05 21:56:17 greve Exp $'
 
 if($#argv == 0) goto usage_exit;
 
@@ -73,6 +73,11 @@ rm -f $afnistem+orig.BRIK
 rm -f $afnistem+orig.HEAD
 set afnistemstem = `basename $afnistem`;
 set TO3D = /usr/pubsw/packages/AFNI/current/bin/to3d
+#set TO3D = to3d
+if( ! -e $TO3D) then
+  echo "ERROR: cannot find $TO3D"
+  exit 1;
+endif
 set cmd = ($TO3D -session $afnidir -prefix $afnistemstem $imghdr)
 echo "-------------------------------"
 pwd
