FSFAST fcseed. #BF. Configuration and execution of FC seeds will now do the appropriate rescaling.

diff --git a/fsfast/bin/fcseed-config b/fsfast/bin/fcseed-config
--- a/fsfast/bin/fcseed-config
+++ b/fsfast/bin/fcseed-config
@@ -24,6 +24,7 @@ set SVDSynth = 0;
 set UseB0DC = 0;
 set UseExtract = 0
 set funcstem = (); # default fmcpr set in fcseed-sess
+set RescaleType = ()
 
 set Overwrite = 0;
 set cleanup = 1;
@@ -71,6 +72,7 @@ echo "SVDSynth $SVDSynth" >> $fcconfig
 echo "DoWM $DoWM"         >> $fcconfig
 echo "UseB0DC $UseB0DC"   >> $fcconfig
 echo "UseExtract $UseExtract"   >> $fcconfig
+echo "RescaleType $RescaleType"   >> $fcconfig
 if($#funcstem) echo "funcstem $funcstem"   >> $fcconfig
 if($#rlf)       echo "RunListFile $rlf"     >> $fcconfig
 if($#roicfg)    echo "roicfg $roicfg"       >> $fcconfig
@@ -205,6 +207,16 @@ while( $#argv != 0 )
       set UseExtract = 1;
       breaksw
 
+    case "-no-rescale":
+      set RescaleType = 0;
+      breaksw
+    case "-rescale-global":
+      set RescaleType = 1;
+      breaksw
+    case "-rescale-local":
+      set RescaleType = 2;
+      breaksw
+
     case "-nolog":
       set nolog = 1;
       breaksw
@@ -282,6 +294,17 @@ check_params:
     endif
   endif
 
+  if($#RescaleType == 0) then
+    if(! $DoSVD) then
+      echo "ERROR: you must pick a rescale type"
+      echo "  -no-rescale"
+      echo "  -rescale-global"
+      echo "  -rescale-local"
+      exit 1;
+    endif
+    set RescaleType = 0
+  endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -314,8 +337,14 @@ usage_exit:
   echo "  -extract : use extract_seg_waveform "
   echo "    has better PVC and can use b0dc and does not need a fill thresh; only with -mean"
   echo ""
-  echo "  -mean : compute the mean waveform over the voxels of the ROI"
+  echo "  -mean : compute the mean waveform over the spatial voxels of the ROI"
   echo "  -pca  : compute the PCA/SVD of the waveforms over the voxels of the ROI (or -svd)"
+  echo ""
+  echo "New as of 1/11/2024"
+  echo "  -no-rescale : do not rescale the intensity of the seed waveform (replicates 7.4.1 and before)"
+  echo "  -rescale-global : rescale the intensity of the seed waveform based on the mean over the brain mask"
+  echo "  -rescale-local :  rescale the intensity of the seed waveform based on the mean over the ROI"
+  echo "  It is recommended to use a scaling method, typically -rescale-global (note: does not apply to -pca)"
   echo ""
   echo " -fcname fcname : name of output file (default is configname)"
   echo " -mask  : create a mask for segmentation-based. Good for checking"
diff --git a/fsfast/bin/fcseed-sess b/fsfast/bin/fcseed-sess
--- a/fsfast/bin/fcseed-sess
+++ b/fsfast/bin/fcseed-sess
@@ -13,6 +13,7 @@ set maskfile = ();
 set segidlist = ();
 set UpdateOnly = 1;
 set regfilename = ();
+set RequireRescaleType = 1
 
 set cleanup = 1;
 set nolog = 0;
@@ -95,6 +96,11 @@ foreach sess ($SessList)
     echo $cmdargs | tee -a $LLF
     cat $FREESURFER_HOME/build-stamp.txt | tee -a $LLF
     echo "" | tee -a $LLF
+
+    set gmfile = $rundir/global.meanval.dat
+    if(! -e $gmfile) exit 1
+    set gmval = `cat $gmfile`
+    echo "GlobalMeanVal $gmval" | tee -a $LF
 
     set outfile = $rundir/$fcname
     set UpdateNeeded = 0;
@@ -205,6 +211,8 @@ foreach sess ($SessList)
         # Compute mean time course inside the mask
         set cmd = (mri_segstats --i $f --seg $mask --id 1 \
           --sum $tmpdir/junk.sum --avgwfvol $tmpdir/avgwf.mgh)
+        if($RescaleType == 1) set cmd = ($cmd --mul 100 --div $gmval)
+        if($RescaleType == 2) set cmd = ($cmd --avgwf-norm-mean 100)
         echo $cmd | tee -a $LLF
         $cmd | tee -a $LLF
         if($status) exit 1;
@@ -226,6 +234,8 @@ foreach sess ($SessList)
         set cmd = (extract_seg_waveform --seg $seganat --i $f --id $segidlist\
           --reg $reg --demean --o $rundir/$fcname)
         if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
+        if($RescaleType == 1) set cmd = ($cmd --mul 100 --div $gmval)
+        if($RescaleType == 2) set cmd = ($cmd --rescale-local 100)
         echo $cmd | tee -a $LLF
         $cmd | tee -a $LLF
         if($status) exit 1;
@@ -243,6 +253,9 @@ foreach sess ($SessList)
       set cmd = (mri_segstats --sqr --i $tmpdir/glm/eres.mgh  \
         --seg $mask --id 1  --sum $tmpdir/junk.sum \
         --avgwf $rundir/$fcname)
+      # Not sure if this should be done here as I can't remember the original app
+      if($RescaleType == 1) set cmd = ($cmd --mul 100 --div $gmval)
+      if($RescaleType == 2) set cmd = ($cmd --avgwf-norm-mean 100)
       echo $cmd | tee -a $LLF
       $cmd | tee -a $LLF
       if($status) exit 1;
@@ -303,6 +316,10 @@ while( $#argv != 0 )
     case "-no-mask":
     case "-no-make-mask":
       set MakeMask = 0;
+      breaksw
+
+    case "-no-require-rescale-type":
+      set RequireRescaleType = 0
       breaksw
 
     case "-nolog":
@@ -381,7 +398,7 @@ check_params:
   set tmp = `cat $fcconfig | awk '{if($1 == "funcstem") print $2}'`
   if($#tmp) set funcstem = $tmp;
 
-  # Note: Unless UseExtract, this is imperfect for B0DC because
+  # Note: Unless UseExtract, B0DC is imperfect because
   # label2vol cannot take a b0 map yet This just uses the reg computed
   # with B0DC so that it does not die
   set UseB0DC = 0;
@@ -391,6 +408,23 @@ check_params:
   set UseExtract = 0;
   set tmp = `cat $fcconfig | awk '{if($1 == "UseExtract") print $0}'`
   if($#tmp) set UseExtract = $tmp[2];
+
+  set tmp = `cat $fcconfig | awk '{if($1 == "RescaleType") print $0}'`
+  if($#tmp == 0) then
+    if($RequireRescaleType && $DoSVD == 0) then
+      echo "ERROR: this config file $fcconfig does not have a rescaling specification"
+      echo "It is recommened that you reconfigure this fcseed to have a scaling type"
+      echo "See https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes"
+      echo "To run this anyway, add -no-require-rescale-type to the command line"
+      exit 1
+    endif
+    echo "Setting RescaleType to 0"
+    set RescaleType = 0
+  else
+    set RescaleType = $tmp[2];
+    echo "Setting RescaleType to $RescaleType"
+  endif
+
 
   if($MakeMask) set maskfile = $fcname.mask
 
