more dev

diff --git a/fsfast/bin/fsfeat b/fsfast/bin/fsfeat
--- a/fsfast/bin/fsfeat
+++ b/fsfast/bin/fsfeat
@@ -14,8 +14,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/01/25 23:02:06 $
-#    $Revision: 1.2 $
+#    $Date: 2007/01/29 19:06:09 $
+#    $Revision: 1.3 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -31,7 +31,7 @@
 #
 
 
-set VERSION = '$Id: fsfeat,v 1.2 2007/01/25 23:02:06 greve Exp $';
+set VERSION = '$Id: fsfeat,v 1.3 2007/01/29 19:06:09 greve Exp $';
 set inputargs = ($argv);
 
 set fsf     = ();
@@ -72,9 +72,14 @@ if($FSLOUTPUTTYPE == ANALYZE) then
   exit 1;
 endif
 
-# This cannot exist, or else get +s
+# Set up the output path
+#   Feat needs a full path
+#   But this cannot exist, or else get +s
 set outdirpath = $outdir.feat
-rm -r $outdirpath
+mkdir -p $outdirpath
+set outdirpath = `getfullpath $outdirpath`;
+rm -fr $outdirpath
+echo $outdir
 
 # Get number of time points from input volume
 set tmpfile = /tmp/fsfeat.nframes.$$.dat
@@ -134,16 +139,21 @@ echo "set fmri(featwatcher_yn) 0"             >> $tmpfsf
 
 feat $tmpfsf
 if($status) exit 1;
+if(! -e $outdirpath/example_func.$outext) then
+  echo "ERROR: feat failed"
+  exit 1;
+endif
 
 # Compute sigs from zstats
-set statsdir = $outdirpath.feat/stats
+set statsdir = $outdirpath/stats
 set nzstats = `ls $statsdir/zstat*.$outext | wc -w`;
 echo nzstats = $nzstats
 @ nthzstat = 0;
-while ($nthzstat <= $nzstats)
+while ($nthzstat < $nzstats)
   @ nthzstat = $nthzstat + 1;
   set z = $statsdir/zstat$nthzstat.$outext
-  set cmd = (mri_z2p --z $z --logp $sig --signed)
+  set sig = $statsdir/zsig$nthzstat.$outext
+  set cmd = (mri_z2p --z $z --log10p $sig --signed)
   pwd
   echo $cmd
   $cmd
@@ -152,15 +162,16 @@ while ($nthzstat <= $nzstats)
   set conname = `fsfget $fsf conname_real.$nthzstat`
   if($#conname != 0) then
     set sig2 = $statsdir/$conname.sig.$outext
+    if(-e $sig2) rm $sig2
     ln -s $sig $sig2
   endif
 end
 
 # Compute sigs from zfstats
-set nzstats = `ls $statsdir/zfstat*.$outext | wc -w`;
+set nzfstats = `ls $statsdir/zfstat*.$outext | wc -w`;
 echo nzfstats = $nzfstats
 @ nthzfstat = 0;
-while ($nthzfstat <= $nzfstats)
+while ($nthzfstat < $nzfstats)
   @ nthzfstat = $nthzfstat + 1;
   set zf = $statsdir/zfstat$nthzfstat.$outext
   set sig = $statsdir/zfsig$nthzfstat.$outext
@@ -172,7 +183,9 @@ while ($nthzfstat <= $nzfstats)
 end
 
 if($#subject) then
-  set cmd = (reg-feat2anat --featdir $outdirpath --subject $subject);
+  set cmd = (reg-feat2anat --feat $outdirpath --subject $subject);
+  echo "setenv SUBJECTS_DIR $SUBJECTS_DIR"
+  echo "cd `pwd`"
   echo $cmd
   $cmd
   if($status) exit 1;
@@ -250,12 +263,12 @@ check_params:
     echo "ERROR: cannot find $invol"
     exit 1;
   endif
-
   isanalyze $invol
   if($status) then
     echo "ERROR: get a real format"
     exit 1;
   endif
+  set invol = `getfullpath $invol`;
 
   if(! -e $fsf) then
     echo "ERROR: cannot find $fsf"
