Added ability to run on abblocked and sfa.

diff --git a/fsfast/bin/func2roi-sess b/fsfast/bin/func2roi-sess
--- a/fsfast/bin/func2roi-sess
+++ b/fsfast/bin/func2roi-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # func2roi-sess 
 
-set VERSION = '$Id: func2roi-sess,v 1.3 2003/03/20 23:11:03 greve Exp $';
+set VERSION = '$Id: func2roi-sess,v 1.4 2003/04/25 17:15:12 greve Exp $';
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 set inputargs = ($argv);
@@ -120,6 +120,7 @@ if($SourceType == $AvgSource) then
   set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
   set funcstem = `cat $infofile | awk '{if($1 == "funcstem") print $2}'`;
   set runlistfile = `cat $infofile | awk '{if($1 == "runlistfile") print $2}'`;
+  set designtype  = `cat $infofile | awk '{if($1 == "designtype") print $2}'`;
 endif
 
 # If a mask session was specified, get the full stem to the mask map
@@ -191,9 +192,27 @@ foreach sess ($SessList)
     endif
   endif
 
+  if($#NthRun != 0) then
+    set runlist = `getrunlist $fsd $runlistfile`;
+    if($status) then
+      echo $runlist;
+      exit 1;
+    endif
+    if($NthRun > $#runlist) then
+      echo "ERROR: NthRun = $NthRun, nruns = $#runlist"
+      exit 1;
+    endif
+    set run = $runlist[$NthRun];
+    if($NthRunType == perrun) set anapend = "-$run"
+    if($NthRunType == jk) set anapend = "-jk$run"
+    echo "NthRun: $NthRun $NthRunType $anapend"
+  endif
+
+
   if($#masksessid == 0 && $#maskcontrast != 0) then
     # Use a local mask #
-    set maskstem = $fsd/$maskanalysis/$maskspacedir/$maskcontrast/$maskmap;
+    set maskstem = $fsd/$maskanalysis$anapend/$maskspacedir/$maskcontrast/$maskmap;
+    # Note: anapend will be null if maskanalysis != analysis or masksessid != null
     if($volcheck) then
       bfvcheck $maskstem;
       if($status) then
@@ -210,23 +229,6 @@ foreach sess ($SessList)
         exit 1;
       endif
     endif
-  endif
-
-
-  if($#NthRun != 0) then
-    set runlist = `getrunlist $fsd $runlistfile`;
-    if($status) then
-      echo $runlist;
-      exit 1;
-    endif
-    if($NthRun > $#runlist) then
-      echo "ERROR: NthRun = $NthRun, nruns = $#runlist"
-      exit 1;
-    endif
-    set run = $runlist[$NthRun];
-    if($NthRunType == perrun) set anapend = "-$run"
-    if($NthRunType == jk) set anapend = "-jk$run"
-    echo "NthRun: $NthRun $NthRunType $anapend"
   endif
 
 
@@ -324,9 +326,13 @@ foreach sess ($SessList)
     if($status) exit 1;
 
     # Create a more convenient table #
-    set tblfile = $outdir/h.tbl
-    roitxt2tbl $outdir/h.dat $outdir/h.txt $outdir/h-offset.txt $tblfile
-    if($status) exit 1;
+    if($designtype != retinotopy && $designtype != abblocked) then
+      set tblfile = $outdir/h.tbl
+      roitxt2tbl $outdir/h.dat $outdir/h.txt $outdir/h-offset.txt $tblfile
+      if($status) exit 1;
+    else
+      cp $fsd/$analysis/h.sfa $outdir/h.sfa      
+    endif
 
     #--------------------------------------------------#
     # This will average all the raw data used in the 
@@ -420,6 +426,14 @@ while( $#argv != 0 )
       set SourceType = $AvgSource;
       breaksw
 
+    case "-raw"
+      if($#analysis != 0) then
+        echo "ERROR: cannot specify both -raw and -analysis"
+        exit 1;
+      endif
+      set SourceType = $RawSource;
+      breaksw
+
     case "-nthrun"
       if ( $#argv == 0) goto arg2err;
       set NthRun = $argv[1]; shift;
@@ -432,14 +446,6 @@ while( $#argv != 0 )
         echo "ERROR: NthRunType = $NthRunType, must be perrun or jk"
         exit 1;
       endif
-      breaksw
-
-    case "-raw"
-      if($#analysis != 0) then
-        echo "ERROR: cannot specify both -raw and -analysis"
-        exit 1;
-      endif
-      set SourceType = $RawSource;
       breaksw
 
     case "-rawfsd"
@@ -786,9 +792,20 @@ check_params:
     exit 1;
   endif
 
-  if($#anapend != 0 && $NthRun != 0) then
+  if($#anapend != 0 && $#NthRun != 0) then
     echo "ERROR: cannot specify both anapend and nthrun"
     exit 1;
+  endif
+
+  if($#anapend != 0  || $#NthRun != 0) then
+    if($maskanalysis != $analysis) then
+      echo "ERROR: with nthrun or anapend, mask must use same analysis"
+      exit 1;
+    endif
+    if($#masksessid != 0) then
+      echo "ERROR: cannot use masksess with nthrun or anapend"
+      exit 1;
+    endif
   endif
 
 goto check_params_return;
