Now should find all contrasts for all types of analyses

diff --git a/fsfast/bin/funcroi-config b/fsfast/bin/funcroi-config
--- a/fsfast/bin/funcroi-config
+++ b/fsfast/bin/funcroi-config
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/11/30 17:26:39 $
-#    $Revision: 1.4 $
+#    $Date: 2010/11/30 17:47:16 $
+#    $Revision: 1.5 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,7 +22,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: funcroi-config,v 1.4 2010/11/30 17:26:39 greve Exp $';
+set VERSION = '$Id: funcroi-config,v 1.5 2010/11/30 17:47:16 greve Exp $';
 
 set roiconfig = ();
 set label = ();
@@ -255,15 +255,16 @@ check_params:
     endif
   endif
 
-  set IsRetinotopy = `getana -a $analysis -t isretinotopy`
-
   if($#contrast) then
-    if(! $IsRetinotopy) then
-      set mat = $analysis/$contrast.mat
-      if(! -e $mat) then
-        echo "ERROR: cannot find $mat"
-        exit 1;
-      endif
+    set ConList = (`getana -a $analysis -t contrasts`)
+    set ConFound = 0;
+    foreach con ($ConList)
+      if($contrast == $con) set ConFound = 1;
+    end
+    if(! $ConFound) then
+      echo "ERROR: cannot find contrast $contrast in analysis $analysis"
+      exit 1;
+    endif
     else
       if($contrast != polar && $contrast != eccen) then
         echo "ERROR: contrast must be polar or eccen for retinotopy"
