Created better error traps

diff --git a/fsfast/bin/funcroi-config b/fsfast/bin/funcroi-config
--- a/fsfast/bin/funcroi-config
+++ b/fsfast/bin/funcroi-config
@@ -5,8 +5,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2011/02/15 21:01:54 $
-#    $Revision: 1.10 $
+#    $Date: 2011/04/08 15:52:51 $
+#    $Revision: 1.11 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -21,7 +21,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: funcroi-config,v 1.10 2011/02/15 21:01:54 greve Exp $';
+set VERSION = '$Id: funcroi-config,v 1.11 2011/04/08 15:52:51 greve Exp $';
 
 set roiconfig = ();
 set label = ();
@@ -35,7 +35,8 @@ set contrast = ();
 set thresh = ();
 set pct = ();
 set map = sig;
-set frame = 0;
+set sign = ();
+set frame = ();
 set fillthresh = 0;
 
 set Force = 0;
@@ -260,6 +261,21 @@ check_params:
     endif
   endif
 
+  if($#contrast == 0) then
+    if($#frame) then
+      echo "ERROR: you must specify a contrast with -frame"
+      exit 1;
+    endif
+    if($#sign) then
+      echo "ERROR: you must specify a contrast with -sign"
+      exit 1;
+    endif
+    if($#thresh) then
+      echo "ERROR: you must specify a contrast with -thresh"
+      exit 1;
+    endif
+  endif
+
   if($#contrast) then
     set ConList = (`getana -a $analysis -t contrasts`)
     set ConFound = 0;
@@ -282,6 +298,7 @@ check_params:
       echo "ERROR: must specify a sign (-sign) with contrast"
       exit 1;
     endif
+    if($#frame == 0) set frame = 0;
   endif
 
   if(0) then
@@ -338,7 +355,7 @@ usage_exit:
   echo "   -thresh threshold "
   echo "   -sign sign : abs, pos, neg"
   echo "   -map  map  : (default is sig)"
-  echo "   -frame frameno : default is 0"
+  echo "   -frame frameno : frame within contrast sig (default is 0)"
   echo ""
   echo " Other options"
   echo ""
diff --git a/fsfast/bin/funcroi-table-sess b/fsfast/bin/funcroi-table-sess
--- a/fsfast/bin/funcroi-table-sess
+++ b/fsfast/bin/funcroi-table-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/12/07 19:04:46 $
-#    $Revision: 1.3 $
+#    $Date: 2011/04/08 15:52:51 $
+#    $Revision: 1.4 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: funcroi-table-sess,v 1.3 2010/12/07 19:04:46 greve Exp $';
+set VERSION = '$Id: funcroi-table-sess,v 1.4 2011/04/08 15:52:51 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -31,7 +31,7 @@ set outtable = ();
 set roicfg = ();
 set analysis = ();
 set contrast = ();
-set map = ces;
+set map = ();
 set frame = 0;
 set measure = "mean";
 
@@ -285,6 +285,11 @@ endif
 
 if($#analysis == 0) set analysis = $ROIanalysis
 
+if($#contrast == 0 && $#map != 0) then
+  echo "ERROR: you must specify a contrast with -map"
+  exit 1;
+endif
+
 if($#contrast) then
   set conlist = (`getana -a $analysis -t contrasts`);
   set ConFound = 0;
@@ -295,6 +300,7 @@ if($#contrast) then
     echo "ERROR: cannot find $contrast in $analysis"
     exit 1;
   endif
+  if($#map == 0) set map = ces;
 endif
 
 set fsd = `getana -a $analysis -t fsd`
