Added ability to specify the nthrun for processing perrun and/or jk.

diff --git a/fsfast/bin/func2roi-sess b/fsfast/bin/func2roi-sess
--- a/fsfast/bin/func2roi-sess
+++ b/fsfast/bin/func2roi-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # func2roi-sess 
 
-set VERSION = '$Id: func2roi-sess,v 1.1 2003/03/04 21:22:08 greve Exp $';
+set VERSION = '$Id: func2roi-sess,v 1.2 2003/03/20 22:32:38 greve Exp $';
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 set inputargs = ($argv);
@@ -45,6 +45,8 @@ set labelfillthresh = ();
 
 set runlistfile = ();
 
+set NthRun = ();
+set NthRunType = ();
 
 set umaskarg = ();
 set nolog = 0;
@@ -209,6 +211,24 @@ foreach sess ($SessList)
       endif
     endif
   endif
+
+
+  if($#NthRun != 0) then
+    set runlist = `getrunlist $fsd $runlistfile`;
+    if($status) then
+      echo $runlist;
+      exit 1;
+    endif
+    if($NthRun > $#runlist) then
+      echo "ERROR: NthRun = $NthRun, nruns = $#runlist"
+      exit 1;
+    endif
+    set run = $runlist[$NthRun];
+    if($NthRunType == perrun) set anapend = "-$run"
+    if($NthRunType == jk) set anapend = "-jk$run"
+    echo "NthRun: $NthRun $NthRunType $anapend"
+  endif
+
 
   if($SourceType == $AvgSource) then
     set srcstem = $fsd/$analysis$anapend/h
@@ -398,6 +418,20 @@ while( $#argv != 0 )
       endif
       set analysis = $argv[1]; shift;
       set SourceType = $AvgSource;
+      breaksw
+
+    case "-nthrun"
+      if ( $#argv == 0) goto arg2err;
+      set NthRun = $argv[1]; shift;
+      set NthRunType = $argv[1]; shift;
+      if($NthRun <= 0) then
+        echo "ERROR: NthRun = $NthRun, must be > 0"
+        exit 1;
+      endif
+      if("$NthRunType" != perrun && "$NthRunType" != jk) then
+        echo "ERROR: NthRunType = $NthRunType, must be perrun or jk"
+        exit 1;
+      endif
       breaksw
 
     case "-raw"
@@ -762,6 +796,12 @@ arg1err:
 ############--------------##################
 
 ############--------------##################
+arg2err:
+  echo "ERROR: flag $flag requires two arguments"
+  exit 1
+############--------------##################
+
+############--------------##################
 usage_exit:
   echo "USAGE: func2roi-sess"
   echo "Options:";
@@ -793,6 +833,8 @@ usage_exit:
   echo "   -maskisxavg   effect: fixed or random (when masksessid is a group)"
 
   echo "   -float2int method: method = <tkreg>,round,floor"
+
+  echo "   -nthrun nthrun type : type = perrun or jk"
 
   echo "   -sf sessidfile  ..."
   echo "   -df srchdirfile ..."
