Now makes sure that an anlysis is included

diff --git a/fsfast/bin/func2roi-sess b/fsfast/bin/func2roi-sess
--- a/fsfast/bin/func2roi-sess
+++ b/fsfast/bin/func2roi-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # func2roi-sess 
 
-set VERSION = '$Id: func2roi-sess,v 1.8 2003/08/29 22:58:57 greve Exp $';
+set VERSION = '$Id: func2roi-sess,v 1.9 2006/09/26 19:24:02 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -657,6 +657,11 @@ check_params:
 
   if ($#roidef == 0) then
      echo "ERROR: no ROI definition name specified " |& tee -a $LF 
+     exit 1
+  endif
+
+  if ($#analysis == 0) then
+     echo "ERROR: no analysis specified " |& tee -a $LF 
      exit 1
   endif
 
