Copied files from dev. Created better error traps

diff --git a/fsfast/bin/funcroi-config b/fsfast/bin/funcroi-config
--- a/fsfast/bin/funcroi-config
+++ b/fsfast/bin/funcroi-config
@@ -1,13 +1,12 @@
 #! /bin/csh -f
-
 #
 # funcroi-config
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/07/27 00:04:10 $
-#    $Revision: 1.3 $
+#    $Date: 2011/04/08 15:53:13 $
+#    $Revision: 1.10.2.1 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,7 +21,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: funcroi-config,v 1.3 2010/07/27 00:04:10 greve Exp $';
+set VERSION = '$Id: funcroi-config,v 1.10.2.1 2011/04/08 15:53:13 greve Exp $';
 
 set roiconfig = ();
 set label = ();
@@ -36,7 +35,8 @@ set contrast = ();
 set thresh = ();
 set pct = ();
 set map = sig;
-set frame = 0;
+set sign = ();
+set frame = ();
 set fillthresh = 0;
 
 set Force = 0;
@@ -109,6 +109,12 @@ while( $#argv != 0 )
     case "-roi":
       if($#argv < 1) goto arg1err;
       set roiconfig = $argv[1]; shift;
+      # This is to prevent an annoying bug in LabelWrite() in label.c
+      set n = `echo $roiconfig | grep -e "\.label" | wc -l `
+      if($n != 0) then
+        echo "ERROR: do not include the string .label in your ROI configuration name"
+	exit 1;
+      endif
       breaksw
 
     case "-l":
@@ -255,17 +261,36 @@ check_params:
     endif
   endif
 
+  if($#contrast == 0) then
+    if($#frame) then
+      echo "ERROR: you must specify a contrast with -frame"
+      exit 1;
+    endif
+    if($#sign) then
+      echo "ERROR: you must specify a contrast with -sign"
+      exit 1;
+    endif
+    if($#thresh) then
+      echo "ERROR: you must specify a contrast with -thresh"
+      exit 1;
+    endif
+  endif
+
   if($#contrast) then
-    set mat = $analysis/$contrast.mat
-    if(! -e $mat) then
-      echo "ERROR: cannot find $mat"
+    set ConList = (`getana -a $analysis -t contrasts`)
+    set ConFound = 0;
+    foreach con ($ConList)
+      if($contrast == $con) set ConFound = 1;
+    end
+    if(! $ConFound) then
+      echo "ERROR: cannot find contrast $contrast in analysis $analysis"
       exit 1;
     endif
     if($#thresh && $#pct) then
       echo "ERROR: you cannot specify both -thresh and -pct"
-      exti 1;
+      exit 1;
     endif
-    if($#thresh == 0 && $pct == 0) then
+    if($#thresh == 0 && $#pct == 0) then
       echo "ERROR: must specify a threshold or percent with a contrast"
       exit 1;
     endif
@@ -273,6 +298,7 @@ check_params:
       echo "ERROR: must specify a sign (-sign) with contrast"
       exit 1;
     endif
+    if($#frame == 0) set frame = 0;
   endif
 
   if(0) then
@@ -329,7 +355,7 @@ usage_exit:
   echo "   -thresh threshold "
   echo "   -sign sign : abs, pos, neg"
   echo "   -map  map  : (default is sig)"
-  echo "   -frame frameno : default is 0"
+  echo "   -frame frameno : frame within contrast sig (default is 0)"
   echo ""
   echo " Other options"
   echo ""
@@ -421,8 +447,8 @@ selxavg3-sess -sf sessidlist -analysis wm-sm5.lh
 # the intersection of the left fusiform gyrus (defined in
 # lh.aparc.annot) with the area postively activated above sig=2 in the
 # encode contrast.
-funcroi-config  -annot aparc fusiform 
-  -analyisis wm-sm5.lh -c encode -thresh 2 -sign pos
+funcroi-config  -annot aparc fusiform \
+  -analysis wm-sm5.lh -c encode -thresh 2 -sign pos \
   -roi lh.fusi+encode.th2.pos.roicfg 
 # This instantly creates the file lh.fusi+encode.th2.pos.roicfg
 
@@ -444,6 +470,10 @@ funcroi-table-sess -roi lh.fusi+encode.th2.pos.roicfg
 # lh.fusi+encode.th2.pos.nii mask. Note: if you do not run
 # funcroi-sess above, it will be run automatically when you run
 # funcroi-table-sess
+
+# Now summarize the volume of this ROI.
+funcroi-table-sess -roi lh.fusi+encode.th2.pos.roicfg
+    -o lh.fusi+encode.th2.pos.volume.dat -vol
 
 ==================================================
 Example 2. Right hippocampus
diff --git a/fsfast/bin/funcroi-table-sess b/fsfast/bin/funcroi-table-sess
--- a/fsfast/bin/funcroi-table-sess
+++ b/fsfast/bin/funcroi-table-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/07/19 20:53:41 $
-#    $Revision: 1.1 $
+#    $Date: 2011/04/08 15:53:13 $
+#    $Revision: 1.3.2.1 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: funcroi-table-sess,v 1.1 2010/07/19 20:53:41 greve Exp $';
+set VERSION = '$Id: funcroi-table-sess,v 1.3.2.1 2011/04/08 15:53:13 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -31,7 +31,7 @@ set outtable = ();
 set roicfg = ();
 set analysis = ();
 set contrast = ();
-set map = ces;
+set map = ();
 set frame = 0;
 set measure = "mean";
 
@@ -118,16 +118,21 @@ foreach sess ($SessList)
     exit 1;
   endif
 
-  set condir = $sess/$fsd/$analysis/$contrast
-  set mapfile = `stem2fname $condir/$map`;
-  if($status) then
-    echo "$mapfile"
-    exit 1;
+  if($#contrast) then
+    set condir = $anadir/$contrast
+    set mapfile = `stem2fname $condir/$map`;
+    if($status) then
+      echo "$mapfile"
+      exit 1;
+    endif
+    set sum = $condir/$map.$ROIname.$frame.dat
+  else
+    set mapfile = `stem2fname $anadir/meanfunc`
+    set sum = $anadir/$ROIname.$frame.dat
   endif
 
-  set sum = $condir/$map.$ROIname.$frame.dat
-  set cmd = (mri_segstats --seg $ROImask --i $mapfile --frame $frame \
-    --id 1 --sum $sum)
+  set cmd = (mri_segstats --seg $ROImask --frame $frame --id 1 \
+     --i $mapfile --sum $sum)
   echo $cmd
   $cmd | tee -a $LF
   if($status) exit 1;
@@ -269,15 +274,33 @@ if($ROIIsSurface) then
 endif
 set ROIfsd = `getana -a $ROIanalysis -t fsd`
 
-if($#analysis == 0) set analysis = $ROIanalysis
-
-if($#contrast == 0) then
-  echo "ERROR: must specify a contrast"
+if($measure == volume && $#analysis) then
+  echo "ERROR: do not specify an analysis with -vol"
   exit 1;
 endif
-if(! -e $analysis/$contrast.mat) then
-  echo "ERROR: cannot find $contrast.mat in $analysis"
+if($measure == volume && $#contrast) then
+  echo "ERROR: do not specify a contrast with -vol"
   exit 1;
+endif
+
+if($#analysis == 0) set analysis = $ROIanalysis
+
+if($#contrast == 0 && $#map != 0) then
+  echo "ERROR: you must specify a contrast with -map"
+  exit 1;
+endif
+
+if($#contrast) then
+  set conlist = (`getana -a $analysis -t contrasts`);
+  set ConFound = 0;
+  foreach con ($conlist)
+    if($con == $contrast) set ConFound = 1;
+  end
+  if(! $ConFound) then
+    echo "ERROR: cannot find $contrast in $analysis"
+    exit 1;
+  endif
+  if($#map == 0) set map = ces;
 endif
 
 set fsd = `getana -a $analysis -t fsd`
@@ -323,6 +346,7 @@ usage_exit:
   echo ""
   echo "   -roi roicfg     : ROI configuration (created by funcroi-config)"
   echo ""
+  echo "   -vol : report the ROI volume"
   echo "   -a analysisname : session-level functional analysis name"
   echo "   -c contrast     : contrast "
   echo "   -m map          : default ces"
@@ -331,6 +355,7 @@ usage_exit:
   echo ""
   echo "   -mean : compute spatail mean of map inside of ROI (default)"
   echo "   -std : compute spatail standard deviation of map inside of ROI (probably not useful)"
+  echo "   -vol : report the volume of the ROI"
   echo ""
   echo "   -sf sessidfile  ..."
   echo "   -df srchdirfile ..."
@@ -360,16 +385,44 @@ analysis. The ROI is defined by funcroi-config and may be constrained
 by a subject-specific anatomical ROI, and, possibly, a
 subject-specific functional ROI. The summary table (-o) is a simple
 text file that has a row for each session followed by the mean
-contrast (ces) inside the boundaries of the ROI.
+contrast (ces) inside the boundaries of the ROI. The percent contrast
+can be reported by specifying -map cespct. The ROI volume can be
+reported instead with the -vol.
 
-You are required to specify an analysis and a contrast eventhough you
-might have specified these when you configured the ROI with
-funcroi-config. This is because you may want to use the ROI to
-summarize different contrasts in the same or different analyses. It is
-usually wise to do this. For example, you can construct the ROI based
-on the sum of two conditions and then sumarize the values based on the
-difference between two conditions.
+The boundaries of the ROI itself are fixed by the funcroi-config and
+funcroi-sess commands. The purpose of this program is to report
+characteristics of this ROI. This may include the following:
+
+1. The mean of a contrast inside the ROI
+2. The mean of a percent contrast inside the ROI (-map cespct)
+3. The volume of the ROI (with -vol)
+
+If you want (1) or (2) above, then you need to specify a contrast.
+You can also specify an analysis if the contrast you want was not in
+the analysis used to configure the ROI. If you specify the analysis
+and contrast used to configure the ROI, you may be creating a
+circularity (this is bad). An example of a better way is to configure
+the ROI based on the sum of two conditions and then summarize the
+values based on the difference between two conditions.
+
+For (3), the volume of the ROI, you are not allowed to specify a
+contrast or analysis. This is because the volume depends only on the
+boundaries of the ROI which are fixed when you run funcroi-sess.
+If you do not specify a contrast or vol, then it will report
+the mean of the meanfunc volume in the ROI analysis.
 
 See funcroi-config -help for more info.
 
+Examples:
+
+1. Report the percent contrast of the e-n.dist contrast within the 
+lh.fusi+encode.th2.pos.roicfg ROI.
+
+funcroi-table-sess -sf sessidfile -roi lh.fusi+encode.th2.pos.roicfg \
+  -c e-n.dist -map cespct -o myroi.cespct.dat 
+
+2. Report the volume of the lh.fusi+encode.th2.pos.roicfg ROI.
+
+funcroi-table-sess -sf sessidfile -roi lh.fusi+encode.th2.pos.roicfg \
+  -vol -o myroi.vol.dat 
 
