Added ability to autodetect func stem format

diff --git a/fsfast/bin/getformat_from_stem b/fsfast/bin/getformat_from_stem
--- a/fsfast/bin/getformat_from_stem
+++ b/fsfast/bin/getformat_from_stem
@@ -8,14 +8,39 @@
 #
 # Return: format extension and exit 0. If fails, then exits 1.
 #
-# $Id: getformat_from_stem,v 1.1 2006/04/12 22:45:37 greve Exp $
+# As a convenience, you can spec the format to try as the 2nd arg.
+# If the stem.fmt does not exist, then exit 1. Otherwise exit 0
+# and echoes the given fmt to the terminal. This just helps to
+# cut out a few lines of code from the calling program.
+#
+# $Id: getformat_from_stem,v 1.2 2006/04/12 23:19:06 greve Exp $
 
-if($#argv != 1) then
-  echo "getformat_from_stem stem"
+if($#argv < 1 || $#argv > 2) then
+  echo "getformat_from_stem stem <fmt>"
   exit 1;
 endif
 
 set stem = $argv[1];
+
+if($#argv == 2) then
+  # Format has been specified
+  set fmt = $argv[2];
+else
+  # Format has been not specified
+  set fmt = ();
+endif
+
+if($#fmt) then
+  # Format has been specified, check that file exists
+  if(! -e $stem.$fmt) then
+    echo "ERROR: cannot find $stem.$fmt"
+    exit 1;
+  endif
+  echo $fmt
+  exit 0;
+endif
+
+# Only gets here when autodetecting
 
 if(-e $stem.nii.gz) then
   echo nii.gz
diff --git a/fsfast/bin/isxavg-re-sess b/fsfast/bin/isxavg-re-sess
--- a/fsfast/bin/isxavg-re-sess
+++ b/fsfast/bin/isxavg-re-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # isxavg-re-sess - random effects intersubject averaging
 #
-set VERSION = '$Id: isxavg-re-sess,v 1.6 2005/03/28 20:56:50 greve Exp $'
+set VERSION = '$Id: isxavg-re-sess,v 1.7 2006/04/12 23:19:06 greve Exp $'
 set cmdargs = ($argv);
 
 set analysis    = ();
@@ -112,6 +112,7 @@ else
   end
 endif
 
+if(0) then
 mkdir -p scripts
 set scriptfile = scripts/run-isxavg-re-$analysis-$contrast
 rm -f $scriptfile
@@ -119,6 +120,7 @@ touch $scriptfile
 echo "#\!/bin/csh -f" >> $scriptfile
 echo "cd .." >> $scriptfile
 chmod a+x $scriptfile
+endif
 
 foreach hs ($hemi)
 
@@ -157,8 +159,15 @@ foreach hs ($hemi)
       set inhoffstem = $sess/$fsd/$analysis/$spacedir/h-$hs-offset
     endif
 
+    if(! -e $instem"_000.bfloat") then
+      echo "ERROR: cannot find $instem"
+      exit 1;
+    endif
+
     set instems     = ($instems     -i $instem);
     set inhoffstems = ($inhoffstems -i $inhoffstem);
+
+
 
   end # loop over SessList #
   
