Replaced the matlab code with a single matlab call to fast_group_glm.

diff --git a/fsfast/bin/groupreg-sess b/fsfast/bin/groupreg-sess
--- a/fsfast/bin/groupreg-sess
+++ b/fsfast/bin/groupreg-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # groupreg-sess
 #
-set VERSION = '$Id: groupreg-sess,v 1.2 2003/12/20 00:46:50 greve Exp $';
+set VERSION = '$Id: groupreg-sess,v 1.3 2004/11/20 00:23:21 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -122,6 +122,7 @@ mkdir -p $outdir
 
 # Check that the input volume is there for each subj
 set InstemList = ();
+set FLAXMatList = ();
 foreach sess ($SessList)
   set instem = $sess/$fsd/$analysis/$spacedir/$contrast/$volstem$hemicode
   set fname = $instem"_000.hdr";
@@ -136,8 +137,23 @@ foreach sess ($SessList)
     exit 1;
   endif
   set InstemList = ($InstemList $instem);
+  if("$spacename" == "tal") then
+    set reg = $sess/$fsd/$analysis/$spacedir/register.dat
+    cp $reg $groupid/$fsd/$analysis/$spacedir-rfx
+  endif
+  set FLAXMat = $sess/$fsd/$analysis/X.mat
+  if(! -e $FLAXMat) then
+    echo "ERROR: cannot find $FLAXMat"
+    exit 1;
+  endif
+  set FLAXMatList = ($FLAXMatList $FLAXMat);
 end
 
+set FLAConMat = $analysis/$contrast.mat
+if(! -e $FLAConMat) then
+  echo "ERROR: cannot find $FLAConMat"
+  exit 1;
+endif
 
 if(! $monly) set MLF = /tmp/groupreg-sess-$$.m
 rm -f $MLF 
@@ -149,124 +165,16 @@ rm -f $okfile
 #--------------------------------------------#
 tee -a $MLF > /dev/null <<EOF
 
-tic;
-
 InstemList = splitstring('$InstemList');
+FLAXMatList = splitstring('$FLAXMatList');
+FLAConMat = '$FLAConMat';
 ninputs = size(InstemList,1);
 outdir = '$outdir';
 okfile = '$okfile';
 xmatfile = '$xmat';
+gconmatfile = '$gconmat';
 QuitOnError = ~[$monly];
-
-% X = load('$xmat','-ascii');
-[X, rowid, colid] = fast_ldtable(xmatfile);
-if(isempty(X))
-  fprintf('ERROR: loading %s\n',xmatfile);
-  return;
-end
-[nxf nbeta] = size(X);
-
-XtX = X'*X;
-c = cond(XtX);
-fprintf('Design matrix condition %g\n',c);
-if(c > 1000)
-  fprintf('ERROR: design matrix is ill-conditioned.\n');
-  fprintf('  Run groupreg-sess -help for more info.\n');
-  if(QuitOnError) exit; end
-  return;
-end
-
-C = load('$gconmat','-ascii');
-if(isempty(C))
-  fprintf('ERROR: loading %s\n','$gconmat');
-  if(QuitOnError) exit; end
-  return;
-end
-ncbeta = size(C,2);
-
-if(nbeta ~= ncbeta)
-  fprintf('ERROR: number of columns in X (%d) does not equal\n');
-  fprintf('  the number of columns in C (%d)\n',nbeta,ncbeta);
-  if(QuitOnError) exit; end
-  return;
-end
-
-if(nxf ~= ninputs)
-  fprintf('ERROR: number of rows in X (%d) does not equal\n');
-  fprintf('  the number of input (%d)\n',nxf,ninputs);
-  if(QuitOnError) exit; end
-  return;
-end
-
-instem = deblank(InstemList(1,:));
-[ns nr nc nf] = fmri_bvoldim(instem);
-if(isempty(ns))
-  fprintf('ERROR: loading %s\n',instem);
-  return;
-end
-if(nf > 1)
-  fprintf('ERROR: first-level contrast has more than one plane\n');
-  if(QuitOnError) exit; end
-  return;
-end
-
-nvslice = nr*nc;
-
-mristruct = fast_ldbhdr(instem);
-if(isempty(mristruct))
-  fprintf('ERROR: could not load bhdr for %s\n',instem);
-  if(QuitOnError) exit; end
-  return;
-end
-
-for slice = 1:ns
-  fprintf('slice = %d (%g)\n',slice,toc);
-
-  y = [];
-  for n = 1:ninputs
-
-    instem = deblank(InstemList(n,:));
-    yn = fast_ldbslice(instem,slice-1);
-    if(isempty(yn))
-      fprintf('ERROR: loading %s\n',instem);
-      if(QuitOnError) exit; end
-      return;
-    end
-
-    yn = reshape(yn,[nvslice nf])';
-    y = [y; yn];
-
-  end
-
-  [beta rvar] = fast_glmfit(y,X);
-  [F, Fsig, ces] = fast_fratio(beta,X,rvar,C);
-
-  beta = reshape(beta', [nr nc nbeta]);
-  rvar = reshape(rvar', [nr nc 1]);
-  F = reshape(F', [nr nc 1]);
-  Fsig = reshape(Fsig', [nr nc 1]);
-  ces = reshape(ces', [nr nc 1]);
-
-  stem = sprintf('%s/beta',outdir);
-  fast_svbslice(beta,stem,slice-1,'',mristruct);
-
-  stem = sprintf('%s/beta-var',outdir);
-  fast_svbslice(rvar,stem,slice-1,'',mristruct);
-
-  stem = sprintf('%s/f',outdir);
-  fast_svbslice(F,stem,slice-1,'',mristruct);
-
-  stem = sprintf('%s/ces',outdir);
-  fast_svbslice(ces,stem,slice-1,'',mristruct);
-
-  stem = sprintf('%s/fsig',outdir);
-  tmp = -sign(ces).*log10(abs(Fsig));
-  fast_svbslice(tmp,stem,slice-1,'',mristruct);
-
-end
-
-fmri_touch(okfile);
-fprintf('matlab groupreg-sess done (%g)\n',toc);
+fast_group_glm;
 
 return;
 
@@ -369,6 +277,7 @@ while( $#argv != 0 )
     case "-monly":
       if ( $#argv == 0) goto arg1err;
       set MLF = $argv[1]; shift;
+      set monly = 1;
       breaksw
 
     case "-umask":
