Now has WLS capability, though I need to make sure my WLS algoritm is correct.

diff --git a/fsfast/bin/groupreg-sess b/fsfast/bin/groupreg-sess
--- a/fsfast/bin/groupreg-sess
+++ b/fsfast/bin/groupreg-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # groupreg-sess
 #
-set VERSION = '$Id: groupreg-sess,v 1.5 2004/12/01 21:40:48 greve Exp $';
+set VERSION = '$Id: groupreg-sess,v 1.6 2005/01/10 18:37:35 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -20,6 +20,7 @@ set spacedir  = ();
 set hemi      = ();
 set hemicode  = ();
 set PrintHelp = 0;
+set WLS       = 0;
 
 if($#argv == 0)  goto usage_exit;
 set n = `echo $argv | grep -e -help | wc -l` 
@@ -122,6 +123,7 @@ mkdir -p $outdir
 
 # Check that the input volume is there for each subj
 set InstemList = ();
+set InVarStemList = ();
 set FLAXMatList = ();
 foreach sess ($SessList)
   set instem = $sess/$fsd/$analysis/$spacedir/$contrast/$volstem$hemicode
@@ -137,6 +139,14 @@ foreach sess ($SessList)
     exit 1;
   endif
   set InstemList = ($InstemList $instem);
+  if($WLS) then
+    set varstem = $sess/$fsd/$analysis/$spacedir/$contrast/cesvar$hemicode
+    if(! -e $varstem.bhdr) then
+      echo "ERROR: cannot find $varstem.bhdr"
+      exit 1;
+    endif
+    set InVarStemList = ($InVarStemList $varstem);
+  endif
   if("$spacename" == "tal") then
     set reg = $sess/$fsd/$analysis/$spacedir/register.dat
     cp $reg $groupid/$fsd/$analysis/$spacedir-rfx
@@ -174,6 +184,8 @@ hemicode = '$hemicode';
 okfile = '$okfile';
 xmatfile = '$xmat';
 gconmatfile = '$gconmat';
+WLS = $WLS;
+InVarStemList = splitstring('$InVarStemList');
 QuitOnError = ~[$monly];
 fast_group_glm;
 
@@ -279,6 +291,10 @@ while( $#argv != 0 )
       if ( $#argv == 0) goto arg1err;
       set MLF = $argv[1]; shift;
       set monly = 1;
+      breaksw
+
+    case "-wls":
+      set WLS = 1;
       breaksw
 
     case "-umask":
@@ -404,6 +420,7 @@ usage_exit:
   echo "Optional:";
   echo ""
   echo "   -vol  stem : use stem instead of ces"
+  echo "   -wls : use Weighted Least Squares"
   echo ""
   echo "   -df srchdirfile ..."
   echo "   -d  srchdir     ..."
