Removed trap that required space to be tal, sph, or naitve in order to accomodate roidef

diff --git a/fsfast/bin/isxavg-re-sess b/fsfast/bin/isxavg-re-sess
--- a/fsfast/bin/isxavg-re-sess
+++ b/fsfast/bin/isxavg-re-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # isxavg-re-sess - random effects intersubject averaging
 #
-set VERSION = '$Id: isxavg-re-sess,v 1.3 2003/08/28 22:45:06 greve Exp $'
+set VERSION = '$Id: isxavg-re-sess,v 1.4 2004/04/07 17:32:56 greve Exp $'
 set cmdargs = ($argv);
 
 set analysis    = ();
@@ -271,10 +271,11 @@ while( $#argv != 0 )
     case "-space":
       if ( $#argv == 0) goto arg1err;
       set space = $argv[1]; shift;
-      if($space != "tal" && $space != "sph" && $space != "native") then
-        echo "ERROR: space = $space, must be tal, sph, or native"
-        exit 1;
-      endif
+      # Below is removed because it could be an roidef
+      #if($space != "tal" && $space != "sph" && $space != "native") then
+      #  echo "ERROR: space = $space, must be tal, sph, or native"
+      #  exit 1;
+      #endif
       breaksw
 
     case "-spacedir":
@@ -442,7 +443,7 @@ usage_exit:
   echo "Options:";
   echo "   -analysis analysisname : session-level functional analysis name"
   echo "   -group    groupname    : name of group"
-  echo "   -space    spacename    : space in which to average (native, tal, sph)"
+  echo "   -space    spacename    : space in which to average (native, tal, sph, roidef)"
   echo "   -spacedir spacedirname : space in which to average (eg, spm-smooth)"
   echo "   -hemi     hemisphere   : with sph space <lh rh>";
   echo "   -contrast  contrastname: contrast name"
