Added error trap for space.

diff --git a/fsfast/bin/isxavg-re-sess b/fsfast/bin/isxavg-re-sess
--- a/fsfast/bin/isxavg-re-sess
+++ b/fsfast/bin/isxavg-re-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # isxavg-re-sess - random effects intersubject averaging
 #
-set VERSION = '$Id: isxavg-re-sess,v 1.1 2003/03/04 21:22:09 greve Exp $'
+set VERSION = '$Id: isxavg-re-sess,v 1.2 2003/08/28 21:42:24 greve Exp $'
 set cmdargs = ($argv);
 
 set analysis    = ();
@@ -271,6 +271,10 @@ while( $#argv != 0 )
     case "-space":
       if ( $#argv == 0) goto arg1err;
       set space = $argv[1]; shift;
+      if($space != "tal" && $space != "sph" $space != "native") then
+        echo "ERROR: space = $space, must be tal, sph, or native"
+        exit 1;
+      endif
       breaksw
 
     case "-spacedir":
@@ -439,17 +443,18 @@ usage_exit:
   echo "   -analysis analysisname : session-level functional analysis name"
   echo "   -group    groupname    : name of group"
   echo "   -space    spacename    : space in which to average (native, tal, sph)"
+  echo "   -spacedir spacedirname : space in which to average (eg, spm-smooth)"
   echo "   -hemi     hemisphere   : with sph space <lh rh>";
   echo "   -contrast  contrastname: contrast name"
   echo "   -pctsigch  : use percent signal change"
   echo "   -nojackknife           : do not use jackknifing";
   echo "   -trunc  sign : truncation (pos or neg; neg = set neg vals to 0)";
-#  echo "   -compsig               : report (1-sig)";
+  echo ""
   echo "   -sf sessidfile  ..."
   echo "   -df srchdirfile ..."
   echo "   -s  sessid      ..."
   echo "   -d  srchdir     ..."
-#  echo "   -umask umask   : set unix file permission mask"
+  echo ""
   echo "   -scriptonly    : don't run, just generate a script"
   echo "   -version       : print version and exit"
 exit 1;
