More dev

diff --git a/fsfast/bin/isxconcat-sess b/fsfast/bin/isxconcat-sess
--- a/fsfast/bin/isxconcat-sess
+++ b/fsfast/bin/isxconcat-sess
@@ -2,12 +2,14 @@
 # mask
 # cesvar, cespct
 # 
-set VERSION = '$Id: isxconcat-sess,v 1.3 2006/11/28 21:48:13 greve Exp $'
+set VERSION = '$Id: isxconcat-sess,v 1.4 2006/11/29 06:03:05 greve Exp $'
 
 set inputargs = ($argv);
 
 set outvol = ();
 set analysis = ();
+set flac = ();
+set fsd  = ();
 set contrast = ();
 set mapname = ces
 set interp = trilin
@@ -54,14 +56,6 @@ parse_args_return:
 
 goto check_params;
 check_params_return:
-
-## Get functional subdirectory from the info file ##
-set infofile = $analysis/analysis.info
-if(! -e $infofile) then
-  echo "ERROR: cannot find $infofile" 
-  exit 1;
-endif
-set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
 
 ##### Create a log file ######
 set LF = $outvol.log
@@ -192,6 +186,17 @@ while( $#argv != 0 )
       set analysis = $argv[1]; shift;
       breaksw
 
+    case "-f":
+    case "-flac":
+      if ( $#argv == 0) goto arg1err;
+      set flac = $argv[1]; shift;
+      breaksw
+
+    case "-fsd":
+      if ( $#argv == 0) goto arg1err;
+      set fsd = $argv[1]; shift;
+      breaksw
+
     case "-c":
     case "-contrast":
       if ( $#argv == 0) goto arg1err;
@@ -290,9 +295,24 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
-  if($#analysis == 0) then
+  if($#analysis == 0 && $#flac == 0) then
     echo "ERROR: no analysis specified"
     exit 1;
+  endif
+
+  if($#analysis != 0 && $#flac != 0) then
+    echo "ERROR: cannot specify flac and analysis"
+    exit 1;
+  endif
+
+  ## Get functional subdirectory from the info file ##
+  if($#fsd == 0) then
+    set infofile = $analysis/analysis.info
+    if(! -e $infofile) then
+      echo "ERROR: cannot find $infofile, needed for fsd" 
+      exit 1;
+    endif
+    set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
   endif
 
   if(0 & $#contrast == 0) then
@@ -306,7 +326,6 @@ check_params:
   endif
 
   if($Force) rm -f $outvol
-
   if(-e $outvol) then
     echo "ERROR: output $outvol exists, delete or rename or -force"
     exit 1;
@@ -371,7 +390,7 @@ usage_exit:
   echo "   -paired-diff    : compute 1-2, 3-4, etc"
   echo ""
   echo "  Volume-based options:"
-  echo "   -talres res     : 1 or 2 mm"
+  echo "   -talres res     : 1 or 2 mm (def is 2)"
   echo ""
   echo "  Surface-based options:"
   echo "   -hemi hemisphere : for surface-based analysis (lh or rh)";
