Added -fsgd

diff --git a/fsfast/bin/isxconcat0-sess b/fsfast/bin/isxconcat0-sess
--- a/fsfast/bin/isxconcat0-sess
+++ b/fsfast/bin/isxconcat0-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/02/27 19:25:46 $
-#    $Revision: 1.10 $
+#    $Date: 2008/02/28 04:01:55 $
+#    $Revision: 1.11 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: isxconcat0-sess,v 1.10 2008/02/27 19:25:46 greve Exp $';
+set VERSION = '$Id: isxconcat0-sess,v 1.11 2008/02/28 04:01:55 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -43,6 +43,7 @@ set ToVol = 0;
 set ToSurf = 0;
 set DoLogFile = 0;
 set DoSplit = 0;
+set fsgd = ();
 
 # for volume-based only
 set talres = 2;
@@ -52,7 +53,7 @@ set DoMorph = 0;
 set hemi = ();
 set projfrac = ()
 set DoProjFracAvg = 0
-set subject = fsaverage; 
+set trgsubject = fsaverage; 
 
 set tmpdir = ();
 set cleanup = 1;
@@ -84,6 +85,15 @@ parse_args_return:
 goto check_params;
 check_params_return:
 
+if($#fsgd) then
+  set subjlist = (`cat $fsgd | awk '{if($1 == "Input") print $2}'`)
+  if($#subjlist != $#SessList) then
+    echo "ERROR: number of session ($#SessList) does not equal the "
+    echo "       number of subjects ($#subjlist) in fsgd $fsgd"
+    exit 1;
+  endif
+endif
+
 ##### Create a log file ######
 if($DoLogFile) then
   set LF = $outvol.log
@@ -106,7 +116,9 @@ id            >> $LF
 set StartTime = `date`;
 set maplist = ();
 set nframes0 = -1;
+@ nthsess = 0;
 foreach sess ($SessList)
+  @ nthsess = $nthsess + 1;
   set sessid = `basename $sess`;
   set sessinfo = $sess/session.info
   if(-e $sessinfo) then
@@ -124,6 +136,15 @@ foreach sess ($SessList)
   if(! -e $reg) then
     echo "ERROR: cannot find $reg"|& tee -a $LF
     exit 1;
+  endif
+  set subject = `head -n 1 $reg`
+
+  if($#fsgd) then
+    if("$subject" != "$subjlist[$nthsess]") then
+      echo "ERROR: $sessid  subject mismatch with fsgd $fsgd" |& tee -a $LF
+      echo "  $subject vs $subjlist[$nthsess]" |& tee -a $LF
+      exit 1;
+    endif
   endif
 
   set condir = $sess/$fsd/$analysis/$contrast
@@ -153,7 +174,7 @@ foreach sess ($SessList)
 
   if($#hemi != 0) then
     set mapout = $tmpdir/$sessid-$analysis-$contrast-$mapname-$hemi.mgh
-    set cmd = (mri_vol2surf --mov $map --reg $reg --trgsubject $subject)
+    set cmd = (mri_vol2surf --mov $map --reg $reg --trgsubject $trgsubject)
     set cmd = ($cmd --hemi $hemi --interp $interp --noreshape)
     if($#projfrac) set cmd = ($cmd --projfrac $projfrac)
     if($#DoProjFracAvg) set cmd = ($cmd --projfrac-avg 0 1 .2)
@@ -194,7 +215,7 @@ if($#fwhm) then
   endif
   if($ToSurf) then
     set cmd = (mris_fwhm --i $outvol --o $outvol --fwhm $fwhm \
-      --subject $subject --hemi $hemi --no-detrend)
+      --subject $trgsubject --hemi $hemi --no-detrend)
   endif
   echo "------------------------------------" |& tee -a $LF
   pwd |& tee -a $LF
@@ -330,10 +351,20 @@ while( $#argv != 0 )
       set ToSurf = 1;
       breaksw
 
+    case "-trgsubject":
     case "-subject":
       if( $#argv == 0) goto arg1err;
-      set subject = $argv[1]; shift;
+      set trgsubject = $argv[1]; shift;
       set ToSurf = 1;
+      breaksw
+
+    case "-fsgd":
+      if($#argv == 0) goto arg1err;
+      set fsgd = $argv[1]; shift;
+      if(! -e $fsgd) then
+        echo "ERROR: cannot find $fsgd"
+        exit 0;
+      endif
       breaksw
 
     case "-tmpdir":
@@ -513,7 +544,7 @@ usage_exit:
   echo "   -hemi hemisphere : for surface-based analysis (lh or rh)";
   echo "   -projfrac frac   : sample frac into surface (def is 0.5)"
   echo "   -projfrac-avg    : average over cortex"
-  echo "   -subject subject : sample to subject's surface (def fsaverage)"
+  echo "   -trgsubject subject : sample to subject's surface (def fsaverage)"
   echo ""
   echo "   -space spacename : tal, lh. rh"
   echo ""
@@ -521,6 +552,8 @@ usage_exit:
   echo "   -df srchdirfile ..."
   echo "   -s  sessid      ..."
   echo "   -d  srchdir     ..."
+  echo ""
+  echo "   -fsgd fsgdfile : for comparing subject order"
   echo ""
   echo "   -help"
   echo "   -debug"
