fairly major changes plus docs

diff --git a/fsfast/bin/kmacf-sess b/fsfast/bin/kmacf-sess
--- a/fsfast/bin/kmacf-sess
+++ b/fsfast/bin/kmacf-sess
@@ -1,8 +1,8 @@
 #!/bin/csh -f
 # kmacf-sess
 #
-# $Id: kmacf-sess,v 1.2 2003/04/15 04:00:30 greve Exp $
-set VERSION = '$Id: kmacf-sess,v 1.2 2003/04/15 04:00:30 greve Exp $';
+# $Id: kmacf-sess,v 1.3 2003/04/22 05:39:15 greve Exp $
+set VERSION = '$Id: kmacf-sess,v 1.3 2003/04/22 05:39:15 greve Exp $';
 set FASTVER = `cat $FSFAST_HOME/docs/version`;
 
 set inputargs = ($argv);
@@ -11,31 +11,32 @@ set DateStr = "`date '+%y%m%d%H%M'`"
 set TopDir = `pwd`;
 
 set analysis = ();
-set anapend = ();
 set nclusters = ();
 set nmaxlag = ();
 set acfdirname = acf;
-set mask = ();
+set mask = brain;
 set outbase = ();
 set monly = 0;
 set MLF = ();
 set QuitOnError = 0;
 set FitPolyZ = 0;
 set PolyZOrder = 0;
+set UseKJW = 0;
+set InitMethod = '';
+set kmacfid = ();
+set PrintHelp = 0;
 
-if($#argv == 0) then
-  goto usage_exit;
-  exit 1;
-endif
-
+if($#argv == 0) goto usage_exit;
 set n = `echo $argv | grep version | wc -l` 
 if($n != 0) then
   echo $VERSION
   exit 0;
 endif
-
-set n = `echo $argv | grep -e -help | wc -l` 
-if($n != 0)  goto help
+set n = `echo $argv | grep help | wc -l` 
+if($n != 0) then
+  set PrintHelp = 1;
+  goto usage_exit;
+endif
 
 set SessList = `getsesspath $argv`;
 if($status || $#SessList == 0) then
@@ -173,6 +174,7 @@ clear all;
 fsdpath = '$fsdpath';
 cd(fsdpath);
 
+kmacfid   = '$kmacfid';
 acfstem   = '$acfstem';
 maskstem   = '$maskstem';
 nmaxlag   = $nmaxlag;
@@ -182,6 +184,8 @@ outbasestem = '$outbasestem';
 xmatfile    = '$xmatfile';
 fitpolyz    = $FitPolyZ;
 polyzorder  = $PolyZOrder;
+usekjw      = $UseKJW;
+initmethod  = '$InitMethod';
 
 fast_kmacf;
 
@@ -225,9 +229,9 @@ while( $#argv != 0 )
       set analysis = `basename $analysis`; # remove trailing /
       breaksw
 
-    case "-anapend":
+    case "-kmacfid":
       if ( $#argv == 0) goto arg1err;
-      set anapend = $argv[1]; shift;
+      set kmacfid = $argv[1]; shift;
       breaksw
 
     case "-k":
@@ -272,8 +276,18 @@ while( $#argv != 0 )
       set monly = 1;
       breaksw
 
-    case "-help":
-      goto help;
+    case "-nomask":
+      set mask = ();
+      breaksw
+
+    case "-init":
+      if ( $#argv < 1) goto arg1err;
+      set InitMethod = $argv[1]; shift;
+      breaksw
+
+    case "-debias":
+    case "-kjw":
+      set UseKJW = 1;
       breaksw
 
     case "-verbose":
@@ -342,6 +356,11 @@ check_params:
     exit 1;
   endif
 
+  if($#kmacfid == 0) then
+    echo "ERROR: no kmacf id specified"
+    exit 1;
+  endif
+
   if($#nmaxlag == 0) then
     echo "ERROR: nmaxlag not specified"
     exit 1;
@@ -374,15 +393,17 @@ usage_exit:
   echo ""
   echo "Required Arguments:";
   echo "   -analysis  analysisname : name of functional analysis"
+  echo "   -kmacfid   id : id used for naming"
   echo "   -k         nclusters    : number of clusters"
   echo "   -nmaxlag   nmaxlag      : max lag when fitting"
   echo "   -nitersmax nitersmax    : maximum number of iterations"
   echo ""
   echo "Optional Arguments:";
-  echo "   -anapend  anapend "
-  echo "   -acfdir  acfdirname : default is acf"
-  echo "   -mask    stem : use mask in FSD/masks/stem"
-  echo "   -o       outbase : acfRRR"
+  #echo "   -acfdir  acfdirname : default is acf"
+  echo "   -mask    stem : use mask in FSD/masks/stem (default brain)"
+  echo "   -nomask  : do not use a mask"
+  echo "   -init method : firstlag or svd"
+#  echo "   -o       outbase : acfRRR"
   echo ""
   echo "Session Arguments (Required)"
   echo "   -sf sessidfile  ..."
@@ -395,11 +416,72 @@ usage_exit:
   echo "   -version       : print version and exit"
   echo ""
   echo ""
+
+  if($PrintHelp) \
+  cat $0 | awk 'BEGIN{prt=0}{if(prt) print $0; if($1 == "BEGINHELP") prt = 1 }'
+
 exit 1;
 
-#-----------------------------------------------------------#
-help:
+#---- Everything below here is printed out as part of help -----#
+BEGINHELP
 
-  echo ""
+Performs k-means clustering of the autocorrelation functions (ACFs) of
+the residuals of the given analysis as saved by a run of
+selxavg-sess-perrun -svacf. The cluster map is saved in
+ana/acf/acf001-kmacfid-kmap, and the cluster vectors are saved in
+ana/acf/acf001-kmacfid-racf, where kmacfid is the argument to the
+-kmacfid flag. These will be used by kmacfcond-sess and
+kmacfwht-sess. By default, only the voxels found in the brain mask are
+used; this can be changed with -nomask or -mask newmask.
 
-exit;
+-kmacfid id
+
+Unique id that will be used to name files.
+
+-k nclusters
+
+Run k-means with nclusters. Suggest 10.
+
+-nmaxlag nmaxlag
+
+Train k-means with nmaxlag components of the ACF. This is only used
+when determining the cluster vectors. The output ACFs will have a
+length equal to that of the input acf.
+
+-nitersmax nitersmax 
+
+Run k-means with a maximum nitersmax iterations. Suggest 25.
+
+-mask maskname
+
+Use maskname (as found in fsd/masks) instead of brain.
+
+-nomask
+
+Do not use a mask at all.
+
+-init method
+
+Initialize the k-means with either firstlag or svd. With firstlag,
+k-means is run on the first lag of the ACF (this takes about 10-15
+sec), then a new set of nmaxlag length k-means are computed from this
+map and used as input to the full k-means. With svd, the top ncluster
+eigenvectors of the input data set are used. If no init method is
+specified, then the first nclusters from the input set are used.
+Suggest: firstlag.
+
+-polyz order
+
+Remove components from the input data set that are not spanned by the
+space of a polynomial of the given order. This polynomial basis
+is set up to have a zero at nmaxlag. See fast_polyzacf_fit.m. Suggest
+not using this.
+
+-debias
+
+Remove bias from the input ACF. The bias comes from the fact that the
+ACFs are from the residual and not the actual noise process.  Uses
+method proposed by KJW. See fast_kjw_mtx.m. Suggest not using this
+here; use with kmacfcond-sess.
+
+See also fast_kmacf.m, kmacfcond-sess, kmacfwht-sess
