Allows spec of explict run to use as target

diff --git a/fsfast/bin/mc-sess b/fsfast/bin/mc-sess
--- a/fsfast/bin/mc-sess
+++ b/fsfast/bin/mc-sess
@@ -1,9 +1,9 @@
 #!/bin/csh -f
 # mc-sess - motion correction
 #
-# $Id: mc-sess,v 1.4 2003/10/04 20:16:47 greve Exp $
+# $Id: mc-sess,v 1.5 2005/01/26 19:53:48 greve Exp $
 
-set VERSION    = '$Id: mc-sess,v 1.4 2003/10/04 20:16:47 greve Exp $'
+set VERSION    = '$Id: mc-sess,v 1.5 2005/01/26 19:53:48 greve Exp $'
 set cmdargs = ($argv);
 
 set ScriptOnly = 0;
@@ -16,6 +16,7 @@ set funcstem   = f;  # stem of functional volume
 set funcmcstem = (); # stem of functional motion-corrected volume
 set PWDCMD = `getpwdcmd`;
 set targnthrun = 1;  # use nth run as target
+set targrun = ();    # use explicit run as target
 set nolog = 0;
 set RunListFile = ();
 
@@ -126,12 +127,18 @@ foreach sess ($SessList)
     chmod a+x $scriptfile
   endif
 
-  if($#RunList < $targnthrun) then
-    echo "ERROR: $sessid target run ($targnthrun) exceeds number of runs ($#RunList)"
-    exit 1;
+  if($#targrun == 0) then
+    if($#RunList < $targnthrun) then
+      echo "ERROR: $sessid target run ($targnthrun) exceeds "
+      echo "   number of runs ($#RunList)."
+      exit 1;
+    endif
+    if(! $PerRun) set targstem = $RunList[$targnthrun]/$funcstem
+  else
+    if(! $PerRun) set targstem = $targrun/$funcstem
   endif
+  echo "Targ Stem is $targstem"
 
-  if(! $PerRun) set targstem = $RunList[$targnthrun]/$funcstem
   foreach run ($RunList)  
     echo "  ------- ************************** -----------" |& tee -a $LF
     echo "  ------- Motion Correcting Run $run -----------" |& tee -a $LF
@@ -214,6 +221,11 @@ while( $#argv != 0 )
     case "-targnthrun":
       if ( $#argv == 0) goto arg1err;
       set targnthrun = $argv[1]; shift;
+      breaksw
+
+    case "-targrun":
+      if ( $#argv == 0) goto arg1err;
+      set targrun = $argv[1]; shift;
       breaksw
 
     case "-runlistfile":
@@ -313,6 +325,7 @@ usage_exit:
   echo "Optional Arguments:";
   echo "   -method  mcmethod  : afni"
   echo "   -targnthrun n      : use nth run as target (default=1)"
+  echo "   -targrun RRR       : use run RRR as target"
   echo "   -toff m            : target image offset ($targoff)"
   echo "   -fstem stem        : stem of output motion-corrected volume (fmc)"
   echo "   -fmcstem stem      : stem of output motion-corrected volume (fmc)"
diff --git a/fsfast/bin/preproc-sess b/fsfast/bin/preproc-sess
--- a/fsfast/bin/preproc-sess
+++ b/fsfast/bin/preproc-sess
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # preproc-sess - runs preprocessing (mc, spatsmooth, mkbrainmask, inorm)
 
-set VERSION = '$Id: preproc-sess,v 1.4 2004/02/10 22:33:56 greve Exp $';
+set VERSION = '$Id: preproc-sess,v 1.5 2005/01/26 19:53:48 greve Exp $';
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M'`"
@@ -17,6 +17,7 @@ set fwhm    = ();
 set fsd     = bold;
 set rlf     = ();
 set mcnthrun = ();
+set mcrun    = ();
 set MCPerRun = 0;
 set DoMC     = 1;
 set DoSmooth = 1;
@@ -107,6 +108,7 @@ foreach sess ($SessList)
     set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
     if($MCPerRun) set cmd = ($cmd -perrun)
     if($#mcnthrun) set cmd = ($cmd -targnthrun $mcnthrun)
+    if($#mcrun)    set cmd = ($cmd -targrun    $mcrun)
     if($#rlf != 0) set cmd = ($cmd -rlf $rlf);
     echo "$sessid MC -----------------------------" |& tee -a $LF
     date      |& tee -a $LF
@@ -205,6 +207,11 @@ while( $#argv != 0 )
     case "-mcnthrun":
       if ( $#argv == 0) goto arg1err;
       set mcnthrun = $argv[1]; shift;
+      breaksw
+
+    case "-mcrun":
+      if ( $#argv == 0) goto arg1err;
+      set mcrun = $argv[1]; shift;
       breaksw
 
     case "-smin":
@@ -343,8 +350,13 @@ check_params:
     endif
   endif
 
-  if($MCPerRun && $#mcnthrun) then
+  if($MCPerRun && $#mcnthrun ) then
     echo "ERROR: cannot specify both -mcperrun and -mcnthrun"
+    exit 1;
+  endif
+
+  if($MCPerRun && $#mcrun ) then
+    echo "ERROR: cannot specify both -mcperrun and -mcrun"
     exit 1;
   endif
 
@@ -378,6 +390,7 @@ usage_exit:
   echo "  -rlf    rlf  : run list file (default all runs)"
   echo "  -mcperrun : perform motion correction on all runs separately"
   echo "  -mcnthrun nthrun : use nthrun as reference"
+  echo "  -mcrun    RRR    : use run RRR as reference"
   echo ""
   echo "  -nomc     : don't do motion correction"
   echo "  -nosmooth : don't do smoothing"
