Now requires users to spec -per-run or per-session

diff --git a/fsfast/bin/mc-sess b/fsfast/bin/mc-sess
--- a/fsfast/bin/mc-sess
+++ b/fsfast/bin/mc-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/13 19:56:48 $
-#    $Revision: 1.24 $
+#    $Date: 2010/04/15 18:49:34 $
+#    $Revision: 1.25 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION    = '$Id: mc-sess,v 1.24 2010/04/13 19:56:48 greve Exp $'
+set VERSION    = '$Id: mc-sess,v 1.25 2010/04/15 18:49:34 greve Exp $'
 set cmdargs = ($argv);
 
 set fsd = "bold";
@@ -31,6 +31,7 @@ set mcmethod   = "afni"
 set targoff    = 0;
 set targoffmid = 0;
 set PerRun = 0;
+set PerSess = 0;
 set funcstem   = f;  # stem of functional volume
 set funcmcstem = (); # stem of functional motion-corrected volume
 set PWDCMD = `getpwdcmd`;
@@ -135,7 +136,7 @@ foreach sess ($SessList)
   endif
   echo "RunList: $RunList" |& tee -a $LF
 
-  if(! $PerRun) then
+  if($PerSess) then
     set template = `stem2fname template`
     if($status) then
       echo "ERROR: cannot find $template for $sess/$fsd"  |& tee -a $LF
@@ -193,8 +194,8 @@ foreach sess ($SessList)
     #set cmd = (mcparams2extreg -mcfile $outstem.mcdat -northog 6)
     #set cmd = ($cmd -extreg $run/mcextreg)
     
-    if(! $PerRun) set mcextreg = $run/mcextreg
-    if($PerRun)   set mcextreg = $run/mcprextreg
+    if($PerSess) set mcextreg = $run/mcextreg
+    if($PerRun)  set mcextreg = $run/mcprextreg
     set cmd = (mcdat2mcextreg --i $outstem.mcdat --o $mcextreg)
     echo $cmd |& tee -a $LF
     $cmd |& tee -a $LF
@@ -263,9 +264,11 @@ while( $#argv != 0 )
     case "-per-run":
     case "-perrun":
       set PerRun = 1;
+      set PerSess = 0;
       breaksw
 
     case "-per-session":
+      set PerSess = 1;
       set PerRun = 0;
       breaksw
 
@@ -325,6 +328,11 @@ if($#SessList == 0) then
   echo "ERROR: no sessions specified"
   exit 1
 endif
+if($PerRun == 0 && $PerSess == 0) then
+  echo "ERROR: You must specify -per-run or -per-session"
+  exit 1;
+endif
+
 if($#funcmcstem == 0) then
   if($PerRun) then
     set funcmcstem = fmcpr
@@ -353,13 +361,15 @@ usage_exit:
   echo "   -s  sessid      "
   echo "   -d  srchdir     "
   echo ""
+  echo "You must specify one of these"
+  echo "   -per-run           : MC each run to run-level template"
+  echo "   -per-session       : MC each run to session-level template"
+  echo ""
   echo "Optional Arguments:";
   echo "   -fsd dir        (optional - default = bold)"
   echo "   -fstem fstem       : stem of input volume <f>"
   echo "   -fmcstem fmcstem   : stem of output motion-corrected volume (fmc or fmcpr)"
   echo ""
-  echo "   -per-run           : MC each run to run-level template"
-  echo "   -per-session       : MC each run to session-level template"
   echo "   -outfmt format     : nii, nii.gz, mgh, or mgz (default is $outfmt)"
   echo "   -update            : only mc if input is newer than output"
   echo "   -version           : print version and exit"
