Added ability to do rfx and ffx

diff --git a/fsfast/bin/mergecontrasts-sess b/fsfast/bin/mergecontrasts-sess
--- a/fsfast/bin/mergecontrasts-sess
+++ b/fsfast/bin/mergecontrasts-sess
@@ -2,7 +2,7 @@
 # mergecontrasts-sess - AND conjunction of two contrasts
 #
 
-set VERSION = '$Id: mergecontrasts-sess,v 1.3 2005/11/30 22:58:14 greve Exp $';
+set VERSION = '$Id: mergecontrasts-sess,v 1.4 2005/12/01 20:56:58 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -25,6 +25,8 @@ set monly = 0;
 set MLF = ();
 set nolog = 0;
 set checkvolumes = 0;
+
+set isxavgmethod  = ();
 
 set PrintHelp = 0;
 
@@ -55,6 +57,10 @@ endif
 
 goto check_params;
 check_params_return:
+
+set FX = ();
+if("$isxavgmethod" == fixed)  set FX = "-ffx";
+if("$isxavgmethod" == random) set FX = "-rfx";
 
 ## Get functional subdirectory from the info file ##
 set infofile = $analysis/analysis.info
@@ -102,7 +108,7 @@ foreach sess ($SessList)
   set inbhdr  = ();
   set instems = ();
   foreach contrast ($contrastlist)
-    set indir = $sess/$fsd/$analysis/$spacedir/$contrast
+    set indir = $sess/$fsd/$analysis/$spacedir$FX/$contrast
     if(! -d $indir) then
       echo "ERROR: $indir does not exist"   |& tee -a $LF
       exit 1;
@@ -123,7 +129,7 @@ foreach sess ($SessList)
   end
   endif
 
-  set outdir = $sess/$fsd/$analysis/$spacedir/$mergedcontrast
+  set outdir = $sess/$fsd/$analysis/$spacedir$FX/$mergedcontrast
   mkdir -p $outdir
   if(! -d $outdir) then
     echo "ERROR: cannot create $outdir"|& tee -a $LF
@@ -316,6 +322,15 @@ while( $#argv != 0 )
       endif
       breaksw
 
+    case "-isxavg":
+      if ( $#argv == 0) goto arg1err;
+      set isxavgmethod = $argv[1]; shift;
+      if($isxavgmethod != "fixed" && $isxavgmethod != "random") then
+        echo "ERROR: -isxavg must be either fixed or random"
+        exit 1;
+      endif
+      breaksw
+
     case "-monly":
       if ( $#argv == 0) goto arg1err;
       set MLF = $argv[1]; shift;
@@ -461,6 +476,7 @@ usage_exit:
   echo "   -map       mapname"
   echo "   -space  spacename : tal or sph"
   echo "   -spacedir spacedir : if not tal or sph"
+  echo "   -isxavg    method (fixed or random)"
   echo "   -sf sessidfile  ..."
   echo "   -df srchdirfile ..."
   echo "   -s  sessid      ..."
