Added error trap so that people do not spec -per-run with -per-session or -native

diff --git a/fsfast/bin/mkanalysis-sess b/fsfast/bin/mkanalysis-sess
--- a/fsfast/bin/mkanalysis-sess
+++ b/fsfast/bin/mkanalysis-sess
@@ -7,8 +7,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2013/01/22 21:50:52 $
-#    $Revision: 1.72 $
+#    $Date: 2014/11/18 17:14:38 $
+#    $Revision: 1.73 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: mkanalysis-sess,v 1.72 2013/01/22 21:50:52 greve Exp $';
+set VERSION = '$Id: mkanalysis-sess,v 1.73 2014/11/18 17:14:38 greve Exp $';
 
 set analysis = ();
 set TR = ();
@@ -492,18 +492,31 @@ while( $#argv != 0 )
       breaksw
 
     case "-per-run":
+      if($PerSession) then
+        echo "ERROR: cannot spec -per-run and -per-session or -native"
+        exit 1;
+      endif
       set PerRun = 1;
       set PerSession = 0;
       set mcstem = fmcpr
       breaksw
 
     case "-per-session":
+      if($PerRun) then
+        echo "ERROR: cannot specify -per-run and -per-session"
+        exit 1;
+      endif
       set PerRun = 0;
       set PerSession = 1;
       set mcstem = fmc
       breaksw
 
     case "-native":
+      if($PerRun) then
+        echo "ERROR: cannot specify -per-run and -native"
+        exit 1;
+      endif
+      set PerRun = 0;
       set PerSession = 1;
       set RawSpaceType = volume
       set RawSpace = native
