Updated anat specifiers in mkanalysis. selxavg3 implements inorm with global.meanval.dat; it also masks.

diff --git a/fsfast/bin/mkanalysis-sess b/fsfast/bin/mkanalysis-sess
--- a/fsfast/bin/mkanalysis-sess
+++ b/fsfast/bin/mkanalysis-sess
@@ -7,8 +7,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/01 21:28:13 $
-#    $Revision: 1.30 $
+#    $Date: 2010/04/02 23:18:21 $
+#    $Revision: 1.31 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: mkanalysis-sess,v 1.30 2010/04/01 21:28:13 greve Exp $';
+set VERSION = '$Id: mkanalysis-sess,v 1.31 2010/04/02 23:18:21 greve Exp $';
 
 # These two should agree with values in mkanalysis_gui.m
 set DefaultTER     = .050; # 50 ms
@@ -39,6 +39,7 @@ set fsd    = ();
 set parname    = ();
 set analysis   = ();
 set cloneanalysis = ();
+set CopyCloneCons = 0;
 set funcstem   = f;
 set designtype = ();
 set eventrelated = 0;
@@ -76,7 +77,7 @@ set timeoffset = ();
 set extreg = ();
 set nextreg = ();
 set extregorthog = 0;
-set maskstem = ();
+set maskstem = brain;
 set autostimdur = ();
 set stimdur = ();
 set PrintHelp = 0;
@@ -87,6 +88,9 @@ set FSV3whiten = 0;
 set mfile = ();
 set monly = 0;
 set RefEventDur = ();
+set subject = ();
+set hemi = ();
+set UseTalairach = ()
 
 #### If no arguments, print usage and exit ####
 if($#argv == 0) goto usage_exit;
@@ -116,11 +120,6 @@ parse_args_return:
 
 goto check_params;
 check_params_return:
-
-## File permission masking ###
-if(! $?MRI_UMASK ) set MRI_UMASK = `umask`;
-umask $MRI_UMASK;
-set umaskarg = "-umask $MRI_UMASK"
 
 #-----------------------------------------
 if($UseGUI) then
@@ -239,6 +238,9 @@ if($#runlistfile != 0) echo "runlistfile $runlistfile" >> $infofile
 echo "tpexclude  $tpexclude"  >> $infofile
 if($#parname)  echo "parname    $parname"    >> $infofile
 echo "designtype $designtype" >> $infofile
+if($#maskstem != 0) echo "maskstem $maskstem" >> $infofile
+if($#subject) echo "surface $subject $hemi" >> $infofile
+if($UseTalairach) echo "UseTalairach" >> $infofile
 if($eventrelated || $blocked) then
   echo "nconditions $nconditions"  >> $infofile 
   @ nthc = 1
@@ -247,122 +249,11 @@ if($eventrelated || $blocked) then
     @ nthc = $nthc + 1
   end
 endif
-if($#maskstem != 0) echo "maskstem $maskstem" >> $infofile
 
-if($#SessList == 0) then
-  echo "Completed successfully"
-  exit 0;
-endif
+if($CopyCloneCons && $#cloneanalysis) cp $cloneanalysis/*.mat $analysis
 
-#----- Set up session-level scripts -------#
-echo $SessList
+echo "mkanalysis-sess done"
 
-set TRAnalysis = $TR;
-
-# Go through each session, make sure it exists, and check consistency #
-set n = 1;
-foreach sess ($SessList)
-  set sessbase = `basename $sess`;
-
-  ## check that the runlistfile exists ##
-  if($#runlistfile != 0) then
-    set rlf = $sess/$fsd/$runlistfile
-    if(! -e $rlf) then
-      echo "ERROR: cannot find $rlf"
-      exit 1;
-    endif
-  endif
-
-  @ n = $n + 1;
-end # Loop over sessions #
-
-mkdir -p scripts
-set scriptsdir = $analysis/scripts
-mkdir -p $scriptsdir
-
-##---- Create default motion correction script ------#
-set scr = scripts/run-mc-sess
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Motion-Correction " >> $scr
-echo "cd .."                >> $scr
-echo "mc-sess -method afni -toff 0 $GSPArgs $umaskarg" >> $scr
-echo ""                     >> $scr
-
-if($designtype == "event-related" || $designtype == "blocked") then
-##---- Create default selxavg script ------##
-set scr = $scriptsdir/run-selxavg-sess
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Within-Session Averaging of Raw (ie, Not Motion-Corrected) Data" >> $scr
-echo "cd ../.."                >> $scr
-echo "selxavg-sess -analysis $analysis $GSPArgs " >> $scr
-echo ""                     >> $scr
-
-##---- Create default stxgrinder subject script ------#
-set scr = $scriptsdir/run-stxgrinder-subj
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Session-Level Statistical Grinding " >> $scr
-echo "cd ../.."                >> $scr
-echo "stxgrinder-sess -contrast allvfix -analysis $analysis -umask 0 $GSPArgs " >> $scr
-echo ""                     >> $scr
-
-##---- Create default tal script ------#
-set scr = $scriptsdir/run-func2tal-sess
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Resampling of functional averages into Talariach Space" >> $scr
-echo "cd ../.."                >> $scr
-echo "func2tal-sess -res 4 -analysis $analysis $GSPArgs -umask 0" >> $scr
-echo ""                     >> $scr
-
-##---- Create default func2sph script ------#
-set scr = $scriptsdir/run-func2sph-sess
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Resampling of functional averages into Spherical Space" >> $scr
-echo "cd ../.."                >> $scr
-echo "func2sph-sess -analysis $analysis $GSPArgs -umask 0">> $scr
-echo ""                     >> $scr
-
-##---- Create default isxavg-fe script ------#
-set scr = $scriptsdir/run-isxavg-fe-sess
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Intersubject Averaging (Fixed-Effects) in  Talariach Space" >> $scr
-echo "cd ../.."                >> $scr
-echo "isxavg-fe-sess -grpname all -analysis $analysis -resamp tal $GSPArgs -umask 0">> $scr
-echo ""                     >> $scr
-
-##---- Create default stxgrinder group script ------#
-set scr = $scriptsdir/run-stxgrinder-grp
-rm -f $scr
-touch $scr
-chmod a+x $scr
-echo "#\!/bin/csh -f "      >> $scr
-echo "# Group-Level Statistical Grinding " >> $scr
-echo "cd ../.."                >> $scr
-echo "stxgrinder-sess -contrast allvfix -analysis $analysis -umask 0 -grpname all -resamp tal" >> $scr
-echo ""                     >> $scr
-endif
-
-# Delete the h.dat file if it exists
-rm -f  $analysis/h.dat
-
-echo "Completed successfully"
 exit 0;
 ###############################################
 
@@ -390,6 +281,12 @@ while( $#argv != 0 )
       set GSPArgs = ($GSPArgs -cwd);
       breaksw
 
+    case "-copy-clone-contrasts":
+    case "-copy-clone-con":
+    case "-ccc":
+      set CopyCloneCons = 1;
+      breaksw
+
     case "-clone":
       if ( $#argv == 0) goto arg1err;
       set cloneanalysis = $argv[1]; shift;
@@ -411,6 +308,14 @@ while( $#argv != 0 )
   set TR = `cat $cainfo   | awk '{if($1 == "TR") print $2}'`;
   set tmp = `cat $cainfo | awk '{if($1 == "RefEventDur") print $2}'`;
   if($#tmp) set RefEventDur = $tmp
+  set tmp = `cat $cainfo | awk '{if($1 == "surface") print $2" "$3}'`;
+  if($#tmp) then
+    set subject = $tmp[1];
+    set hemi = $tmp[2];
+  endif
+  set tmp = `cat $cainfo | awk '{if($1 == "hemi") print $2}'`;
+  if($#tmp) set hemi = $tmp
+  set UseTalairach = `cat $cainfo | awk '{if($1 == "UseTalairach") print $2}'`;
   set designtype = `cat $cainfo | awk '{if($1 == "designtype") print $2}'`;
   set fsd       = `cat $cainfo | awk '{if($1 == "fsd") print $2}'`;
   set funcstem  = `cat $cainfo | awk '{if($1 == "funcstem") print $2}'`;
@@ -418,7 +323,8 @@ while( $#argv != 0 )
   set tpexclude = `cat $cainfo | awk '{if($1 == "tpexclude") print $2}'`;
   set runlistfile = `cat $cainfo | awk '{if($1 == "runlistfile") print $2}'`;
   set nconditions = `cat $cainfo | awk '{if($1 == "nconditions") print $2}'`;
-  set maskstem = `cat $cainfo | awk '{if($1 == "maskstem") print $2}'`;
+  set tmp = `cat $cainfo | awk '{if($1 == "maskstem") print $2}'`;
+  if($#tmp) set maskstem = $tmp;
 
   set gDelta = `cat $cacfg | awk '{if($1 == "-gammafit") print $2}'`;
   set gTau   = `cat $cacfg | awk '{if($1 == "-gammafit") print $3}'`;
@@ -683,6 +589,36 @@ while( $#argv != 0 )
       set ncycles = $argv[1]; shift;
       breaksw
 
+    case "-surface":
+    case "-surf":
+      if($#argv < 2) goto arg2err;
+      set subject = $argv[1]; shift;
+      set hemi = $argv[1]; shift;
+      breaksw
+    case "-no-surf":
+    case "-no-surface":
+      set subject = ();
+      set hemi = ();
+      breaksw
+
+    case "-tal":
+    case "-talairach":
+      set UseTalairach = 1;
+      breaksw
+
+    case "-no-tal":
+    case "-no-talairach":
+      set UseTalairach = 0;
+      breaksw
+
+    case "-perrun":
+      set PerRun = 1;
+      breaksw
+
+    case "-synth":
+      set DoSynth = 1;
+      breaksw
+
     case "-designtype":
     case "-design":
     case "-dt":
@@ -902,27 +838,17 @@ check_params:
   if($#fsd == 0)  set fsd = bold
 
   if($#funcstem == 0) then
-    if($motioncor) then
-      set funcstem = fmc;
-    else
-      set funcstem = f;
-    endif
-  endif
-
-  if($#designtype == 0) then
-    echo "ERROR: must specify a design type"
+    echo "ERROR: must specify a funcstem"
     exit 1;
   endif
 
+  if($#designtype == 0) set designtype = "event-related"
   if("$designtype" == "event-related") set eventrelated = 1;
   if("$designtype" == "blocked")       set blocked      = 1;
   if("$designtype" == "abblocked")     set abblocked    = 1;
   if("$designtype" == "retinotopy")    set retinotopy   = 1;
 
-  if($#parname == 0 && $abblocked) then
-    set parname = NONE;
-  endif
-
+  if($#parname == 0 && $abblocked)  set parname = NONE;
   if($#parname == 0) then
     echo "ERROR: must specify a paradigm file name"
     exit 1;
@@ -990,6 +916,11 @@ check_params:
 
   if(($gammafit || $spmhrf != -1) && $#RefEventDur == 0) then
     echo "ERROR: you must specify a reference event duration with an HRF"
+    exit 1;
+  endif
+
+  if($#subject && $UseTalairach) then
+    echo "ERROR: cannot use -surface and -talairach"
     exit 1;
   endif
 
diff --git a/fsfast/bin/tksurfer-sess b/fsfast/bin/tksurfer-sess
--- a/fsfast/bin/tksurfer-sess
+++ b/fsfast/bin/tksurfer-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/03/25 16:25:08 $
-#    $Revision: 1.9 $
+#    $Date: 2010/04/02 23:18:21 $
+#    $Revision: 1.10 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: tksurfer-sess,v 1.9 2010/03/25 16:25:08 greve Exp $'
+set VERSION = '$Id: tksurfer-sess,v 1.10 2010/04/02 23:18:21 greve Exp $'
 set inputargs = ($argv);
 set analysis      = ();
 set contrastlist   = ();
@@ -41,6 +41,12 @@ set Delink = 0;
 set UseVol2Surf = 1;
 set ProjFrac = 0.5;
 set Interp = nearest
+set ToSelf = 0;
+
+set SurfAna = 0;
+set UseTalairach = 0;
+set subject = ();
+
 
 if($#argv == 0) goto usage_exit;
 set n = `echo $argv | grep -e -help | wc -l` 
@@ -54,42 +60,78 @@ if($n != 0) then
   echo $VERSION
   exit 0;
 endif
-
 set SessList = (`getsesspath $argv`);
 if($status || $#SessList == 0) then
   echo $SessList
   exit 1;
 endif
-
 goto parse_args;
 parse_args_return:
-
 goto check_params;
 check_params_return:
 
-## Get functional subdirectory from the info file ##
-set infofile = $analysis/analysis.info
-set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
-set designtype = `cat $infofile | awk '{if($1 == "designtype") print $2}'`;
-if($#designtype == 0) then
-  set designtype = `cat $infofile | awk '{if($1 == "avgtype") print $2}'`;
-endif
-if("$designtype" != "event-related") set ShowHDR = 0;
-
-set cfgfile = $analysis/analysis.cfg
-set gammafit  = (`cat $cfgfile | awk '{if($1 == "-gammafit") print 1}'`);
-set spmhrffit = (`cat $cfgfile | awk '{if($1 == "-spmhrf")   print 1}'`);
-if($#gammafit || $#spmhrffit) set ShowHDR = 0;
-
-## Get map functional subdirectory from the info file ##
-if($#mapanalysis != 0) then
-  if(! -e $mapanalysis ) then
-    echo "ERROR: $mapanalysis does not exist. Try running mkanalysis-sess" 
+## Parse the analysis
+if($#analysis != 0) then
+  if(! -e $analysis ) then
+    echo "ERROR: $analysis does not exist." |& tee -a $LF
     exit 1;
   endif
-  set mapfsd = `cat $mapanalysis/analysis.info | awk '{if($1 == "fsd") print $2}'`;
-else
-  set mapfsd = $fsd
+  set infofile = $analysis/analysis.info
+  set cfg = $analysis/analysis.cfg
+  set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
+  set designtype = `cat $infofile | awk '{if($1 == "designtype") print $2}'`;
+  if($#designtype == 0) then
+    set designtype = `cat $infofile | awk '{if($1 == "avgtype") print $2}'`;
+  endif
+  set tmp = `cat $infofile | awk '{if($1 == "surface") print $2" "$3}'`;
+  if($#tmp != 0) then
+    set SurfAna = 1;
+    set subject = $tmp[1];
+    set hemi    = $tmp[2]; # may overwrite -hemi
+    echo "Surface $subject $hemi"
+    set UseVol2Surf = 0;
+  endif
+  set tmp = `cat $infofile | awk '{if($1 == "UseTalairach") print 1}'`;
+  set UseTalairach = $#tmp;
+  if($UseTalairach) set subject = fsaverage
+  set IsFIR = 1;
+  set tmp = `grep -e -gammafit $cfg`;
+  if($#tmp) set IsFIR = 0;
+  set tmp = `grep -e -spmhrf $cfg`;
+  if($#tmp) set IsFIR = 0;
+endif
+if(! $IsFIR) set ShowHDR = 0;
+if($#hemi == 0) then
+  echo "ERROR: no hemisphere specified" 
+  exit 1;
+endif
+
+## Parse the map analysis
+if($#mapanalysis != 0) then
+  set infofile = $mapanalysis/analysis.info
+  set mapfsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
+  set tmp = `cat $infofile | awk '{if($1 == "surface") print $2" "$3}'`;
+  if($#tmp != 0) then
+    set mapsubject = $tmp[1];
+    set maphemi    = $tmp[2];
+    echo "Map Surface $mapsubject $maphemi"
+    if($subject != $mapsubject || $hemi != $maphemi) then
+      echo "ERROR: map analysis $mapanalysis uses a different surface."
+      exit 1;
+    endif      
+  endif
+  set tmp = `cat $infofile | awk '{if($1 == "UseTalairach") print 1}'`;
+  set MapUseTalairach = $#tmp;
+  if($UseTalairach != $MapUseTalairach) then
+    if($MapUseTalairach) then
+      echo "ERROR: map analysis $mapanalysis is talairach-based."
+      echo "This does not match the analysis $analysis"
+    else
+      echo "ERROR: map analysis $mapanalysis is NOT talairach-based."
+      echo "This does not match the analysis $analysis"
+    endif      
+    exit 1;
+  endif
 endif
 
 echo $VERSION
@@ -100,18 +142,22 @@ which tksurfer
 # ---------------------------------------------
 foreach sess ($SessList)
   echo ""
-  echo ""
 
-  set reg = $sess/$fsd/register.dat
-  if(! -e $reg) then
-    echo "ERROR: cannot find $reg"
-    exit 1
-  endif
-  set subject = `head -n 1 $reg`;
-  echo "subject is $subject"
-  if(! -e $SUBJECTS_DIR/$subject) then
-    echo "ERROR: cannot find $SUBJECTS_DIR/$subject"
-    exit 1;
+  set self = `cat $sess/subjectname`;
+
+  set reg = ();
+  if($#subject == 0) then
+    set reg = $sess/$fsd/register.dat
+    if(! -e $reg) then
+      echo "ERROR: cannot find $reg"
+      exit 1
+    endif
+    set subject = `head -n 1 $reg`;
+    echo "subject is $subject"
+    if(! -e $SUBJECTS_DIR/$subject) then
+      echo "ERROR: cannot find $SUBJECTS_DIR/$subject"
+      exit 1;
+    endif
   endif
 
   set anapath = $sess/$fsd/$analysis
@@ -160,13 +206,19 @@ foreach sess ($SessList)
   $cmd
   if($status) exit 1;
 
+  set overlayregopt = ()
+  set hdrregopt = ()
   if($UseVol2Surf) then
     # Sample volume to the surface
+    # Set up vol2surf basic cmd
+    set cmd0 = (mri_vol2surf --hemi $hemi --projfrac $ProjFrac \
+      --interp $Interp --cortex)
+    if(! $UseTalairach) set cmd0 = ($cmd0 --reg $reg)
+    if($UseTalairach)   set cmd0 = ($cmd0 --regheader $subject)
+
     set mov = $mapconcatfile
     set out = $sess/$mapfsd/$mapanalysis/$hemi.tksconcat.mgh
-    set cmd = (mri_vol2surf --mov $mov --reg $reg\
-     --hemi $hemi --projfrac $ProjFrac --interp $Interp \
-     --o $out)
+    set cmd = ($cmd0 --mov $mov --o $out)
     echo $cmd
     $cmd
     if($status) exit 1;
@@ -174,40 +226,53 @@ foreach sess ($SessList)
     set mapconcatfile = $out
 
     if($ShowHDR) then
+      # HRF
       set mov = $hpath
       set out = $sess/$mapfsd/$mapanalysis/$hemi.h.mgh
-      set cmd = (mri_vol2surf --mov $mov --reg $reg\
-        --hemi $hemi --projfrac $ProjFrac --interp $Interp \
-        --o $out)
+      set cmd = ($cmd0 --mov $mov --o $out)
       echo $cmd
       $cmd
       if($status) exit 1;
       set hpath = $out
-
+      # Offset
       set mov = $hoffsetpath
       set out = $sess/$mapfsd/$mapanalysis/$hemi.h-offset.mgh
-      set cmd = (mri_vol2surf --mov $mov --reg $reg\
-        --hemi $hemi --projfrac $ProjFrac --interp $Interp \
-        --o $out)
+      set cmd = ($cmd0 --mov $mov --o $out)
+      if(! $UseTalairach) set cmd = ($cmd --reg $reg)
+      if($UseTalairach) set cmd = ($cmd --regheader $subject)
       echo $cmd
       $cmd
       if($status) exit 1;
       set hoffsetpath = $out
     endif
-    set overlayregopt = ()
-    set hdrregopt = ()
   else
-    set overlayregopt = (-overlay-reg $reg)
-    if($ShowHDR) then
-      set hdrregopt = (-timecourse-reg $reg -timecourse-offset-reg-file $reg)
+    if(! $SurfAna) then
+      set overlayregopt = (-overlay-reg $reg)
+      if($ShowHDR) then
+        set hdrregopt = (-timecourse-reg $reg -timecourse-offset-reg-file $reg)
+      endif
     endif
   endif
 
-  # tksurfer subject hemi surf 
-  #   -annot aparc.annot
-  #   -overlay overlay       -overlay-reg   reg
-  #   -timecourse tc         -timecourse-reg reg
-  #   -timecourse-offset tco -timecourse-offset-reg
+  if($ToSelf && $subject != $self) then
+    set cmd0 = (mri_surf2surf --srcsubject $subject \
+     --trgsubject $self --hemi $hemi)
+    set cmd = ($cmd0 --sval $mapconcatfile --tval $mapconcatfile)
+    echo $cmd
+    $cmd
+    if($status) exit 1;
+    if($ShowHDR) then
+      set cmd = ($cmd0 --sval $hpath --tval $hpath)
+      echo $cmd
+      $cmd
+      if($status) exit 1;
+      set cmd = ($cmd0 --sval $hoffsetpath --tval $hoffsetpath)
+      echo $cmd
+      $cmd
+      if($status) exit 1;
+    endif
+    set subject = $self
+  endif
 
   set cmd = (tksurfer $subject $hemi $surf)
   set cmd = ($cmd -overlay $mapconcatfile $overlayregopt)
@@ -224,14 +289,20 @@ foreach sess ($SessList)
 
   echo " cd `pwd`"
   echo "setenv SUBJECTS_DIR $SUBJECTS_DIR"
+  echo $cmd
+  echo ""
+
+  # Print a list of contrasts
+  echo "Contrasts"
   @ nth = 0;
   foreach c ($contrastlist)
     echo $nth $c
     @ nth = $nth + 1;
   end
-  echo $cmd
   echo ""
   echo ""
+
+  # Runit
   $cmd
 
   # delete tmp files
@@ -328,6 +399,10 @@ while( $#argv != 0 )
       set Interp = $argv[1]; shift
       breaksw
 
+    case "-self":
+      set ToSelf = 1;
+      breaksw
+
     case "-debug":
       set verbose = 1;
       set echo = 1;
@@ -361,11 +436,6 @@ goto parse_args_return;
 
 ############--------------##################
 check_params:
-
-  if($#hemi == 0) then
-    echo "ERROR: no hemisphere specified" 
-    exit 1;
-  endif
 
   if($#analysis == 0) then
     echo "ERROR: no analysis specified" 
