sync from cvs.

diff --git a/fsfast/bin/mkanalysis-sess b/fsfast/bin/mkanalysis-sess
--- a/fsfast/bin/mkanalysis-sess
+++ b/fsfast/bin/mkanalysis-sess
@@ -7,8 +7,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2015/05/21 17:49:20 $
-#    $Revision: 1.76 $
+#    $Date: 2015/11/04 20:53:30 $
+#    $Revision: 1.77 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: mkanalysis-sess,v 1.76 2015/05/21 17:49:20 greve Exp $';
+set VERSION = '$Id: mkanalysis-sess,v 1.77 2015/11/04 20:53:30 greve Exp $';
 
 set analysis = ();
 set TR = ();
@@ -38,6 +38,7 @@ set RawRes = ();
 set RawFWHM = ();
 set volsurffwhm = (); # smooth in the volume, for testing
 set RawSTC = none;
+set SliceDelayFile = ();
 set nSliceGroups = 1;
 set ExpKey = ();
 set mcstem = ();
@@ -147,6 +148,10 @@ echo "RawFWHM $RawFWHM" | tee -a $flac
 if($#volsurffwhm) echo "VolSurfFWHM $volsurffwhm" | tee -a $flac
 if($#RawSTC) echo "RawSTC $RawSTC" | tee -a $flac
 echo "nSliceGroups $nSliceGroups" | tee -a $flac
+if($#SliceDelayFile) then 
+  echo "SliceDelayFile $SliceDelayFile" | tee -a $flac
+  cp $SliceDelayFile $analysis/
+endif
 if($#ExpKey) echo "ExpKey $ExpKey" | tee -a $flac
 echo "UseB0DC $UseB0DC" | tee -a $flac
 echo "ApplySubCortMask $ApplySubCortMask" | tee -a $flac
@@ -456,6 +461,15 @@ while( $#argv != 0 )
          $RawSTC != odd && $RawSTC != even && $RawSTC != none) then
          echo "ERROR: -stc is $RawSTC, must be siemens, up, down, odd, even, or none"
          exit 1;
+      endif
+      breaksw
+
+    case "-sdf":
+      if ( $#argv == 0) goto arg1err;
+      set SliceDelayFile = $argv[1]; shift;
+      if(! -e $SliceDelayFile) then
+        echo "ERROR: cannot find $SliceDelayFile"
+        exit 1;
       endif
       breaksw
 
@@ -787,6 +801,11 @@ check_params:
     exit 1;
   endif
 
+  if($RawSTC != "none" && $#SliceDelayFile) then
+    echo "ERROR: cannot specify both -stc and -sdf"
+    exit 1;
+  endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -815,6 +834,7 @@ usage_exit:
   echo "  -native               : leave raw data in native functional space"
   echo "  -fwhm FWHMmm : spatially smooth input by FWHM (in mm) in proper space"
   echo "  -stc SliceOrder : slice-time correct using the name of the SliceOrder (default none)"
+  echo "  -sdf SlicDelayFile : specify a slice delay file instead of -stc"
   echo "  -ngroups nSliceGroups : number of SMS slice groups for STC"
   echo "  -reg-dof DOF    : use given DOF when performing registration (default is $RegDOF)"
   echo "  -fsd FSD        : functional subdirectory (eg, bold)"
@@ -951,6 +971,14 @@ If you do not want smoothing, you must still specify 0.
 Perform slice-timing correction using FSLs slicetimer. Options for 
 Slice Order are siemens, up, down, odd, even. By default, no
 slice timing correction is done.
+
+-sdf slicedelayfile
+
+Provide a text file that gives the slice delay of each slice in
+fractions of TR rather than computing it analytically from up,
+down, etc. Usually the middle of the TR has a value of 0.  The
+format should be the same as the output of the slicedelay program.
+This allows for arbitrary slice orders.
 
 -per-run : to be used when you run preproc-sess -per-session
 -per-session : to be used when you run preproc-sess -per-session
diff --git a/fsfast/bin/preproc-sess b/fsfast/bin/preproc-sess
--- a/fsfast/bin/preproc-sess
+++ b/fsfast/bin/preproc-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2015/10/14 01:06:28 $
-#    $Revision: 1.61 $
+#    $Date: 2015/11/04 20:53:30 $
+#    $Revision: 1.62 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -27,7 +27,7 @@
 # This creates fmcpr.sm5, then
 # mkanalysis-sess -native -funcstem fmcpr.sm5 ...
 
-set VERSION = '$Id: preproc-sess,v 1.61 2015/10/14 01:06:28 greve Exp $';
+set VERSION = '$Id: preproc-sess,v 1.62 2015/11/04 20:53:30 greve Exp $';
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M'`"
@@ -47,6 +47,7 @@ set fwhm     = ();
 set surffwhm = ();
 set volsurffwhm  = (); # for testing
 set SliceOrder = ();
+set SliceDelayFile = ()
 set nSliceGroups = 1;
 set fsd      = ();
 set mcrun    = ();
@@ -249,6 +250,7 @@ foreach sess ($SessList)
   if($DoSTC) then
     set cmd = (stc-sess -i $stcinstem -o $stcoutstem -ngroups $nSliceGroups)
     if($#SliceOrder) set cmd = ($cmd -so $SliceOrder)
+    if($#SliceDelayFile) set cmd = ($cmd -sdf $SliceDelayFile)
     set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
     if($#RunListFile != 0)  set cmd = ($cmd -rlf $RunListFile);
     if($nolog)      set cmd = ($cmd -nolog);
@@ -268,6 +270,7 @@ foreach sess ($SessList)
     if($subject != self) set cmd = ($cmd -trgsubject $subject)
     if($#RunListFile != 0)  set cmd = ($cmd -rlf $RunListFile);
     if($#SliceOrder) set cmd = ($cmd -stc $SliceOrder)
+    if($#SliceDelayFile) set cmd = ($cmd -sdf $SliceDelayFile)
     if($nolog)      set cmd = ($cmd -nolog);
     if($UpdateOnly) set cmd = ($cmd -update);
     if($UseB0DC)    set cmd = ($cmd -b0dc)
@@ -287,6 +290,7 @@ foreach sess ($SessList)
     if($RawRes == 1) set cmd = ($cmd -1mm)
     if($#RunListFile != 0)  set cmd = ($cmd -rlf $RunListFile);
     if($#SliceOrder) set cmd = ($cmd -stc $SliceOrder)
+    if($#SliceDelayFile) set cmd = ($cmd -sdf $SliceDelayFile)
     if($nolog)      set cmd = ($cmd -nolog);
     if($UpdateOnly) set cmd = ($cmd -update);
     if($UseB0DC)    set cmd = ($cmd -b0dc)
@@ -540,6 +544,16 @@ while( $#argv != 0 )
       set DoSTC = 1;
       breaksw
 
+    case "-sdf":
+      if ( $#argv == 0) goto arg1err;
+      set SliceDelayFile = $argv[1]; shift;
+      if(! -e $SliceDelayFile) then
+        echo "ERROR: cannot find $SliceDelayFile"
+        exit 1;
+      endif
+      set DoSTC = 1;
+      breaksw
+
     case "-ngroups":
       if ( $#argv == 0) goto arg1err;
       set nSliceGroups = $argv[1]; shift;
@@ -660,6 +674,11 @@ while( $#argv != 0 )
       set SliceOrder = `getana -a $analysis -t stc`;
       if($SliceOrder != none) set DoSTC = 1;
       if($SliceOrder == none) set SliceOrder = ();
+      set SliceDelayFile = `getana -a $analysis -t sdf`;
+      if($#SliceDelayFile != none) then
+        set DoSTC = 1;
+        set SliceDelayFile = $analysis/$SliceDelayFile
+      endif
       set nSliceGroups = `getana -a $analysis -t nslicegroups`;
       set ToSurf = `getana -a $analysis -t IsSurface`;
       if($ToSurf) then
@@ -784,7 +803,10 @@ check_params:
 
   if($DoSTC) then
     if($#stcinstem  == 0) set stcinstem  = $mcoutstem
-    if($#stcoutstem == 0) set stcoutstem = $stcinstem.$SliceOrder
+    if($#stcoutstem == 0) then
+      if($#SliceOrder)  set stcoutstem = $stcinstem.$SliceOrder
+      if($#SliceDelayFile)  set stcoutstem = $stcinstem.sdf
+    endif
   else
     set stcoutstem = $mcoutstem
   endif
@@ -836,6 +858,11 @@ check_params:
   if($#regfile == 0) then
     if(! $UseB0DC) set regfile = register.dof$RegDOF.lta
     if($UseB0DC)   set regfile = register.dof$RegDOF.b0dc.lta
+  endif
+
+  if($#SliceDelayFile != 0 && $#SliceOrder != 0) then
+    echo "ERROR: cannot specify both -so and -sdf"
+    exit 1;
   endif
 
 goto check_params_return;
@@ -972,6 +999,14 @@ the second slice for an even number. "up" is 1st, 2nd, 3rd,
 etc. "down" is last, next to last, etc. odd is 1st, 3rd, 5th, , etc,
 then 2nd, 4th, 6th, etc. "even" is 2nd, 4th, 6th, etc, then 1st, 3rd,
 5th, etc.  See also stc-sess.
+
+-sdf slicedelayfile
+
+Provide a text file that gives the slice delay of each slice in
+fractions of TR rather than computing it analytically from up,
+down, etc. Usually the middle of the TR has a value of 0.  The
+format should be the same as the output of the slicedelay program.
+This allows for arbitrary slice orders.
 
 -surface subject hemi
 
diff --git a/fsfast/bin/stc-sess b/fsfast/bin/stc-sess
--- a/fsfast/bin/stc-sess
+++ b/fsfast/bin/stc-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2015/03/10 20:47:17 $
-#    $Revision: 1.11 $
+#    $Date: 2015/11/04 16:29:45 $
+#    $Revision: 1.12 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: stc-sess,v 1.11 2015/03/10 20:47:17 greve Exp $';
+set VERSION = '$Id: stc-sess,v 1.12 2015/11/04 16:29:45 greve Exp $';
 
 set cmdargs = ($argv);
 
@@ -33,7 +33,8 @@ set infmt  = bhdr;
 set outfmt = bhdr;
 set RunListFile = ();
 set fsd = bold;
-set SliceOrder = siemens
+set SliceOrder = ()
+set SliceDelayFile = ()
 set UpdateOnly = 0;
 set ngroups = 1; # number of slice groups for SMS
 set nolog     = 0;
@@ -112,12 +113,15 @@ foreach sess ($SessList)
 
     test $outfunc -nt $infunc
     if($status || ! $UpdateOnly || ! -e $outfunc) then
-      set cmd = (stc.fsl --i $infunc --o $outfunc --$SliceOrder --ngroups $ngroups)
+      set cmd = (stc.fsl --i $infunc --o $outfunc --ngroups $ngroups)
+      if($#SliceOrder) set cmd = ($cmd --$SliceOrder)
+      if($#SliceDelayFile) set cmd = ($cmd --sdf $SliceDelayFile)
       echo "---------------------------------------------"| tee -a $LF
       pwd | tee -a $LF
       echo $cmd | tee -a $LF
       $cmd | tee -a $LF
       if($status) exit 1;
+      if($#SliceDelayFile) cp $SliceDelayFile $RunPath/$Run/$outstem.sdf
     else
       ls -lt $outfunc $infunc | tee -a $LF
       echo "Update not needed" | tee -a $LF
@@ -166,6 +170,15 @@ while( $#argv != 0 )
     case "-so":
       if ( $#argv == 0) goto arg1err;
       set SliceOrder = $argv[1]; shift;
+      breaksw
+
+    case "-sdf":
+      if ( $#argv == 0) goto arg1err;
+      set SliceDelayFile = $argv[1]; shift;
+      if(! -e $SliceDelayFile) then
+        echo "ERROR: cannot find $SliceDelayFile"
+        exit 1;
+      endif
       breaksw
 
     case "-infmt":
@@ -224,6 +237,16 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
+if($#SliceDelayFile == 0 && $#SliceOrder == 0) then
+  echo "ERROR: must specify -so or -sdf"
+  exit 1;
+endif
+
+if($#SliceDelayFile != 0 && $#SliceOrder != 0) then
+  echo "ERROR: cannot specify both -so and -sdf"
+  exit 1;
+endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -240,6 +263,7 @@ usage_exit:
   echo "   -i instem "
   echo "   -o outstem "
   echo "   -so sliceorder : <siemens>, up, down, odd, even"
+  echo "   -sdf sdfile : explicitly pass custom slice delay file"
   echo "   -ngroups ngroups : number of slice groups (for use with SMS)"
   echo "   -infmt  fmt : input  format ($infmt)"
   echo "   -outfmt fmt : output format ($outfmt)"
@@ -289,6 +313,15 @@ shifted in time such that time=0 occurs at the middle of the TR
 instead of the beginning of the TR. Thus, you must subtract half
 a TR from the stimulus onsets. This can be done during
 mkanalysis-sess with "-timeoffset -1.0" for TR=2s.
+
+-sdf slicedelayfile
+
+Provide a text file that gives the slice delay of each slice in
+fractions of TR rather than computing it analytically from --up,
+--down, etc. Usually the middle of the TR has a value of 0.  The
+format should be the same as the output of the slicedelay program.
+This allows for arbitrary slice orders.
+
 
 Example:
 
