Now computes an eroded mask and the global 4D mean

diff --git a/fsfast/bin/mkbrainmask-sess b/fsfast/bin/mkbrainmask-sess
--- a/fsfast/bin/mkbrainmask-sess
+++ b/fsfast/bin/mkbrainmask-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/01 03:27:10 $
-#    $Revision: 1.14 $
+#    $Date: 2010/04/01 21:27:03 $
+#    $Revision: 1.15 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: mkbrainmask-sess,v 1.14 2010/04/01 03:27:10 greve Exp $'
+set VERSION = '$Id: mkbrainmask-sess,v 1.15 2010/04/01 21:27:03 greve Exp $'
 
 set cmdargs = ($argv);
 
@@ -75,21 +75,18 @@ goto check_params;
 check_params_return:
 
 set ProjectDir = `pwd`;
+mkdir -p $ProjectDir/log
 
 #---------------------------------------------------------------#
 foreach sess ($SessList)
-
   set sessid = `basename $sess`;
 
   # Create a log file #
+  set LF = /dev/null
   if(-w .) then
-    mkdir -p log
     set LF = $ProjectDir/log/mkbrainmask-$sessid-$fsd.log
     rm -f $LF
-  else
-    set LF = /dev/null
   endif
-
   echo "mkbrainmask-sess" >> $LF
   echo $sessid      >> $LF
   echo $VERSION     >> $LF
@@ -99,7 +96,6 @@ foreach sess ($SessList)
   echo $0 $cmdargs  >> $LF
   echo "ProjectDir $ProjectDir" >> $LF
 
-  echo "------------------------------------------------" |& tee -a $LF
   echo "------------------------------------------------" |& tee -a $LF
   echo "$sess " |& tee -a $LF
   date |& tee -a $LF
@@ -112,67 +108,83 @@ foreach sess ($SessList)
   ### Goto the functional subdirectory ###
   cd $sess/$fsd
 
-  ### Session-level mask
-  if(! $PerRun) then
-    set template = `stem2fname template`
-    if($status) then
-      echo "ERROR: cannot find template for $sess/$fsd"  |& tee -a $LF
-      echo "       run mktemplate-sess"  |& tee -a $LF
-      exit 1;
-    endif
-    set mask = $maskdir/$maskstem.$outfmt;
-    if($UpdateOnly && -e $mask) then
-      test $template -nt $mask
-      if($status) then
-        echo "$sess Update not needed" | tee -a $LF
-        continue
-      endif
-    endif
-    set cmd = (mkbrainmask -i $template -o $mask);
-    set cmd = ($cmd -thresh $thresh );
-    set cmd = ($cmd -ndil $ndilations)
-    set cmd = ($cmd -nerode $nerodes)
-    if($debug) set cmd = ($cmd -debug);
+  ### Session-level mask ----------------------------------
+  set template = `stem2fname template`
+  if($status) then
+    echo "ERROR: cannot find template for $sess/$fsd"  |& tee -a $LF
+    echo "       run mktemplate-sess"  |& tee -a $LF
+    exit 1;
+  endif
+  set mask = $maskdir/$maskstem.$outfmt;
+
+  set UpdateNeeded = 0;
+  if(! $UpdateOnly) set UpdateNeeded = 1;
+  if(`UpdateNeeded $mask $template`) set UpdateNeeded = 1;
+
+  if($UpdateNeeded) then
+    set cmd = (mkbrainmask -i $template -o $mask -thresh $thresh)
+    set cmd = ($cmd -ndil $ndilations -nerode $nerodes)
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
     if($status) exit 1;
-    continue;
-  endif    
+  else
+    echo "$sessid Update not needed for session-level mask"| tee -a $LF
+  endif
 
-  ### Run-level mask
-  ### Get the list of runs in the FSD ###
+  ### Run-level masks --------------------------
   set RunList = `getrunlist .`;
   if($status || $#RunList == 0) then
     echo "ERROR: $sess/$fsd has no runs"  |& tee -a $LF
     exit 1;
   endif
 
-  foreach run ($RunList)
+  foreach Run ($RunList)
 
-    set template = `stem2fname $run/template`
+    set template = `stem2fname $Run/template`
     if($status) then
-      echo "ERROR: cannot find $template for $sess/$fsd/$run" |& tee -a $LF
+      echo "ERROR: cannot find $template for $sess/$fsd/$Run" |& tee -a $LF
       echo "       run mktemplate-sess"  |& tee -a $LF
       exit 1;
     endif
-    set mask = $run/$maskdir/$maskstem.$outfmt;
+    set mask = $Run/$maskdir/$maskstem.$outfmt;
+    set maske3 = $Run/$maskdir/$maskstem.e3.$outfmt;
 
-    if($UpdateOnly && -e $mask) then
-      test $template -nt $mask
-      if($status) then
-        echo "$sessid $run Update not needed" | tee -a $LF
-        continue
-      endif
+    set UpdateNeeded = 0;
+    if(! $UpdateOnly) set UpdateNeeded = 1;
+    if(`UpdateNeeded $mask   $template`) set UpdateNeeded = 1;
+    if(`UpdateNeeded $maske3 $template`) set UpdateNeeded = 1;
+
+    if($UpdateNeeded) then
+      set cmd = (mkbrainmask -i $template -o $mask -thresh $thresh );
+      set cmd = ($cmd -ndil $ndilations -nerode $nerodes)
+      echo $cmd | tee -a $LF
+      $cmd | tee -a $LF
+      if($status) exit 1;
+      # Create a second mask eroded by 3 to compute the mean
+      set cmd = (mri_binarize --i $mask --min 0.5 \
+       --zero-edges --erode 3 --o $maske3)
+      echo $cmd | tee -a $LF
+      $cmd | tee -a $LF
+      if($status) exit 1;
+    else
+      echo "$sessid Update not needed for run $Run mask" | tee -a $LF
     endif
 
-    set cmd = (mkbrainmask -i $template -o $mask);
-    set cmd = ($cmd -thresh $thresh );
-    set cmd = ($cmd -ndil $ndilations)
-    set cmd = ($cmd -nerode $nerodes)
-    if($debug) set cmd = ($cmd -debug);
-    echo $cmd | tee -a $LF
-    $cmd | tee -a $LF
-    if($status) exit 1;
+    # Compute the global mean in the eroded mask from the 4D volume
+    set meanval = $Run/global.meanval.dat
+    set fstem = `cat $Run/template.log | grep FUNCSTEM | awk '{print $2}'`
+    set ffile = `stem2fname $Run/$fstem`;
+    set UpdateNeeded = 0;
+    if(! $UpdateOnly) set UpdateNeeded = 1;
+    if(`UpdateNeeded $meanval $maske3 $ffile`) set UpdateNeeded = 1;
+    if($UpdateNeeded) then
+      set cmd = (meanval --i $ffile --m $maske3 --o $meanval);
+      echo $cmd | tee -a $LF
+      $cmd | tee -a $LF
+      if($status) exit 1;
+    else
+      echo "$sessid Update not needed for run $Run meanval" | tee -a $LF
+    endif
 
   end # Run
 
@@ -337,18 +349,20 @@ exit 1;
 #---- Everything below here is printed out as part of help -----#
 BEGINHELP
 
-This program creates a binary mask of the brain given an input 
-functional volume. It uses the FSL (www.fmrib.ox.ac.uk/fsl) Brain 
-Extraction Tool (BET). By default, the input is the f volume from the 
-first run of the session from the bold directory.  The input volume 
-can be changed with the -funcstem option; the run can be changed with 
-the -run option; and the functional subdirectory can be changed with 
-the -fsd option. The output will be placed in a directory called masks 
-under the FSD. The stem will be brain unless changed with the 
--maskstem option. The only real parameter is the threshold (controlled 
-with the -thresh option). The absolute threshold is set to thresh 
-times the global mean. -ndil N will expand the mask by approximatedly
-N voxels.
+This program creates a binary mask of the brain from the template
+created by mktemplate-sess.  It uses the FSL (www.fmrib.ox.ac.uk/fsl)
+Brain Extraction Tool (BET). This BET mask is dilated by one voxel 
+to make sure that it gets all tissue. A second mask is created
+that is eroded by 3 voxels. This is used to compute the global
+mean intensity, which can then be used for global intensity 
+normalization. The mean intensity is stored in each run in the
+global.mean.dat file. This script creates a session-level mask
+based on the session-level template as well as a mask for each
+run. 
+
+The only real parameter is the threshold (controlled with the -thresh
+option). The absolute threshold is set to thresh times the global
+mean. -ndil N will expand the mask by approximatedly N voxels.
 
 Those using this program should cite: Smith, S. (2000).  Robust
 automated brain extraction.  NeuroImage.  Submitted.
