Added ability to erode and dialiate

diff --git a/fsfast/bin/mkbrainmask b/fsfast/bin/mkbrainmask
--- a/fsfast/bin/mkbrainmask
+++ b/fsfast/bin/mkbrainmask
@@ -1,20 +1,22 @@
 #!/bin/csh -f
 # mkbrainmask - frontend for FSL's BET (Brain Extraction Tool)
 #
-# $Id: mkbrainmask,v 1.2 2004/04/26 18:10:33 greve Exp $
+# $Id: mkbrainmask,v 1.3 2004/05/07 03:04:57 greve Exp $
 #
 
-set VERSION = '$Id: mkbrainmask,v 1.2 2004/04/26 18:10:33 greve Exp $';
+set VERSION = '$Id: mkbrainmask,v 1.3 2004/05/07 03:04:57 greve Exp $';
 set FASTVER = `cat $FSFAST_HOME/docs/version`;
 
 set inputargs = ($argv);
 
-set instem   = ();
-set outstem  = ();
-set thresh     = 0.5;
+set instem     = ();
+set outstem    = ();
+set thresh     = 0.1;
 set scratchdir = ();
 set cleanup    = 1;
-set seqinfo = ();
+set seqinfo     = ();
+set ndilates = 0;
+set nerodes = 0;
 
 if($#argv == 0) then
   goto usage_exit;
@@ -93,6 +95,42 @@ if($status) then
   exit 1;
 endif
 
+#------------------------------------------------------------------
+if($ndilates > 0) then
+  echo Diliating $ndilates
+  set srcmask = $scratchdir/$outbase"_mask".img
+  @ n = 1
+  while( $n <= $ndilates) 
+    set cmd = (avwmaths $srcmask -dil $srcmask)
+    pwd
+    echo $cmd
+    $cmd
+    if($status) then
+      echo "ERROR: dilation failed"
+      exit 1;
+    endif
+    @ n = $n + 1
+  end
+endif
+
+#------------------------------------------------------------------
+if($nerodes > 0) then
+  echo Eroding $nerodes
+  set srcmask = $scratchdir/$outbase"_mask".img
+  @ n = 1
+  while( $n <= $nerodes) 
+    set cmd = (avwmaths $srcmask -ero $srcmask)
+    pwd
+    echo $cmd
+    $cmd
+    if($status) then
+      echo "ERROR: erosion failed"
+      exit 1;
+    endif
+    @ n = $n + 1
+  end
+endif
+
 # Copy .mat file to outbase
 cp $scratchdir/$inbase.mat $scratchdir/$outbase"_mask".mat
 
@@ -151,6 +189,16 @@ while( $#argv != 0 )
     case "-seqinfo":
       if ( $#argv == 0) goto arg1err;
       set seqinfo = $argv[1]; shift;
+      breaksw
+
+    case "-ndil":
+      if ( $#argv == 0) goto arg1err;
+      set ndilates = $argv[1]; shift;
+      breaksw
+
+    case "-nerode":
+      if ( $#argv == 0) goto arg1err;
+      set nerodes = $argv[1]; shift;
       breaksw
 
     case "-umask":
@@ -223,6 +271,7 @@ usage_exit:
   echo "   -scratch dir : directory to put temporary files"
   echo "   -nocleanup   : don't delete temporary files"
   echo "   -seqinfo seqinfofile : use this if there is no .bhdr"
+  echo "   -ndil n : number of dilations to expand the mask"
   echo ""
   echo "Other Arguments (Optional)"
   echo "   -umask umask   : set unix file permission mask"
