Now uses template

diff --git a/fsfast/bin/mkbrainmask-sess b/fsfast/bin/mkbrainmask-sess
--- a/fsfast/bin/mkbrainmask-sess
+++ b/fsfast/bin/mkbrainmask-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2009/04/02 19:00:47 $
-#    $Revision: 1.13 $
+#    $Date: 2010/04/01 03:27:10 $
+#    $Revision: 1.14 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: mkbrainmask-sess,v 1.13 2009/04/02 19:00:47 greve Exp $'
+set VERSION = '$Id: mkbrainmask-sess,v 1.14 2010/04/01 03:27:10 greve Exp $'
 
 set cmdargs = ($argv);
 
@@ -36,39 +36,32 @@ set maskstem = brain;
 set maskdir = masks;
 set nolog     = 0;
 set nthrun = ();
-set perrun = 0;
+set PerRun = 0;
 set debug = 0;
 set scratchdir = ();
 set PrintHelp = 0;
 set UpdateOnly = 0;
 
 set infmt  = ();
-set outfmt = bhdr
+set outfmt = nii
 if($?FSF_OUTPUT_FORMAT) then
   set outfmt = $FSF_OUTPUT_FORMAT;
 endif
 
 set StartTime = `date`;
 
-if($#argv == 0) then
-  goto usage_exit;
-  exit 1;
-endif
-
-set n = `echo $argv | grep version | wc -l` 
-if($n != 0) then
-  echo $VERSION
-  exit 0;
-endif
-
+if($#argv == 0) goto usage_exit;
 set n = `echo $argv | grep -e -help | wc -l` 
 if($n != 0) then
   set PrintHelp = 1;
   goto usage_exit;
   exit 1;
 endif
-
-set PWDCMD = `getpwdcmd`;
+set n = `echo $argv | grep -e -version | wc -l` 
+if($n != 0) then
+  echo $VERSION
+  exit 0;
+endif
 
 set SessList = `getsesspath $argv`;
 if($status || $#SessList == 0) then
@@ -78,25 +71,8 @@ endif
 
 goto parse_args;
 parse_args_return:
-
 goto check_params;
 check_params_return:
-
-# Create a log file #
-if(! $nolog) then
-  mkdir -p log
-  set LF = `$PWDCMD`/log/mkbrainmask-sess-$fsd.log
-  rm -f $LF
-else
-  set LF = /dev/null
-endif
-
-echo "mkbrainmask-sess" >> $LF
-echo '$Id: mkbrainmask-sess,v 1.13 2009/04/02 19:00:47 greve Exp $' >> $LF
-uname -a          >> $LF
-date              >> $LF
-$PWDCMD           >> $LF
-echo $cmdargs     >> $LF
 
 set ProjectDir = `pwd`;
 
@@ -120,7 +96,7 @@ foreach sess ($SessList)
   uname -a          >> $LF
   date              >> $LF
   pwd               >> $LF
-  echo $cmdargs     >> $LF
+  echo $0 $cmdargs  >> $LF
   echo "ProjectDir $ProjectDir" >> $LF
 
   echo "------------------------------------------------" |& tee -a $LF
@@ -133,16 +109,37 @@ foreach sess ($SessList)
     echo "ERROR: $sess/$fsd does not exist"   |& tee -a $LF
     exit 1;
   endif
-
-  ### Check that the target directory is writable ###
-  if(! -w $sess/$fsd) then
-    echo "ERROR: $sess/$fsd is not writable"   |& tee -a $LF
-    exit 1;
-  endif
-
   ### Goto the functional subdirectory ###
   cd $sess/$fsd
 
+  ### Session-level mask
+  if(! $PerRun) then
+    set template = `stem2fname template`
+    if($status) then
+      echo "ERROR: cannot find template for $sess/$fsd"  |& tee -a $LF
+      echo "       run mktemplate-sess"  |& tee -a $LF
+      exit 1;
+    endif
+    set mask = $maskdir/$maskstem.$outfmt;
+    if($UpdateOnly && -e $mask) then
+      test $template -nt $mask
+      if($status) then
+        echo "$sess Update not needed" | tee -a $LF
+        continue
+      endif
+    endif
+    set cmd = (mkbrainmask -i $template -o $mask);
+    set cmd = ($cmd -thresh $thresh );
+    set cmd = ($cmd -ndil $ndilations)
+    set cmd = ($cmd -nerode $nerodes)
+    if($debug) set cmd = ($cmd -debug);
+    echo $cmd | tee -a $LF
+    $cmd | tee -a $LF
+    if($status) exit 1;
+    continue;
+  endif    
+
+  ### Run-level mask
   ### Get the list of runs in the FSD ###
   set RunList = `getrunlist .`;
   if($status || $#RunList == 0) then
@@ -150,58 +147,32 @@ foreach sess ($SessList)
     exit 1;
   endif
 
-  if($#nthrun) then
-    if($#RunList < $nthrun) then
-      echo "ERROR: number of runs ($#RunList) exceeds specified run $nthrun"
-      exit 1;
-    endif
-    set RunList = $RunList[$nthrun];
-  endif
-
   foreach run ($RunList)
 
-    set instem = $run/$funcstem;
-    set infmtuse = `getformat_from_stem $instem $infmt`
+    set template = `stem2fname $run/template`
     if($status) then
-      echo "$infmtuse" 
+      echo "ERROR: cannot find $template for $sess/$fsd/$run" |& tee -a $LF
+      echo "       run mktemplate-sess"  |& tee -a $LF
       exit 1;
     endif
+    set mask = $run/$maskdir/$maskstem.$outfmt;
 
-    if($perrun) then
-      set outfile = $run/$maskdir/$maskstem.$outfmt;
-    else
-      set outfile = $maskdir/$maskstem.$outfmt;
-    endif
-
-    if($UpdateOnly && -e $outfile) then
-      test $instem.$infmtuse -nt $outfile
+    if($UpdateOnly && -e $mask) then
+      test $template -nt $mask
       if($status) then
-        pwd | tee -a $LF
-        ls -lt $instem.$infmtuse $outfile | tee -a $LF
-        echo "Update not needed" | tee -a $LF
+        echo "$sessid $run Update not needed" | tee -a $LF
         continue
       endif
     endif
 
-    set cmd = (mkbrainmask);
-    set cmd = ($cmd -i $instem.$infmtuse);
-    set cmd = ($cmd -o $outfile);
+    set cmd = (mkbrainmask -i $template -o $mask);
     set cmd = ($cmd -thresh $thresh );
     set cmd = ($cmd -ndil $ndilations)
     set cmd = ($cmd -nerode $nerodes)
     if($debug) set cmd = ($cmd -debug);
-    if($#scratchdir != 0) set cmd = ($cmd -scratch $scratchdir);
-
-    echo "--------------------------------------------------"
-    pwd       |& tee -a $LF
-    echo $cmd |& tee -a $LF
-    echo "--------------------------------------------------"
-
-    $cmd |& tee -a $LF
-    if($status) then
-      echo "ERROR: mkbrainmask failed"  |& tee -a $LF
-      exit 1;
-    endif
+    echo $cmd | tee -a $LF
+    $cmd | tee -a $LF
+    if($status) exit 1;
 
   end # Run
 
@@ -222,13 +193,6 @@ while( $#argv != 0 )
   set flag = $argv[1]; shift;
   
   switch($flag)
-
-    case "-funcstem":
-    case "-instem":
-    case "-i":
-      if ( $#argv == 0) goto arg1err;
-      set funcstem = $argv[1]; shift;
-      breaksw
 
     case "-fsd":
       set fsd = $argv[1]; shift;
@@ -262,31 +226,7 @@ while( $#argv != 0 )
       set nerodes = $argv[1]; shift;
       breaksw
 
-    case "-run":
-      if ( $#argv == 0) goto arg1err;
-      set nthrun = $argv[1]; shift;
-      breaksw
-
-    case "-perrun":
-      set perrun = 1;
-      breaksw
-
-    case "-scratch":
-      if ( $#argv == 0) goto arg1err;
-      set scratchdir = $argv[1]; shift;
-      breaksw
-
     case "-fmt":
-      if ( $#argv == 0) goto arg1err;
-      set infmt = $argv[1]; shift;
-      set outfmt = $argv[1]; shift;
-      breaksw
-
-    case "-infmt":
-      if ( $#argv == 0) goto arg1err;
-      set infmt = $argv[1]; shift;
-      breaksw
-
     case "-outfmt":
       if ( $#argv == 0) goto arg1err;
       set outfmt = $argv[1]; shift;
@@ -294,6 +234,10 @@ while( $#argv != 0 )
 
     case "-update":
       set UpdateOnly = 1;
+      breaksw
+
+    case "-perrun":
+      set PerRun = 1;
       breaksw
 
     case "-nolog":
@@ -344,13 +288,6 @@ if($#SessList == 0) then
   exit 1
 endif
 
-if($#nthrun && $perrun) then
-  echo "ERROR: cannot use -run and -perrun"
-  exit 1;
-endif
-if($#nthrun == 0 && ! $perrun) set nthrun = 1;
-
-
 goto check_params_return;
 ############--------------##################
 
@@ -365,12 +302,16 @@ usage_exit:
   echo ""
   echo "USAGE: mkbrainmask-sess"
   echo ""
+  echo "Session Arguments (Required)"
+  echo "   -sf sessidfile  "
+  echo "   -df sessdirfile "
+  echo "   -s  sessid      "
+  echo "   -d  sessdir     "
+  echo ""
   echo "Optional Arguments"
-  echo "   -fsd   funcsubdir  : functional subdirectory (default: bold)"
-  echo "   -run  nth          : use the nth run (default is 1st)"
-  echo "   -funcstem stem     : stem of functional volume (default: f)"
-  echo "   -thresh  threshold : fraction of global mean to separate "
+  echo "   -thresh  threshold : fraction of global mean to separate ($thresh)"
   echo "                        brain and air (default is .1)"
+  echo "   -fsd   funcsubdir  : functional subdirectory (default: bold)"
   echo "   -ndil ndialations  : dialate (ie, expand) the mask (def is 1)"
   echo "   -nero nerodes      : erodes (ie, contracts) the mask"
   echo "   -maskstem stem     : stem of binary mask (stored in fsd/masks/stem)"
@@ -379,11 +320,6 @@ usage_exit:
   echo "           of just the brain. thresh=0.05, ndil=3, stem=head"
   echo "   -perrun : perform on a run-by-run basis"
   echo ""
-  echo "Session Arguments (Required)"
-  echo "   -sf sessidfile  "
-  echo "   -df srchdirfile "
-  echo "   -s  sessid      "
-  echo "   -d  srchdir     "
   echo ""
   echo "Other Options"
   echo "   -update            : only run if input is newer than output"
@@ -392,26 +328,29 @@ usage_exit:
   echo ""
 
   if(! $PrintHelp ) exit 1;
+  echo " "
+  echo "$VERSION "
+  echo " "
+  cat $0 | awk 'BEGIN{prt=0}{if(prt) print $0; if($1 == "BEGINHELP") prt = 1 }'
+exit 1;
 
-  echo "\
-mkbrainmask-sess\
-\
-This program creates a binary mask of the brain given an input \
-functional volume. It uses the FSL (www.fmrib.ox.ac.uk/fsl) Brain \
-Extraction Tool (BET). By default, the input is the f volume from the \
-first run of the session from the bold directory.  The input volume \
-can be changed with the -funcstem option; the run can be changed with \
-the -run option; and the functional subdirectory can be changed with \
-the -fsd option. The output will be placed in a directory called masks \
-under the FSD. The stem will be brain unless changed with the \
--maskstem option. The only real parameter is the threshold (controlled \
-with the -thresh option). The absolute threshold is set to thresh \
-times the global mean. -ndil N will expand the mask by approximatedly\
-N voxels.\
-\
-Those using this program should cite: Smith, S. (2000).  Robust\
-automated brain extraction.  NeuroImage.  Submitted.\
-\
-"
+#---- Everything below here is printed out as part of help -----#
+BEGINHELP
+
+This program creates a binary mask of the brain given an input 
+functional volume. It uses the FSL (www.fmrib.ox.ac.uk/fsl) Brain 
+Extraction Tool (BET). By default, the input is the f volume from the 
+first run of the session from the bold directory.  The input volume 
+can be changed with the -funcstem option; the run can be changed with 
+the -run option; and the functional subdirectory can be changed with 
+the -fsd option. The output will be placed in a directory called masks 
+under the FSD. The stem will be brain unless changed with the 
+-maskstem option. The only real parameter is the threshold (controlled 
+with the -thresh option). The absolute threshold is set to thresh 
+times the global mean. -ndil N will expand the mask by approximatedly
+N voxels.
+
+Those using this program should cite: Smith, S. (2000).  Robust
+automated brain extraction.  NeuroImage.  Submitted.
 
 exit 1;
