Now does not look for matlab if matlab binary is used. -greve

diff --git a/fsfast/bin/mkcontrast2 b/fsfast/bin/mkcontrast2
--- a/fsfast/bin/mkcontrast2
+++ b/fsfast/bin/mkcontrast2
@@ -5,9 +5,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: zkaufman $
-#    $Date: 2015/12/10 22:51:30 $
-#    $Revision: 1.2 $
+#    $Author: greve $
+#    $Date: 2016/03/11 23:46:48 $
+#    $Revision: 1.3 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set MKCONTRAST_VER = '$Id: mkcontrast2,v 1.2 2015/12/10 22:51:30 zkaufman Exp $';
+set MKCONTRAST_VER = '$Id: mkcontrast2,v 1.3 2016/03/11 23:46:48 greve Exp $';
 
 set CorrIdeal = 0;
 set monly = 0;
@@ -96,11 +96,6 @@ endif
 
 echo "  $MKCONTRAST_VER"
 
-set UseOctave = 0;
-if($?FS_USE_OCTAVE) then
-  set UseOctave = $FS_USE_OCTAVE
-endif
-
 source $FREESURFER_HOME/sources.csh
 
 goto parse_args;
@@ -112,19 +107,11 @@ check_params_return:
 goto dump_params;
 dump_params_return:
 
-if($monly) then
-  set TARGET = "tee $mfile"
-  rm -f $mfile;
-else
-  if($UseOctave == 0) then
-    set MATLAB = `getmatlab`;
-    if($status) then
-      echo "ERROR: cannot find matlab. Is it in your path?"
-      exit 1;
-    endif
-    set TARGET =  "$MATLAB -display iconic"
-  else
-    set TARGET = $FS_OCTAVE_BIN;
+if($FS_MKCON_USE_BIN == 0) then
+  set MATLAB = `getmatlab`;
+  if($status) then
+    echo "ERROR: cannot find matlab. Is it in your path?"
+    exit 1;
   endif
 endif  
 
