Lots of scary changes

diff --git a/fsfast/bin/mkcontrast-sess b/fsfast/bin/mkcontrast-sess
--- a/fsfast/bin/mkcontrast-sess
+++ b/fsfast/bin/mkcontrast-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2009/04/10 01:55:35 $
-#    $Revision: 1.12 $
+#    $Date: 2010/04/28 19:42:50 $
+#    $Revision: 1.13 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: mkcontrast-sess,v 1.12 2009/04/10 01:55:35 greve Exp $'
+set VERSION = '$Id: mkcontrast-sess,v 1.13 2010/04/28 19:42:50 greve Exp $'
 set cmdargs = ($argv);
 
 set contrast   = ();
@@ -85,45 +85,16 @@ parse_args_return:
 goto check_params;
 check_params_return:
 
-## Get the number of delays (ie, estimates) ##
-if(! $UseSXADat) then
-   set cfg = $analname/analysis.cfg
-   if(! -e $cfg) then
-      echo "ERROR: $cfg does not exist"
-      exit 1;
-   endif
-   set info = $analname/analysis.info
-   if(! -e $info) then
-     echo "ERROR: $info does not exist"
-     exit 1;
-   endif
-   set TER = `cat $cfg | awk '{if($1 == "-TER") print $2}'`;
-   set TW = `cat $cfg | awk '{if($1 == "-timewindow") print $2}'`;
-   set gDelta = `cat $cfg | awk '{if($1 == "-gammafit") print $2}'`;
-   set GammaFit = 0;
-   if($#gDelta != 0) set GammaFit = 1;
-   set spmhrf = `cat $cfg | awk '{if($1 == "-spmhrf") print $2}'`;
-   if($#spmhrf == 0) set spmhrf = -1;
-   if($GammaFit) then
-     set Nh = 1;
-   else if($spmhrf != -1) then
-     @ Nh = 1 + $spmhrf;
-   else
-     set Nh = `echo $TW/$TER | bc `
-   endif
-   if($#Nh == 0) exit 1;
-   set Nc = `cat $info | awk '{if($1 == "nconditions") print $2}'`;
-else
-  set tmp = `grep Nh $datfile`;
-  @ Nh = $tmp[2];
-  set tmp = `grep nCond $datfile`;
-  @ Nc = $tmp[2] - 1;
+set iser = `getana -a $analname -t IsEventRelated`;
+if(! $iser) then
+  echo "ERROR: analysis $analname is not event-related or blocked"
+  exit 1;
 endif
 
-
-## Get the number of conditions ##
-echo "INFO: Found $Nh Delays"
+set Nc  = `getana -a $analname -t nconditions`;
+set Nh  = `getana -a $analname -t npercond`;
 echo "INFO: Found $Nc Non-Null Conditions"
+echo "INFO: Found $Nh Delays"
 
 if($#ncond != 0) then
   if($ncond != $Nc) then
@@ -132,7 +103,6 @@ if($#ncond != 0) then
     exit 1;
   endif
 endif
-
 
 ## Check that the conditions are within range ##
 foreach c ($actcond $ctrlcond)
@@ -198,11 +168,7 @@ set tmp = `basename $contrast .mat`
 if($tmp == $contrast) set cmtxfile = $cmtxfile.mat
 
 set cmd = (mkcontrast)
-if($UseSXADat) then
-  set cmd = ($cmd -sxadat $datfile)
-else
-  set cmd = ($cmd -anadir $analname)
-endif
+set cmd = ($cmd -anadir $analname)
 set cmd = ($cmd -wcond $wcond $sumconds -o $cmtxfile)
 
 set cmd = ($cmd  $sumdelays $showcmtx $rmprestim)
@@ -373,10 +339,6 @@ while( $#argv != 0 )
       set mfile = $argv[1]; shift;
       breaksw
 
-    case "-sxadat":
-      set UseSXADat = 1;
-      breaksw
-
     case "-verbose":
       set verbose = 1;
       breaksw
@@ -435,14 +397,6 @@ check_params:
   if(! -d $analname ) then
     echo "ERROR: analysis $analname does not exist"
     exit 1;
-  endif
-
-  if($UseSXADat) then
-    set datfile = $analname/h.dat
-    if(! -e $datfile) then
-      echo "ERROR: cannot find $datfile"
-      exit 1;
-    endif
   endif
 
   if($#wcond == 0) then
@@ -505,7 +459,6 @@ usage_exit:
   echo "   -ircorr nircorr   : correlate with gamma function"
   echo "   -deltarange dmin dmax : range of delta for gamma function"
   echo "   -taurange   tmin tmax : range of tau for gamma function"
-  echo "   -sxadat           : use sxadat file"
   echo "   -umask umask      : set unix file permission mask"
   echo "   -scriptonly       : don't run, just generate a script"
   echo "   -version          : print version and exit"
diff --git a/fsfast/bin/preproc-sess b/fsfast/bin/preproc-sess
--- a/fsfast/bin/preproc-sess
+++ b/fsfast/bin/preproc-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/15 21:03:11 $
-#    $Revision: 1.30 $
+#    $Date: 2010/04/28 19:42:50 $
+#    $Revision: 1.31 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: preproc-sess,v 1.30 2010/04/15 21:03:11 greve Exp $';
+set VERSION = '$Id: preproc-sess,v 1.31 2010/04/28 19:42:50 greve Exp $';
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M'`"
@@ -59,10 +59,16 @@ set DoVolSmooth = 1;
 set DoSurfSmooth = 0;
 set DoSmooth = 1; # any smoothing
 set DoInorm  = 0;
-set regfile = register.dat
 set ProjFrac = (); # default will be 0.5
 set DoProjAvg = 0;
-set DoReg = 0;
+set DoReg = 1;
+set ToSurf = 0;
+set subject = ();
+set hemi = ();
+set ToMNI305 = 0;
+set RawRes = 2;
+set RegDOF = 6;
+set regfile = ();
 
 set nskip = 0; # for inorm
 set nolog = 0;
@@ -183,6 +189,7 @@ foreach sess ($SessList)
 
   if($DoReg) then
     set cmd = (register-sess -s $sessid -d $sessparent -fsd $fsd)
+    set cmd = ($cmd -dof $RegDOF)
     if($#RunListFile) set cmd = ($cmd -rlf $RunListFile);
     if($PerRun)     set cmd = ($cmd -per-run)
     if($PerSess) set cmd = ($cmd -per-session)
@@ -216,6 +223,36 @@ foreach sess ($SessList)
     if($nolog)      set cmd = ($cmd -nolog);
     if($UpdateOnly) set cmd = ($cmd -update);
     echo "$sessid STC -----------------------------" |& tee -a $LF
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+  endif
+
+  if($ToSurf) then
+    set cmd = (rawfunc2surf-sess -fwhm $fwhm)
+    set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
+    # By default it will do both, so set -hemi to anything
+    if($hemi == lh || $hemi == rh) set cmd = ($cmd -hemi $hemi)
+    if($subject == self) set cmd = ($cmd -self)
+    if($#RunListFile != 0)  set cmd = ($cmd -rlf $RunListFile);
+    if($#SliceOrder) set cmd = ($cmd -stc $SliceOrder)
+    if($nolog)      set cmd = ($cmd -nolog);
+    if($UpdateOnly) set cmd = ($cmd -update);
+    echo "$sessid To Surface -----------------------------" |& tee -a $LF
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+  endif
+
+  if($ToMNI305) then
+    set cmd = (rawfunc2tal-sess -fwhm $fwhm )
+    set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
+    if($RawRes == 1) set cmd = ($cmd -1mm)
+    if($#RunListFile != 0)  set cmd = ($cmd -rlf $RunListFile);
+    if($#SliceOrder) set cmd = ($cmd -stc $SliceOrder)
+    if($nolog)      set cmd = ($cmd -nolog);
+    if($UpdateOnly) set cmd = ($cmd -update);
+    echo "$sessid To Surface -----------------------------" |& tee -a $LF
     echo $cmd |& tee -a $LF
     $cmd |& tee -a $LF
     if($status) exit 1;
@@ -291,6 +328,15 @@ while( $#argv != 0 )
 
     case "-reg":
       set DoReg = 1;
+      breaksw
+
+    case "-no-reg":
+      set DoReg = 0;
+      breaksw
+
+    case "-reg-dof":
+      if ( $#argv == 0) goto arg1err;
+      set RegDOF = $argv[1]; shift;
       breaksw
 
     case "-mc-in":
@@ -407,6 +453,9 @@ while( $#argv != 0 )
     case "-perrun":
       set PerRun = 1;
       set PerSess = 0;
+      set DoSmooth = 0;
+      set DoVolSmooth = 0;
+      set DoSurfSmooth = 0;
       breaksw
 
     case "-per-session":
@@ -420,6 +469,7 @@ while( $#argv != 0 )
       set DoSTC = 0;
       breaksw
 
+    case "-stc":
     case "-sliceorder":
     case "-so":
       if ( $#argv == 0) goto arg1err;
@@ -432,6 +482,59 @@ while( $#argv != 0 )
       set DoVolSmooth = 0;
       set DoSurfSmooth = 0;
       set DoSmooth = 0;
+      breaksw
+
+    case "-surf":
+    case "-surface":
+      if($#argv< 2) goto arg2err;
+      set subject = $argv[1]; shift;
+      set hemi = $argv[1]; shift;
+      set ToSurf = 1;
+      set PerRun = 1;
+      set PerSess = 0;
+      breaksw
+
+    case "-mni305":
+      set RawRes = 2;
+      set ToMNI305 = 1;
+      set PerRun = 1;
+      set PerSess = 0;
+      breaksw
+
+    case "-mni305-1mm":
+      set RawRes = 1;
+      set ToMNI305 = 1;
+      set PerRun = 1;
+      set PerSess = 0;
+      breaksw
+
+    case "-a":
+    case "-analysis":
+      if($#argv< 1) goto arg1err;
+      set analysis = $argv[1]; shift;
+      if(! -e $analysis) then
+        echo "ERROR: cannot find $analysis"
+        exit 1;
+      endif
+      set fsd = `getana -a $analysis -t fsd`;
+      set RunListFile = `getana -a $analysis -t runlistfile`;
+      set RegDOF = `getana -a $analysis -t RegDOF`;
+      set PerRun = `getana -a $analysis -t IsPerRun`;
+      set PerSess = `getana -a $analysis -t IsPerSession`;
+      set fwhm = `getana -a $analysis -t RawFWHM`;
+      if($fwhm == 0 || $PerRun) set DoVolSmooth = 0;
+      set SliceOrder = `getana -a $analysis -t stc`;
+      if($SliceOrder != none) set DoSTC = 1;
+      if($SliceOrder == none) set SliceOrder = ();
+      set ToSurf = `getana -a $analysis -t IsSurface`;
+      if($ToSurf) then
+        set subject = `getana -a $analysis -t subject`;
+        set hemi    = `getana -a $analysis -t hemi`;
+      endif
+      set ToMNI305 = `getana -a $analysis -t IsMNI305`;
+      if($ToMNI305) then
+        set RawRes = `getana -a $analysis -t RawRes`;
+      endif
       breaksw
 
     case "-no-inorm":
@@ -530,9 +633,20 @@ check_params:
 
   if($DoSTC) then
     if($#stcinstem  == 0) set stcinstem  = $mcoutstem
-    if($#stcoutstem == 0) set stcoutstem = $stcinstem"stc"
+    if($#stcoutstem == 0) set stcoutstem = $stcinstem.$SliceOrder
   else
     set stcoutstem = $mcoutstem
+  endif
+
+  if($ToSurf || $ToMNI305) then
+    if($#fwhm == 0) then
+      echo "ERROR: must specify -fwhm with -surface or -mni305."
+      echo "       Set it to 0 for no smoothing"
+      exit 1;
+    endif
+    set DoVolSmooth = 0;
+    set DoSurfSmooth = 0;
+    set DoSmooth = 0;  
   endif
 
   if($DoSmooth) then
@@ -543,8 +657,8 @@ check_params:
     endif
     if($#sminstem  == 0) set sminstem  = $stcoutstem
     if($#smoutstem == 0) then
-      if($DoVolSmooth) set smoutstem = $sminstem"sm"$fwhm
-      if($DoSurfSmooth) set smoutstem = $sminstem"sm"$fwhm"s"
+      if($DoVolSmooth) set smoutstem = $sminstem."sm"$fwhm
+      if($DoSurfSmooth) set smoutstem = $sminstem."sm"$fwhm
     endif
   endif
 
@@ -558,7 +672,7 @@ check_params:
     endif
   endif
 
-  if(! $DoMC && ! $DoSTC  && ! $DoSmooth && ! $DoMask) then
+  if(! $DoMC && ! $DoSTC  && ! $DoSmooth && ! $DoMask && ! $DoTemplate) then
     echo "ERROR: nothing to do"
     exit 1;
   endif
@@ -567,6 +681,8 @@ check_params:
     echo "ERROR: cannot -projfrac and -projfrac-avg"
     exit 1;
   endif
+
+  if($#regfile == 0) set regfile = register.dof$RegDOF.dat
 
 goto check_params_return;
 ############--------------##################
@@ -582,8 +698,6 @@ usage_exit:
   echo ""
   echo "USAGE: preproc-sess"
   echo ""
-  echo "  -i    instem    : stem to use as overal input <f>"
-  echo ""
   echo "  -per-run : motion cor and reg to middle TP of each run"
   echo "  -per-session : motion cor and reg to 1st TP of 1st run"
   echo ""
@@ -593,6 +707,9 @@ usage_exit:
   echo "  -smooth-mask   : use mask when volume smoothing"
   echo "  -no-smooth-mask: do not use mask when volume smoothing"
   echo "  -sliceorder so : turn on slice timing correction with the given slice order"
+  echo "  -surface subject hemi : set hemi to lhrh to do both"
+  echo "  -mni305        : sample raw data to mni305 at 2mm"
+  echo "  -mni305-1mm    : sample raw data to mni305 at 1mm"
   echo ""
   echo "  -nomc     : don't do motion correction"
   echo "  -nostc    : don't do slice-timing correction"
@@ -609,6 +726,7 @@ usage_exit:
   echo "  -smout  sminstem    : stem to use as output of smoothing "
   echo "  -mask   maskstem    : <brain>"
   echo ""
+  echo "  -i    instem    : stem to use as overal input <f>"
   echo "  -vol-fwhm  fwhm : 3D fwhm (mm) (not with -surf-fwhm)"
   echo "  -surf-fwhm fwhm : 2D fwhm (mm) (not with -vol-fwhm)"
   echo "  -inorm        : perform intensity normalization (off by default)"
diff --git a/fsfast/bin/rawfunc2surf-sess b/fsfast/bin/rawfunc2surf-sess
--- a/fsfast/bin/rawfunc2surf-sess
+++ b/fsfast/bin/rawfunc2surf-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/15 21:04:10 $
-#    $Revision: 1.13 $
+#    $Date: 2010/04/28 19:42:50 $
+#    $Revision: 1.14 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,14 +22,15 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: rawfunc2surf-sess,v 1.13 2010/04/15 21:04:10 greve Exp $';
+set VERSION = '$Id: rawfunc2surf-sess,v 1.14 2010/04/28 19:42:50 greve Exp $';
 
 set inputargs = ($argv);
 
 set fsd        = bold;
 set instem     = ()
 set outstem    = ();
-set regfile    = register.dat
+set regfile    = ();
+set regdof     = 6;
 set trgsubject = fsaverage
 set hemilist = ()
 set ProjFrac = 0.5;
@@ -37,6 +38,7 @@ set interp = trilin
 set PerRun = 1;
 set maskname = brain
 set maskdir = masks
+set maskstem = ();
 set RunListFile = ();
 set fwhm = ();
 set UpdateOnly = 0;
@@ -45,6 +47,9 @@ set debug = 0;
 set DoSelf = 0;
 set PrintHelp = 0;
 set SurfReg = sphere.reg
+set ExpKey = ();
+set ExpKeyNeeded = 0;
+set SliceOrder = ();
 
 set outfmt = nii
 if($?FSF_OUTPUT_FORMAT) then
@@ -96,7 +101,7 @@ foreach sess ($SessList)
   if(! $nolog) then
     set logdir = $ProjectDir/log;
     mkdir -p $logdir
-    set LF = $logdir/rawfunc2surf-sess.$sessid.$fsd.$outstem.$hemistr.log
+    set LF = $logdir/rawfunc2surf-sess.$sessid.$fsd.$outstem.$hemistr$ExpKey.log
     if(-e $LF) mv $LF $LF.old
   endif
   echo "rawfunc2surf-sess log file" >> $LF
@@ -122,14 +127,14 @@ foreach sess ($SessList)
       echo "Try running register-sess" | tee -a $LF
       exit 1;
     endif
-    set maskstem = $sess/$fsd/$maskdir/$maskname
-    set mask = `stem2fname $maskstem`
+    set maskstempath = $sess/$fsd/$maskdir/$maskname
+    set mask = `stem2fname $maskstempath`
     if($status) then
       echo "$mask" | tee -a $LF
       echo "Try running mkbrainmask-sess" | tee -a $LF
       exit 1;
     endif
-    set outmask = $sess/$fsd/$maskdir/$maskname.$subjstr.$hemi.$outfmt
+    set outmask = $sess/$fsd/$maskdir/$maskstem.$hemi.$outfmt
   endif
 
   set RunList = `getrunlist $sess/$fsd $RunListFile`;
@@ -156,17 +161,17 @@ foreach sess ($SessList)
         echo "Try running register-sess with -per-run" | tee -a $LF
         exit 1;
       endif
-      set maskstem = $sess/$fsd/$maskdir/$maskname
-      set mask = `stem2fname $maskstem`
+      set maskstempath = $sess/$fsd/$maskdir/$maskname
+      set mask = `stem2fname $maskstempath`
       if($status) then
         echo "$mask" | tee -a $LF
         echo "Try running mkbrainmask-sess with -per-run" | tee -a $LF
         exit 1;
       endif
-      set outmask = $sess/$fsd/$Run/$maskdir/$maskname.$subjstr.$hemi.$outfmt
+      set outmask = $sess/$fsd/$Run/$maskdir/$maskstem.$hemi$ExpKey.$outfmt
     endif
 
-    set outvol = $funcdir/$outstem.$hemi.$outfmt
+    set outvol = $funcdir/$outstem.$hemi$ExpKey.$outfmt
     set UpdateNeeded = 0;
     if(! $UpdateOnly) set UpdateNeeded = 1;
     if(! -e $outvol || ! -e $mask) set UpdateNeeded = 1;
@@ -207,7 +212,7 @@ foreach sess ($SessList)
     if($status) exit 1;
 
     # Smooth raw data within mask
-    if($#fwhm) then
+    if($fwhm != 0) then
       set cmd = (mris_fwhm --s $trgsubject --hemi $hemi --smooth-only \
         --i $outvol --fwhm $fwhm --o $outvol --mask $outmask )
       echo $cmd | tee -a $LF
@@ -241,12 +246,6 @@ while( $#argv != 0 )
       set instem = $argv[1]; shift;
       breaksw
 
-    case "-o":
-    case "-outstem":
-      if ( $#argv == 0) goto arg1err;
-      set outstem = $argv[1]; shift;
-      breaksw
-
     case "-fsd":
       if ( $#argv == 0) goto arg1err;
       set fsd = $argv[1]; shift;
@@ -267,11 +266,19 @@ while( $#argv != 0 )
     case "-no-per-run":
     case "-no-perrun":
       set PerRun = 0;
+      set ExpKeyNeeded = 1;
       breaksw
 
     case "-surfreg":
       if ( $#argv == 0) goto arg1err;
       set SurfReg = $argv[1]; shift;
+      set ExpKeyNeeded = 1;
+      breaksw
+
+    case "-expkey":
+      if($#argv < 1) goto arg1err;
+      set ExpKey = $argv[1]; shift;
+      set ExpKey = (.$ExpKey); # prepend a dot
       breaksw
 
     case "-update":
@@ -283,7 +290,8 @@ while( $#argv != 0 )
       breaksw
 
     case "-nearest":
-      set interp = "nearest"
+      set interp = "nearest"e
+      set ExpKeyNeeded = 1;
       breaksw
 
     case "-trilin":
@@ -295,9 +303,28 @@ while( $#argv != 0 )
       set trgsubject = $argv[1]; shift;
       breaksw
 
+    case "-stc":
+    case "-sliceorder":
+    case "-so":
+      if ( $#argv == 0) goto arg1err;
+      set SliceOrder = $argv[1]; shift;
+      if($SliceOrder != siemens && $SliceOrder != up && $SliceOrder != down && \
+         $SliceOrder != odd && $SliceOrder != even && $SliceOrder != none) then
+         echo "ERROR: -stc is $SliceOrder, must be siemens, up, down, odd, even, or none"
+         exit 1;
+      endif
+      breaksw
+
     case "-reg":
       if($#argv < 1) goto arg1err;
       set regfile = $argv[1]; shift;
+      set ExpKeyNeeded = 1;
+      breaksw
+
+    case "-projfrac":
+      if($#argv < 1) goto arg1err;
+      set ProjFrac = $argv[1]; shift;
+      set ExpKeyNeeded = 1;
       breaksw
 
     case "-fwhm":
@@ -321,6 +348,18 @@ while( $#argv != 0 )
 
     case "-self":
       set DoSelf = 1;
+      breaksw
+
+    # should not use either of these
+    case "-o":
+    case "-outstem":
+      if ( $#argv == 0) goto arg1err;
+      set outstem = $argv[1]; shift;
+      breaksw
+    case "-mask":
+      # output mask stem
+      if ( $#argv == 0) goto arg1err;
+      set maskstem = $argv[1]; shift;
       breaksw
 
     case "-nolog":
@@ -359,9 +398,21 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
+if($#fwhm == 0) then
+  echo "ERROR: you must enter a FWHM. Use 0 for no smoothing."
+  exit 1;
+endif
+if($ExpKeyNeeded && $#ExpKey == 0) then
+  echo "ERROR: experts key needed (-expkey)"
+  exit 1;
+endif
+
+if($#SliceOrder == 0) set SliceOrder = "none";
+
 if($#instem == 0) then
   if($PerRun)   set instem = fmcpr
   if(! $PerRun) set instem = fmc
+  if($SliceOrder != none) set instem = $instem.$SliceOrder
 endif
 
 if($DoSelf) then
@@ -369,11 +420,18 @@ if($DoSelf) then
 else
   set subjstr = $trgsubject
 endif
-if($#outstem == 0) set outstem = $instem.sm$fwhm
-set outstem = $outstem.$subjstr
+
+if($#outstem == 0) set outstem = $instem
+set outstem = $outstem.sm$fwhm.$subjstr; # hemi appended later
+
+if($#maskstem == 0) set maskstem = $maskname
+set maskstem = $maskstem.$subjstr # hemi appended later
+
 if($#hemilist == 0) set hemilist = (lh rh);
 echo "instem $instem"
 echo "outstem $outstem.hemi"
+
+if($#regfile == 0) set regfile  = register.dof$regdof.dat
 
 goto check_params_return;
 ############--------------##################
@@ -388,27 +446,28 @@ arg1err:
 usage_exit:
   echo "rawfunc2surf-sess"
   echo ""
-  echo " Required"
-  echo "  -i instem : eg, fmc"
-  echo ""
   echo " Session Arguments (some required)"
   echo "  -sf sessidfile  ..."
   echo "  -df srchdirfile ..."
   echo "  -s  sessid      ..."
   echo "  -d  srchdir     ..."
   echo ""
-  echo " Optional Arguments"
-  echo "  -o outstem   : eg, fmc.ssm5 (default is instem.trgsubj.hemi)"
-  echo "  -self : map to native subject surface instead of fsaverage"
-  echo "  -nearest     : use nearest neighbor interp (default is trilin)"
-  echo "  -reg regfile : default is register.dat"
-  echo "  -per-session : use session-level registration and mask instead of -per-run"
-  echo "  -surfreg SurfReg : change from $SurfReg"
-  echo "  -fsd dir     : functional subdirectory ($fsd)"
+  echo "  -fwhm FWHMmm : smooth by FWHM mm (enter 0 for no smoothing)"
   echo ""
+  echo "Optional Arguments"
+  echo "  -i instem    :  fmcpr (default is fmcpr)"
+  echo "  -fsd dir     : functional subdirectory ($fsd)"
+  echo "  -self : map to native subject surface instead of fsaverage"
+  echo ""
+  echo "Expert Options"
+  echo "  -reg regfile : default is register.dof$regdof.dat"
+  echo "  -nearest     : use nearest neighbor interp (default is trilin)"
+  echo "  -surfreg SurfReg : change from $SurfReg"
+  echo "  -per-session : use session-level registration and mask instead of -per-run"
+  echo ""
+  echo "Other options"
   echo "  -update : only run if update is needed"
   echo "  -force : force an update (default)"
-  echo ""
   echo "  -version       : print version and exit"
   echo "  -debug"
   echo ""
diff --git a/fsfast/bin/rawfunc2tal-sess b/fsfast/bin/rawfunc2tal-sess
--- a/fsfast/bin/rawfunc2tal-sess
+++ b/fsfast/bin/rawfunc2tal-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/19 22:17:21 $
-#    $Revision: 1.11 $
+#    $Date: 2010/04/28 19:42:50 $
+#    $Revision: 1.12 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,24 +22,31 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: rawfunc2tal-sess,v 1.11 2010/04/19 22:17:21 greve Exp $'
+set VERSION = '$Id: rawfunc2tal-sess,v 1.12 2010/04/28 19:42:50 greve Exp $'
 
 set inputargs = ($argv);
 
 set fsd        = bold;
 set instem     = ();
 set outstem    = ();
-set regfile    = register.dat
-set talres = 2;
+set regfile    = ();
+set regdof     = 6;
+set target = mni305
+set res = 2;
 set talxfm = talairach.xfm
 set interp = trilin
 set PerRun = 1;
 set maskname = brain
 set maskdir = masks
-set fwhm = 0;
+set maskstem = ();
+set fwhm = ();
 set MaskedSmoothing = 1;
 set RunListFile = ();
 set UpdateOnly = 0;
+set ExpKey = ();
+set ExpKeyNeeded = 0;
+set SliceOrder = ();
+
 set nolog = 0;
 set debug = 0;
 set PrintHelp = 0;
@@ -88,7 +95,7 @@ foreach sess ($SessList)
   if(! $nolog) then
     set logdir = $ProjectDir/log;
     mkdir -p $logdir
-    set LF = $logdir/rawfunc2tal-sess.$sessid.$fsd.$outstem.log
+    set LF = $logdir/rawfunc2tal-sess.$sessid.$fsd.$outstem$ExpKey.log
     if(-e $LF) mv $LF $LF.old
   endif
   echo "rawfunc2tal-sess log file" >> $LF
@@ -115,14 +122,14 @@ foreach sess ($SessList)
       echo "Try running register-sess" | tee -a $LF
       exit 1;
     endif
-    set maskstem = $sess/$fsd/$maskdir/$maskname
-    set mask = `stem2fname $maskstem`
+    set maskstempath = $sess/$fsd/$maskdir/$maskname
+    set mask = `stem2fname $maskstempath`
     if($status) then
       echo "$mask" | tee -a $LF
       echo "Try running mkbrainmask-sess" | tee -a $LF
       exit 1;
     endif
-    set outmask = $sess/$fsd/$maskdir/$maskname.tal.$outfmt
+    set outmask = $sess/$fsd/$maskdir/$maskstem$ExpKey.$outfmt
   endif
 
   set RunList = `getrunlist $sess/$fsd $RunListFile`;
@@ -149,17 +156,17 @@ foreach sess ($SessList)
         echo "Try running register-sess with -per-run" | tee -a $LF
         exit 1;
       endif
-      set maskstem = $sess/$fsd/$maskdir/$maskname
-      set mask = `stem2fname $maskstem`
+      set maskstempath = $sess/$fsd/$maskdir/$maskname
+      set mask = `stem2fname $maskstempath`
       if($status) then
         echo "$mask" | tee -a $LF
         echo "Try running mkbrainmask-sess with -per-run" | tee -a $LF
         exit 1;
       endif
-      set outmask = $sess/$fsd/$Run/$maskdir/$maskname.tal.$outfmt
+      set outmask = $sess/$fsd/$Run/$maskdir/$maskstem$ExpKey.$outfmt
     endif
 
-    set outvol = $funcdir/$outstem.$outfmt
+    set outvol = $funcdir/$outstem$ExpKey.$outfmt
     set UpdateNeeded = 0;
     if(! $UpdateOnly) set UpdateNeeded = 1;
     if(! -e $outvol || ! -e $mask) set UpdateNeeded = 1;
@@ -180,7 +187,7 @@ foreach sess ($SessList)
 
     # Create the mask
     set cmd = (mri_vol2vol --mov $mask --reg $reg \
-      --tal --talres $talres --talxfm $talxfm --nearest \
+      --tal --talres $res --talxfm $talxfm --nearest \
       --no-save-reg --o $outmask)
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
@@ -188,7 +195,7 @@ foreach sess ($SessList)
 
     # Convert the native functional space data
     set cmd = (mri_vol2vol --mov $invol --reg $reg \
-      --tal --talres $talres --talxfm $talxfm --interp $interp \
+      --tal --talres $res --talxfm $talxfm --interp $interp \
       --no-save-reg --o $outvol)
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
@@ -229,12 +236,6 @@ while( $#argv != 0 )
       set instem = $argv[1]; shift;
       breaksw
 
-    case "-o":
-    case "-outstem":
-      if ( $#argv == 0) goto arg1err;
-      set outstem = $argv[1]; shift;
-      breaksw
-
     case "-fsd":
       if ( $#argv == 0) goto arg1err;
       set fsd = $argv[1]; shift;
@@ -253,6 +254,7 @@ while( $#argv != 0 )
 
     case "-no-masked-smooth":
       set MaskedSmooth = 0;
+      set ExpKeyNeeded = 1;
       breaksw
 
     case "-per-run":
@@ -264,6 +266,7 @@ while( $#argv != 0 )
     case "-no-per-run":
     case "-no-perrun":
       set PerRun = 0;
+      set ExpKeyNeeded = 1;
       breaksw
 
     case "-update":
@@ -276,6 +279,7 @@ while( $#argv != 0 )
 
     case "-nearest":
       set interp = "nearest"
+      set ExpKeyNeeded = 1;
       breaksw
 
     case "-trilin":
@@ -283,22 +287,49 @@ while( $#argv != 0 )
       breaksw
 
     case "-1mm":
-      set talres = 1;
+      set res = 1;
       breaksw
 
     case "-xfm":
       if($#argv < 1) goto arg1err;
       set talxfm = $argv[1]; shift;
+      set ExpKeyNeeded = 1;
+      breaksw
+
+    case "-stc":
+    case "-sliceorder":
+    case "-so":
+      if ( $#argv == 0) goto arg1err;
+      set SliceOrder = $argv[1]; shift;
+      if($SliceOrder != siemens && $SliceOrder != up && $SliceOrder != down && \
+         $SliceOrder != odd && $SliceOrder != even && $SliceOrder != none) then
+         echo "ERROR: -stc is $SliceOrder, must be siemens, up, down, odd, even, or none"
+         exit 1;
+      endif
       breaksw
 
     case "-reg":
       if($#argv < 1) goto arg1err;
       set regfile = $argv[1]; shift;
+      set ExpKeyNeeded = 1;
       breaksw
 
-    case "-umask":
+    case "-expkey":
+      if($#argv < 1) goto arg1err;
+      set ExpKey = $argv[1]; shift;
+      set ExpKey = (.$ExpKey); # prepend a dot
+      breaksw
+
+    # these should not be used
+    case "-o":
+    case "-outstem":
       if ( $#argv == 0) goto arg1err;
-      umask $argv[1]; shift;
+      set outstem = $argv[1]; shift;
+      breaksw
+    case "-mask":
+      # output mask stem
+      if ( $#argv == 0) goto arg1err;
+      set maskstem = $argv[1]; shift;
       breaksw
 
     case "-nolog":
@@ -337,13 +368,29 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
+if($#fwhm == 0) then
+  echo "ERROR: you must enter a FWHM. Use 0 for no smoothing."
+  exit 1;
+endif
+if($ExpKeyNeeded && $#ExpKey == 0) then
+  echo "ERROR: experts key needed (-expkey)"
+  exit 1;
+endif
+if($#SliceOrder == 0) set SliceOrder = "none";
+
 if($#instem == 0) then
   if($PerRun)   set instem = fmcpr
   if(! $PerRun) set instem = fmc
+  if($SliceOrder != none) set instem = $instem.$SliceOrder
 endif
-if($#outstem == 0) then
-  set outstem = $instem.sm$fwhm.tal
-endif
+
+if($#outstem == 0) set outstem = $instem
+set outstem = $outstem.sm$fwhm.$target.$res"mm"
+
+if($#maskstem == 0) set maskstem = $maskname
+set maskstem = $maskstem.$target.$res"mm"
+
+if($#regfile == 0) set regfile  = register.dof$regdof.dat
 
 goto check_params_return;
 ############--------------##################
@@ -364,22 +411,24 @@ usage_exit:
   echo "  -s  sessid      ..."
   echo "  -d  srchdir     ..."
   echo ""
+  echo "  -fwhm FWHMmm : smooth by FWHM mm  (enter 0 for no smoothing)"
+  echo ""
   echo " Optional Arguments"
-  echo "  -fwhm FWHM : smooth by FWHM mm"
-  echo "  -no-masked-smooth : do not mask when smoothing"
-  echo "  -i instem  : default is fmc.pr"
-  echo "  -o outstem : default is instem.tal"
+  echo "  -1mm         : set output resolution to 1mm (default is 2mm)"
+  echo "  -i instem  : default is fmcpr"
   echo "  -fsd dir     : functional subdirectory ($fsd)"
   echo "  -rlf RLF     : run-list file"
+  echo ""
+  echo "Expert Options"
+  echo "  -no-masked-smooth : do not mask when smoothing"
   echo "  -nearest     : use nearest neighbor interp (default is trilin)"
-  echo "  -1mm         : set output resolution to 1mm (default is 2mm)"
   echo "  -xfm tal.xfm : xfm file found in subject/mri/transforms (default is $talxfm)"
-  echo "  -reg regfile : default is register.dat"
+  echo "  -reg regfile : default is register.dof$regdof.dat"
   echo "  -per-session : use session-level registration and mask instead of -per-run"
   echo ""
+  echo "Other options"
   echo "  -update : only run if update is needed"
   echo "  -force : force an update (default)"
-  echo ""
   echo "  -version       : print version and exit"
   echo "  -debug"
   echo ""
diff --git a/fsfast/bin/selxavg3-sess b/fsfast/bin/selxavg3-sess
--- a/fsfast/bin/selxavg3-sess
+++ b/fsfast/bin/selxavg3-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/23 19:46:24 $
-#    $Revision: 1.48 $
+#    $Date: 2010/04/28 19:42:50 $
+#    $Revision: 1.49 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,18 +23,18 @@
 #
 
 
-set VERSION = '$Id: selxavg3-sess,v 1.48 2010/04/23 19:46:24 greve Exp $'
+set VERSION = '$Id: selxavg3-sess,v 1.49 2010/04/28 19:42:50 greve Exp $'
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M%S'`"
 
 set analysis = ();
 set flacfile = ();
-set fsd = bold
 set geometry = volume
 set subject = ();
 set perrun = 0;
 set jkrun  = 0;
+set DoPreProc = 1;
 
 set OutParent = ();
 set nolog = 0;
@@ -50,7 +50,6 @@ set SaveRes = 0;
 set MatlabSaveRes = 0;
 set SaveResUnwhitened = 0;
 set RequireContrasts = 1;
-set Skip  = 0;
 set Overwrite = 0;
 
 set DoSynth = 0;
@@ -82,47 +81,24 @@ check_params_return:
 set StudyDir = `pwd`;
 
 if($#analysis) then
-  # get full path for cfg and info files #
-  pushd $analysis > /dev/null;
-  set analysisdir = `pwd`;
-  popd > /dev/null;
-  set cfgfile  = $analysisdir/analysis.cfg
-  set infofile = $analysisdir/analysis.info
-  if(! -e $infofile) then
-    echo "ERROR: cannot find $infofile"
-    exit 1;
-  endif
-  set fsd  = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
+  # analysis, not flac file
   set analysisname = $analysis
-  set tmp = `cat $infofile | awk '{if($1 == "surface") print $2" "$3}'`;
-  if($#tmp) then
-    set subject = $tmp[1];
-    set hemi = $tmp[2];
-    set geometry = $hemi;
+  set fsd = `getana -a $analysis -t fsd`;
+  set IsSurface = `getana -a $analysis -t IsSurface`
+  if($IsSurface) then
+    set subject = `getana -a $analysis -t subject`
+    set hemi    = `getana -a $analysis -t hemi`
     echo "Surface data $subject $hemi"
   endif
-  set dt = `cat $infofile | awk '{if($1 == "designtype") print $2}'`;
+  set dt = `getana -a $analysis -t designtype`
   if($dt == "abblocked") set RequireContrasts = 0;
-  ls $analysis/*.mat >& /dev/null
-  if($status && $RequireContrasts) then
+  if($dt == "retinotopy") set RequireContrasts = 0;
+  set contrasts = `getana -a $analysis -t contrasts`
+  if($#contrasts == 0 && $RequireContrasts) then
     echo "ERORR: no contrasts in $analysis."
     echo "  Create contrasts with mkcontrast-sess or run with -no-con-ok."
     exit 1;
   endif
-else
-  #set analysisname = `cat $flacfile | awk '{if($1 == "flacname") print $2}'`
-  set analysisname = `basename $flacfile .flac`
-  set inherit = $flacfile
-  while(1)
-    set tmp = `cat $inherit | awk '{if($1 == "INHERIT") print $2}'`
-    if($#tmp != 0) then
-      set inherit = $tmp;
-      continue
-    endif
-    set fsd = `cat $inherit | awk '{if($1 == "fsd") print $2}'`
-    echo "fsd = $fsd"
-    break;
-  end
 endif
 
 ##### Create a log file ######
@@ -162,6 +138,18 @@ set StartTime = `date`;
 
 if($SaveRes || $SaveResUnwhitened) set MatlabSaveRes = 1;
 
+### Preprocess each session ####
+if($DoPreProc) then
+  foreach sess ($SessList)
+    set sessbase = `basename $sess`;
+    set sessdir  = `dirname  $sess`;
+    set cmd = (preproc-sess -s $sessbase -d $sessdir -a $analysis -nolog -no-reg)
+    echo $cmd | tee -a $LF
+    $cmd | tee -a $LF
+    if($status) exit 1;
+  end
+endif
+
 if($#MLF == 0) set MLF = /tmp/selxavg3-sess-$$.m
 rm -f $MLF
 echo "% `date`  " >> $MLF
@@ -173,12 +161,16 @@ echo "  " >> $MLF
 set okfile = /tmp/selxavg3-sess-$$.ok
 rm -f $okfile
 
+set parname  = `getana -a $analysis -t parname`
+set funcstem = `getana -a $analysis -t funcstem`
+set rlf = `getana -a $analysis -t runlistfile`
+set ConList = `getana -a $analysis -t contrasts`
+
 ### Go through each session ###
 @ nthsess = 0;
 @ nprocs = 0;
 foreach sess ($SessList)
   @ nthsess = $nthsess + 1;
-
   set sessbase = `basename $sess`;
   set sessdir  = `dirname  $sess`;
 
@@ -199,29 +191,71 @@ foreach sess ($SessList)
     set anadir = $OutParent/$sessbase/$fsd/$analysisname
   endif
   echo anadir = $anadir | tee -a $LF
-  if(-e $anadir && $DoGLMFit) then
-    echo "analysis $analysis alread exists for $sessbase" | tee -a $LF
-    if($Skip == 0 && $Overwrite == 0 && ! $monly && ! $perrun && ! $jkrun) then
-      echo "ERROR: analysis $analysis already exists. You must " | tee -a $LF
-      echo "       specify whether to -skip or -overwrite" | tee -a $LF
-      exit 1;
-    endif
-    if($Skip) then
-      if(! -e $anadir/X.mat) then
-        echo "ERROR: analysis dir $anadir exists, but it does not look like "
-        echo "anything is there. Try reanalyzing just this session ($sessbase)"
-        echo "with the -overwrite flag."
+
+  set DoGLMFit = 0;
+  if($Overwrite) set DoGLMFit = 1;
+  set beta = `stem2fname $anadir/beta`
+  if($status) set DoGLMFit = 1;  # Beta file does not exist
+  if($DoGLMFit == 0) then
+    # Ouput beta exists, check against dependencies
+    set deplist = ($analysis/analysis.info);
+    set RunList = (`getrunlist $sess/$fsd $rlf`);
+    set funclist = ()
+    foreach Run ($RunList)
+      set funcstempath = $sess/$fsd/$Run/$funcstem;
+      set func = `stem2fname $funcstempath`;
+      if($status) then
+        echo "ERROR: cannot find $funcstempath"
         exit 1;
       endif
-      echo " ... skipping" | tee -a $LF
-      continue;
-    endif
-    if(! $monly && ! $perrun && ! $jkrun) then
-      echo " ... reanalyzing (deleting old analysis)" | tee -a $LF
-      rm -f $anadir/* $anadir/*/*sig* $anadir/*/*cnr* $anadir/*/*ces* >& /dev/null
-    endif
+      set deplist = ($deplist $func);
+      if($#parname) then
+        set parfile = $sess/$fsd/$Run/$parname
+        if(! -e $parfile) then
+          echo "ERROR: cannot find $parfile"
+          exit 1;
+        endif
+        set deplist = ($deplist $parfile);
+      endif
+    end
+    set DoGLMFit = `UpdateNeeded $beta $deplist`
+    #ls -lt $beta $deplist
   endif
+
+  set DoContrasts = 0;
+  if($Overwrite) set DoContrasts = 1;
+  if($DoGLMFit)  set DoContrasts = 1;
+  foreach con ($ConList)
+    # Check whether output contrast exists
+    set ces = `stem2fname $anadir/$con/ces`
+    if($status) set DoContrasts = 1;
+    # Check dependencies
+    set deplist = ($beta)
+    set mat = $analysis/$con.mat
+    if(-e $mat)  set deplist = ($deplist $mat)
+    set tmp = `UpdateNeeded $ces $deplist`
+    if($tmp) set DoContrasts = 1;
+  end
+
+  set UpdateNeeded = 0;
+  if($DoGLMFit || $DoContrasts) set UpdateNeeded = 1; 
+  if($monly || $perrun) set UpdateNeeded = 1; 
+
+  echo "DoGLMFit = $DoGLMFit"
+  echo "DoContrasts = $DoContrasts"
+  echo "UpdateNeeded = $UpdateNeeded"
+
+  if($UpdateNeeded == 0) then
+    echo "    $sessbase $Run Update not needed" | tee -a $LF
+    continue
+  endif
+
+  # -- If it gets here, then an update is needed --
   @ nprocs = $nprocs + 1;
+
+  if(! $monly && ! $perrun && $DoGLMFit) then
+    rm -f $anadir/* $anadir/*/*sig* $anadir/*/*cnr* $anadir/*/*ces* >& /dev/null
+  endif
 
   echo "%--------------------------------" >> $MLF
   echo "which fast_selxavg3"               >> $MLF
@@ -272,10 +306,7 @@ if(! $monly && $nprocs > 0) then
     exit 1;
   endif
   rm -f $okfile
-endif
-
-# Copy the flac or analysis.*
-if(! $monly) then
+  # Copy the fs build, etc
   foreach sess ($SessList)
     set sessbase = `basename $sess`;
     set sessdir  = `dirname  $sess`;
@@ -285,25 +316,9 @@ if(! $monly) then
       set anadir = $OutParent/$sessbase/$fsd/$analysisname
     endif
     cp $FREESURFER_HOME/build-stamp.txt $anadir/fs.build-stamp.txt
-    if($#flacfile) then
-      cp $flacfile $anadir 
-    else
-      cp $cfgfile $anadir
-      cp $infofile $anadir
-    endif
+    cp $analysis/analysis.info $anadir
   end
-endif
-
-# Compute FWHM
-# Now done in fast_selxavg3
-
-if($#flacfile == 0) then
-  echo "Copying h.dat" | tee -a $LF
-  # Just use the most recent one
-  set sxadat = $anadir/h.dat
-  set cmd = (cp $sxadat $analysis)
-  echo $cmd
-  $cmd |& tee -a $LF
+  # The computing of FWHM is now done in fast_selxavg3
 endif
 
 if($nprocs == 0) then
@@ -377,6 +392,10 @@ while( $#argv != 0 )
       set perrun = 1;
       breaksw
 
+    case "-no-preproc":
+      set DoPreProc = 0;
+      breaksw
+
     case "-jkrun":
       set jkrun = 1;
       breaksw
@@ -400,10 +419,6 @@ while( $#argv != 0 )
 
     case "-fwhm":
       set DoFWHM = 1;
-      breaksw
-
-    case "-skip":
-      set Skip = 1;
       breaksw
 
     case "-force":
@@ -514,7 +529,6 @@ usage_exit:
   echo ""
   echo "Optional Arguments:";
   echo ""
-  echo "   -skip           : skip session of already analyzed"
   echo "   -overwrite      : delete analysis if session of already analyzed"
   echo "   -contrasts-only : only compute contrasts (estimation already done) <-co>"
   echo "   -c c1 <-c c2 ...> : compute contrasts c1, c2, ... (default is to compute all)"
@@ -531,6 +545,7 @@ usage_exit:
   echo "   -d  srchdir     ..."
   echo ""
   echo "Other args"
+  echo "   -no-preproc    : do not run preprocessing"
   echo "   -version       : print version and exit"
   echo "   -debug"
   echo "   -nolog         : do not create a log file"
