Added trap to catch when a condition is specified for both act and ctrl.

diff --git a/fsfast/bin/mkcontrast-sess b/fsfast/bin/mkcontrast-sess
--- a/fsfast/bin/mkcontrast-sess
+++ b/fsfast/bin/mkcontrast-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # stxgrinder-sess
 #
-set VERSION = '$Id: mkcontrast-sess,v 1.3 2004/10/19 21:50:21 greve Exp $'
+set VERSION = '$Id: mkcontrast-sess,v 1.4 2004/11/08 17:47:59 greve Exp $'
 set cmdargs = ($argv);
 
 set contrast   = ();
@@ -365,6 +365,14 @@ check_params:
       echo "ERROR: no control conditions or wcond specified"
       exit 1;
     endif
+    foreach a ($actcond)
+      foreach c ($ctrlcond)
+        if($a == $c) then
+          echo "ERROR: cannot specify the same condition as control and active"
+          exit 1;
+        endif
+      end
+    end
   else
     if($#actcond != 0 || $#ctrlcond != 0) then
       echo "ERROR: cannot specify -wcond with -a or -c"
