Now runs both session and perrun. Now creates a log.

diff --git a/fsfast/bin/mktemplate-sess b/fsfast/bin/mktemplate-sess
--- a/fsfast/bin/mktemplate-sess
+++ b/fsfast/bin/mktemplate-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2009/04/09 21:22:06 $
-#    $Revision: 1.3 $
+#    $Date: 2010/03/31 20:45:58 $
+#    $Revision: 1.4 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,15 +23,14 @@
 #
 
 
-set VERSION = '$Id: mktemplate-sess,v 1.3 2009/04/09 21:22:06 greve Exp $';
+set VERSION = '$Id: mktemplate-sess,v 1.4 2010/03/31 20:45:58 greve Exp $';
 set inputargs = ($argv);
 
 set fsd          = bold;
 set nolog        = 0;
 set NthRun       = ();
 set NthFrame     = ();
-set DoMidFrame     = 0;
-set PerRun       = 0;
+set DoMidFrame   = 0;
 set RunListFile  = ();
 set funcstem     = f;
 set tempstem     = template;
@@ -74,7 +73,7 @@ if(! $nolog) then
     echo "WARNING: could not create $logdir"
     set LF = /dev/null
   else
-    set LF = $logdir/mktemplate-sess.log
+    set LF = $logdir/mktemplate-sess.$$.log
     if(-e $LF) mv $LF $LF.old
   endif
 else
@@ -108,21 +107,74 @@ foreach sess ($SessList)
     exit 1;
   endif
 
-  if(! $PerRun) then  #----------------------------------------------
-    # Make one template for all runs
-    if($#NthRun == 0) then
-      set funcdir = `getfirstrundir-sess $sess/$fsd`;
-      if($status) then
-        echo "$funcdir" |& tee -a $LF
-        exit 1;
-      endif
-    else
-      set funcdir = $sess/$fsd/$Run
-      if(! -e $funcdir) then
-        echo "ERROR: $Run does not exist in $sess/$fsd" |& tee -a $LF
-        exit 1;
-      endif
+  set RunList = `getrunlist $sess/$fsd $RunListFile`;
+  if($status) then
+    echo "$RunList" |& tee -a $LF
+    exit 1;
+  endif
+  if($NthRun > $#RunList) then
+    echo "ERROR: $sess/$fsd only has $#RunList runs, NthRun = $NthRun"|& tee -a $LF
+    exit 1;
+  endif
+
+  # Make one template for all runs
+  set Run = $RunList[$NthRun];
+  set funcdir = $sess/$fsd/$Run
+
+  set ext = `stem2fmt $funcdir/$funcstem`
+  if($status) then
+    echo "$ext" |& tee -a $LF
+    exit 1;
+  endif
+  echo "Detected input format at $ext" |& tee -a $LF
+  set srcvol = $funcdir/$funcstem.$ext
+   
+  set templatevol = $sess/$fsd/template.$FSF_OUTPUT_FORMAT;
+
+  set UpdateNeeded = 1;
+  if(-e $templatevol && $UpdateOnly) then
+    test $srcvol -nt $templatevol
+    if($status) then
+      pwd | tee -a $LF
+      ls -lt $srcvol $templatevol | tee -a $LF
+      echo "Update not needed" | tee -a $LF
+      set UpdateNeeded = 0;
     endif
+  endif
+
+  if($UpdateNeeded) then
+    set cmd = (mri_convert $srcvol $templatevol )
+    if($DoMidFrame) set cmd = ($cmd --mid-frame);
+    if($#NthFrame) set cmd = ($cmd --frame $NthFrame);
+    pwd  |& tee -a $LF
+    echo $cmd |& tee -a $LF
+    $cmd  |& tee -a $LF
+    if($status) exit 1;
+    set llog = $sess/$fsd/template.log
+    rm -f $llog
+    echo "FUNCSTEM $funcstem" >> $llog
+    echo "NTHRUN $NthRun" >> $llog
+    echo "RUNUSE $Run" >> $llog
+    if($DoMidFrame) echo "FRAME mid" >> $llog
+    if($#NthFrame)  echo "FRAME $NthFrame" >> $llog
+  endif
+
+  if($DoView)  tkmedit -f $templatevol
+  if($DoConcat) set concatlist = ($concatlist $templatevol);
+
+  # --------------------------------------------------
+  # Now do separately for each run
+  set st = $status;
+  if($st) then
+    echo "ERROR: getting run list"
+    echo "  $RunList"
+    exit 1;
+  endif
+   
+  foreach Run ($RunList)
+    echo "  Run: $Run ----------------" |& tee -a $LF
+    date  |& tee -a $LF
+    set funcdir = $sess/$fsd/$Run
 
     set ext = `stem2fmt $funcdir/$funcstem`
     if($status) then
@@ -131,8 +183,7 @@ foreach sess ($SessList)
     endif
     echo "Detected input format at $ext" |& tee -a $LF
     set srcvol = $funcdir/$funcstem.$ext
-   
-    set templatevol = $sess/$fsd/template.$FSF_OUTPUT_FORMAT;
+    set templatevol = $funcdir/template.$FSF_OUTPUT_FORMAT;
 
     set UpdateNeeded = 1;
     if(-e $templatevol && $UpdateOnly) then
@@ -146,9 +197,8 @@ foreach sess ($SessList)
     endif
 
     if($UpdateNeeded) then
-      set cmd = (mri_convert $srcvol $templatevol)
-      if($DoMidFrame) set cmd = ($cmd --mid-frame);
-      if($#NthFrame) set cmd = ($cmd --frame $NthFrame);
+      # Force to be mid-frame
+      set cmd = (mri_convert $srcvol $templatevol --mid-frame);
       pwd  |& tee -a $LF
       echo $cmd |& tee -a $LF
       $cmd  |& tee -a $LF
@@ -156,59 +206,8 @@ foreach sess ($SessList)
     endif
 
     if($DoView)  tkmedit -f $templatevol
-
     if($DoConcat) set concatlist = ($concatlist $templatevol);
-
-  else #-------------------------------------------------------
-    # Do separately for each run
-    set RunList = `getrunlist $sess/$fsd $RunListFile`;
-    set st = $status;
-    if($st) then
-      echo "ERROR: getting run list"
-      echo "  $RunList"
-      exit 1;
-    endif
-   
-    foreach Run ($RunList)
-      echo "  Run: $Run ----------------" |& tee -a $LF
-      date  |& tee -a $LF
-      set funcdir = $sess/$fsd/$Run
-
-      set ext = `stem2fmt $funcdir/$funcstem`
-      if($status) then
-        echo "$ext" |& tee -a $LF
-        exit 1;
-      endif
-      echo "Detected input format at $ext" |& tee -a $LF
-      set srcvol = $funcdir/$funcstem.$ext
-      set templatevol = $funcdir/template.$FSF_OUTPUT_FORMAT;
-
-      set UpdateNeeded = 1;
-      if(-e $templatevol && $UpdateOnly) then
-        test $srcvol -nt $templatevol
-        if($status) then
-          pwd | tee -a $LF
-          ls -lt $srcvol $templatevol | tee -a $LF
-          echo "Update not needed" | tee -a $LF
-          set UpdateNeeded = 0;
-        endif
-      endif
-
-      if($UpdateNeeded) then
-        set cmd = (mri_convert $srcvol $templatevol)
-        if($DoMidFrame) set cmd = ($cmd --mid-frame);
-        if($#NthFrame) set cmd = ($cmd --frame $NthFrame);
-        pwd  |& tee -a $LF
-        echo $cmd |& tee -a $LF
-        $cmd  |& tee -a $LF
-        if($status) exit 1;
-      endif
-
-      if($DoView)  tkmedit -f $templatevol
-      if($DoConcat) set concatlist = ($concatlist $templatevol);
-    end  # Loop over runs
-
-  endif
+  end  # Loop over runs
 
 end  # foreach sess ($SessList)
 
@@ -234,6 +233,11 @@ while( $#argv != 0 )
   
   switch($flag)
 
+    case "-funcstem":
+      if ( $#argv == 0) goto arg1err;
+      set funcstem = $argv[1]; shift;
+      breaksw
+
     case "-fsd":
       if ( $#argv == 0) goto arg1err;
       set fsd = $argv[1]; shift;
@@ -245,27 +249,19 @@ while( $#argv != 0 )
       set NthRun = $argv[1]; shift;
       breaksw
 
-    case "-perrun":
-      set PerRun = 1;
-      set DoMidFrame = 1;
-      breaksw
-
     case "-rlf":
       if ( $#argv == 0) goto arg1err;
       set RunListFile = $argv[1]; shift;
       breaksw
 
-    case "-funcstem":
-      if ( $#argv == 0) goto arg1err;
-      set funcstem = $argv[1]; shift;
-      breaksw
-
     case "-frame":
+      # for cross-run template
       if ( $#argv < 1) goto arg1err;
       set NthFrame = $argv[1]; shift;
       breaksw
 
     case "-mid-frame":
+      # for cross-run template, perrun gets mid
       set DoMidFrame = 1;
       breaksw
 
@@ -334,6 +330,8 @@ check_params:
   endif
   if(! $#NthFrame && ! $DoMidFrame) set NthFrame = 0;
 
+  if($#NthRun == 0) set NthRun = 1;
+
 goto check_params_return;
 ############--------------##################
 
@@ -347,23 +345,27 @@ arg1err:
 usage_exit:
   echo "USAGE: mktemplate-sess"
   echo ""
-  echo "  -nthrun nthrun   : 0-based run number (def 0)"
-  echo "  -frame  nthframe : 0-based frame number (def 0)"
-  echo "  -perrun : register each run separately (implies -mid-frame)"
-  echo ""
-  echo "  -fsd dir     : functional subdirectory ($fsd)"
-  echo "  -rlf RLF       : run-list file (with -perrun)"
-  echo "  -funcstem stem : default is f"
-  echo ""
-  echo "  -veiw : dont create template, just view it"
-  echo "  -concat concatfile : concatenate all templates into one file"
-  echo "  -force : force an update"
-  echo ""
+  echo " Session Arguments (some required)"
   echo "  -sf sessidfile  ..."
   echo "  -df srchdirfile ..."
   echo "  -s  sessid      ..."
   echo "  -d  srchdir     ..."
+  echo ""
+  echo " Optional Arguments"
+  echo "  -nthrun nthrun   : 0-based run number (def 0)"
+  echo "  -frame  nthframe : 0-based frame number (def 0)"
+  echo "  -mid-frame  : use the middle time point"
+  echo ""
+  echo "  -fsd dir     : functional subdirectory ($fsd)"
+  echo "  -funcstem stem : default is f"
+  echo "  -rlf RLF       : run-list file"
+  echo ""
+  echo "  -force : force an update"
+  #echo "  -view : dont create template, just view it"
+  #echo "  -concat concatfile : concatenate all templates into one file"
+  echo ""
   echo "  -version       : print version and exit"
+  echo "  -debug"
   echo ""
   if(! $PrintHelp ) exit 1;
 
@@ -377,4 +379,22 @@ exit 1;
 #---- Everything below here is printed out as part of help -----#
 BEGINHELP
 
-Make a template.
+This creates a functional template which is used as the target for
+motion correction and registration and for mask creation. The output
+will be session/bold/template.nii. A template is created for each run
+separately as well for per-run operations.
+
+By default, the session level template is created from the first time
+point of the first run. The run can be changed with -nthrun.  The time
+point can be changed with -frame N or -mid-frame to use the middle
+time point.
+
+By default, the func stem is f (meaning it looks for f.nii or
+f.nii.gz). This can be changed with -funcstem.
+
+By default, it uses "bold". This can be changed with -fsd.
+
+If the template already exists, it looks to see if it is more recent
+than its source. If it is, no action is taken. This can be changed
+by adding -force. 
+
