Added error trap

diff --git a/fsfast/bin/paint-sess b/fsfast/bin/paint-sess
--- a/fsfast/bin/paint-sess
+++ b/fsfast/bin/paint-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # paint-sess
 #
-set VERSION = '$Id: paint-sess,v 1.7 2005/10/07 17:48:04 greve Exp $';
+set VERSION = '$Id: paint-sess,v 1.8 2006/01/05 23:49:44 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -579,6 +579,10 @@ check_params:
   end
   if($IsGroup && ($nGroup != $#SessList) ) then
     echo "ERROR: cannot mix individual and group sessions"
+    exit 1;
+  endif
+  if($IsGroup && $space == sph && $ProjFrac != 0) then
+    echo "ERROR: cannot use -projfrac with spherical space in group analysis"
     exit 1;
   endif
 
