Added -auto

diff --git a/fsfast/bin/par2stf b/fsfast/bin/par2stf
--- a/fsfast/bin/par2stf
+++ b/fsfast/bin/par2stf
@@ -5,9 +5,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: nicks $
-#    $Date: 2007/01/09 22:41:18 $
-#    $Revision: 1.2 $
+#    $Author: greve $
+#    $Date: 2007/11/28 18:45:12 $
+#    $Revision: 1.3 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -31,6 +31,9 @@ set paridlist  = ();
 set durlist = ();
 set wlist   = ();
 set stflist = ();
+set DoAuto  = 0;
+set AutoDur = ();
+set AutoBase = ();
 set PrintHelp = 0;
 
 if($#argv == 0)  goto usage_exit;
@@ -46,11 +49,6 @@ parse_args_return:
 
 goto check_params;
 check_params_return:
-
-if(! -e $parfile) then
-  echo "ERROR: $parfile does not exist"
-  exit 1;
-endif
 
 @ nthid = 1;
 foreach parid ($paridlist)
@@ -78,6 +76,13 @@ while( $#argv != 0 )
     case "-p":
       if ( $#argv == 0) goto arg1err;
       set parfile = $argv[1]; shift;
+      breaksw
+
+    case "-auto":
+      if($#argv < 2) goto arg2err;
+      set AutoBase = $argv[1]; shift;
+      set AutoDur  = $argv[1]; shift;
+      set DoAuto = 1;
       breaksw
 
     case "-id":
@@ -115,6 +120,20 @@ if($#parfile == 0) then
   echo "ERROR: need a par file"
   exit 1;
 endif
+if(! -e $parfile) then
+  echo "ERROR: $parfile does not exist"
+  exit 1;
+endif
+
+if($DoAuto) then
+  set paridlist = `cat $parfile | awk '{if($2 != 0) print $2}'`
+  foreach parid ($paridlist)
+    set durlist   = ($durlist $AutoDur)
+    set wlist     = ($wlist   1);
+    set stflist   = ($stflist $AutoBase.$parid.stf)
+  end
+endif
+
 
 if($#paridlist == 0) then
   echo "ERROR: need at least 1 id"
@@ -131,12 +150,19 @@ arg1err:
 ############--------------##################
 
 ############--------------##################
+arg2err:
+  echo "ERROR: flag $flag requires two arguments"
+  exit 1
+############--------------##################
+
+############--------------##################
 usage_exit:
   echo ""
   echo "USAGE: par2stf"
   echo ""
   echo "  -p parfile"
   echo "  -id parid dur weight stf"
+  echo "  -auto base dur"
   echo ""
   echo "   -version        : print version and exit"
   echo "   -help           : print help and exit"
