Added ability to mc each run individually, using the middle TP as the ref.

diff --git a/fsfast/bin/preproc-sess b/fsfast/bin/preproc-sess
--- a/fsfast/bin/preproc-sess
+++ b/fsfast/bin/preproc-sess
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # preproc-sess - runs preprocessing (mc, spatsmooth, mkbrainmask, inorm)
 
-set VERSION = '$Id: preproc-sess,v 1.1 2003/03/04 21:22:09 greve Exp $';
+set VERSION = '$Id: preproc-sess,v 1.2 2003/09/20 00:43:34 greve Exp $';
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M'`"
@@ -16,6 +16,7 @@ set maskstem   = brain;
 set fwhm    = ();
 set fsd     = bold;
 set rlf     = ();
+set MCPerRun = 0;
 set DoMC     = 1;
 set DoSmooth = 1;
 set DoInorm  = 1;
@@ -83,6 +84,7 @@ foreach sess ($SessList)
   if($DoMC) then
     set cmd = (mc-sess -fstem $mcinstem -fmcstem $mcoutstem -umask $umask);
     set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
+    if($MCPerRun) set cmd = ($cmd -perrun)
     if($#rlf != 0) set cmd = ($cmd -rlf $rlf);
     echo "$sessid MC -----------------------------" |& tee -a $LF
     date      |& tee -a $LF
@@ -221,6 +223,10 @@ while( $#argv != 0 )
       set DoMC = 0;
       breaksw
 
+    case "-mcperrun":
+      set MCPerRun = 1;
+      breaksw
+
     case "-nosmooth":
       set DoSmooth = 0;
       breaksw
@@ -309,6 +315,10 @@ check_params:
     endif
   endif
 
+  if($#rlf != 0 && $MCPerRun) then
+    echo "ERROR: cannot specify both -rlf and -mcperrun"
+    exit 1;
+  endif
 
 goto check_params_return;
 ############--------------##################
@@ -333,6 +343,7 @@ usage_exit:
   echo "  -fwhm   fwhm (mm)"
   echo "  -fsd    fsd <bold>"
   echo "  -rlf    rlf  : run list file (default all runs)"
+  echo "  -mcperrun : perform motion correction on all runs separately"
   echo ""
   echo "  -nomc     : don't do motion correction"
   echo "  -nosmooth : don't do smoothing"
@@ -371,3 +382,5 @@ This will perform the preprocessing steps. The final output will be a
 volume called fmcsm which will be motion corrected and spatially
 smoothed at 5 mm FWHM. Use this name (i,e fmcsm) as the -funcstem
 argument in mkanalysis-sess.new
+
+When -mcperrun is used, the target volume is the middle frame.
