Copied file from dev. Now masks mni305 to subcort by default

diff --git a/fsfast/bin/preproc-sess b/fsfast/bin/preproc-sess
--- a/fsfast/bin/preproc-sess
+++ b/fsfast/bin/preproc-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/07/26 15:55:06 $
-#    $Revision: 1.35 $
+#    $Date: 2011/03/22 17:16:19 $
+#    $Revision: 1.45.2.1 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,8 +22,12 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
+# To get per-run reg with smoothing, make sure -fwhm is after -per-run:
+# preproc-sess -s risk001 -per-run -fwhm 5 -fsd bold 
+# This creates fmcpr.sm5, then
+# mkanalysis-sess -native -funcstem fmcpr.sm5 ...
 
-set VERSION = '$Id: preproc-sess,v 1.35 2010/07/26 15:55:06 greve Exp $';
+set VERSION = '$Id: preproc-sess,v 1.45.2.1 2011/03/22 17:16:19 greve Exp $';
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M'`"
@@ -42,7 +46,7 @@ set UseSmoothMask = 0;
 set fwhm     = ();
 set surffwhm = ();
 set SliceOrder = ();
-set fsd     = bold;
+set fsd      = ();
 set mcrun    = ();
 set mctargstem = ();
 set mctargframe = ();
@@ -69,6 +73,8 @@ set ToMNI305 = 0;
 set RawRes = 2;
 set RegDOF = 6;
 set regfile = ();
+set UseB0DC = 0;
+set ApplySubCortMask = 1;
 
 set nskip = 0; # for inorm
 set nolog = 0;
@@ -112,7 +118,12 @@ else
     echo "WARNING: could not create $logdir"
     set LF = /dev/null
   else
-    set LF = $logdir/preproc-sess.log
+    if($#SessList > 1) then
+      set LF = $logdir/preproc-sess.$$.log
+    else
+      set sb = `basename $SessList`
+      set LF = $logdir/preproc-sess.$sb.log
+    endif
     if(-e $LF) mv $LF $LF.old
   endif
 endif
@@ -195,6 +206,7 @@ foreach sess ($SessList)
     if($PerSess) set cmd = ($cmd -per-session)
     if($nolog)      set cmd = ($cmd -nolog);
     if($UpdateOnly) set cmd = ($cmd -update);
+    if($UseB0DC)    set cmd = ($cmd -b0dc)
     echo "$sessid Registration -----------------------------" |& tee -a $LF
     echo $cmd |& tee -a $LF
     $cmd |& tee -a $LF
@@ -232,12 +244,13 @@ foreach sess ($SessList)
     set cmd = (rawfunc2surf-sess -fwhm $fwhm)
     set cmd = ($cmd -s $sessid -d $sessparent -fsd $fsd)
     # By default it will do both, so set -hemi to anything
-    if($hemi == lh || $hemi == rh) set cmd = ($cmd -hemi $hemi)
+    if("$hemi" == lh || "$hemi" == rh) set cmd = ($cmd -hemi $hemi)
     if($subject == self) set cmd = ($cmd -self)
     if($#RunListFile != 0)  set cmd = ($cmd -rlf $RunListFile);
     if($#SliceOrder) set cmd = ($cmd -stc $SliceOrder)
     if($nolog)      set cmd = ($cmd -nolog);
     if($UpdateOnly) set cmd = ($cmd -update);
+    if($UseB0DC)    set cmd = ($cmd -b0dc)
     echo "$sessid To Surface -----------------------------" |& tee -a $LF
     echo $cmd |& tee -a $LF
     $cmd |& tee -a $LF
@@ -252,7 +265,10 @@ foreach sess ($SessList)
     if($#SliceOrder) set cmd = ($cmd -stc $SliceOrder)
     if($nolog)      set cmd = ($cmd -nolog);
     if($UpdateOnly) set cmd = ($cmd -update);
-    echo "$sessid To Surface -----------------------------" |& tee -a $LF
+    if($UseB0DC)    set cmd = ($cmd -b0dc)
+    if($ApplySubCortMask)   set cmd = ($cmd -subcort-mask)
+    if(! $ApplySubCortMask) set cmd = ($cmd -no-subcort-mask)
+    echo "$sessid To MNI305 -----------------------------" |& tee -a $LF
     echo $cmd |& tee -a $LF
     $cmd |& tee -a $LF
     if($status) exit 1;
@@ -493,8 +509,13 @@ while( $#argv != 0 )
       set ToSurf = 1;
       set PerRun = 1;
       set PerSess = 0;
+      if($subject != self && ! -e $SUBJECTS_DIR/$subject) then
+        echo "ERROR: cannot find $subject in $SUBJECTS_DIR"
+        exit 1;
+      endif
       breaksw
 
+    case "-mni305-2mm":
     case "-mni305":
       set RawRes = 2;
       set ToMNI305 = 1;
@@ -502,11 +523,35 @@ while( $#argv != 0 )
       set PerSess = 0;
       breaksw
 
+    case "-usual":
+      set subject = fsaverage;
+      set hemi = lhrh
+      set ToSurf = 1;
+      set RawRes = 2;
+      set ToMNI305 = 1;
+      set PerRun = 1;
+      set PerSess = 0;
+      set fwhm = 5;
+      breaksw
+
     case "-mni305-1mm":
       set RawRes = 1;
       set ToMNI305 = 1;
       set PerRun = 1;
       set PerSess = 0;
+      breaksw
+
+    case "-subcort-mask":
+    case "-subcort":
+      set ApplySubCortMask = 1;
+      breaksw
+    case "-no-subcort-mask":
+    case "-no-subcort":
+      set ApplySubCortMask = 0;
+      breaksw
+
+    case "-b0dc":
+      set UseB0DC = 1;
       breaksw
 
     case "-a":
@@ -522,6 +567,8 @@ while( $#argv != 0 )
       set RegDOF = `getana -a $analysis -t RegDOF`;
       set PerRun = `getana -a $analysis -t IsPerRun`;
       set PerSess = `getana -a $analysis -t IsPerSession`;
+      set UseB0DC = `getana -a $analysis -t UseB0DC`;
+      if($#UseB0DC == 0) set UseB0DC = 0;
       set fwhm = `getana -a $analysis -t RawFWHM`;
       if($fwhm == 0 || $PerRun) set DoVolSmooth = 0;
       set SliceOrder = `getana -a $analysis -t stc`;
@@ -612,6 +659,12 @@ goto parse_args_return;
 check_params:
   if($#instem == 0) set instem = "f";
 
+  if($#fsd == 0) then
+    echo "ERROR: you must specify a functional subdirectory with -fsd"
+    echo "       eg, -fsd bold or -fsd rest"
+    exit 1
+  endif
+
   if($DoMC || $DoReg) then
     if($PerRun == 0 && $PerSess == 0) then
       echo "ERROR: You must specify -per-run or -per-session"
@@ -624,7 +677,7 @@ check_params:
     if($#mcoutstem == 0) then
       if($PerRun) then
         set mcoutstem = $mcinstem"mcpr"
-      else
+      else # PerSess
         set mcoutstem = $mcinstem"mc"
       endif    
     endif    
@@ -683,7 +736,10 @@ check_params:
     exit 1;
   endif
 
-  if($#regfile == 0) set regfile = register.dof$RegDOF.dat
+  if($#regfile == 0) then
+    if(! $UseB0DC) set regfile = register.dof$RegDOF.dat
+    if($UseB0DC)   set regfile = register.dof$RegDOF.b0dc.dat
+  endif
 
 goto check_params_return;
 ############--------------##################
@@ -691,6 +747,10 @@ goto check_params_return;
 ############--------------##################
 arg1err:
   echo "ERROR: flag $flag requires one argument"
+  exit 1
+############--------------##################
+arg2err:
+  echo "ERROR: flag $flag requires two arguments"
   exit 1
 ############--------------##################
 
@@ -708,7 +768,7 @@ usage_exit:
   echo "  -no-update     : same as -force"
   echo "  -sliceorder so : turn on slice timing correction with the given slice order"
   echo "  -surface subject hemi : set hemi to lhrh to do both"
-  echo "  -mni305        : sample raw data to mni305 at 2mm"
+  echo "  -mni305-2mm    : sample raw data to mni305 at 2mm (same as -mni305)"
   echo "  -mni305-1mm    : sample raw data to mni305 at 1mm"
   echo ""
   echo "Session Arguments (some combination required)"
diff --git a/fsfast/bin/rawfunc2tal-sess b/fsfast/bin/rawfunc2tal-sess
--- a/fsfast/bin/rawfunc2tal-sess
+++ b/fsfast/bin/rawfunc2tal-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/07/26 15:35:44 $
-#    $Revision: 1.15 $
+#    $Date: 2011/03/22 17:16:19 $
+#    $Revision: 1.16.2.1 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,7 +22,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: rawfunc2tal-sess,v 1.15 2010/07/26 15:35:44 greve Exp $'
+set VERSION = '$Id: rawfunc2tal-sess,v 1.16.2.1 2011/03/22 17:16:19 greve Exp $'
 
 set inputargs = ($argv);
 
@@ -46,6 +46,9 @@ set UpdateOnly = 0;
 set ExpKey = ();
 set ExpKeyNeeded = 0;
 set SliceOrder = ();
+set UseB0DC = 0;
+set b0dcmapstem = b0dcmap
+set ApplySubCortMask = 1;
 
 set nolog = 0;
 set debug = 0;
@@ -113,6 +116,15 @@ foreach sess ($SessList)
   if(! -e $sess/$fsd) then
     echo "ERROR: $sess/$fsd does not exist" |& tee -a $LF
     exit 1;
+  endif
+
+  set b0dcmap = ();
+  if($UseB0DC) then
+    set b0dcmap = `stem2fname $sess/$fsd/$b0dcmapstem`;
+    if($status) then
+      echo "$b0dcmap"|& tee -a $LF
+      exit 1;
+    endif
   endif
 
   if(! $PerRun) then
@@ -189,14 +201,28 @@ foreach sess ($SessList)
     set cmd = (mri_vol2vol --mov $mask --reg $reg \
       --tal --talres $res --talxfm $talxfm --nearest \
       --no-save-reg --o $outmask)
+    if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
     if($status) exit 1;
+
+    if($ApplySubCortMask) then
+      set subcortmask = $FREESURFER_HOME/subjects/fsaverage/mri.2mm/subcort.mask.mgz
+      if(! -e $subcortmask) then
+        echo "ERROR: cannot find $subcortmask"      
+        exit 1;
+      endif
+      set cmd = (mri_mask $outmask $subcortmask $outmask)
+      echo $cmd | tee -a $LF
+      $cmd | tee -a $LF
+      if($status) exit 1;
+    endif
 
     # Convert the native functional space data
     set cmd = (mri_vol2vol --mov $invol --reg $reg \
       --tal --talres $res --talxfm $talxfm --interp $interp \
       --no-save-reg --o $outvol)
+    if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
     if($status) exit 1;
@@ -282,6 +308,15 @@ while( $#argv != 0 )
       set ExpKeyNeeded = 1;
       breaksw
 
+    case "-subcort-mask":
+    case "-subcort":
+      set ApplySubCortMask = 1;
+      breaksw
+    case "-no-subcort-mask":
+    case "-no-subcort":
+      set ApplySubCortMask = 0;
+      breaksw
+
     case "-trilin":
       set interp = "trilin"
       breaksw
@@ -318,6 +353,13 @@ while( $#argv != 0 )
       if($#argv < 1) goto arg1err;
       set ExpKey = $argv[1]; shift;
       set ExpKey = (.$ExpKey); # prepend a dot
+      breaksw
+
+    case "-b0dc":
+    case "-b0dcor":
+    case "-vsm":
+      set UseB0DC = 1;
+      set ExpKey = ".b0dc"
       breaksw
 
     # these should not be used
@@ -390,7 +432,10 @@ set outstem = $outstem.sm$fwhm.$target.$res"mm"
 if($#maskstem == 0) set maskstem = $maskname
 set maskstem = $maskstem.$target.$res"mm"
 
-if($#regfile == 0) set regfile  = register.dof$RegDOF.dat
+if($#regfile == 0) then
+  if(! $UseB0DC) set regfile = register.dof$RegDOF.dat
+  if($UseB0DC)   set regfile = register.dof$RegDOF.b0dc.dat
+endif
 
 goto check_params_return;
 ############--------------##################
@@ -425,6 +470,7 @@ usage_exit:
   echo "  -xfm tal.xfm : xfm file found in subject/mri/transforms (default is $talxfm)"
   echo "  -reg regfile : default is register.dof$regdof.dat"
   echo "  -per-session : use session-level registration and mask instead of -per-run"
+  echo "  -no-subcort-mask : do not apply MNI305 subcortical mask"
   echo ""
   echo "Other options"
   echo "  -update : only run if update is needed"
