UPdated to use new mri_vol2vol. Now requires that dim be specified instead of fov.

diff --git a/fsfast/bin/rawfunc2tal b/fsfast/bin/rawfunc2tal
--- a/fsfast/bin/rawfunc2tal
+++ b/fsfast/bin/rawfunc2tal
@@ -1,14 +1,15 @@
 #!/bin/csh -f
 # rawfunc2tal
 #
-# $Id: rawfunc2tal,v 1.1 2003/03/04 21:22:09 greve Exp $
-set VERSION = '$Id: rawfunc2tal,v 1.1 2003/03/04 21:22:09 greve Exp $'
+# $Id: rawfunc2tal,v 1.2 2004/07/23 15:44:31 greve Exp $
+set VERSION = '$Id: rawfunc2tal,v 1.2 2004/07/23 15:44:31 greve Exp $'
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 #------ Defaults --------#
 set instem   = ();
 set outstem  = ();
 set voxsize  = ();
+set dim      = ();
 set fov      = ();
 set reg      = ();
 set talxfm   = ();
@@ -40,15 +41,16 @@ date
 set outdir = `dirname $outstem`;
 mkdir -p $outdir
 
-set cmd = ( mri_vol2vol --srcvol $instem --srcreg $reg)
-set cmd = ( $cmd --trgvol $outstem );
-set cmd = ( $cmd --trgres $voxsize);
-set cmd = ( $cmd --trgfov $fov);
-if($#talxfm != 0) then
-  set cmd = ( $cmd --src2trg $talxfm --trgsubject talairach);
-else
-  set cmd = ( $cmd --fstalairach);
-endif
+set inbext = `getbext $instem`;
+set infile = $instem"_000."$inbext
+set outfile = $outstem"_000.bfloat"
+
+set cmd = ($DEV/mri_vol2vol/mri_vol2vol --in $infile)
+set cmd = ( $cmd --out $outfile );
+set cmd = ( $cmd --temp $SUBJECTS_DIR/talairach/mri/orig COR)
+set cmd = ( $cmd --voxres $voxsize);
+set cmd = ( $cmd --xfm $reg --fstal);
+if($#dim) set cmd = ( $cmd --voxdim $dim);
 
 echo "---------------------------------------------" 
 pwd        
@@ -114,6 +116,15 @@ while( $#argv != 0 )
       shift; shift; shift;
       breaksw
 
+    case "-dim":
+      if( $#argv < 3) then
+        echo "ERROR: $flag requires 3 arguments"
+        exit 1;
+      endif
+      set dim = ($argv[1] $argv[2] $argv[3]);
+      shift; shift; shift;
+      breaksw
+
     case "-umask":
       if ( $#argv == 0) goto arg1err;
       umask $argv[1]; shift;
@@ -172,8 +183,8 @@ check_params:
     exit 1;
   endif
 
-  if($#fov == 0) then
-    echo "ERROR: need to specify output FOV"
+  if($#dim == 0) then
+    echo "ERROR: need to specify output dimension"
     exit 1;
   endif
 
@@ -196,7 +207,8 @@ usage_exit:
   echo " -o outstem : output stem"
   echo " -r regfile : register.dat file"
   echo " -voxsize colsize rowsize slicesize : size in mm"
-  echo " -fov     colfov  rowfov  slicefov  : field of view in mm"
+  echo " -dim     ncols  nrows  nslice  : dimension of the output vol"
+  #echo " -fov     colfov  rowfov  slicefov  : field of view in mm"
   echo ""
   echo "Other Arguments"
   echo " -t talxfm      : talairach.xfm file"
diff --git a/fsfast/bin/rawfunc2tal-sess b/fsfast/bin/rawfunc2tal-sess
--- a/fsfast/bin/rawfunc2tal-sess
+++ b/fsfast/bin/rawfunc2tal-sess
@@ -1,8 +1,8 @@
 #!/bin/csh -f
 # rawfunc2tal-sess
 #
-# $Id: rawfunc2tal-sess,v 1.1 2003/03/04 21:22:09 greve Exp $
-set VERSION = '$Id: rawfunc2tal-sess,v 1.1 2003/03/04 21:22:09 greve Exp $'
+# $Id: rawfunc2tal-sess,v 1.2 2004/07/23 15:44:31 greve Exp $
+set VERSION = '$Id: rawfunc2tal-sess,v 1.2 2004/07/23 15:44:31 greve Exp $'
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 #------ Defaults --------#
@@ -12,11 +12,13 @@ set talstem  = ();
 set talsd    = ();
 set voxsize  = ();
 set fov      = ();
+set dim      = ();
 set samesess = 0;
 set asd      = 3danat;  
 set userun   = ();
 set runlistfile = ();
 set parlist  = ();
+set nolog    = 0;
 
 set inputargs = ($argv);
 
@@ -45,15 +47,20 @@ goto check_params;
 check_params_return:
 
 ##### Create a log file ######
-set logdir = `pwd`/log;
-mkdir -p $logdir
-if(! -e $logdir) then
-  echo "WARNING: could not create $logdir"
-  set LF = /dev/null
+if(! $nolog) then
+  set logdir = `pwd`/log;
+  mkdir -p $logdir
+  if(! -e $logdir) then
+    echo "WARNING: could not create $logdir"
+    set LF = /dev/null
+  else
+    set LF = $logdir/rawfunc2tal-sess.log
+    if(-e $LF) mv $LF $LF.old
+  endif
 else
-  set LF = $logdir/rawfunc2tal-sess.log
-  if(-e $LF) mv $LF $LF.old
+  set LF = /dev/null
 endif
+
 
 echo "--------------------------------------------------------------"
 echo "rawfunc2tal-sess logfile is $LF"
@@ -153,7 +160,8 @@ foreach sess ($SessList)
     set cmd = ($cmd -o $talsd/$Run/$talstem)
     set cmd = ($cmd -r $regfile)
     set cmd = ($cmd -voxsize $voxsize)
-    set cmd = ($cmd -fov $fov)
+    #set cmd = ($cmd -fov $fov)
+    if($#dim) set cmd = ( $cmd -dim $dim);
     if($#talxfm != 0) set cmd = ($cmd -t $talxfm)
     set cmd = ($cmd -umask `umask`)
 
@@ -242,6 +250,15 @@ while( $#argv != 0 )
       shift; shift; shift;
       breaksw
 
+    case "-dim":
+      if( $#argv < 3) then
+        echo "ERROR: $flag requires 3 arguments"
+        exit 1;
+      endif
+      set dim = ($argv[1] $argv[2] $argv[3]);
+      shift; shift; shift;
+      breaksw
+
     case "-fov":
       if( $#argv < 3) then
         echo "ERROR: $flag requires 3 arguments"
@@ -291,6 +308,10 @@ while( $#argv != 0 )
     case "-umask":
       if ( $#argv == 0) goto arg1err;
       umask $argv[1]; shift;
+      breaksw
+
+    case "-nolog":
+      set nolog = 1;
       breaksw
 
     case "-verbose":
@@ -356,8 +377,8 @@ check_params:
     exit 1;
   endif
 
-  if($#fov == 0) then
-    echo "ERROR: need to specify output FOV"
+  if($#dim == 0) then
+    echo "ERROR: need to specify output dimension"
     exit 1;
   endif
 
@@ -379,7 +400,8 @@ usage_exit:
   echo "  -funcstem stem   : convert this volume"
   echo "  -talsd talsubdir : put output volume in this subdirectory"
   echo "  -voxsize colsize rowsize slicesize : size in mm"
-  echo "  -fov     colfov  rowfov  slicefov  : field of view in mm"
+  echo "  -dim     ncols  nrows  nslice  : dimension of the output vol"
+  #echo "  -fov     colfov  rowfov  slicefov  : field of view in mm"
   echo ""
   echo "Optional Arguments:"
   echo "  -talstem talstem : stem to give to output volume (default funcstem)"
