Added -cvs

diff --git a/fsfast/bin/rawfunc2tal-sess b/fsfast/bin/rawfunc2tal-sess
--- a/fsfast/bin/rawfunc2tal-sess
+++ b/fsfast/bin/rawfunc2tal-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2014/10/30 16:18:12 $
-#    $Revision: 1.23 $
+#    $Date: 2014/11/26 00:33:19 $
+#    $Revision: 1.24 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,7 +22,7 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: rawfunc2tal-sess,v 1.23 2014/10/30 16:18:12 greve Exp $'
+set VERSION = '$Id: rawfunc2tal-sess,v 1.24 2014/11/26 00:33:19 greve Exp $'
 
 set inputargs = ($argv);
 
@@ -49,6 +49,7 @@ set SliceOrder = ();
 set UseB0DC = 0;
 set b0dcmapstem = b0dcmap
 set ApplySubCortMask = 1;
+set UseCVS = 0;
 
 set nolog = 0;
 set debug = 0;
@@ -182,10 +183,23 @@ foreach sess ($SessList)
     set UpdateNeeded = `UpdateNeeded $outmask $reg $mask $b0dcmap`;
     if(! $UpdateOnly) set UpdateNeeded = 1;    
     if($UpdateNeeded) then
-      set cmd = (mri_vol2vol --mov $mask --reg $reg \
-        --tal --talres $res --talxfm $talxfm --nearest \
-        --no-save-reg --o $outmask)
-      if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
+      if($UseCVS == 0) then
+        set cmd = (mri_vol2vol --mov $mask --reg $reg \
+          --tal --talres $res --talxfm $talxfm --nearest \
+          --no-save-reg --o $outmask)
+        if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
+      else
+        set gcam = $SUBJECTS_DIR/fsf01anat/cvs/final_CVSmorph_tocvs_avg35_inMNI152.m3z
+	if(! -e $gcam) then
+          echo "ERROR: cannot find $gcam" | tee -a $LF
+          exit 1;
+        endif
+        set dstreg = $FREESURFER_HOME/subjects/cvs_avg35_inMNI152/mri.2mm/register.lta
+        set cmd = (mri_vol2vol --gcam $mask $reg $gcam $dstreg)
+        if($UseB0DC) set cmd = ($cmd $b0dcmap)
+        if(! $UseB0DC) set cmd = ($cmd 0)
+        set cmd = ($cmd 0 $outmask)
+      endif
       echo $cmd | tee -a $LF
       $cmd | tee -a $LF
       if($status) exit 1;
@@ -202,10 +216,14 @@ foreach sess ($SessList)
     endif
 
     if($ApplySubCortMask) then
-      if($res == 2) then
-        set subcortmask = $FREESURFER_HOME/subjects/fsaverage/mri.2mm/subcort.mask.mgz
+      if($UseCVS == 0) then
+        if($res == 2) then
+          set subcortmask = $FREESURFER_HOME/subjects/fsaverage/mri.2mm/subcort.mask.mgz
+        else
+          set subcortmask = $FREESURFER_HOME/subjects/fsaverage/mri/subcort.mask.1mm.mgz
+        endif
       else
-        set subcortmask = $FREESURFER_HOME/subjects/fsaverage/mri/subcort.mask.1mm.mgz
+        set subcortmask = $FREESURFER_HOME/subjects/cvs_avg35_inMNI152/mri.2mm/subcort.mask.mgz
       endif
       if(! -e $subcortmask) then
         echo "ERROR: cannot find $subcortmask"      
@@ -218,10 +236,23 @@ foreach sess ($SessList)
     endif
 
     # Convert the native functional space data
-    set cmd = (mri_vol2vol --mov $invol --reg $reg \
-      --tal --talres $res --talxfm $talxfm --interp $interp \
-      --no-save-reg --o $outvol)
-    if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
+    if($UseCVS == 0) then
+      set cmd = (mri_vol2vol --mov $invol --reg $reg \
+        --tal --talres $res --talxfm $talxfm --interp $interp \
+        --no-save-reg --o $outvol)
+      if($UseB0DC) set cmd = ($cmd --vsm $b0dcmap)
+    else
+      set gcam = $SUBJECTS_DIR/fsf01anat/cvs/final_CVSmorph_tocvs_avg35_inMNI152.m3z
+      if(! -e $gcam) then
+        echo "ERROR: cannot find $gcam" | tee -a $LF
+        exit 1;
+      endif
+      set dstreg = $FREESURFER_HOME/subjects/cvs_avg35_inMNI152/mri.2mm/register.lta
+      set cmd = (mri_vol2vol --gcam $invol $reg $gcam $dstreg)
+      if($UseB0DC) set cmd = ($cmd $b0dcmap)
+      if(! $UseB0DC) set cmd = ($cmd 0)
+      set cmd = ($cmd 0 $outvol)
+    endif
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
     if($status) exit 1;
@@ -275,6 +306,12 @@ while( $#argv != 0 )
     case "-fwhm":
       if ( $#argv == 0) goto arg1err;
       set fwhm = $argv[1]; shift;
+      breaksw
+
+    case "-cvs"
+      set target = cvs_avg35_inMNI152;
+      set UseCVS = 1;
+      set res = 2;
       breaksw
 
     case "-no-masked-smooth":
@@ -469,7 +506,8 @@ usage_exit:
   echo "  -xfm tal.xfm : xfm file found in subject/mri/transforms (default is $talxfm)"
   echo "  -reg regfile : default is register.dof$RegDOF.lta"
   echo "  -per-session : use session-level registration and mask instead of -per-run"
-  echo "  -no-subcort-mask : do not apply MNI305 subcortical mask"
+  echo "  -no-subcort-mask : do not apply subcortical mask"
+  echo "  -cvs : use cvs_avg35_inMNI152 instead of MNI305 (res fixed at 2mm)"
   echo ""
   echo "Other options"
   echo "  -update : only run if update is needed"
