Added ability to access jk and perrun analysis with -nthrun flag.

diff --git a/fsfast/bin/roisummary-sess b/fsfast/bin/roisummary-sess
--- a/fsfast/bin/roisummary-sess
+++ b/fsfast/bin/roisummary-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # func2roi-sess 
 
-set VERSION = '$Id: roisummary-sess,v 1.1 2003/03/04 21:22:09 greve Exp $';
+set VERSION = '$Id: roisummary-sess,v 1.2 2003/03/20 23:11:34 greve Exp $';
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 set inputargs = ($argv);
@@ -18,6 +18,10 @@ set rawstem = ();
 set rawrunlistfile = ();
 set tbltranspose = 0;
 set includesessid = 1;
+set NthRun = ();
+set NthRunType = ();
+set anapend = ();
+set runlistfile = ();
 
 set umaskarg = ();
 set nolog = 0;
@@ -84,6 +88,7 @@ if(! -e $infofile) then
   exit 1;
 endif
 set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
+set runlistfile = `cat $infofile | awk '{if($1 == "runlistfile") print $2}'`;
 
 set outdir = `dirname $sumfile`;
 mkdir -p $outdir
@@ -96,7 +101,23 @@ foreach sess ($SessList)
   set sessid = `basename $sess`;
   set sessidlist = ($sessidlist $sessid)
 
-  set roidir = $sess/$fsd/$analysis/$roidef
+  if($#NthRun != 0) then
+    set runlist = `getrunlist $sess/$fsd $runlistfile`;
+    if($status) then
+      echo $runlist;
+      exit 1;
+    endif
+    if($NthRun > $#runlist) then
+      echo "ERROR: NthRun = $NthRun, nruns = $#runlist"
+      exit 1;
+    endif
+    set run = $runlist[$NthRun];
+    if($NthRunType == perrun) set anapend = "-$run"
+    if($NthRunType == jk) set anapend = "-jk$run"
+    #echo "NthRun: $NthRun $NthRunType $anapend"
+  endif
+
+  set roidir = $sess/$fsd/$analysis$anapend/$roidef
   if(! -e $roidir) then
     echo "ERROR: cannot find $roidir"
     exit 1;
@@ -105,7 +126,7 @@ foreach sess ($SessList)
   set hdat = $roidir/h.dat
   set htxt = $roidir/h.txt
   set hoffsettxt = $roidir/h-offset.txt
-  set tblfile = $sess/$fsd/$analysis/$roidef/h.tbl
+  set tblfile = $sess/$fsd/$analysis$anapend/$roidef/h.tbl
 
   roitxt2tbl $hdat $htxt $hoffsettxt $tblfile
   if($status)then
@@ -160,6 +181,25 @@ while( $#argv != 0 )
     case "-analysis":
       if ( $#argv == 0) goto arg1err;
       set analysis = $argv[1]; shift;
+      breaksw
+
+    case "-anapend":
+      if ( $#argv == 0) goto arg1err;
+      set anapend = $argv[1]; shift;
+      breaksw
+
+    case "-nthrun"
+      if ( $#argv == 0) goto arg2err;
+      set NthRun = $argv[1]; shift;
+      set NthRunType = $argv[1]; shift;
+      if($NthRun <= 0) then
+        echo "ERROR: NthRun = $NthRun, must be > 0"
+        exit 1;
+      endif
+      if("$NthRunType" != perrun && "$NthRunType" != jk) then
+        echo "ERROR: NthRunType = $NthRunType, must be perrun or jk"
+        exit 1;
+      endif
       breaksw
 
     case "-sumfile":
@@ -242,6 +282,11 @@ check_params:
     exit 1
   endif
 
+  if($#anapend != 0 && $NthRun != 0) then
+    echo "ERROR: cannot specify both anapend and nthrun"
+    exit 1;
+  endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -259,6 +304,7 @@ usage_exit:
   echo "   -roidef   name : name of ROI definition"
 
   echo "   -analysis name : source is averaged data from analysis"
+  echo "   -nthrun nthrun type : type = perrun or jk"
   echo "   -sf sessidfile  ..."
   echo "   -df srchdirfile ..."
   echo "   -s  sessid      ..."
