Added hook for PE preopt

diff --git a/fsfast/bin/segregister-sess b/fsfast/bin/segregister-sess
--- a/fsfast/bin/segregister-sess
+++ b/fsfast/bin/segregister-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/01/14 03:18:40 $
-#    $Revision: 1.4 $
+#    $Date: 2008/01/14 07:28:25 $
+#    $Revision: 1.5 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: segregister-sess,v 1.4 2008/01/14 03:18:40 greve Exp $';
+set VERSION = '$Id: segregister-sess,v 1.5 2008/01/14 07:28:25 greve Exp $';
 set inputargs = ($argv);
 set DateString = "`date '+%y%m%d%H%M'`"
 
@@ -43,6 +43,10 @@ set frame        = ();
 set midframe     = 0;
 set svtemplate   = 1;
 set UseSessInReg = 0;
+set Do1DPreOpt = 0;
+set PreOptMin = ();
+set PreOptMax = ();
+set PreOptDelta = ();
 
 ## If there are no options, just print the usage ##
 if($#argv == 0) goto usage_exit;
@@ -196,6 +200,9 @@ foreach sess ($SessList)
          --cost $funcdir/cost.register.seg.dat)
       if($midframe) set cmd = ($cmd --mid-frame)
       if($#frame)   set cmd = ($cmd --frame $frame)
+      if($Do1DPreOpt) then
+         set cmd = ($cmd --1dpreopt $PreOptMin $PreOptMax $PreOptDelta)
+      endif
       pwd |& tee -a $LF
       echo $cmd |& tee -a $LF
       $cmd |& tee -a $LF
@@ -301,6 +308,18 @@ while( $#argv != 0 )
       set outregfilename = $argv[1]; shift;
       breaksw
 
+    case "-1dpreopt":
+      if ($#argv < 3) goto arg3err;
+      set PreOptMin   = $argv[1]; shift;
+      set PreOptMax   = $argv[1]; shift;
+      set PreOptDelta = $argv[1]; shift;
+      set Do1DPreOpt = 1;
+      breaksw
+
+    case "-no-1dpreopt":
+      set Do1DPreOpt = 0;
+      breaksw
+
     case "-nolog":
       set nolog = 1;
       breaksw
@@ -374,6 +393,12 @@ arg1err:
 ############--------------##################
 
 ############--------------##################
+arg3err:
+  echo "ERROR: flag $flag requires three arguments"
+  exit 1
+############--------------##################
+
+############--------------##################
 usage_exit:
   echo "USAGE: segregister-sess"
   echo ""
@@ -395,6 +420,8 @@ usage_exit:
   echo "   -in-reg-sess    : use session input reg even with -perrun"
   echo "   -out-reg  file  : output registration file"
   echo "   -fmt format     : format of functional: <auto>, nii.gz, bhdr, mgh, etc"
+  echo "   -1dpreopt min max delta"
+  echo "   -no-1dpreopt"
   echo ""
   echo "   -umask umask   : set unix file permission mask"
   echo "   -version       : print version and exit"
