added more stuff

diff --git a/fsfast/bin/selxavg3-sess b/fsfast/bin/selxavg3-sess
--- a/fsfast/bin/selxavg3-sess
+++ b/fsfast/bin/selxavg3-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/02/07 22:56:54 $
-#    $Revision: 1.5 $
+#    $Date: 2007/02/07 23:28:27 $
+#    $Revision: 1.6 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: selxavg3-sess,v 1.5 2007/02/07 22:56:54 greve Exp $'
+set VERSION = '$Id: selxavg3-sess,v 1.6 2007/02/07 23:28:27 greve Exp $'
 
 set inputargs = ($argv);
 set DateStr = "`date '+%y%m%d%H%M%S'`"
@@ -39,6 +39,10 @@ set MLF = ();
 
 set DoGLMFit = 1;
 set DoContrasts = 1;
+
+set Skip  = 0;
+set Overwrite = 0;
+
 set DoSynth = 0;
 set SynthNoiseAmp = 1;
 set SynthSignalAmp = 0;
@@ -78,6 +82,19 @@ if($#analysis) then
     exit 1;
   endif
   set fsd  = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
+else
+  set analysis = `cat $flacfile | awk '{if($1 == "flacname") print $2}'`
+  set inherit = $flacfile
+  while(1)
+    set tmp = `cat $inherit | awk '{if($1 == "INHERIT") print $2}'`
+    if($#tmp != 0) then
+      set inherit = $tmp;
+      continue
+    endif
+    set fsd = `cat $inherit | awk '{if($1 == "fsd") print $2}'`
+    echo "fsd = $fsd"
+    break;
+  end
 endif
 
 ##### Create a log file ######
@@ -117,8 +134,10 @@ if($#MLF == 0) set MLF = /tmp/selxavg3-sess-$$.m
 rm -f $MLF
 
 ### Go through each session ###
-@ nthsess = 1;
+@ nthsess = 0;
+@ nprocs = 0;
 foreach sess ($SessList)
+  @ nthsess = $nthsess + 1;
 
   set sessbase = `basename $sess`;
   set sessdir  = `dirname  $sess`;
@@ -130,6 +149,24 @@ foreach sess ($SessList)
     echo "ERROR: $sess does not exist"   |& tee -a $LF
     exit 1;
   endif
+
+  set funcdir = $sess/$fsd
+  set anadir = $sess/$fsd/$analysis
+  if(-e $anadir && $DoGLMFit) then
+    echo "analysis $analysis alread exists" | tee -a $LF
+    if($Skip == 0 && $Overwrite == 0) then
+      echo "ERROR: analysis $analysis already exists. You must " | tee -a $LF
+      echo "       specify whether to -skip or -overwrite" | tee -a $LF
+      exit 1;
+    endif
+    if($Skip) then
+      echo " ... skipping" | tee -a $LF
+      continue;
+    endif
+    echo " ... reanalyzing (deleting old analysis)" | tee -a $LF
+    rm -r $anadir
+  endif
+  @ nprocs = $nprocs + 1;
 
   echo "monly          = $monly;"       >> $MLF
   echo "DoGLMFit       = $DoGLMFit;"    >> $MLF
@@ -148,7 +185,6 @@ foreach sess ($SessList)
     echo "pack;" >> $MLF
   endif
 
-  @ nthsess = $nthsess + 1;
 end # Loop over sessions #
 
 set okfile = /tmp/selxavg3-sess-$$.ok
@@ -160,7 +196,12 @@ echo "------------------------------------------" >> $LF
 cat $MLF >> $LF
 echo "------------------------------------------" >> $LF
 
-if(! $monly) then
+if($nprocs == 0) then
+  echo "INFO: no data sets needed processing" | tee -a $LF
+  exit 0;
+endif
+
+if(! $monly && $nprocs > 0) then
   echo "------------------------------------------" | tee -a $LF
   echo "------- matlab output --------------------" | tee -a $LF
   cat $MLF | matlab -display iconic | tee -a $LF
@@ -173,10 +214,9 @@ if(! $monly) then
   rm -f $okfile
 endif
 
-# Should now go through each session and compute fwhm
+# Should now go through each session and compute fwhm, then del res
 
-
-if($#analysis) then
+if($#flacfile == 0) then
   set sxadat = $sess/$fsd/$analysis/h.dat
   cp $sxadat $analysis
 endif
@@ -230,8 +270,12 @@ while( $#argv != 0 )
       set DoContrasts = 1;
       breaksw
 
-    case "-nolog":
-      set nolog = 1;
+    case "-skip":
+      set Skip = 1;
+      breaksw
+
+    case "-overwrite":
+      set Overwrite = 1;
       breaksw
 
     case "-debug":
