Added ability to get summary of all runs/sessions

diff --git a/fsfast/bin/spikedet-sess b/fsfast/bin/spikedet-sess
--- a/fsfast/bin/spikedet-sess
+++ b/fsfast/bin/spikedet-sess
@@ -1,9 +1,9 @@
 #!/bin/csh -f
 # spikedet-sess
 #
-# $Id: spikedet-sess,v 1.4 2004/05/21 22:18:56 greve Exp $
+# $Id: spikedet-sess,v 1.5 2005/02/22 23:46:15 greve Exp $
 
-set VERSION = '$Id: spikedet-sess,v 1.4 2004/05/21 22:18:56 greve Exp $';
+set VERSION = '$Id: spikedet-sess,v 1.5 2005/02/22 23:46:15 greve Exp $';
 
 set cmdargs = ($argv);
 
@@ -14,6 +14,7 @@ set PrintHelp = 0;
 set fftflag   = 0;
 set maskthresh = 0;
 set sumsuffix = ();
+set SessSumFile = ();
 set SessSumOnly = 0;
 
 if($#argv == 0)  goto usage_exit;
@@ -55,6 +56,9 @@ echo $VERSION | tee -a $LF
 hostname  | tee -a $LF
 
 #------------------------------------------------------------------#
+if($#SessSumFile) then
+  if(-e $SessSumFile) mv $SessSumFile $SessSumFile.bak
+endif
 set StartTime = `date`;
 foreach sess ($SessList)
   set sessid = `basename $sess`;
@@ -94,6 +98,7 @@ foreach sess ($SessList)
   ## Go through each run ##
   foreach run ($RunList)
 
+    # Generate the run-by-run summary file
     if(! $SessSumOnly) then
       # Construct and run the command for this run #
       set cmd = (spikedet --i $sess/$fsd/$run/$funcstem)
@@ -106,6 +111,25 @@ foreach sess ($SessList)
       if($status) then
         echo "ERROR: spikedet failed" | tee -a $LF
         exit 1
+      endif
+    endif
+
+    if($#SessSumFile) then
+      if(! $#sumsuffix) then
+        set runsum = $sess/$fsd/$run/$funcstem.spike.sum
+      else
+        set runsum = $sess/$fsd/$run/$funcstem.$sumsuffix.sum
+      endif
+      if(! -e $runsum) then
+        echo "ERROR: cannot find $runsum" | tee -a $LF
+        exit 1;
+      endif
+      set jkzmax  = `cat $runsum | grep jkzmax  | awk '{print $2}'`;
+      set nspikes = `cat $runsum | grep nspikes | awk '{print $2}'`;
+      echo "$sessid $run $jkzmax $nspikes" >> $SessSumFile
+      if($nspikes > 0) then
+        echo "#  Slice   TP     JKZ" >> $SessSumFile
+        grep \# $runsum >> $SessSumFile
       endif
     endif
 
@@ -157,6 +181,15 @@ while( $#argv != 0 )
       set sumsuffix = $argv[1]; shift;
       breaksw
 
+    case "-sesssum":
+      if ( $#argv == 0) goto arg1err;
+      set SessSumFile = $argv[1]; shift;
+      breaksw
+
+    case "-sesssumonly":
+      set SessSumOnly = 1;
+      breaksw
+
     case "-fft":
       set fftflag = 1;
       breaksw
@@ -199,6 +232,11 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
+if($SessSumOnly == 1 && ! $#SessSumFile) then
+  echo "ERROR: need SessSum File with -sesssumonly"
+  exit 1;
+endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -220,6 +258,8 @@ usage_exit:
   echo "   -fft             : perform 2D FFT prior to spike detection"
   echo "   -mask maskthresh : mask OUT regions over thresh"
   echo "   -suffix suffix   : summary will be funcstem.suffix.sum"
+  echo "   -sesssum fname   : summarize all data in file fname"
+  echo "   -sesssumonly     : only create summary from already-proc data"
   echo ""
   echo "Session Arguments (Required)"
   echo "   -sf sessidfile  "
