Added ability to spec fmt on cmd

diff --git a/fsfast/bin/spmregister-sess b/fsfast/bin/spmregister-sess
--- a/fsfast/bin/spmregister-sess
+++ b/fsfast/bin/spmregister-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # spmregister-sess
 #
-set VERSION = '$Id: spmregister-sess,v 1.9 2005/01/21 22:52:37 greve Exp $';
+set VERSION = '$Id: spmregister-sess,v 1.10 2005/05/06 20:27:09 greve Exp $';
 set inputargs = ($argv);
 set DateString = "`date '+%y%m%d%H%M'`"
 
@@ -119,10 +119,15 @@ foreach sess ($SessList)
 
     set movfile = $funcdir/$funcstem"_000.bshort"
     if(! -e $movfile) then
-      set movfile = $funcdir/$funcstem"_000.bfloat"
+      if($fmt != COR) then
+        set movfile = $funcdir/$funcstem.$fmt
+      else
+        set movfile = $funcdir
+      endif
       if(! -e $movfile) then
-         echo "ERROR: cannot find f volume in $funcdir" |& tee -a $LF
-         exit 1;
+        echo "ERROR: cannot find f volume in $funcdir" |& tee -a $LF
+        echo "  $movfile"
+        exit 1;
       endif
     endif
 
@@ -149,9 +154,14 @@ foreach sess ($SessList)
       echo "  Run: $Run ----------------" |& tee -a $LF
       date  |& tee -a $LF
       set funcdir = $fsd/$Run
-      set movfile = $funcdir/$funcstem.$fmt
+      if($fmt != COR) then
+        set movfile = $funcdir/$funcstem.$fmt
+      else
+        set movfile = $funcdir
+      endif
       if(! -e $movfile) then
         echo "ERROR: cannot find f volume in $funcdir" |& tee -a $LF
+        echo "  $movfile"
         exit 1;
       endif
       set regfile = $funcdir/fs.register.dat
@@ -219,6 +229,11 @@ while( $#argv != 0 )
     case "-fsvol":
       if ( $#argv < 1) goto arg1err;
       set fsvol = $argv[1]; shift;
+      breaksw
+
+    case "-fmt":
+      if ( $#argv < 1) goto arg1err;
+      set fmt = $argv[1]; shift;
       breaksw
 
     case "-umask":
@@ -304,6 +319,7 @@ usage_exit:
   echo "   -frame frameno : 0-based frame no (default 0)"
   echo "   -fsvol volid   : FreeSurfer vol id (default is $fsvol)"
   echo "   -regfile file  : Save reg as file instead of register.dat"
+  echo "   -fmt format    : format of functional: <bhdr>, mgh, COR"
   echo "   -umask umask   : set unix file permission mask"
   echo "   -version       : print version and exit"
   echo ""
