Added ability to specify multiple contrasts.

diff --git a/fsfast/bin/stxgrinder-sess b/fsfast/bin/stxgrinder-sess
--- a/fsfast/bin/stxgrinder-sess
+++ b/fsfast/bin/stxgrinder-sess
@@ -1,12 +1,12 @@
 #!/bin/csh -f
 # stxgrinder-sess
 #
-set VERSION = '$Id: stxgrinder-sess,v 1.1 2003/03/04 21:22:09 greve Exp $';
+set VERSION = '$Id: stxgrinder-sess,v 1.2 2003/03/19 01:03:48 greve Exp $';
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 
 set inputargs = ($argv);
 
-set contrast    = ();
+set contrastlist = ();
 set pxform      = log10;
 set analysis    = ();
 set grpname     = ();
@@ -73,7 +73,7 @@ if(! $nolog) then
     echo "ERROR: could not create $logdir"
     exit 1;
   endif
-  set LF = $logdir/stxgrinder-sess-$fsd-$analysis-$contrast.log
+  set LF = $logdir/stxgrinder-sess-$fsd-$analysis.log
   if(-e $LF) mv $LF $LF.old
 else
   echo "No log file"
@@ -95,17 +95,8 @@ which stxgrinder >> $LF
 
 ## Prepare the script, if need be ##
 if($ScriptOnly) then
-  mkdir -p scripts
-  if(! -d scripts) then
-    echo "ERROR ($sess): cannot create `pwd`/scripts"
-    exit 1;
-  endif
-  set scriptfile = scripts/run-stxgrinder-$analysis-$contrast
-  rm -f $scriptfile
-  touch $scriptfile
-  echo "#\!/bin/csh -f" >> $scriptfile
-  echo "cd .." >> $scriptfile
-  chmod a+x $scriptfile
+  echo "ERROR: scriptonly not supported"
+  exit 1;
 endif
 
 if($#perrun != 0) then
@@ -119,6 +110,9 @@ foreach hs ($hemi)
   date |& tee -a $LF
 
   foreach sess ($SessList)
+
+
+   foreach contrast ($contrastlist)
 
     echo "-------------------------------------------------------"
     echo "-------------------------------------------------------"
@@ -206,6 +200,8 @@ foreach hs ($hemi)
       cp $cmtx $outdir
     endif
 
+   end # loop over contrast list
+
   end # loop over SessList #
 
 end # loop over hemispheres #
@@ -230,7 +226,7 @@ while( $#argv != 0 )
     case "-c":
     case "-contrast":
       if ( $#argv == 0) goto arg1err;
-      set contrast = $argv[1]; shift;
+      set contrastlist = ($contrastlist $argv[1]); shift;
       breaksw
 
     case "-space":
@@ -339,7 +335,7 @@ goto parse_args_return;
 ############--------------##################
 check_params:
 
-  if ($#contrast == 0) then
+  if ($#contrastlist == 0) then
      echo "ERROR: no contrast specified"
      exit 1
   endif
@@ -349,11 +345,13 @@ check_params:
      exit 1
   endif
 
-  set cmtx = `pwd`/$analysis/$contrast.mat
-  if(! -e $cmtx) then
-    echo "ERROR: cannot find $cmtx, see mkcontrast-sess"
-    exit 1;
-  endif
+  foreach contrast ($contrastlist)
+    set cmtx = `pwd`/$analysis/$contrast.mat
+    if(! -e $cmtx) then
+      echo "ERROR: cannot find $cmtx, see mkcontrast-sess"
+      exit 1;
+    endif
+  end
 
   if($#hemi != 0 && $space != sph) then
     echo "ERROR: -hemi can only be used with sph space"
@@ -390,6 +388,7 @@ usage_exit:
   echo "   -analysis  analysisname : name of session-level functional analysis";
   echo "   -anapend code : sets analysis to analysisname-code"
   echo "   -contrast  contrastname : contrast name"
+  echo "   <-contrast  contrastname : 2nd contrast name>"
   echo "   -pxform    xform : <log10>, ln, none";
   echo "   -space     spacename    : space in which to grind (native, tal, sph)"
   echo "   -hemi hemisphere : with sph space <lh rh>";
