Forces user to supply a space when a session is a group.

diff --git a/fsfast/bin/stxgrinder-sess b/fsfast/bin/stxgrinder-sess
--- a/fsfast/bin/stxgrinder-sess
+++ b/fsfast/bin/stxgrinder-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # stxgrinder-sess
 #
-set VERSION = '$Id: stxgrinder-sess,v 1.6 2003/08/04 17:49:25 greve Exp $';
+set VERSION = '$Id: stxgrinder-sess,v 1.7 2003/08/11 23:48:11 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -98,6 +98,11 @@ foreach sess ($SessList)
   endif
   set IsGroupList = ($IsGroupList $IsGroup);
   if($IsGroup) then
+    if($#space == 0) then
+      echo "ERROR: session `basename $sess` is a group."
+      echo "You must specify a space (tal or sph)."
+      exit 1;
+    endif
     set ffx = "-ffx";
   else
     set ffx = ();
