Fixed log file stuff.

diff --git a/fsfast/bin/surf-sess b/fsfast/bin/surf-sess
--- a/fsfast/bin/surf-sess
+++ b/fsfast/bin/surf-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # surf-sess
 #
-set VERSION = '$Id: surf-sess,v 1.4 2004/04/02 22:12:11 greve Exp $'
+set VERSION = '$Id: surf-sess,v 1.5 2004/05/04 18:16:24 greve Exp $'
 set FASTVER = `cat $FMRI_ANALYSIS_DIR/docs/version`;
 set inputargs = ($argv);
 
@@ -59,11 +59,21 @@ if($n != 0) then
   exit 0;
 endif
 
+goto parse_args;
+parse_args_return:
+
+set SessList = `getsesspath $inputargs`;
+if($status) then
+  echo "$SessList" 
+  exit 1;
+endif
+
+goto check_params;
+check_params_return:
+
 ## Look for nolog option ##
 set n = `echo $argv | grep nolog | wc -l` 
-if($n != 0) then
-  set nolog = 1;
-endif
+if($n != 0) set nolog = 1;
 
 ##### Create a log file ######
 if(! $nolog) then
@@ -73,7 +83,12 @@ if(! $nolog) then
     echo "ERROR: could not create $logdir"
     exit 1;
   endif
-  set LF = $logdir/surf-sess.log
+  if($#rtopymode == 0) then
+    set LF = $logdir/surf-sess.$analysis.$rtopymode.log
+  else
+    set LF = $logdir/surf-sess.$analysis.$contrast.log
+  endif
+  touch $LF
   if(-w $LF) then
     mv -f $LF $LF.old 
   else
@@ -98,33 +113,7 @@ uname -a      >> $LF
 date          >> $LF
 which tksurfer >> $LF
 
-goto parse_args;
-parse_args_return:
-
-set SessList = `getsesspath $inputargs`;
-if($status) then
-  echo "$SessList" |& tee -a $LF
-  exit 1;
-endif
-
-goto check_params;
-check_params_return:
-
-if($#usenew != 0) then
-  echo " "
-  echo " "
-  echo " "
-  echo "---------->>>>>>>>>>>....<<<<<<<<<<<<-------------------- "
-  echo "INFO: You are about to use the NEW version of tksurfer."
-  echo "INFO: If you want to use the OLD version, re-run surf-sess"
-  echo "INFO: with the -old flag."
-  echo "---------->>>>>>>>>>>....<<<<<<<<<<<<-------------------- "
-  echo " "
-  echo " "
-  echo " "
-  sleep 2;
-else
-  echo " "
+if($#usenew == 0) then
   echo " "
   echo " "
   echo "---------->>>>>>>>>>>....<<<<<<<<<<<<-------------------- "
@@ -132,7 +121,6 @@ else
   echo "INFO: If you want to use the NEW version, re-run surf-sess"
   echo "INFO: WITHOUT the -old flag."
   echo "---------->>>>>>>>>>>....<<<<<<<<<<<<-------------------- "
-  echo " "
   echo " "
   echo " "
   sleep 1;
@@ -642,12 +630,12 @@ goto parse_args_return;
 check_params:
 
   if ($#analysis == 0) then
-     echo "ERROR: no sxa name specified"|& tee -a $LF 
+     echo "ERROR: no sxa name specified"
      exit 1
   endif
   set infofile = $analysis/analysis.info
   if(! -e $infofile) then
-    echo "ERROR: cannot find $infofile"|tee -a $LF
+    echo "ERROR: cannot find $infofile"
     exit 1;
   endif
   set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
@@ -678,17 +666,17 @@ check_params:
   end
 
   if($#contrast == 0 && ! $rtopy ) then
-    echo "ERROR: no contrast specified"|& tee -a $LF 
+    echo "ERROR: no contrast specified"
     exit 1
   endif
 
   if($#contrast != 0 && $rtopy) then
-    echo "ERROR: do not specify contrast with retinotopic designs"|& tee -a $LF 
+    echo "ERROR: do not specify contrast with retinotopic designs"
     exit 1
   endif
 
   if($space != "tal" && $space != "sph" && $space != "native" ) then
-    echo "ERROR: no surf support for space $space "|& tee -a $LF 
+    echo "ERROR: no surf support for space $space "
     exit 1
   endif
 
@@ -703,20 +691,19 @@ check_params:
   ## Group Contingencies ##
   if($IsGroup) then
     if($space == "native") then
-      echo "ERROR: currently no support for painting group data in native space"\
-           |& tee -a $LF 
+      echo "ERROR: currently no support for painting group data in native space"
       exit 1;
     endif
     if($#subject == 0) then
-      echo "ERROR: $sess is a group average, need -subject"|& tee -a $LF 
+      echo "ERROR: $sess is a group average, need -subject"
       exit 1;
     endif
     if($#isxavgmethod == 0) then
-      echo "ERROR: must supply -isxavg method with group data" |& tee -a $LF 
+      echo "ERROR: must supply -isxavg method with group data" 
       exit 1;
     endif
     if($isxavgmethod != "fixed" && $isxavgmethod != "random") then
-      echo "ERROR: -isxavg must be either fixed or random" |& tee -a $LF 
+      echo "ERROR: -isxavg must be either fixed or random"
       exit 1;
     endif
   endif
