Can now pass par files externally

diff --git a/fsfast/bin/synth-sess b/fsfast/bin/synth-sess
--- a/fsfast/bin/synth-sess
+++ b/fsfast/bin/synth-sess
@@ -5,8 +5,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/05/16 23:19:15 $
-#    $Revision: 1.4 $
+#    $Date: 2007/06/07 16:51:51 $
+#    $Revision: 1.5 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -22,7 +22,7 @@
 #
 
 
-set VERSION = '$Id: synth-sess,v 1.4 2007/05/16 23:19:15 greve Exp $'
+set VERSION = '$Id: synth-sess,v 1.5 2007/06/07 16:51:51 greve Exp $'
 
 set inputargs = ($argv);
 
@@ -35,6 +35,7 @@ set templatesess = ();
 set runlistfile = ();
 set fsd = bold;
 set funcstem = f;
+set parfiles = ();
 
 set ntrs = ();
 
@@ -122,6 +123,10 @@ foreach runid ($RunList)
     cp $templatesess/$fsd/$runid/*.infodump $sess/$fsd/$runid/ >& /dev/null
   endif
 
+  foreach p ($parfiles)
+    cp $p $sess/$fsd/$runid/
+  end
+
 end
 
 echo "synth-sess done"
@@ -161,6 +166,15 @@ while( $#argv != 0 )
     case "-t":
       if ( $#argv == 0) goto arg1err;
       set template = $1; shift;
+      breaksw
+
+    case "-p":
+      if ( $#argv == 0) goto arg1err;
+      if(! -e $1) then
+        echo "ERROR: cannot find $1"
+        exit 1;
+      endif
+      set parfiles = ($parfiles $1); shift;
       breaksw
 
     case "-fsd":
@@ -258,6 +272,7 @@ usage_exit:
   echo "   -nruns nruns "
   echo ""
   echo "Options:";
+  echo "   -p parfile <-p parfile2> : copied to each run"
   echo "   -ntrs n  : override template"
   echo "   -fsd dir : functional subdirectory ($fsd)"
   echo ""
