Automatically detects most EPI parameters.

diff --git a/fsfast/bin/tdr-recon b/fsfast/bin/tdr-recon
--- a/fsfast/bin/tdr-recon
+++ b/fsfast/bin/tdr-recon
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # tdr-fidmat
 
-set VERSION = '$Id: tdr-recon,v 1.8 2004/02/10 22:33:56 greve Exp $';
+set VERSION = '$Id: tdr-recon,v 1.9 2004/04/13 22:02:32 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -9,30 +9,20 @@ set rawkdir    = ();
 set rcolmat    = ();
 set outstem    = ();
 set bhdrfile   = ();
-set nframes    = ();
 set nechoes    = ();
+set nthecho    = ();
 set usefid     = 1;
 set monly      = 0;
 set fidstem    = ();
 set cleanup    = 1;
 set convmdh    = 1;
 set fixpedrift = 1;
+set nslices    = ();
+set npcns      = 3;
 
 # This is for reconning a few frames instead of all
 # for debugging purposes
 set nframesrecon  = ();
-
-# EPI timing parameters in us
-set epitdwell = 3.2;      
-set epidelsamp = 30;      
-set tRampUp    = 140; 
-set tFlat      = 190; 
-set tRampDown  = 140; 
-
-set nslices    = 35; 
-set nrows      = 64;
-set nkcols     = 128;
-set npcns      = 3;
 
 set PrintHelp = 0;
 if($#argv == 0) goto usage_exit;
@@ -45,38 +35,6 @@ set n = `echo $argv | grep -e -version | wc -l`
 if($n != 0) then
   echo $VERSION
   exit 0;
-endif
-
-# for martin
-if(1) then
-  echo ""
-  echo "INFO: Using martins parameters"
-  echo ""
-  set nslices    = 23; 
-  set nrows      = 128; 
-  set nkcols      = 256;
-  set epiechospacing = 530;   # us
-  set epitdwell      = 1.6;      # us
-  set epidelsamp     = 60;      # us
-  set tRampUp    = 190; 
-  set tFlat      = 150; 
-  set tRampDown  = 190; 
-endif
-
-# for p41-7T
-if(0) then
-  echo ""
-  echo "INFO: Using p41-7T parameters"
-  echo ""
-  set nslices        = 12; 
-  set nrows          = 64; 
-  set nkcols         = 128;
-  set epitdwell      =  2.7;      # us
-  set epidelsamp     = 27;      # us
-  set epiechospacing = 400;   # us
-  set tRampUp        = 100; 
-  set tFlat          = 200; 
-  set tRampDown      = 100; 
 endif
 
 goto parse_args;
@@ -111,6 +69,83 @@ uname -a      >> $LF
 date          >> $LF
 
 set StartTime = `date`;
+
+# Get EPI parameters
+set epimeasasc = $rawkdir/meas.asc
+set tmp = `parse-measasc $epimeasasc "m_iNoOfFourierColumns"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set nkcols = $tmp;
+
+set tmp = `parse-measasc $epimeasasc "m_iNoOfFourierLines"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set nrows = $tmp;
+
+set tmp = `parse-measasc $epimeasasc "m_lEchoSpacing"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set epiechospacing = $tmp
+
+set tmp = `parse-measasc $epimeasasc "m_alRegridDelaySamplesTime"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set epidelsamp = $tmp
+
+set tmp = `parse-measasc $epimeasasc "m_alRegridRampupTime"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set tRampUp = $tmp;
+
+set tmp = `parse-measasc $epimeasasc "m_alRegridFlattopTime"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set tFlat = $tmp;
+
+set tmp = `parse-measasc $epimeasasc "m_alRegridRampdownTime"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set tRampDown = $tmp;
+
+set tmp = `parse-measasc $epimeasasc "sRXSPEC.alDwellTime[0]"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set epitdwell = `echo "$tmp/1000" |bc -l`; # convert to us
+
+set tmp = `parse-measasc $epimeasasc "lRepetitions"`
+if($status) then
+  echo "$tmp"| tee -a $LF
+  exit 1;
+endif
+set nframes = `echo "$tmp+1" | bc `;
+
+echo "epiechospacing $epiechospacing" | tee -a $LF
+echo "epidelsamp $epidelsamp " | tee -a $LF
+echo "epitdwell $epitdwell " | tee -a $LF
+echo "tRampUp   $tRampUp" | tee -a $LF
+echo "tFlat     $tFlat" | tee -a $LF
+echo "tRampDown $tRampDown" | tee -a $LF
+echo "nrows   $nrows" | tee -a $LF
+echo "nkcols  $nkcols" | tee -a $LF
+echo "nslices $nslices" | tee -a $LF
+echo "nframes $nframes" | tee -a $LF
+echo "nframesrecon $nframesrecon" | tee -a $LF
 
 set kepimghdir = $outdir/tmp
 if($convmdh) then
@@ -203,14 +238,14 @@ while( $#argv != 0 )
       set rcolmat = $argv[1]; shift;
       breaksw
 
+    case "--nechoes":
+      if ( $#argv == 0) goto arg1err;
+      set nechoes = $argv[1]; shift;
+      breaksw
+
     case "--echo":
       if ( $#argv == 0) goto arg1err;
       set nthecho = $argv[1]; shift;
-      breaksw
-
-    case "--nframes":
-      if ( $#argv == 0) goto arg1err;
-      set nframes = $argv[1]; shift;
       breaksw
 
     case "--nframesrecon":
@@ -218,9 +253,9 @@ while( $#argv != 0 )
       set nframesrecon = $argv[1]; shift;
       breaksw
 
-    case "--nechoes":
+    case "--nslices":
       if ( $#argv == 0) goto arg1err;
-      set nechoes = $argv[1]; shift;
+      set nslices = $argv[1]; shift;
       breaksw
 
     case "--o":
@@ -302,12 +337,12 @@ check_params:
     echo "ERROR: $rawkdir/meas.asc does not exist"
     exit 1;
   endif
-  if($#nframes == 0 ) then
-    echo "ERROR: must spec nframes"
-    exit 1;
-  endif
   if($#nechoes == 0 ) then
     echo "ERROR: must spec nechoes"
+    exit 1;
+  endif
+  if($#nthechoes == 0 ) then
+    echo "ERROR: must which echo to recon"
     exit 1;
   endif
   if(! -e $rcolmat ) then
@@ -353,16 +388,16 @@ usage_exit:
   echo ""
   echo "USAGE: tdr-recon"
   echo ""
-  echo "  --rawk    dir"
-  echo "  --rcol    rcolmat"
-  echo "  --echo    nthecho"
-  echo "  --notdr   don't compensate for decay"
+  echo "  --rawk    dir : directory with EPI meas.{out,asc}"
+  echo "  --rcol    rcolmat : as created by tdr-rcolmat"
+  echo "  --echo    nthecho : echo to recon (starting at 1)"
+  echo "  --nechoes nechoes : number of echos in raw data"
+  echo "  --nslices nslices : number of slices"
+  echo "  --notdr   don't compensate for distortion"
   echo "  --nofixpedrift  don't compensate for PE drift"
-  echo "  --nframes nframes : actual number of frames"
   echo "  --nframesrecon nframesrecon : only recon this number of frames"
-  echo "  --nechoes nechoes"
-  echo "  --o       outstem"
-  echo "  --fid     save first echo of fid as an anatomical"
+  echo "  --o       outstem : bfloat output"
+  echo "  --fid     fidstem : save first echo of fid as an anatomical"
   echo "  --bhdr    bhdrfile (use as a template)"
   echo "  --nocleanup : do not delete intermediate mgh files"
   echo "  --noconvmdh : do not convert mdh files (must exist already, forces nocleanup)"
@@ -382,3 +417,11 @@ BEGINHELP
 
 Converts raw k-space data into images using time-domain 
 reconstruction  method.
+
+EXAMPLE:
+
+tdr-recon --rawk func3_mtl_raw \
+    --echo 1 --nechoes 1 --nslices 23 \
+    --rcol tdr/R28.mat \
+    --o    tdr/func3_mtl_raw/f \
+    --fid  tdr/fid/f 
