Allows spec of all parameters on cmdline

diff --git a/fsfast/bin/tdr-recon b/fsfast/bin/tdr-recon
--- a/fsfast/bin/tdr-recon
+++ b/fsfast/bin/tdr-recon
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # tdr-fidmat
 
-set VERSION = '$Id: tdr-recon,v 1.5 2003/11/07 00:44:32 greve Exp $';
+set VERSION = '$Id: tdr-recon,v 1.6 2003/12/19 21:58:28 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -15,6 +15,39 @@ set usefid     = 1;
 set monly      = 0;
 set fidstem    = ();
 set cleanup    = 1;
+set convmdh    = 1;
+set fixpedrift = 1;
+
+# This is for reconning a few frames instead of all
+# for debugging purposes
+set nframesrecon  = ();
+
+# EPI timing parameters in us
+set epitdwell = 3.2;      
+set epidelsamp = 30;      
+set tRampUp    = 140; 
+set tFlat      = 190; 
+set tRampDown  = 140; 
+
+set nslices    = 35; 
+set nrows      = 64;
+set nkcols     = 128;
+set npcns      = 3;
+
+# for martin
+if(0) then
+  echo ""
+  echo "INFO: Using martins parameters"
+  echo ""
+  set nslices    = 23; 
+  set nrows      = 128; 
+  set nkcols      = 256;
+  set epidelsamp = 60;      # us
+  set epitdwell = 1.6;      # us
+  set tRampUp    = 190; 
+  set tFlat      = 150; 
+  set tRampDown  = 190; 
+endif
 
 set PrintHelp = 0;
 if($#argv == 0) goto usage_exit;
@@ -63,48 +96,61 @@ date          >> $LF
 set StartTime = `date`;
 
 set kepimghdir = $outdir/tmp
-mkdir -p $kepimghdir
-set cmd = (mri_convert_mdh --srcdir $rawkdir \
-      --outdir $kepimghdir --dim $nframes 35 $nechoes 64 128 3 \
+if($convmdh) then
+  mkdir -p $kepimghdir
+  set cmd = (mri_convert_mdh --srcdir $rawkdir \
+      --outdir $kepimghdir \
+      --dim $nframes $nslices $nechoes $nrows $nkcols $npcns \
       --fasterdim line)
-echo "---------------------------------" |& tee -a $LF
-date |& tee -a $LF
-echo $cmd |& tee -a $LF
-$cmd |& tee -a $LF
-if($status) exit 1;
+  echo "---------------------------------" |& tee -a $LF
+  date |& tee -a $LF
+  echo $cmd |& tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) exit 1;
+else
+  if(! -e $kepimghdir ) then
+    echo "ERROR: $kepiimghdir does not exist, run without --noconvmdh"
+    exit 1;
+  endif
+endif
 
-@ nthecho = 1;
-while($nthecho <= $nechoes)
-  echo "Echo $nthecho -----------"| & tee -a $LF
-  date | & tee -a $LF
-  set funcstem = $outstem$nthecho
-  echo "funcstem is $funcstem" | & tee -a $LF
+echo "Echo $nthecho -----------"| & tee -a $LF
+date | & tee -a $LF
+set funcstem = $outstem
+echo "funcstem is $funcstem" | & tee -a $LF
 
-  set MLF = $outdir/run_tdr_recon_$nthecho.m
-  rm -f $MLF
+if($#nframesrecon == 0) set nframesrecon = $nframes;
+
+set MLF = $outdir/run_tdr_recon_$nthecho.m
+rm -f $MLF
   #---------------------------------------------#
 tee -a > /dev/null $MLF  <<EOF
   kepidir = '$kepimghdir';
   epiecho =  $nthecho;
-  rcolmatfile = '$rcolmat[$nthecho]';
+  rcolmatfile = '$rcolmat';
   usefid = $usefid;
-  nframes = $nframes;
+  fixpedrift = $fixpedrift;
+  %nframes = $nframes;
+  nframes = $nframesrecon;
   %nframes = 1;
   funcstem = '$funcstem';
   fidstem  = '$fidstem';
   bhdrfile = '$bhdrfile';
+  tDwell     = $epitdwell; % usec
+  tDelSamp   = $epidelsamp;  % usec
+  tRampUp    = $tRampUp; % usec
+  tFlat      = $tFlat; % usec
+  tRampDown  = $tRampDown; % usec
+  tdelay     = 1.0;
   tdr_recon;
 EOF
   #---------------------------------------------#
 
-  if(! $monly) then
-    cat $MLF >> $LF
-    cat $MLF | matlab -display iconic -nojvm -nosplash | & tee -a $LF
-    echo "" | & tee -a $LF
-  endif
-
-  @ nthecho = $nthecho + 1;
-end # Loop over echoes
+if(! $monly) then
+  cat $MLF >> $LF
+  cat $MLF | matlab -display iconic -nojvm -nosplash | & tee -a $LF
+  echo "" | & tee -a $LF
+endif
 
 if($cleanup) then
   echo "Deleting mgh files" |& tee -a $LF
@@ -139,12 +185,22 @@ while( $#argv != 0 )
 
     case "--rcol":
       if ( $#argv == 0) goto arg1err;
-      set rcolmat = ($rcolmat $argv[1]); shift;
+      set rcolmat = $argv[1]; shift;
+      breaksw
+
+    case "--echo":
+      if ( $#argv == 0) goto arg1err;
+      set nthecho = $argv[1]; shift;
       breaksw
 
     case "--nframes":
       if ( $#argv == 0) goto arg1err;
       set nframes = $argv[1]; shift;
+      breaksw
+
+    case "--nframesrecon":
+      if ( $#argv == 0) goto arg1err;
+      set nframesrecon = $argv[1]; shift;
       breaksw
 
     case "--nechoes":
@@ -171,8 +227,16 @@ while( $#argv != 0 )
       set usefid = 0;
       breaksw
 
+    case "--nofixpedrift":
+      set fixpedrift = 0;
+      breaksw
+
     case "--nocleanup":
       set cleanup = 0;
+      breaksw
+
+    case "--noconvmdh":
+      set convmdh = 0;
       breaksw
 
     case "--debug":
@@ -219,16 +283,10 @@ check_params:
     echo "ERROR: must spec nechoes"
     exit 1;
   endif
-  if($#rcolmat != $nechoes) then
-    echo "ERROR: must specify $nechoes rcolmat files ($#rcolmat)"
+  if(! -e $rcolmat ) then
+    echo "ERROR: $rcolmat does not exist"
     exit 1;
   endif
-  foreach rcol ($rcolmat)
-    if(! -e $rcol ) then
-      echo "ERROR: $rcol does not exist"
-      exit 1;
-    endif
-  end
 
   if($#bhdrfile) then
     if(! -e $bhdrfile ) then
@@ -270,13 +328,16 @@ usage_exit:
   echo ""
   echo "  --rawk    dir"
   echo "  --rcol    rcolmat"
+  echo "  --echo    nthecho"
   echo "  --nofid   don't compensate for decay"
+  echo "  --nofixpedrift  don't compensate for PE drift"
   echo "  --nframes nframes"
   echo "  --nechoes nechoes"
   echo "  --o       outstem"
   echo "  --fid     save first echo of fid as an anatomical"
   echo "  --bhdr    bhdrfile (use as a template)"
   echo "  --nocleanup : do not delete intermediate mgh files"
+  echo "  --noconvmdh : do not convert mdh files (must exist alreay)"
   echo ""
 
   if(! $PrintHelp) exit 1;
