Added ability to run without converting the mdh (mdh must already be converted)

diff --git a/fsfast/bin/tdr-fidmat b/fsfast/bin/tdr-fidmat
--- a/fsfast/bin/tdr-fidmat
+++ b/fsfast/bin/tdr-fidmat
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # tdr-fidmat
 
-set VERSION = '$Id: tdr-fidmat,v 1.2 2003/09/26 18:21:47 greve Exp $';
+set VERSION = '$Id: tdr-fidmat,v 1.3 2003/10/20 22:19:50 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -10,6 +10,7 @@ set outdir     = ();
 set fwhm       = 0;
 set monly      = 0;
 set cleanup    = 1;
+set convmdh    = 1;
 
 set PrintHelp = 0;
 if($#argv == 0) goto usage_exit;
@@ -76,16 +77,23 @@ foreach fidsubdir (`cat $fidrlf`);
   set fiddir = `pwd`;
   popd > /dev/null
 
-  set fidmghdir = $outdir/tmp/fid1
-  mkdir -p $fidmghdir
-  set cmd = (mri_convert_mdh --srcdir $fiddir \
-      --outdir $fidmghdir --dim 1 35 99 64 128 0 \
-      --fasterdim echo)
-  echo "---------------------------------" |& tee -a $LF
-  date |& tee -a $LF
-  echo $cmd |& tee -a $LF
-  $cmd |& tee -a $LF
-  if($status) exit 1;
+  set fidmghdir = $outdir/tmp/fid$nthfid
+  if($convmdh) then
+    mkdir -p $fidmghdir
+    set cmd = (mri_convert_mdh --srcdir $fiddir \
+        --outdir $fidmghdir --dim 1 35 99 64 128 0 \
+        --fasterdim echo)
+    echo "---------------------------------" |& tee -a $LF
+    date |& tee -a $LF
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+  else
+    if(! -e $fidmghdir) then
+      echo "ERROR: $fidmghdir does not exist, run without --noconvmdh"
+      exit 1;
+    endif
+  endif
 
   set MLF = $fidmghdir/run_tdr_fidmat.m
   rm -f $MLF
@@ -94,13 +102,13 @@ foreach fidsubdir (`cat $fidrlf`);
 tee -a > /dev/null $MLF  <<EOF
   fiddirlist = '$fidmghdir';
   fidfwhm = [$fwhm];
-  %TEList      = [20 50 30];  % Echo time in ms
-  %TEPERevList = [ 0  1  0];  % Flag indicating reversal in PE direction
-  TEList      = [20 50];  % Echo time in ms
-  TEPERevList = [ 0  1];  % Flag indicating reversal in PE direction
+  TEList      = [20 50 30];  % Echo time in ms
+  TEPERevList = [ 0  1  0];  % Flag indicating reversal in PE direction
+  %TEList      = [20 50];  % Echo time in ms
+  %TEPERevList = [ 0  1];  % Flag indicating reversal in PE direction
   outlist =                 '$outdir/D20.$nthfid.mat';
   outlist = strvcat(outlist,'$outdir/D50.$nthfid.mat');
-  %outlist = strvcat(outlist,'$outdir/D30.$nthfid.mat');
+  outlist = strvcat(outlist,'$outdir/D30.$nthfid.mat');
   tdr_fidmat;
 EOF
 #---------------------------------------------#
@@ -155,6 +163,10 @@ while( $#argv != 0 )
 
     case "--nocleanup":
       set cleanup = 0;
+      breaksw
+
+    case "--noconvmdh":
+      set convmdh = 0;
       breaksw
 
     case "--verbose":
@@ -223,8 +235,8 @@ usage_exit:
   echo "  --outdir  dir"
   echo "  --fwhm    fwhm"
   echo "  --nocleanup : do not delete intermediate mgh files"
+  echo "  --noconvmdh : do not convert mdh files (already there)"
   echo ""
-
 
   if(! $PrintHelp) exit 1;
 
