Now saves bbrsum for session

diff --git a/fsfast/bin/tkregister-sess b/fsfast/bin/tkregister-sess
--- a/fsfast/bin/tkregister-sess
+++ b/fsfast/bin/tkregister-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/04/01 21:27:49 $
-#    $Revision: 1.29 $
+#    $Date: 2010/04/03 22:56:29 $
+#    $Revision: 1.30 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: tkregister-sess,v 1.29 2010/04/01 21:27:49 greve Exp $';
+set VERSION = '$Id: tkregister-sess,v 1.30 2010/04/03 22:56:29 greve Exp $';
 set inputargs = ($argv);
 set DateString = "`date '+%y%m%d%H%M'`"
 
@@ -90,20 +90,21 @@ if($#BBRSumFile) then
         exit 1;
       endif
       set mincost = `cat $reg.mincost | awk '{print $1}'`
-      printf "%-10s %6.4f\n" $sessid $mincost
+      printf "%-10s %6.4f\n" $sessid $mincost | tee -a $BBRSumFile
       continue
+    else
+      set RunList = `getrunlist $sess/$fsd`;
+      foreach Run ($RunList)
+        set reg = $sess/$fsd/$Run/$regfilename
+        if(! -e $reg.mincost) then
+          echo "ERROR: cannot find costfile $reg.mincost"
+          echo "Make sure to run register-sess using -bbr"
+          exit 1;
+        endif
+        set mincost = `cat $reg.mincost | awk '{print $1}'`
+        printf "%-10s %s %6.4f\n" $sessid $Run $mincost | tee -a $BBRSumFile
+      end 
     endif
-    set RunList = `getrunlist $sess/$fsd`;
-    foreach Run ($RunList)
-      set reg = $sess/$fsd/$Run/$regfilename
-      if(! -e $reg.mincost) then
-        echo "ERROR: cannot find costfile $reg.mincost"
-        echo "Make sure to run register-sess using -bbr"
-        exit 1;
-      endif
-      set mincost = `cat $reg.mincost | awk '{print $1}'`
-      printf "%-10s %s %6.4f\n" $sessid $Run $mincost | tee -a $BBRSumFile
-    end 
   end
   exit 0
 endif
