Added ability to specify a particular run to register to.

diff --git a/fsfast/bin/tkregister-sess b/fsfast/bin/tkregister-sess
--- a/fsfast/bin/tkregister-sess
+++ b/fsfast/bin/tkregister-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # tkregister-sess
 #
-set VERSION = '$Id: tkregister-sess,v 1.3 2003/07/18 23:54:43 greve Exp $';
+set VERSION = '$Id: tkregister-sess,v 1.4 2003/10/30 23:42:53 greve Exp $';
 set inputargs = ($argv);
 set DateString = "`date '+%y%m%d%H%M'`"
 
@@ -15,6 +15,7 @@ set nolog        = 0;
 set anatvol      = T1;
 set UseNew       = 1;
 set Surf         = white;
+set Run          = ();
 
 ## If there are no options, just print the usage ##
 if($#argv == 0) then
@@ -127,7 +128,15 @@ foreach sess ($SessList)
     echo "ERROR: $rsd does not exist"
     exit 1;
   endif
-  set funcdir = `getfirstrundir-sess $rsd`;
+  if($#Run == 0) then
+    set funcdir = `getfirstrundir-sess $rsd`;
+  else
+    set funcdir = $rsd/$Run
+    if(! -e $funcdir) then
+      echo "ERROR: $Run does not exist in $rsd"
+      exit 1;
+    endif
+  endif
 
   cd $funcdir
   ## Make sure there is not a register.dat in the data dir ##
@@ -291,6 +300,11 @@ while( $#argv != 0 )
     case "-rsd":
       if ( $#argv == 0) goto arg1err;
       set rsd = $argv[1]; shift;
+      breaksw
+
+    case "-run":
+      if ( $#argv == 0) goto arg1err;
+      set Run = $argv[1]; shift;
       breaksw
 
     case "-anatvol":
