Now requires register.dat or -regheader. Copied file from dev.

diff --git a/fsfast/bin/tkregister-sess b/fsfast/bin/tkregister-sess
--- a/fsfast/bin/tkregister-sess
+++ b/fsfast/bin/tkregister-sess
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/12/10 19:01:15 $
-#    $Revision: 1.23.2.1 $
+#    $Date: 2008/09/08 22:22:17 $
+#    $Revision: 1.23.2.2 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA). 
@@ -23,7 +23,7 @@
 #
 
 
-set VERSION = '$Id: tkregister-sess,v 1.23.2.1 2007/12/10 19:01:15 greve Exp $';
+set VERSION = '$Id: tkregister-sess,v 1.23.2.2 2008/09/08 22:22:17 greve Exp $';
 set inputargs = ($argv);
 set DateString = "`date '+%y%m%d%H%M'`"
 
@@ -199,7 +199,11 @@ foreach sess ($SessList)
   echo $regfile
 
   if($UseNew) then
-    if(! -e $regfile || $ForceRegHeader) then
+    if(! -e $regfile) then
+      if(! $ForceRegHeader) then
+        echo "ERROR: $regfile not found. Create it or use -regheader"
+        exit 1;
+      endif
       echo ""
       echo "INFO: using default registration"
       echo ""
@@ -458,6 +462,7 @@ while( $#argv != 0 )
       set Surf = $argv[1]; shift;
       breaksw
 
+    case "-reg":
     case "-regfile":
       if ( $#argv == 0) goto arg1err;
       set regfilename = $argv[1]; shift;
@@ -583,7 +588,7 @@ usage_exit:
   echo "   -movframe frame: 0-based frame number"
   echo "   -plane orient  : starup with orient. <cor>, sag, or ax"
   echo "   -slice sliceno : starup with slice. Default is 128."
-  echo "   -regfile file  : use file instead of register.dat"
+  echo "   -reg file      : use file instead of register.dat"
   echo "   -regheader     : force init based on header"
   echo "   -umask umask   : set unix file permission mask"
   echo "   -version       : print version and exit"
