Added ability to specify startup slice, plane, inorm, and volume.

diff --git a/fsfast/bin/tkregister-sess b/fsfast/bin/tkregister-sess
--- a/fsfast/bin/tkregister-sess
+++ b/fsfast/bin/tkregister-sess
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # tkregister-sess
 #
-set VERSION = '$Id: tkregister-sess,v 1.4 2003/10/30 23:42:53 greve Exp $';
+set VERSION = '$Id: tkregister-sess,v 1.5 2003/11/05 21:32:31 greve Exp $';
 set inputargs = ($argv);
 set DateString = "`date '+%y%m%d%H%M'`"
 
@@ -16,6 +16,10 @@ set anatvol      = T1;
 set UseNew       = 1;
 set Surf         = white;
 set Run          = ();
+set Plane        = "cor";
+set Slice        = ();
+set Inorm        = 0;
+set VolView      = targ;
 
 ## If there are no options, just print the usage ##
 if($#argv == 0) then
@@ -85,6 +89,7 @@ foreach sess ($SessList)
   echo "Session: $sess ----------------" |& tee -a $LF
   date  |& tee -a $LF
   pushd $sess > /dev/null
+  set sessid = `basename $sess`;
 
   ## Get the anatomical directory ##
   if($samesessanat) then
@@ -98,7 +103,8 @@ foreach sess ($SessList)
     endif
     set subject = `cat subjectname`;
     if(! -e $SUBJECTS_DIR/$subject) then
-      echo "ERROR: $subject is not in database"
+      echo "ERROR: $subject is not in SUBJECTS_DIR"
+      echo "  SUBJECTS_DIR is $SUBJECTS_DIR"
       exit 1;
     endif
     set anatdir = $SUBJECTS_DIR/$subject/mri/$anatvol;
@@ -161,8 +167,14 @@ foreach sess ($SessList)
       exit 1;
     endif
     set movext = `getbext $movstem`;
-    set cmd = (tkregister2 --targ $anatdir --mov $movstem $movext)
-    set cmd = ($cmd $mkregopt --reg $regfile)
+    #set TKR2 = ~/sg1/build/tkregister2/tkregister2
+    set TKR2 = tkregister2
+    set cmd = ($TKR2 --targ $anatdir --mov $movstem $movext)
+    set cmd = ($cmd $mkregopt --reg $regfile --plane $Plane)
+    set cmd = ($cmd --title $subject--$sessid)
+    set cmd = ($cmd --volview $VolView)
+    if($#Slice) set cmd = ($cmd --slice $Slice)
+    if($Inorm)  set cmd = ($cmd --inorm)
     if($#Surf != 0) then
       set lhsurfpath = $SUBJECTS_DIR/$subject/surf/lh.$Surf;
       set rhsurfpath = $SUBJECTS_DIR/$subject/surf/rh.$Surf;
@@ -307,6 +319,29 @@ while( $#argv != 0 )
       set Run = $argv[1]; shift;
       breaksw
 
+    case "-plane":
+      if ( $#argv == 0) goto arg1err;
+      set Plane = $argv[1]; shift;
+      breaksw
+
+    case "-slice":
+      if ( $#argv == 0) goto arg1err;
+      set Slice = $argv[1]; shift;
+      breaksw
+
+    case "-volview":
+      if ( $#argv == 0) goto arg1err;
+      set VolView = $argv[1]; shift;
+      if($VolView != mov && $VolView != targ) then
+        echo "ERROR: volview = $VolView, must be mov or targ"
+        exit 1;
+      endif
+      breaksw
+
+    case "-inorm":
+      set Inorm = 1;
+      breaksw
+
     case "-anatvol":
       if ( $#argv == 0) goto arg1err;
       set anatvol = $argv[1]; shift;
@@ -422,6 +457,9 @@ usage_exit:
   echo "   -nocopy        : do not copy registration to fsd"
   echo "   -sessanat      : register to same-session anatomical"
   echo "   -anatvol dir   : specify subdirectory of subjid/mri"
+  echo "   -volview volid : starup with either <targ> or mov"
+  echo "   -plane orient  : starup with orient. <cor>, sag, or ax"
+  echo "   -slice sliceno : starup with slice. Default is 128."
   echo "   -umask umask   : set unix file permission mask"
   echo "   -version       : print version and exit"
   echo "   -useold        : use tkregister instead of tkregister2"
