Added -lta flag so that .lta matrices can also be writtten out.

diff --git a/scripts/bbregister b/scripts/bbregister
--- a/scripts/bbregister
+++ b/scripts/bbregister
@@ -5,9 +5,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: greve $
-#    $Date: 2011/10/14 17:02:53 $
-#    $Revision: 1.52 $
+#    $Author: lzollei $
+#    $Date: 2011/11/10 16:24:17 $
+#    $Revision: 1.53 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -22,7 +22,7 @@
 #
 
 #
-set VERSION = '$Id: bbregister,v 1.52 2011/10/14 17:02:53 greve Exp $';
+set VERSION = '$Id: bbregister,v 1.53 2011/11/10 16:24:17 lzollei Exp $';
 set inputargs = ($argv);
 
 set subject = ();
@@ -32,6 +32,7 @@ set frame = ();
 set midframe = 0;
 set outreg = ();
 set outfsl = ();
+set outlta = ();
 set InitFSL = 0;
 set InitSPM = 0;
 set InitRR = 0;
@@ -290,6 +291,14 @@ if($#outfsl) then
   if($status) exit 1;
 endif
 
+if($#outlta) then
+  set cmd = (tkregister2_cmdl --mov $movvol --reg $outreg \
+    --noedit --ltaout $outlta);
+  echo $cmd | tee -a $LF
+  $cmd | tee -a $LF
+  if($status) exit 1;
+endif
+
 if($#featdir) then
   cp $outreg $featdir/reg/freesurfer/register.dat
   set reg152 = $featdir/reg/freesurfer/anat2std.register.dat
@@ -418,6 +427,11 @@ while( $#argv != 0 )
     case "--fslmat":
       if ( $#argv < 1) goto arg1err;
       set outfsl = $argv[1]; shift;
+      breaksw
+
+    case "--lta":
+      if ( $#argv < 1) goto arg1err;
+      set outlta = $argv[1]; shift;
       breaksw
 
     case "--init-rr":
@@ -769,8 +783,12 @@ check_params:
   endif
 
   if($#outreg == 0) then
-    echo "ERROR: must spec an output reg file"
-    exit 1;
+    if ($#outlta == 0) then
+      echo "ERROR: must spec an output reg file (using either --reg or --lta)"
+      exit 1;
+    else
+      set outreg = ${outlta:r}.dat
+    endif
   endif
 
   if($#frame && $midframe) then
