Now requires a contrast specification

diff --git a/scripts/bbregister b/scripts/bbregister
--- a/scripts/bbregister
+++ b/scripts/bbregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/11/18 23:08:23 $
-#    $Revision: 1.14 $
+#    $Date: 2009/01/12 19:50:57 $
+#    $Revision: 1.15 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -23,7 +23,7 @@
 #
 
 #
-set VERSION = '$Id: bbregister,v 1.14 2008/11/18 23:08:23 greve Exp $';
+set VERSION = '$Id: bbregister,v 1.15 2009/01/12 19:50:57 greve Exp $';
 set inputargs = ($argv);
 
 set subject = ();
@@ -39,19 +39,19 @@ set InitReg = ();
 set VSM = ();
 set Brute1Max = 4;
 set Brute1Delta = 4;
+set SubSamp1 = 100;
 
 set LHOnly = 0;
 set RHOnly = 0;
 set Slope1 = 0.5;
 set Slope2 = 0.5;
 set Offset2 = 0;
-set Contrast = +1;
+set Contrast = ()
 set Tol = 1e-8;
 
 set GMProjFrac = 0.5;
 set WMProjAbs = 2;
 set nSubSamp = 1;
-set RandInitMax = ();
 set Interp = trilinear
 set UseEPIMask = 0;
 
@@ -61,6 +61,8 @@ set OutVol = ();
 set fsvol  = brainmask;
 set surfcost = ();
 set surfcon  = ();
+
+set RandInitMax = ();
 
 set debug = 0;
 set tmpdir = ();
@@ -159,13 +161,13 @@ if($#InitReg == 0) then
     if($status) exit 1;
     set InitReg = $InitReg0;
   endif
-
 endif
 
 # Pass 1
 set Pass1Reg = $tmpdir/bbr.pass1.dat
 set cmd = (mri_segreg --mov $template --init-reg $InitReg --out-reg $Pass1Reg\
-  --subsamp-brute 100 --subsamp 100 --tol 1e-4 --tol1d 1e-4 --brute -$Brute1Max $Brute1Max $Brute1Delta );
+  --subsamp-brute $SubSamp1 --subsamp $SubSamp1 --tol 1e-4 --tol1d 1e-4 \
+  --brute -$Brute1Max $Brute1Max $Brute1Delta );
 if("$Contrast" == "-1") set cmd = ($cmd --wm-gt-gm $Slope1);
 if("$Contrast" == "+1") set cmd = ($cmd --gm-gt-wm $Slope1);
 if($LHOnly) set cmd = ($cmd --lh-only);
@@ -173,6 +175,7 @@ if($RHOnly) set cmd = ($cmd --rh-only);
 if($UseEPIMask) set cmd = ($cmd --mask);
 if($#VSM) set cmd = ($cmd --mask --vsm $VSM);
 if($#RandInitMax) then
+  # Only for testing
   set cmd = ($cmd --trans-rand $RandInitMax --rot-rand $RandInitMax);
 endif
 echo $cmd | tee -a $LF
@@ -237,17 +240,11 @@ echo " " |& tee -a $LF
 echo "bbregister Done" |& tee -a $LF
 echo " "
 
-if(-e $SUBJECTS_DIR/$subject/surf/lh.orig) then
-  set tmp = "--surf orig"
-else
-  set tmp = ""
-endif
-
 echo "To check results, run:"
 if($#templateout) then
-  echo "tkregister2 --mov $templateout --reg $outreg $tmp"
+  echo "tkregister2 --mov $templateout --reg $outreg --surf"
 else
-  echo "tkregister2 --mov $movvol --reg $outreg $tmp"
+  echo "tkregister2 --mov $movvol --reg $outreg --surf"
 endif
 echo " "
 
@@ -315,6 +312,8 @@ while( $#argv != 0 )
       set InitReg = ();
       breaksw
  
+    case "--regheader":
+    case "--reg-header":
     case "--init-header":
       set InitFSL = 0;
       set InitSPM = 0;
@@ -414,6 +413,11 @@ while( $#argv != 0 )
     case "--brute1delta":
       if ( $#argv < 1) goto arg1err;
       set Brute1Delta = $argv[1]; shift;
+      breaksw
+
+    case "--subsamp1":
+      if ( $#argv < 1) goto arg1err;
+      set SubSamp1 = $argv[1]; shift;
       breaksw
 
     case "--surf-cost":
@@ -519,6 +523,13 @@ check_params:
     exit 1;
   endif
 
+  if($#Contrast == 0) then
+    echo "ERROR: you must specify a contrast."
+    echo " use --bold, --dti, --t2, or --t1,"
+    echo " which ever is most appropriate"
+    exit 1;
+  endif
+
   if($#outreg == 0) then
     echo "ERROR: must spec an output reg file"
     exit 1;
@@ -566,11 +577,14 @@ usage_exit:
   echo "   --init-header : initialize the registration based on header goemetry"
   echo "   --init-reg initregfile : explicitly pass registration"
   echo ""
-  echo "Optional Arguments"
+  echo "Contrast Arguments (one required)"
   echo ""
   echo "   --t1 : assume t1 contrast, ie, WM brighter than GM"
   echo "   --t2 : assume t2 contrast, ie, GM brighter than WM (default)"
   echo "   --bold : same as --t2"
+  echo "   --dti  : same as --t2"
+  echo ""
+  echo "Optional Arguments"
   echo ""
   echo "   --mid-frame : reg to middle frame (not with --frame)"
   echo "   --frame frameno : reg to frameno (default 0=1st)"
@@ -593,6 +607,7 @@ usage_exit:
   echo "   --epi-mask : mask out brain edge and B0 regions (1st and 2nd stages)"
   echo "   --brute1max max     : pass 1 search -max to +max (default $Brute1Max)"
   echo "   --brute1delta delta : pass 1 search -max to +max step delta (default $Brute1Delta)" 
+  echo "   --subsamp1 nsubsamp  : pass 1 vertex subsampling (default $nSubSamp)"
   echo ""
   echo "   --surf-cost basename : saves final cost as basename.?h.mgh"
   echo "   --surf-con  basename : saves final contrast as basename.?h.mgh"
