Copied file from dev.

diff --git a/scripts/bbregister b/scripts/bbregister
--- a/scripts/bbregister
+++ b/scripts/bbregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/12/31 17:14:35 $
-#    $Revision: 1.14.2.2 $
+#    $Date: 2009/01/12 19:51:13 $
+#    $Revision: 1.14.2.3 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -23,7 +23,7 @@
 #
 
 #
-set VERSION = '$Id: bbregister,v 1.14.2.2 2008/12/31 17:14:35 greve Exp $';
+set VERSION = '$Id: bbregister,v 1.14.2.3 2009/01/12 19:51:13 greve Exp $';
 set inputargs = ($argv);
 
 set subject = ();
@@ -46,7 +46,7 @@ set RHOnly = 0;
 set Slope1 = 0.5;
 set Slope2 = 0.5;
 set Offset2 = 0;
-set Contrast = +1;
+set Contrast = ()
 set Tol = 1e-8;
 
 set GMProjFrac = 0.5;
@@ -523,6 +523,13 @@ check_params:
     exit 1;
   endif
 
+  if($#Contrast == 0) then
+    echo "ERROR: you must specify a contrast."
+    echo " use --bold, --dti, --t2, or --t1,"
+    echo " which ever is most appropriate"
+    exit 1;
+  endif
+
   if($#outreg == 0) then
     echo "ERROR: must spec an output reg file"
     exit 1;
@@ -570,11 +577,14 @@ usage_exit:
   echo "   --init-header : initialize the registration based on header goemetry"
   echo "   --init-reg initregfile : explicitly pass registration"
   echo ""
-  echo "Optional Arguments"
+  echo "Contrast Arguments (one required)"
   echo ""
   echo "   --t1 : assume t1 contrast, ie, WM brighter than GM"
   echo "   --t2 : assume t2 contrast, ie, GM brighter than WM (default)"
   echo "   --bold : same as --t2"
+  echo "   --dti  : same as --t2"
+  echo ""
+  echo "Optional Arguments"
   echo ""
   echo "   --mid-frame : reg to middle frame (not with --frame)"
   echo "   --frame frameno : reg to frameno (default 0=1st)"
