Added ability to save init surf cost only

diff --git a/scripts/bbregister b/scripts/bbregister
--- a/scripts/bbregister
+++ b/scripts/bbregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2014/02/21 21:13:49 $
-#    $Revision: 1.63 $
+#    $Date: 2014/02/21 21:41:11 $
+#    $Revision: 1.64 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -22,7 +22,7 @@
 #
 
 #
-set VERSION = '$Id: bbregister,v 1.63 2014/02/21 21:13:49 greve Exp $';
+set VERSION = '$Id: bbregister,v 1.64 2014/02/21 21:41:11 greve Exp $';
 set inputargs = ($argv);
 
 set subject = ();
@@ -66,6 +66,7 @@ set FSLDOF = 6;
 set FSLSwapTrans = 0;
 set FSLBETMov = 0;
 set DoPass1 = 1;
+set InitSurfCostOnly = 0;
 
 set WMProjAbs = 2;
 set GMProjFrac = 0.5;
@@ -115,9 +116,12 @@ check_params_return:
 set StartTime = `date`;
 set tSecStart = `date '+%s'`;
 
-set outdir = `dirname $outreg`;
+if($#outreg)   set outdir = `dirname $outreg`;
+if(! $#outreg) set outdir = `dirname $initsurfcost`;
+
 if($#tmpdir == 0) set tmpdir = $outdir/tmp.bbregister.$$
 mkdir -p $tmpdir
+echo tmp $tmpdir
 
 if(! $nolog) then
   set LF = $outreg.log
@@ -285,6 +289,7 @@ if($DoPass1) then
   if($LHOnly) set cmd = ($cmd --lh-only);
   if($RHOnly) set cmd = ($cmd --rh-only);
   if($#initsurfcost) set cmd = ($cmd --init-surf-cost $initsurfcost);
+  if($InitSurfCostOnly) set cmd = ($cmd --init-surf-cost-only);
   if($UseEPIMask) set cmd = ($cmd --mask);
   if(! $UseCortexLabel) set cmd = ($cmd --no-cortex-label);
   if($#VSM) set cmd = ($cmd --mask --vsm $VSM);
@@ -295,6 +300,12 @@ if($DoPass1) then
   echo $cmd | tee -a $LF
   $cmd |& tee -a $LF
   if($status) exit 1;
+  if($InitSurfCostOnly) then
+    if($cleanup) rm -r $tmpdir
+    echo "InitSurfCostOnly requested, so exiting now" |& tee -a $LF
+    echo "bbregister Done" |& tee -a $LF
+    exit 0;
+  endif
 else
   cp $InitReg $Pass1Reg
 endif
@@ -324,6 +335,7 @@ if($#MaskLabel)  set cmd = ($cmd --label $MaskLabel);
 if("$Contrast" == "-1") set cmd = ($cmd --wm-gt-gm $Slope2);
 if("$Contrast" == "+1") set cmd = ($cmd --gm-gt-wm $Slope2);
 if($#initsurfcost && ! $DoPass1)  set cmd = ($cmd --init-surf-cost $initsurfcost);
+if($InitSurfCostOnly) set cmd = ($cmd --init-surf-cost-only);
 if($#surfcost)  set cmd = ($cmd --surf-cost $surfcost);
 if($#surfcon)   set cmd = ($cmd --surf-con  $surfcon);
 if($DoAbs) set cmd = ($cmd --penalty-abs)
@@ -333,6 +345,12 @@ if($#RMSFile0) set cmd = ($cmd --rms $RMSFile0);
 echo $cmd | tee -a $LF
 $cmd |& tee -a $LF
 if($status) exit 1;
+if($InitSurfCostOnly) then
+  if($cleanup) rm -r $tmpdir
+  echo "InitSurfCostOnly requested, so exiting now" |& tee -a $LF
+  echo "bbregister Done" |& tee -a $LF
+  exit 0;
+endif
 
 echo "MinCost: `cat $MinCostFile`" | tee -a $LF
 
@@ -710,6 +728,10 @@ while( $#argv != 0 )
       set initsurfcost = $argv[1]; shift;
       breaksw
 
+    case "--init-surf-cost-only":
+      set InitSurfCostOnly = 1;
+      breaksw
+
     case "--surf-cost":
       if ( $#argv < 1) goto arg1err;
       set surfcost = $argv[1]; shift;
@@ -944,7 +966,12 @@ check_params:
     exit 1;
   endif
 
-  if($#outreg == 0) then
+  if($InitSurfCostOnly && $#initsurfcost == 0) then
+    echo "ERROR: must supply --init-surf-cost with --init-surf-cost-only"
+    exit 1;
+  endif
+
+  if($#outreg == 0 && ! $InitSurfCostOnly) then
     if ($#outlta == 0) then
       echo "ERROR: must spec an output reg file (using either --reg or --lta)"
       exit 1;
