Fixed bug where user had to be in dicom dir

diff --git a/scripts/dcmdir-info-mgh b/scripts/dcmdir-info-mgh
--- a/scripts/dcmdir-info-mgh
+++ b/scripts/dcmdir-info-mgh
@@ -7,9 +7,9 @@
 #
 # Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
 # CVS Revision Info:
-#    $Author: nicks $
-#    $Date: 2007/01/06 00:01:13 $
-#    $Revision: 1.11 $
+#    $Author: greve $
+#    $Date: 2007/05/11 19:33:27 $
+#    $Revision: 1.12 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -25,7 +25,7 @@
 #
 
 
-set VERSION = '$Id: dcmdir-info-mgh,v 1.11 2007/01/06 00:01:13 nicks Exp $';
+set VERSION = '$Id: dcmdir-info-mgh,v 1.12 2007/05/11 19:33:27 greve Exp $';
 
 if($#argv != 1 && $#argv != 2) then
   echo "dcmdir-info-mgh dicomdir"
@@ -97,7 +97,13 @@ pushd $dcmdir > /dev/null
 # awk  -- print the 2nd to last field, should be series number
 # sort -- sort series numbers numerically
 # uniq -- keep only unique series numbers
-set serlist = (`find $dcmdir -name '*.dcm' | sed 's/-/ /g' | awk '{a=NF-1;print $a}' | sort -n | uniq`);
+#set serlist = (`find $dcmdir -name '*.dcm' | sed 's/-/ /g' | awk '{a=NF-1;print $a}' | sort -n | uniq`);
+set serlist = (`find . -name '*.dcm' | sed 's/-/ /g' | awk '{a=NF-1;print $a}' | sort -n | uniq`);
+if($#serlist == 0) then
+  pwd
+  echo "ERROR: finding data"
+  exit 1;
+endif
 
 set series = $serlist[1];
 set flist = `ls *-$series-*.dcm`
