Can now pass a reg and mask

diff --git a/scripts/dt_recon b/scripts/dt_recon
--- a/scripts/dt_recon
+++ b/scripts/dt_recon
@@ -2,7 +2,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: dt_recon,v 1.13 2009/05/20 17:56:15 greve Exp $';
+set VERSION = '$Id: dt_recon,v 1.14 2009/12/16 20:03:32 greve Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
@@ -20,6 +20,8 @@ set EResPCA = 0;
 set PruneThr = ();
 set infodump = ();
 set OutDir = ();
+set reg = ();
+set mask = ();
 
 set PrintHelp = 0;
 set LF = ();
@@ -140,6 +142,7 @@ endif
 if($SaveERes) set cmd = ($cmd --eres-save)
 if($EResPCA)  set cmd = ($cmd --pca)
 if($#PruneThr)  set cmd = ($cmd --prune_thr $PruneThr)
+if($#mask) set cmd = ($cmd --mask $mask);
 
 echo "cd `pwd`" |  tee -a $LF
 echo $cmd       |  tee -a $LF 
@@ -149,21 +152,26 @@ echo "" | tee -a $LF
 echo "" | tee -a $LF
 
 # Register to subject
-set reg = $OutDir/register.dat
-if($DoRegistration) then
-  echo "#@#-------------------------------" |  tee -a $LF
-  echo "Registration" |  tee -a $LF
-  date |  tee -a $LF
-  set cmd = (bbregister --s $subject --mov $OutDir/lowb.nii \
-     --init-fsl --reg $reg --bold --tol1d 1e-3)
-  if($subject == fsaverage) set cmd = ($cmd --12)
-  echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
-  echo "cd `pwd`" |  tee -a $LF
-  echo $cmd       |  tee -a $LF 
-  $cmd            |& tee -a $LF
-  if($status) exit 1;
-  echo "" | tee -a $LF
-  echo "" | tee -a $LF
+if($#reg == 0) then
+  set reg = $OutDir/register.dat
+  if($DoRegistration) then
+    echo "#@#-------------------------------" |  tee -a $LF
+    echo "Registration" |  tee -a $LF
+    date |  tee -a $LF
+    set cmd = (bbregister --s $subject --mov $OutDir/lowb.nii \
+       --init-fsl --reg $reg --bold --tol1d 1e-3)
+    if($subject == fsaverage) set cmd = ($cmd --12)
+    echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
+    echo "cd `pwd`" |  tee -a $LF
+    echo $cmd       |  tee -a $LF 
+    $cmd            |& tee -a $LF
+    if($status) exit 1;
+    echo "" | tee -a $LF
+    echo "" | tee -a $LF
+  endif
+else
+  cp $reg $OutDir/register.dat
+  set reg = $OutDir/register.dat
 endif
 
 if($DoTalairach) then
@@ -268,6 +276,21 @@ while( $#argv != 0 )
     case "--o":
       if ( $#argv < 1) goto arg1err;
       set OutDir = $argv[1]; shift;
+      breaksw
+
+    case "--reg":
+      if ( $#argv < 1) goto arg1err;
+      set reg = $argv[1]; shift;
+      set subject = `head -n 1 $reg`
+      breaksw
+
+    case "--mask":
+      if ( $#argv < 1) goto arg1err;
+      set mask = $argv[1]; shift;
+      if(! -e $mask) then
+        echo "ERROR: cannot find $mask"
+        exit 1;
+      endif 
       breaksw
 
     case "--ecref":
@@ -426,6 +449,7 @@ usage_exit:
   echo "  --ecref TP       : Use TP as 0-based reference time points for EC"
   echo "  --no-ec          : turn off eddy/motion correction"
   echo "  --no-reg         : do not register to subject or resample to talairach"
+  echo "  --reg  reg.dat   : supply a register.dat file instead of registering"
   echo "  --no-tal         : do not resample FA to talairch space"
   echo "  --sd subjectsdir : specify subjects dir (default env SUBJECTS_DIR)"
   echo "  --eres-save      : save resdidual error (dwires and eres)"
