Copied from dev. Fixed error_exit. Added --ecref. Now does not need a subject.

diff --git a/scripts/dt_recon b/scripts/dt_recon
--- a/scripts/dt_recon
+++ b/scripts/dt_recon
@@ -2,16 +2,19 @@
 #
 umask 002;
 
-set VERSION = '$Id: dt_recon,v 1.6.2.2 2007/08/23 19:17:46 greve Exp $';
+set VERSION = '$Id: dt_recon,v 1.6.2.3 2008/07/29 20:16:04 greve Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
 
 set InputVol = ();
 set DoEddyCorrect = 1;
+set ECRefTP = 0; # 0 for 1st frame
 set subject = ();
 set bvals = ();
 set bvecs = ();
+set DoRegistration = 1;
+set DoTalairach = 1;
 
 set PrintHelp = 0;
 set LF = ();
@@ -49,12 +52,15 @@ if(-e $LF) mv $LF $LF.bak
 echo "dt_recon logfile" | tee -a $LF
 date                    | tee -a $LF
 echo "VERSION $VERSION"  | tee -a $LF
-echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
+if($DoRegistration) then
+  echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
+endif
 echo "cd `pwd`"          | tee -a $LF
 echo $0 $inputargs       | tee -a $LF
 hostname                 | tee -a $LF
 whoami                   | tee -a $LF
 which eddy_correct       | tee -a $LF
+echo "ECRefTP $ECRefTP"  | tee -a $LF
 
 # Force FSL to use nifti
 setenv FSLOUTPUTTYPE NIFTI
@@ -93,7 +99,7 @@ if($DoEddyCorrect) then
   set ectmp = $OutDir/ectmp
   mkdir -p $ectmp
   pushd $ectmp > /dev/null
-  set cmd = (eddy_correct $f $fec 0) # 0 for 1st frame
+  set cmd = (eddy_correct $f $fec $ECRefTP) 
   #set cmd = (cp $f $fec)
   echo "cd `pwd`" |  tee -a $LF
   echo $cmd       |  tee -a $LF 
@@ -133,45 +139,53 @@ echo "" | tee -a $LF
 echo "" | tee -a $LF
 
 # Register to subject
-echo "#@#-------------------------------" |  tee -a $LF
-echo "Registration" |  tee -a $LF
-date |  tee -a $LF
 set reg = $OutDir/register.dat
-set cmd = (fslregister --s $subject --mov $OutDir/lowb.nii)
-set cmd = ($cmd --reg $reg)
-echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
-echo "cd `pwd`" |  tee -a $LF
-echo $cmd       |  tee -a $LF 
-$cmd            |& tee -a $LF
-if($status) exit 1;
-echo "" | tee -a $LF
-echo "" | tee -a $LF
+if($DoRegistration) then
+  echo "#@#-------------------------------" |  tee -a $LF
+  echo "Registration" |  tee -a $LF
+  date |  tee -a $LF
+  set cmd = (fslregister --s $subject --mov $OutDir/lowb.nii)
+  set cmd = ($cmd --reg $reg)
+  echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
+  echo "cd `pwd`" |  tee -a $LF
+  echo $cmd       |  tee -a $LF 
+  $cmd            |& tee -a $LF
+  if($status) exit 1;
+  echo "" | tee -a $LF
+  echo "" | tee -a $LF
+endif
 
-# Map Mask to talairach space
-echo "#@#-------------------------------" |  tee -a $LF
-echo "Reslicing to Tal" |  tee -a $LF
-date |  tee -a $LF
-set mask = $OutDir/mask.nii
-set masktal = $OutDir/mask-tal.nii
-set cmd = (mri_vol2vol --reg $reg --tal --interp nearest\
-            --mov $mask --o $masktal)
-echo "cd `pwd`" |  tee -a $LF
-echo $cmd       |  tee -a $LF 
-$cmd            |& tee -a $LF
-if($status) exit 1;
-echo "" | tee -a $LF
-echo "" | tee -a $LF
+if($DoTalairach) then
+  # Map Mask to talairach space
+  echo "#@#-------------------------------" |  tee -a $LF
+  echo "Reslicing to Tal" |  tee -a $LF
+  if(! -e $reg) then
+    echo "ERROR: cannot find $reg"
+    exit 1;
+  endif
+  date |  tee -a $LF
+  set mask = $OutDir/mask.nii
+  set masktal = $OutDir/mask-tal.nii
+  set cmd = (mri_vol2vol --reg $reg --tal --interp nearest\
+              --mov $mask --o $masktal)
+  echo "cd `pwd`" |  tee -a $LF
+  echo $cmd       |  tee -a $LF 
+  $cmd            |& tee -a $LF
+  if($status) exit 1;
+  echo "" | tee -a $LF
+  echo "" | tee -a $LF
 
-# Map FA to talairach space
-set fa = $OutDir/fa.nii
-set fatal = $OutDir/fa-tal.nii
-set cmd = (mri_vol2vol --reg $reg --tal --mov $fa --o $fatal)
-echo "cd `pwd`" |  tee -a $LF
-echo $cmd       |  tee -a $LF 
-$cmd            |& tee -a $LF
-if($status) exit 1;
-echo "" | tee -a $LF
-echo "" | tee -a $LF
+  # Map FA to talairach space
+  set fa = $OutDir/fa.nii
+  set fatal = $OutDir/fa-tal.nii
+  set cmd = (mri_vol2vol --reg $reg --tal --mov $fa --o $fatal)
+  echo "cd `pwd`" |  tee -a $LF
+  echo $cmd       |  tee -a $LF 
+  $cmd            |& tee -a $LF
+  if($status) exit 1;
+  echo "" | tee -a $LF
+  echo "" | tee -a $LF
+endif
 
 echo "dt_recon finished without error at `date`" |& tee -a $LF
 
@@ -240,8 +254,22 @@ while( $#argv != 0 )
       set OutDir = $argv[1]; shift;
       breaksw
 
+    case "--ecref":
+      if($#argv < 1) goto arg1err;
+      set ECRefTP = $argv[1]; shift;
+      breaksw
+
     case "--no-ec":
       set DoEddyCorrect = 0;
+      breaksw
+
+    case "--no-reg":
+      set DoRegistration = 0;
+      set DoTalairach = 0;
+      breaksw
+
+    case "--no-tal":
+      set DoTalairach = 0;
       breaksw
 
     case "--verbose":
@@ -286,7 +314,7 @@ arg3err:
 
 ############--------------##################
 check_params:
-  if($InputVol == 0) then
+  if($#InputVol == 0) then
     echo "ERROR: must specify input volume"
     exit 1;
   endif
@@ -299,27 +327,29 @@ check_params:
     exit 1;
   endif
 
-  if($#subject == 0) then
-    echo "ERROR: must specify a subject"
-    exit 1;
-  endif
+  if($DoRegistration) then
+    if($#subject == 0) then
+      echo "ERROR: must specify a subject"
+      exit 1;
+    endif
 
-  if(! $?SUBJECTS_DIR ) then
-    echo "ERROR: environment variable SUBJECTS_DIR not set"
-    echo "  this can be done by setting it in the shell before"
-    echo "  executing recon-all or by using the -sd flag"
-    exit 1;
-  endif
-  if(! -e $SUBJECTS_DIR ) then
-    echo "ERROR: SUBJECTS_DIR $SUBJECTS_DIR does not exist."
-    exit 1;
-  endif
-  # Get the full path #
-  echo "INFO: SUBJECTS_DIR is $SUBJECTS_DIR"
-  set subjdir = $SUBJECTS_DIR/$subject
-  if(! -e $subjdir) then
-    echo "ERROR: $subjdir does not exist"
-    exit 1;
+    if(! $?SUBJECTS_DIR ) then
+      echo "ERROR: environment variable SUBJECTS_DIR not set"
+      echo "  this can be done by setting it in the shell before"
+      echo "  executing recon-all or by using the -sd flag"
+      exit 1;
+    endif
+    if(! -e $SUBJECTS_DIR ) then
+      echo "ERROR: SUBJECTS_DIR $SUBJECTS_DIR does not exist."
+      exit 1;
+    endif
+    # Get the full path #
+    echo "INFO: SUBJECTS_DIR is $SUBJECTS_DIR"
+    set subjdir = $SUBJECTS_DIR/$subject
+    if(! -e $subjdir) then
+      echo "ERROR: $subjdir does not exist"
+      exit 1;
+    endif
   endif
  
   if(! $?FREESURFER_HOME ) then
@@ -337,6 +367,15 @@ check_params:
 goto check_params_return;
 ############--------------##################
 
+############--------------##################
+error_exit:
+  uname -a | tee -a $LF 
+  echo "" |& tee -a $LF 
+  echo "dt_recon exited with ERRORS at `date`" |& tee -a $LF 
+  echo "" |& tee -a $LF 
+  exit 1;
+############--------------##################
+
 
 ############--------------##################
 usage_exit:
@@ -350,7 +389,10 @@ usage_exit:
   echo "   --o outputdir"
   echo ""
   echo " Other Arguments (Optional)"
+  echo "  --ecref TP       : Use TP as 0-based reference time points for EC"
   echo "  --no-ec          : turn off eddy/motion correction"
+  echo "  --no-reg         : do not register to subject or resample to talairach"
+  echo "  --no-tal         : do not resample FA to talairch space"
   echo "  --sd subjectsdir : specify subjects dir (default env SUBJECTS_DIR)"
   echo "  --debug          : print out lots of info"
   echo "  --version        : print version of this script and exit"
