Copied from dev. Now checks to make sure that FSLDIR is defined

diff --git a/scripts/fslregister b/scripts/fslregister
--- a/scripts/fslregister
+++ b/scripts/fslregister
@@ -8,8 +8,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2011/03/28 20:35:36 $
-#    $Revision: 1.34.2.1 $
+#    $Date: 2012/11/08 16:18:56 $
+#    $Revision: 1.34.2.2 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -24,7 +24,7 @@
 #
 
 #
-set VERSION = '$Id: fslregister,v 1.34.2.1 2011/03/28 20:35:36 greve Exp $';
+set VERSION = '$Id: fslregister,v 1.34.2.2 2012/11/08 16:18:56 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
@@ -603,6 +603,17 @@ check_params:
   if($initxfm && $#InitFSLMat) then
     echo "ERROR: cannot specify both --initxfm and --initfslmat"
     exit 1;
+  endif
+
+  if($DoTrans) then
+    if($?FSLDIR == 0) then
+      echo "ERROR: you must have the FSLDIR environment variable defined and pointing to the FSL installation"
+      exit 1;
+    endif
+    if(! -e $FSLDIR/etc/flirtsch/xyztrans.sch) then
+      echo "ERROR: cannot find $FSLDIR/etc/flirtsch/xyztrans.sch"
+      exit 1;
+    endif
   endif
 
   if($UseNewSchedule) then
