Copied file from dev.

diff --git a/scripts/fslregister b/scripts/fslregister
--- a/scripts/fslregister
+++ b/scripts/fslregister
@@ -8,8 +8,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/07/26 16:52:54 $
-#    $Revision: 1.16 $
+#    $Date: 2009/01/18 19:43:54 $
+#    $Revision: 1.16.2.1 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -25,7 +25,7 @@
 #
 
 #
-set VERSION = '$Id: fslregister,v 1.16 2007/07/26 16:52:54 greve Exp $';
+set VERSION = '$Id: fslregister,v 1.16.2.1 2009/01/18 19:43:54 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
@@ -35,10 +35,10 @@ set movvol = ();
 set outvol = ();
 set dof = 6;
 set bins = 256;
-set maxangle = 70;
+set maxangle = 90;
 set cost = corratio;
 set fslmat = ();
-set betmov = 1;
+set betmov = 0;
 set betfvalue = 0.1
 set UseBETFunc = 0;
 set betref = 0;
@@ -49,6 +49,14 @@ set tmpdir = ();
 set cleanup = 1;
 set PrintHelp = 0;
 set frame = 0;
+set DoMidFrame = 0;
+set templateout = ();
+set DoSegReg = 0;
+set Verbosity = 0;
+set nIters = 1;
+set BBRMask = 1;
+set UseNewSchedule = 1;
+set sch = ();
 
 if($#argv == 0) goto usage_exit;
 set n = `echo $argv | egrep -e --version | wc -l`
@@ -70,7 +78,7 @@ check_params_return:
 setenv FSLOUTPUTTYPE NIFTI
 
 set movvoldir = `dirname $movvol`;
-if($#tmpdir == 0) set tmpdir = $movvoldir/tmp.$$
+if($#tmpdir == 0) set tmpdir = $movvoldir/tmp.fslregister.$$
 mkdir -p $tmpdir
 
 set LF = $regfile.fslregister.log
@@ -85,20 +93,44 @@ echo $inputargs |& tee -a $LF
 echo $VERSION |& tee -a $LF
 hostname |& tee -a $LF
 uname -a |& tee -a $LF
+echo "nIters $nIters" |& tee -a $LF
 
 set StartTime = `date`;
 set DateString = "`date '+%y%m%d%H%M'`"
 
+# Use the rawavg as input (for testing only)
+if($fsvol == rawavg.cor) then
+  set refvol = $SUBJECTS_DIR/$subjid/mri/$fsvol.mgz
+  if(! -e $refvol) then
+    # Does not exist, create
+    set orig = $SUBJECTS_DIR/$subjid/mri/orig.mgz
+    set rawavg = $SUBJECTS_DIR/$subjid/mri/rawavg.mgz
+    set cmd = (mri_vol2vol --mov $rawavg --targ $orig --o $refvol \
+     --no-save-reg --regheader)
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+    # Now mask it
+    set brain = $SUBJECTS_DIR/$subjid/mri/brainmask.mgz
+    set cmd = (mri_mask $refvol $brain $refvol)
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+  endif
+endif
+
 # Convert reference to analyze
-set refvol = $SUBJECTS_DIR/$subjid/mri/$fsvol.mgz
-if(! -e $refvol) then
-  # Might be COR,
+set refvol = `stem2fname $SUBJECTS_DIR/$subjid/mri/$fsvol`
+if($status) then
+  # OK, Might be COR,
   set refvol = $SUBJECTS_DIR/$subjid/mri/$fsvol
   if(! -e $refvol/COR-.info) then
+    # Give up
     echo "ERROR: $refvol not found"
     exit 1;
   endif
 endif
+
 set refvolbase = $tmpdir/refvol.fslregister
 set refvolimg  = $refvolbase.nii
 set cmd = (mri_convert $refvol $refvolimg)
@@ -111,7 +143,12 @@ if($status) exit 1;
 # Convert input to analyze #
 set movvolbase = $tmpdir/movvol.fslregister
 set movvolimg  = $movvolbase.nii
-set cmd = (mri_convert $movvol $movvolimg --frame $frame)
+set cmd = (mri_convert $movvol $movvolimg)
+if($DoMidFrame) then
+  set cmd = ($cmd --mid-frame)
+else
+  set cmd = ($cmd --frame $frame)
+endif
 echo "--------------------------------------" |& tee -a $LF
 pwd        |& tee -a $LF
 echo $cmd  |& tee -a $LF
@@ -173,17 +210,20 @@ endif
 if($#InitFSLMat)  set fslmat0 = $InitFSLMat;
 
 # Set up and run the Flirt command-line
-set cmd = (flirt -ref $refvolimg -in $movvolimg)
+set cmd = (flirt -ref $refvolimg -in $movvolimg -bins $bins)
 set cmd = ($cmd  -omat $fslmat -cost $cost -dof $dof)
 set cmd = ($cmd  -searchrx -$maxangle $maxangle);
 set cmd = ($cmd  -searchry -$maxangle $maxangle);
 set cmd = ($cmd  -searchrz -$maxangle $maxangle);
-if($#fslmat0) set cmd = ($cmd -init $fslmat0)
+set cmd = ($cmd  -verbose $Verbosity);
+if($#sch) set cmd = ($cmd -schedule $sch);
 if($#outvol) then
   set outvolbase = $tmpdir/outvol.fslregister
   set outvolimg  = $outvolbase.nii
   set cmd = ($cmd -o $outvolimg);
 endif
+set cmdA = ($cmd); # cmd line without init
+if($#fslmat0) set cmd = ($cmd -init $fslmat0)
 date | tee -a $LF
 pwd | tee -a $LF
 echo $cmd | tee -a $LF
@@ -192,6 +232,23 @@ if($status) then
   echo "ERROR: flirt" | tee -a $LF
   exit 1;
 endif
+
+# Go thru some iterations to reduce senstivity to initialization
+@ nthIter = 2
+while($nthIter <= $nIters)
+  echo "Iteration $nthIter" | tee -a $LF
+  set cmd = ($cmdA -init $fslmat)
+  date | tee -a $LF
+  pwd | tee -a $LF
+  echo $cmd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) then
+    echo "ERROR: flirt" | tee -a $LF
+    exit 1;
+  endif
+  @ nthIter = $nthIter + 1;
+end
+
 
 # Convert the output to volume to output format
 if($#outvol) then
@@ -226,6 +283,23 @@ if($isflipped) then
   echo ""
   echo "WARNING: possible left-right reversal" | tee -a $LF
   echo ""
+endif
+
+if($DoSegReg) then
+  set cmd = (mri_segreg --reg $regfile --mov $movvol \
+     --out-reg $segregfile --cost $segregfile.segreg.cost)
+  echo $cmd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($BBRMask == 0) set cmd = ($cmd --no-mask)
+  if($status) then
+    echo "ERROR: mri_segreg failed" | tee -a $LF
+    exit 1;
+  endif
+endif
+
+if($#templateout) then
+  mri_convert $movvolimg $templateout
+  if($status) exit 1;
 endif
 
 # Cleanup
@@ -272,6 +346,8 @@ while( $#argv != 0 )
     case "--fsvol":
       if ( $#argv < 1) goto arg1err;
       set fsvol = $argv[1]; shift;
+      set tmp = `fname2stem $fsvol`;
+      if(! $status)  set fsvol = $tmp;
       breaksw
 
     case "--mov":
@@ -294,6 +370,11 @@ while( $#argv != 0 )
       set bins = $argv[1]; shift;
       breaksw
 
+    case "--niters":
+      if ( $#argv == 0) goto arg1err;
+      set nIters = $argv[1]; shift;
+      breaksw
+
     case "--cost":
       if ( $#argv == 0) goto arg1err;
       set cost = $argv[1]; shift;
@@ -306,6 +387,11 @@ while( $#argv != 0 )
 
     case "--betfunc":
       set UseBETFunc = 1;
+      set betmov = 1;
+      breaksw
+
+    case "--betmov":
+      set betmov = 1;
       breaksw
 
     case "--nobetmov":
@@ -344,9 +430,18 @@ while( $#argv != 0 )
       set fslmat = $argv[1]; shift;
       breaksw
 
+    case "--template-out":
+      if ( $#argv < 1) goto arg1err;
+      set templateout = $argv[1]; shift;
+      breaksw
+
     case "--frame":
       if ( $#argv < 1) goto arg1err;
       set frame = $argv[1]; shift;
+      breaksw
+
+    case "--mid-frame":
+      set DoMidFrame = 1;
       breaksw
 
     case "--reg":
@@ -354,10 +449,32 @@ while( $#argv != 0 )
       set regfile = $argv[1]; shift;
       breaksw
 
+    case "--bbr":
+    case "--segreg":
+      if ( $#argv < 1) goto arg1err;
+      set segregfile = $argv[1]; shift;
+      set DoSegReg = 1;
+      breaksw
+    case "--bbr-mask":
+      set BBRMask = 1;
+      breaksw
+    case "--bbr-no-mask":
+      set BBRMask = 0;
+      breaksw
+
     case "--tmp":
       if ( $#argv < 1) goto arg1err;
       set tmpdir = $argv[1]; shift;
       set cleanup = 0;
+      breaksw
+
+    case "--no-new-schedule":
+      set UseNewSchedule = 0;
+      breaksw
+
+    case "--verbose":
+      if ( $#argv < 1) goto arg1err;
+      set Verbosity = $argv[1]; shift;
       breaksw
 
     case "--nocleanup":
@@ -408,6 +525,14 @@ check_params:
     exit 1;
   endif
 
+  if($UseNewSchedule) then
+    set sch = $FREESURFER_HOME/bin/flirt.newdefault.20080811.sch
+    if(! -e $sch) then
+      echo "ERROR: cannot find $sch"
+      exit 1;
+    endif
+  endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -437,22 +562,27 @@ usage_exit:
   echo "   --fslmat fsl.mat : output registration matrix in fsl format"
   echo "   --initfslmat matfile : supply initial fsl matrix file (implies --noinitxfm)"
   echo "   --noinitxfm  : do not initialize based on header goemetry"
+  echo "   --niters niters  : iterate niter times (default is $nIters)"
   echo " "
   echo "   --dof  dof       : FLIRT DOF (default is $dof)"
   echo "   --bins bins      : FLIRT bins (default is $bins)"
   echo "   --cost cost      : FLIRT cost (default is $cost)"
   echo "   --maxangle angle : FLIRT max search angle (default is $maxangle)"
+  echo "   --no-new-schedule "
   echo " "
-  echo "   --nobetmov    : do not perform brain extration on mov"
+  echo "   --betmov      : perform brain extration on mov"
   echo "   --betfvalue f : f value for bet, 0.1 default (passed with -f to bet)"
   echo "   --betfunc     : betfunc on mov instead of simply bet"
   echo " "
   echo "   --betref      : brain extration on ref (usually not needed)"
   echo " "
   echo "   --frame frameno : reg to frameno (default 0=1st)"
+  echo "   --mid-frame  : use middle frame"
   echo "   --fsvol volid : use FreeSurfer volid (default $fsvol)"
+  echo "   --template-out template : save template (good with --frame)"
   echo " "
   echo "   --out outvol : have flirt reslice mov to targ"
+  echo "   --verbose N  : flirt verbosity level"
   echo "   --tmp tmpdir : use tmpdir (implies --nocleanup)"
   echo "   --nocleanup  : do not delete temporary files"
   echo "   --version    : print version and exit"
@@ -516,6 +646,12 @@ registration does not need to be close at this point.
 Initialize FLIRT based on the geometry information in the header of the
 reference and movable volumes. Note that the geometry information must
 be correct in these volumes.
+
+--niters nIterations
+
+Run FLIRT multiple times, using the output from the previous
+evaluation as an initialization for the next. This helps to remove
+sensitivity to initialization. Default is 4.
 
 --dof dof
 
