Copied from dev. Added more error traps

diff --git a/scripts/fslregister b/scripts/fslregister
--- a/scripts/fslregister
+++ b/scripts/fslregister
@@ -8,8 +8,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2013/08/08 21:14:53 $
-#    $Revision: 1.34.2.3 $
+#    $Date: 2014/05/07 20:03:00 $
+#    $Revision: 1.34.2.4 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -24,11 +24,12 @@
 #
 
 #
-set VERSION = '$Id: fslregister,v 1.34.2.3 2013/08/08 21:14:53 greve Exp $';
+set VERSION = '$Id: fslregister,v 1.34.2.4 2014/05/07 20:03:00 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
 set fsvol  = brainmask;
+set regfile = ();
 set refvol = ();
 set movvol = ();
 set outvol = ();
@@ -127,6 +128,10 @@ endif
 
 # Convert reference to analyze
 set refvol = `stem2fname $SUBJECTS_DIR/$subjid/mri/$fsvol`
+if(! -e "$refvol") then
+  echo "ERROR: cannot find $SUBJECTS_DIR/$subjid/mri/$fsvol"
+  exit 1;
+endif
 if($status) then
   # OK, Might be COR,
   set refvol = $SUBJECTS_DIR/$subjid/mri/$fsvol
@@ -589,9 +594,17 @@ check_params:
     echo "ERROR: must spec a subject id"
     exit 1;
   endif
+  if(! -e $SUBJECTS_DIR/$subjid) then
+    echo "ERROR: cannot find $SUBJECTS_DIR/$subjid"
+    exit 1;
+  endif
 
   if($#movvol == 0) then
     echo "ERROR: must spec an movput vol"
+    exit 1;
+  endif
+  if(! -e $movvol) then
+    echo "ERROR: cannot find $movvol"
     exit 1;
   endif
 
