Copied file from dev. Changed fslswapdim and fslorient to include a .fsl extension

diff --git a/scripts/fslregister b/scripts/fslregister
--- a/scripts/fslregister
+++ b/scripts/fslregister
@@ -8,24 +8,23 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2009/07/31 22:22:46 $
-#    $Revision: 1.29 $
+#    $Date: 2011/03/28 20:35:36 $
+#    $Revision: 1.34.2.1 $
 #
-# Copyright (C) 2002-2007,
-# The General Hospital Corporation (Boston, MA).
-# All rights reserved.
+# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
-# Distribution, usage and copying of this software is covered under the
-# terms found in the License Agreement file named 'COPYING' found in the
-# FreeSurfer source code root directory, and duplicated here:
-# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
+# Terms and conditions for use, reproduction, distribution and contribution
+# are found in the 'FreeSurfer Software License Agreement' contained
+# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
 #
-# General inquiries: freesurfer@nmr.mgh.harvard.edu
-# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
+# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
+#
+# Reporting: freesurfer@nmr.mgh.harvard.edu
+#
 #
 
 #
-set VERSION = '$Id: fslregister,v 1.29 2009/07/31 22:22:46 greve Exp $';
+set VERSION = '$Id: fslregister,v 1.34.2.1 2011/03/28 20:35:36 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
@@ -58,6 +57,8 @@ set BBRMask = 1;
 set UseNewSchedule = 1;
 set sch = ();
 set nolog = 0;
+set DoTrans = 1;
+set AllowSwapPosDet = 1;
 
 if($#argv == 0) goto usage_exit;
 set n = `echo $argv | egrep -e --version | wc -l`
@@ -145,7 +146,7 @@ echo $cmd  |& tee -a $LF
 $cmd       |& tee -a $LF
 if($status) exit 1;
 
-# Convert input to analyze #
+# Convert input/movable to analyze #
 set movvolbase = $tmpdir/movvol.fslregister
 set movvolimg  = $movvolbase.nii
 set cmd = (mri_convert $movvol $movvolimg)
@@ -161,12 +162,32 @@ echo $cmd  |& tee -a $LF
 $cmd       |& tee -a $LF
 if($status) exit 2;
 
+# Check for PosDeterminant
+mri_info --det --o $tmpdir/det.dat $movvol
+set det = `cat $tmpdir/det.dat`
+echo "Mov determinant is $det" | tee -a $LF
+set isPosDet = `perl -e "printf('"'%d'"',$det > 0 ) "`
+set DoSwap = 0;
+if($AllowSwapPosDet && $isPosDet) then
+  echo "Swapping dims for pos det" | tee -a $LF
+  set DoSwap = 1;
+  fslswapdim.fsl $movvolimg -x y z $movvolimg |& tee -a $LF
+  if($status) exit 1;
+  fslorient.fsl  -swaporient $movvolimg |& tee -a $LF
+  if($status) exit 1;
+  set swapreg = $tmpdir/swapreg.dat
+  tkregister2_cmdl --mov $movvol --targ $movvolimg \
+     --regheader --reg $swapreg |& tee -a $LF
+  if($status) exit 1;
+endif
+
+
 # Perform brain extration on the movable
 if($betmov) then
   if($UseBETFunc) then
     set cmd = (betfunc $movvolimg $movvolimg)
   else
-    set cmd = (bet $movvolimg $movvolimg -f $betfvalue);
+    set cmd = (bet.fsl $movvolimg $movvolimg -f $betfvalue);
   endif
   date | tee -a $LF
   pwd | tee -a $LF
@@ -214,13 +235,33 @@ endif
 # Use supplied initial matrix
 if($#InitFSLMat)  set fslmat0 = $InitFSLMat;
 
-# Set up and run the Flirt command-line
-set cmd = (flirt -ref $refvolimg -in $movvolimg -bins $bins)
-set cmd = ($cmd  -omat $fslmat -cost $cost -dof $dof)
-set cmd = ($cmd  -searchrx -$maxangle $maxangle);
-set cmd = ($cmd  -searchry -$maxangle $maxangle);
-set cmd = ($cmd  -searchrz -$maxangle $maxangle);
-set cmd = ($cmd  -verbose $Verbosity);
+# Set up the basic flirt command-line options
+set cmd0 = (flirt.fsl -ref $refvolimg -in $movvolimg -bins $bins)
+set cmd0 = ($cmd0  -cost $cost -dof $dof)
+set cmd0 = ($cmd0  -searchrx -$maxangle $maxangle);
+set cmd0 = ($cmd0  -searchry -$maxangle $maxangle);
+set cmd0 = ($cmd0  -searchrz -$maxangle $maxangle);
+set cmd0 = ($cmd0  -verbose $Verbosity);
+
+# First, run with translation only. This is good for problem data sets
+if($DoTrans) then
+  set newfslmat0 = $tmpdir/fslmat0.trans.mat
+  set cmd = ($cmd0 -omat $newfslmat0 -schedule $FSLDIR/etc/flirtsch/xyztrans.sch)
+  if($#fslmat0) set cmd = ($cmd -init $fslmat0)
+  date | tee -a $LF
+  pwd | tee -a $LF
+  echo $cmd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) then
+    echo "ERROR: flirt" | tee -a $LF
+    exit 1;
+  endif
+  set fslmat0 = $newfslmat0;
+endif
+
+# Now run with full schedule
+set cmd = ($cmd0 -omat $fslmat)
+if($#fslmat0) set cmd = ($cmd -init $fslmat0)
 if($#sch) set cmd = ($cmd -schedule $sch);
 if($#outvol) then
   set outvolbase = $tmpdir/outvol.fslregister
@@ -228,7 +269,6 @@ if($#outvol) then
   set cmd = ($cmd -o $outvolimg);
 endif
 set cmdA = ($cmd); # cmd line without init
-if($#fslmat0) set cmd = ($cmd -init $fslmat0)
 date | tee -a $LF
 pwd | tee -a $LF
 echo $cmd | tee -a $LF
@@ -269,7 +309,11 @@ if($#outvol) then
 endif
 
 # Now create the freesurfer registration matrix
-set cmd = (tkregister2_cmdl --s $subjid --mov $movvol)
+set cmd = (tkregister2_cmdl --s $subjid)
+# movvol and movvoloimg have slightly diff geometries
+# The lines below are for backwards compatibiltiy
+if(! $DoSwap) set cmd = ($cmd --mov $movvol)
+if($DoSwap) set cmd = ($cmd --mov $movvolimg)
 set cmd = ($cmd --reg $regfile)
 set cmd = ($cmd --fslreg $fslmat)
 set tkregcheckcmd = ($cmd --surf orig);  # for visual inspection
@@ -279,6 +323,14 @@ $cmd |& tee -a $LF
 if($status) then
   echo "ERROR: tkregister2_cmdl" | tee -a $LF
   exit 1;
+endif
+
+# Fix for dim swap 
+if($DoSwap) then
+  set cmd = (mri_matrix_multiply -im $swapreg -im $regfile -om $regfile)
+  echo $cmd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) exit 1;
 endif
 
 # Check for possible LR flip
@@ -430,6 +482,24 @@ while( $#argv != 0 )
       set initxfm = 0;
       breaksw
 
+    case "--trans":
+      set DoTrans = 1;
+      breaksw
+
+    case "--notrans":
+    case "--no-trans":
+      set DoTrans = 0;
+      breaksw
+
+    case "--allow-swap":
+      set AllowSwapPosDet = 1;
+      breaksw
+
+    case "--noallow-swap":
+    case "--no-allow-swap":
+      set AllowSwapPosDet = 0;
+      breaksw
+
     case "--fslmat":
       if ( $#argv < 1) goto arg1err;
       set fslmat = $argv[1]; shift;
@@ -579,6 +649,9 @@ usage_exit:
   echo "   --cost cost      : FLIRT cost (default is $cost)"
   echo "   --maxangle angle : FLIRT max search angle (default is $maxangle)"
   echo "   --no-new-schedule "
+  echo " "
+  echo "   --no-allow-swap : do not allow swap dim of positive determinant input volumes"
+  echo "   --no-trans : do not do a translation-only registration prior to full "
   echo " "
   echo "   --betmov      : perform brain extration on mov"
   echo "   --betfvalue f : f value for bet, 0.1 default (passed with -f to bet)"
