sync from cvs.

diff --git a/scripts/fvcompare b/scripts/fvcompare
--- a/scripts/fvcompare
+++ b/scripts/fvcompare
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # fvcompare
 
-set VERSION = '$Id: fvcompare,v 1.4 2015/06/04 16:59:58 greve Exp $';
+set VERSION = '$Id: fvcompare,v 1.6 2015/12/02 20:17:00 greve Exp $';
 
 set subject1 = ();
 set subject2 = ();
@@ -16,10 +16,10 @@ set seglist = ();
 set segcolor = $FREESURFER_HOME/FreeSurferColorLUT.txt
 set segopacity = 1;
 set surflist = (white pial);
-set surfcolor1 = (yellow red);
-set surfcolor2 = (green blue);
-set surfcolor3 = (green blue);
-set surfcolor4 = (green blue);
+set surfcolor1 = (yellow red blue);
+set surfcolor2 = (green blue blue);
+set surfcolor3 = (green blue blue);
+set surfcolor4 = (green blue blue);
 set tmpdir = ();
 set cleanup = 1;
 set LF = ();
@@ -29,9 +29,13 @@ set name3 = "s3"
 set name4 = "s4"
 set grayscale = (":grayscale=0,255")
 set NoSeg = 0;
-set NoSurf = 0;
+#set NoSurf = 0;
 set hemilist = (lh rh)
 set snolist = (1 2)
+set CursorCRS = ();
+set CenterCursor = 0;
+set Zoom = ();
+set annot = ();
 
 set inputargs = ($argv);
 set PrintHelp = 0;
@@ -137,10 +141,27 @@ foreach hemi ($hemilist)
         set name = $name4
       endif
       set cue = "$name-$hemi.$surf-$surfcolor[$nth]"
-      set cmd = ($cmd --surface "$subject/surf/$hemi.$surf":"edgecolor=$surfcolor[$nth]":"name=$cue")
+      set surfarg = "$subject/surf/$hemi.$surf":"edgecolor=$surfcolor[$nth]":"name=$cue"
+      if($#annot) then
+        if($s == 1) set SD = $SD1
+        if($s == 2) set SD = $SD2
+        if($s == 3) set SD = $SD3
+        if($s == 4) set SD = $SD4
+        set annotfile = $subject/label/$hemi.$annot
+        if(! -e $annotfile) then
+          echo "ERROR: cannot find $annotfile"
+          exit 1;
+        endif
+        set surfarg = "$surfarg":"annot=$annotfile":"edgethickness=0:annot_outline=1"
+      endif
+      set cmd = ($cmd --surface $surfarg)
     end
   end
 end
+
+if($#CursorCRS) set cmd = ($cmd -slice $CursorCRS)
+if($CenterCursor) set cmd = ($cmd -cc)
+if($#Zoom) set cmd = ($cmd -zoom $Zoom)
 
 echo $cmd
 $cmd
@@ -288,6 +309,7 @@ while( $#argv != 0 )
 
     case "--no-surf":
       set NoSurf = 1;
+      set surflist = ()
       breaksw
 
     case "--opacity":
@@ -302,12 +324,37 @@ while( $#argv != 0 )
       set hemilist = (rh)
       breaksw
 
+    case "--inflated":
+      set surflist = ($surflist inflated)
+      breaksw
+
     case "--gray":
     case "--grayscale":
       if($#argv < 2) goto arg2err;
       set g1 = $argv[1]; shift;
       set g2 = $argv[1]; shift;
       set grayscale = (":grayscale=$g1,$g2")
+      breaksw
+
+    case "--crs":
+      if($#argv < 3) goto arg3err;
+      set CursorCRS = ($argv[1-3]);
+      shift;shift;shift;
+      set CenterCursor = 1;
+      breaksw
+
+    case "--zoom":
+      if($#argv < 1) goto arg1err;
+      set Zoom = $argv[1]; shift;
+      breaksw
+
+    case "--annot":
+      if($#argv < 1) goto arg1err;
+      set annot = $argv[1]; shift;
+      breaksw
+
+    case "--aparc":
+      set annot = aparc.annot
       breaksw
 
     case "--log":
@@ -391,7 +438,7 @@ if($#vollist == 0) set vollist = (brainmask.mgz)
 if($#seglist == 0) set seglist = (aparc+aseg.mgz)
 
 if($NoSeg) set seglist = ()
-if($NoSurf) set surflist = ()
+#if($NoSurf) set surflist = ()
 
 goto check_params_return;
 ############--------------##################
@@ -422,6 +469,11 @@ usage_exit:
   echo "  --lh, --rh : only display left or right hemi"
   echo "  --no-surf : do not display surfaces"
   echo "  --gray min max : set gray scale levels (default is 0 255)"
+  echo "  --crs col row slice : place cursor at given location and center FoV"
+  echo "  --zoom Zoom : set zoom level"
+  echo "  --annot annotname :  loads annotname.annot onto surfaces"
+  echo "  --aparc : load aparc.annot onto surfaces"
+  echo "  --inflated : load inflated surfaces in addition to white and pial"
   echo ""
 
   if(! $PrintHelp) exit 1;
diff --git a/scripts/sratio b/scripts/sratio
--- a/scripts/sratio
+++ b/scripts/sratio
@@ -2,7 +2,7 @@
 # sratio - signed ratio
 #   +A/B if A>B
 #   -B/A if B>A
-# $Id: sratio,v 1.4 2011/03/02 20:16:40 nicks Exp $
+# $Id: sratio,v 1.7 2015/12/03 16:11:58 greve Exp $
 
 #
 # sratio
@@ -11,9 +11,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: nicks $
-#    $Date: 2011/03/02 20:16:40 $
-#    $Revision: 1.4 $
+#    $Author: greve $
+#    $Date: 2015/12/03 16:11:58 $
+#    $Revision: 1.7 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -29,80 +29,131 @@
 
 setenv FSLOUTPUTTYPE NIFTI
 set tmpdir = ();
+set VERSION = '$Id: sratio,v 1.7 2015/12/03 16:11:58 greve Exp $';
+set cleanup = 1;
+set LF = ();
+set A = ();
+set B = ();
+set sAdivB = ();
+set DoAbs = 0;
 
-if($#argv < 3 || $#argv > 4) then
-  echo "sratio A B sAdivB <tmpdir>"
-  echo "  A/B if A>B, -B/A if B>A"
-  exit 1;
+set inputargs = ($argv);
+set PrintHelp = 0;
+if($#argv == 0) goto usage_exit;
+set n = `echo $argv | grep -e -help | wc -l` 
+if($n != 0) then
+  set PrintHelp = 1;
+  goto usage_exit;
 endif
-
-set A = $argv[1]; shift;
-set B = $argv[1]; shift;
-set sAdivB = $argv[1]; shift;
-if($#argv != 0) then
-  set tmpdir = $argv[1]; shift
+set n = `echo $argv | grep -e -version | wc -l` 
+if($n != 0) then
+  echo $VERSION
+  exit 0;
 endif
+goto parse_args;
+parse_args_return:
+goto check_params;
+check_params_return:
 
-if(! -e $A) then
-  echo "ERROR: cannot find $A"
-  exit 1;
+set StartTime = `date`;
+set tSecStart = `date '+%s'`;
+set year  = `date +%Y`
+set month = `date +%m`
+set day   = `date +%d`
+set hour   = `date +%H`
+set min    = `date +%M`
+
+set outdir = `dirname $sAdivB`
+
+mkdir -p $outdir
+pushd $outdir > /dev/null
+set outdir = `pwd`;
+popd > /dev/null
+
+if($#tmpdir == 0) then
+  if(-dw /scratch)   set tmpdir = /scratch/tmpdir.sratio.$$
+  if(! -dw /scratch) set tmpdir = $outdir/tmpdir.sratio.$$
 endif
-
-if(! -e $B) then
-  echo "ERROR: cannot find $B"
-  exit 1;
-endif
-
-if($#tmpdir == 0) set tmpdir = /tmp
-set code = $$
-if($tmpdir != "/tmp") set code = 0;
-
 mkdir -p $tmpdir
 
+# Set up log file
+set LF = /dev/null
+echo "Log file for sratio" >> $LF
+date  | tee -a $LF
+echo "" | tee -a $LF
+echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
+echo "cd `pwd`"  | tee -a $LF
+echo $0 $inputargs | tee -a $LF
+echo "" | tee -a $LF
+cat $FREESURFER_HOME/build-stamp.txt | tee -a $LF
+echo $VERSION | tee -a $LF
+uname -a  | tee -a $LF
+if($?PBS_JOBID) then
+  echo "pbsjob $PBS_JOBID"  >> $LF
+endif
+
+#========================================================
+mkdir -p $tmpdir
+
+if($DoAbs) then
+  set A2 = $tmpdir/A.nii
+  set cmd = (mri_concat $A --abs --o $A2)
+  echo $cmd | tee -a $LF
+  $cmd | tee -a $LF
+  if($status) goto error_exit;
+  set A = $A2
+  set B2 = $tmpdir/B.nii
+  set cmd = (mri_concat $B --abs --o $B2)
+  echo $cmd | tee -a $LF
+  $cmd | tee -a $LF
+  if($status) goto error_exit;
+  set B = $B2
+endif
+
 # A > B
-set AgtB = $tmpdir/AgtB.$code.nii
+set AgtB = $tmpdir/AgtB.nii
 set cmd = (fscalc.fsl $A -sub $B $AgtB)
 echo $cmd
 $cmd
 if($status) exit 1;
 
 # B > A (A < B)
-set BgtA = $tmpdir/BgtA.$code.nii
+set BgtA = $tmpdir/BgtA.nii
 set cmd = (fscalc.fsl $B -sub $A $BgtA)
 echo $cmd
 $cmd
 if($status) exit 1;
 
 # A/B
-set AdivB = $tmpdir/AdivB.$code.nii
+set AdivB = $tmpdir/AdivB.nii
 set cmd = (fscalc.fsl $A -div $B $AdivB)
 echo $cmd
 $cmd
 if($status) exit 1;
 
 # -B/A
-set BdivA = $tmpdir/BdivA.$code.nii
+set BdivA = $tmpdir/BdivA.nii
 set cmd = (fscalc.fsl $B -div $A -mul -1 $BdivA) # signed by -1
 echo $cmd
 $cmd
 if($status) exit 1;
 
 # Anum = A/B where A > B
-set Anum = $tmpdir/Anum.$code.nii
+set Anum = $tmpdir/Anum.nii
 set cmd = (fscalc.fsl $AdivB -mas $AgtB $Anum)
 echo $cmd
 $cmd
 if($status) exit 1;
 
 # Bnum = -B/A where  B > A
-set Bnum = $tmpdir/Bnum.$code.nii
+set Bnum = $tmpdir/Bnum.nii
 set cmd = (fscalc.fsl $BdivA -mas $BgtA $Bnum)
 echo $cmd
 $cmd
 if($status) exit 1;
 
 # Now just add Anum and Bnum
-set sAdivBtmp = $tmpdir/sAdivB.$code.nii
+set sAdivBtmp = $tmpdir/sAdivB.nii
 set cmd = (fscalc.fsl $Anum -add $Bnum $sAdivBtmp)
 echo $cmd
 $cmd
@@ -114,14 +165,137 @@ echo $cmd
 $cmd
 if($status) exit 1;
 
-# Clean up
-if($tmpdir == "/tmp") rm /tmp/*.$code.nii
+#========================================================
 
+# Cleanup
+if($cleanup) rm -rf $tmpdir
+
+# Done
+echo " " |& tee -a $LF
+set tSecEnd = `date '+%s'`;
+@ tSecRun = $tSecEnd - $tSecStart;
+set tRunHours = `echo $tSecRun/3600|bc -l`
+set tRunHours = `printf %5.2f $tRunHours`
+echo "Started at $StartTime " |& tee -a $LF
+echo "Ended   at `date`" |& tee -a $LF
+echo "Sratio-Run-Time-Sec $tSecRun" |& tee -a $LF
+echo "Sratio-Run-Time-Hours $tRunHours" |& tee -a $LF
+echo " " |& tee -a $LF
+echo "sratio Done" |& tee -a $LF
 exit 0
-###################################################
 
+###############################################
 
+############--------------##################
+error_exit:
+echo "ERROR:"
 
+exit 1;
+###############################################
 
+############--------------##################
+parse_args:
+set cmdline = ($argv);
+while( $#argv != 0 )
 
+  set flag = $argv[1]; shift;
+  
+  switch($flag)
+
+    case "--abs":
+      set DoAbs = 1;
+      breaksw
+
+    case "--tmp":
+    case "--tmpdir":
+      if($#argv < 1) goto arg1err;
+      set tmpdir = $argv[1]; shift;
+      set cleanup = 0;
+      breaksw
+
+    case "--nocleanup":
+      set cleanup = 0;
+      breaksw
+
+    case "--cleanup":
+      set cleanup = 1;
+      breaksw
+
+    case "--debug":
+      set verbose = 1;
+      set echo = 1;
+      breaksw
+
+    default:
+      if($#A == 0) then
+        set A = $flag;
+        if(! -e $A) then
+          echo "ERROR: cannot find $A"
+          exit 1;
+        endif
+      else if( $#B == 0 ) then
+        set B = $flag;
+        if(! -e $B) then
+          echo "ERROR: cannot find $B"
+          exit 1;
+        endif
+      else if($#sAdivB == 0) then 
+        set sAdivB = $flag;
+      else
+        echo ERROR: Flag $flag unrecognized. 
+        echo $cmdline
+        exit 1
+      endif
+      breaksw
+  endsw
+
+end
+
+goto parse_args_return;
+############--------------##################
+
+############--------------##################
+check_params:
+
+if($#A == 0) then
+  echo "ERROR: must spec A"
+  exit 1;
+endif
+if($#B == 0) then
+  echo "ERROR: must spec B"
+  exit 1;
+endif
+if($#sAdivB == 0) then
+  echo "ERROR: must spec output"
+  exit 1;
+endif
+
+goto check_params_return;
+############--------------##################
+
+############--------------##################
+arg1err:
+  echo "ERROR: flag $flag requires one argument"
+  exit 1
+############--------------##################
+arg2err:
+  echo "ERROR: flag $flag requires two arguments"
+  exit 1
+############--------------##################
+
+############--------------##################
+usage_exit:
+  echo "sratio options A B sAdivB"
+  echo "  A/B if A>B, -B/A if B>A"
+  echo " Options:"
+  echo "   --abs : compute absolute value of both A and B before sratio"
+  echo ""
+
+  if(! $PrintHelp) exit 1;
+  echo $VERSION
+  cat $0 | awk 'BEGIN{prt=0}{if(prt) print $0; if($1 == "BEGINHELP") prt = 1 }'
+exit 1;
+
+#---- Everything below here is printed out as part of help -----#
+BEGINHELP
 
