Added ability to supply an LTA and norm. -greve

diff --git a/scripts/gca-apply b/scripts/gca-apply
--- a/scripts/gca-apply
+++ b/scripts/gca-apply
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # gca-apply
 
-set VERSION = '$Id: gca-apply,v 1.5 2015/08/07 14:49:49 greve Exp $';
+set VERSION = '$Id: gca-apply,v 1.6 2015/08/19 15:57:40 greve Exp $';
 
 set gca = ();
 set subject = ();
@@ -10,6 +10,8 @@ set gcabase = ()
 set GCARegIterations = ();
 set DiceSeg = ();
 set DiceFile = ();
+set SrcLTA = ();
+set SrcNorm = ();
 
 set Overwrite = 0;
 set tmpdir = ();
@@ -69,24 +71,33 @@ uname -a  | tee -a $LF
 cd $mdir
 
 # mri_em_register
-set opts = (-mask brainmask.mgz)
-set opts = ($opts -uns 3) # used by recon-all, but not with skull
-# but docs imply it is only with skull that it should be used
-set cmd = (mri_em_register $opts nu.mgz $gca transforms/$gcabase.lta)
+set LTA = transforms/$gcabase.lta
+if($#SrcLTA == 0) then
+  set opts = (-mask brainmask.mgz)
+  set opts = ($opts -uns 3) # used by recon-all, but not with skull
+  # but docs imply it is only with skull that it should be used
+  set cmd = (mri_em_register $opts nu.mgz $gca $LTA)
+else
+  set cmd = (cp $SrcLTA $LTA)
+endif
 echo $cmd |& tee -a $LF
 $cmd |& tee -a $LF
 if($status) exit 1;
 
 # mri_ca_normlize
 set norm = norm.$gcabase.mgz
-set cmd = (mri_ca_normalize -mask brainmask.mgz nu.mgz $gca \
-  transforms/$gcabase.lta $norm)
+if($#SrcNorm == 0) then
+  set cmd = (mri_ca_normalize -mask brainmask.mgz nu.mgz $gca \
+    transforms/$gcabase.lta $norm)
+else
+  set cmd = (cp $SrcNorm $norm)
+endif
 echo $cmd | tee -a $LF
 $cmd |& tee -a $LF
 if($status) exit 1;
 
 # mri_ca_register
-set opts = (-align-after -mask brainmask.mgz -T transforms/$gcabase.lta)
+set opts = (-align-after -mask brainmask.mgz -T $LTA)
 set opts = ($opts -nobigventricles) # Used by recon-all
 # These are not used by recon-all but used in rebuild_gca_atlas.csh
 #set opts = ($opts -smooth 1.0 -levels 2) 
@@ -204,6 +215,26 @@ while( $#argv != 0 )
     case "--sd":
       if ( $#argv < 1) goto arg1err;
       setenv  SUBJECTS_DIR $argv[1]; shift;
+      breaksw
+
+    case "--lta":
+      if($#argv < 1) goto arg1err;
+      set SrcLTA = $argv[1]; shift;
+      if(! -e $SrcLTA) then
+        echo "ERROR: cannot find $SrcLTA"
+        exit 1;
+      endif
+      set SrcLTA = `getfullpath $SrcLTA`
+      breaksw
+
+    case "--norm":
+      if($#argv < 1) goto arg1err;
+      set SrcNorm = $argv[1]; shift;
+      if(! -e $SrcNorm) then
+        echo "ERROR: cannot find $SrcNorm"
+        exit 1;
+      endif
+      set SrcNorm = `getfullpath $SrcNorm`
       breaksw
 
     case "--dice":
@@ -330,6 +361,8 @@ usage_exit:
   echo "  --no-segstats : do not compute segstats "
   echo "  --sd SUBJECTS_DIR, or -sd "
   echo "  --dice DiceSeg DiceFile "
+  echo "  --lta SrcLTA : use SrcLTA instead of running mri_em_register "
+  echo "  --norm SrcNorm : use SrcNorm instead of running mri_ca_normalize "
   echo ""
   echo "  --gcareg-iters : set to 1, only for testing"
   echo ""
