User can supply a -matlab matlab_binary, default is /space/lyon/6/pubsw/common/matlab/6.5/bin/matlab

diff --git a/scripts/grad_unwarp b/scripts/grad_unwarp
--- a/scripts/grad_unwarp
+++ b/scripts/grad_unwarp
@@ -1,10 +1,14 @@
 #!/bin/csh -f
 # grad_unwarp - convert, unwarp, and resample dicom files
 #
-# $Id: grad_unwarp,v 1.3 2003/08/07 17:48:51 ebeth Exp $
-set VERSION = '$Id: grad_unwarp,v 1.3 2003/08/07 17:48:51 ebeth Exp $';
+# $Id: grad_unwarp,v 1.4 2003/08/22 21:55:58 ebeth Exp $
+set VERSION = '$Id: grad_unwarp,v 1.4 2003/08/22 21:55:58 ebeth Exp $';
 
 set inputargs = ($argv);
+
+#set matlab = "/usr/pubsw/bin/matlab6.5"
+#set matlab = "/space/gari/1/pubsw/matlab/bin/matlab"
+set matlab = "/space/lyon/6/pubsw/common/matlab/6.5/bin/matlab"
 
 set infile = ();
 set seriesno = 0;
@@ -111,7 +115,8 @@ if(! $monly ) then
     echo "INFO: $outfileuse exists ... deleting"
     rm -f $outfileuse
   endif
-  cat $MLF | matlab -display iconic | tee -a $LF
+  echo "INFO: using matlab installation $matlab"
+  cat $MLF | $matlab -display iconic | tee -a $LF
   rm $MLF
   if(! -e $outfileuse) then
     echo "ERROR: output file not created"
@@ -215,6 +220,11 @@ while( $#argv != 0 )
       set monly = 1;
       breaksw
 
+    case "-matlab":
+      if ( $#argv == 0) goto arg1err;
+      set matlab = $argv[1]; shift;
+      breaksw
+
     case "-verbose":
       set verbose = 1;
       breaksw
@@ -275,9 +285,15 @@ check_params:
     exit 1;
   endif
 
+  if(! -x $matlab) then
+    echo "ERROR: matlab $matlab not found or not executable"
+    exit 1;
+  endif
+
 # matlab code checks for:
 # -i dcmdir and no -s seriesno, 
 # -i foo.mgh -unwarp and no unwarptype
+# We don't here.
 
 goto check_params_return;
 ############--------------##################
