Now does not crash if mri_glmfit exits with error and the meas is area

diff --git a/scripts/groupstatsdiff b/scripts/groupstatsdiff
--- a/scripts/groupstatsdiff
+++ b/scripts/groupstatsdiff
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # groupstatsdiff
 
-set VERSION = '$Id: groupstatsdiff,v 1.5 2015/05/15 22:41:06 greve Exp $';
+set VERSION = '$Id: groupstatsdiff,v 1.6 2015/05/21 16:50:08 greve Exp $';
 
 set g1dir = ();
 set g2dir = ();
@@ -165,7 +165,15 @@ if($DoMaps) then
         set cmd = (mri_glmfit --surface fsaverage $hemi --y $smdifffile --glmdir $glmdir $gcmd)
         echo "#C# $cmd"  | tee -a $LF
         $cmd | tee -a $LF
-        if($status) exit 1;
+        if($status) then
+	  if($meas == area) then
+            # This can happen when comparing t1-only with the t2 stream
+            echo "Though there was an error, it is probably due to pruning of area diffs" | tee -a $LF
+            echo "so I'm just going to move on to the next one" | tee -a $LF
+	    continue;
+          endif
+          exit 1;
+        endif
 	if($fwhm != 0) then
           set cmd = (mri_glmfit-sim --glmdir $glmdir --cwp .05 --cache 1.3 abs --2spaces)
           echo "#C# $cmd"  | tee -a $LF
