Removed dividing the cerebellum WM segmentation into core and gyrus

diff --git a/scripts/gtmseg b/scripts/gtmseg
--- a/scripts/gtmseg
+++ b/scripts/gtmseg
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # gtmseg
 
-set VERSION = '$Id: gtmseg,v 1.14 2014/10/01 20:45:25 greve Exp $';
+set VERSION = '$Id: gtmseg,v 1.15 2014/10/06 21:26:23 greve Exp $';
 
 set outdir = ();
 set subject = ();
@@ -21,10 +21,10 @@ set wmlhbase=0;
 set wmrhbase=0;
 set DoSegStats = 1;
 set ctab = ();
-set SubSegCblumWM = 1;
+set SubSegCblumWM = 0;
 set AddPons = 1;
 set AddVermis = 1;
-set DoXCerSeg = 0;
+set DoXCerSeg = ();
 
 set tmpdir = ();
 set cleanup = 1;
@@ -199,9 +199,14 @@ while( $#argv != 0 )
       set DoXCerSeg = 1;
       breaksw
 
+    case "--no-xcerseg":
+      set DoXCerSeg = 0;
+      breaksw
+
     case "--head":
       if($#argv < 1) goto arg1err;
       set headseg = $argv[1]; shift;
+      set DoXCerSeg = 0;
       breaksw
 
     case "--no-pons":
@@ -362,12 +367,27 @@ if($#wmannot) then
   end
 endif
 
-if(! $DoXCerSeg && ! -e $SUBJECTS_DIR/$subject/mri/$headseg) then
-  echo "ERROR: cannot find $SUBJECTS_DIR/$subject/mri/$headseg" 
-  if($headseg == apas+head.mgz) then
-    echo "  If you want to use the default head segmentation, then" 
-    echo "  run this command with --xcerseg or run xcerebralseg separately"
+if(! -e $SUBJECTS_DIR/$subject/mri/$headseg) then
+  # Headseg is not there
+  if($#DoXCerSeg == 0) then
+    # No instruction as to whether create it or not, so create it by default
+    set DoXCerSeg = 1;
   endif
+else
+  # Headseg is there
+  if($#DoXCerSeg == 0) then
+    # No instruction as to whether to overwrite it or not
+    echo "ERROR: $SUBJECTS_DIR/$subject/mri/$headseg exists. This is ok"
+    echo "but you must indicate whether to use what is there (--no-xcereseg)"
+    echo "or create a new one and overwrite what is there (--xcereseg)"
+    echo "or specify your own headseg (--head)"
+    echo ""
+    exit 1;
+  endif
+endif
+
+if($DoXCerSeg == 0 && ! -e $SUBJECTS_DIR/$subject/mri/$headseg) then
+  echo "ERROR: $SUBJECTS_DIR/$subject/mri/$headseg does not exist"
   exit 1;
 endif
 
@@ -407,7 +427,7 @@ usage_exit:
   echo " --wm-annot  annot lhbase rhbase : annotation to use for WM segmentation (with --subsegwm, default is lobes 3200 4200)"
   echo " --output-usf OutputUSF : set output USF different than USF, mostly for debugging"
   echo " --head headseg : use headseg instead of $headseg"
-  echo " --no-subseg-cblum-wm : do not subsegment cerebellum WM into core and gyri":
+  echo " --subseg-cblum-wm : subsegment cerebellum WM into core and gyri":
   echo " --no-pons :   do not add pons segmentation when doing ---xcerseg":
   echo " --no-vermis : do not add vermis segmentation when doing ---xcerseg":
   echo " --ctab colortable "
@@ -428,25 +448,20 @@ BEGINHELP
 Creates a segmentation that can then be used with the geometric
 transfer matrix for performing PET partial volume correction. It will
 create a segmentation of the head (approximate extra-cerebral CSF,
-approximate skull, and the rest of the head) using the xcerebralseg
-script. The WM can be subsegmented into lobes with
---subsegwm. Hypointensities can be kept with --keep-hypo. The corpus
-callosum can be kept with --keep-cc. If these segments are not "kept"
-then they are relabelled as WM. The upsampling factor (USF) controls
-the resolution of the segmentation; this make a difference for
-cortical segmentations. Higher resolution is more accurate but takes
-up more disk space and will require more computations later on. 
-
-By default, the cerebellum WM is subsegmented into a core component
-and gyri. The core components keep the
+approximate skull, air cavities, and the rest of the head) using the
+xcerebralseg script; this also adds segments for pons and vermis by
+default; With --subseg-cblum-wm, the cerebellum WM is subsegmented
+into a core component and gyri. The core components keep the
 {Left,Right}-Cerebellum-White-Matter names and indices. The gyri will
-become CbmWM_Gyri_{Left,Right} with indices 690 and 691. This segmentation
-is done because the gyri tend to be very thin and hard to segment
-from GM. Because they are thin, they will be very succeptible to 
-partial volume effects, even with partial volume correction. This
-can be especially problematic when cerebellum WM is used as a 
-reference region. To remerge them when running mri_gtmpvc, add
-this to the command line: --replace 690 7 --replace 691 46
+become CbmWM_Gyri_{Left,Right} with indices 690 and 691.
+
+The WM can be subsegmented into lobes with --subsegwm. Hypointensities
+can be kept with --keep-hypo. The corpus callosum can be kept with
+--keep-cc. If these segments are not "kept" then they are relabelled
+as WM. The upsampling factor (USF) controls the resolution of the
+segmentation; this make a difference for cortical
+segmentations. Higher resolution is more accurate but takes up more
+disk space and will require more computations later on.
 
 Example:
 
@@ -469,8 +484,8 @@ create it with
 
 xcerebralseg --s $subject --o $SUBJECTS_DIR/$subject/mri/apas+head.mgz
 
-Create a new segmentation by replacing voxels in apas+head.mgz with
-your segmentation. Make sure that the index you give your new
+To create a new segmentation by replacing voxels in apas+head.mgz with
+your segmentation: make sure that the index you give your new
 segmentation(s) is not already present in apas+head.mgz. Next create a
 color table text file that looks something like this:
 
