Now forces you to create apas+head.mgz or spec something on the cmd line

diff --git a/scripts/gtmseg b/scripts/gtmseg
--- a/scripts/gtmseg
+++ b/scripts/gtmseg
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # gtmseg
 
-set VERSION = '$Id: gtmseg,v 1.9 2014/09/11 19:31:57 greve Exp $';
+set VERSION = '$Id: gtmseg,v 1.10 2014/09/17 20:35:51 greve Exp $';
 
 set outdir = ();
 set subject = ();
@@ -22,6 +22,7 @@ set wmrhbase=0;
 set DoSegStats = 1;
 set ctab = ();
 set SubSegCblumWM = 1;
+set DoXCerSeg = 0;
 
 set tmpdir = ();
 set cleanup = 1;
@@ -75,14 +76,11 @@ echo $VERSION | tee -a $LF
 uname -a  | tee -a $LF
 
 #========================================================
-if($headseg == apas+head.mgz && ! -e $SUBJECTS_DIR/$subject/mri/$headseg) then
+if($DoXCerSeg) then
   set cmd = (xcerebralseg --s $subject)
   if(! $cleanup) set cmd = ($cmd --tmpdir $tmpdir/xcerebralseg)
   echo $cmd | tee -a $LF
   $cmd | tee -a $LF
-  if($status) goto error_exit;
-else if(! -e $SUBJECTS_DIR/$subject/mri/$headseg) then
-  echo "ERROR: cannot find $SUBJECTS_DIR/$subject/mri/$headseg"
   if($status) goto error_exit;
 endif
 
@@ -188,6 +186,11 @@ while( $#argv != 0 )
     case "--o":
       if($#argv < 1) goto arg1err;
       set outvol = $argv[1]; shift;
+      breaksw
+
+    case "--xcerseg":
+      set headseg = apas+head.mgz
+      set DoXCerSeg = 1;
       breaksw
 
     case "--head":
@@ -345,6 +348,15 @@ if($#wmannot) then
   end
 endif
 
+if(! $DoXCerSeg && ! -e $SUBJECTS_DIR/$subject/mri/$headseg) then
+  echo "ERROR: cannot find $SUBJECTS_DIR/$subject/mri/$headseg" 
+  if($headseg == apas+head.mgz) then
+    echo "  If you want to use the default head segmentation, then" 
+    echo "  run this command with --xcerseg or run xcerebralseg separately"
+  endif
+  exit 1;
+endif
+
 goto check_params_return;
 ############--------------##################
 
@@ -369,6 +381,7 @@ usage_exit:
   echo "   run with --help for more help"
   echo ""
   echo " --s subject     : subject to analyze (required)"
+  echo " --xcerseg : run xcerebralseg on this subject to create $headseg"
   echo ""
   echo " --o outvol      : relative to subject/mri (default is $outvol)" 
   echo " --usf USF       : upsampling factor (default is $USF)"
