NOW will not stop execution if making the average segmentation fails

diff --git a/scripts/make_average_volume b/scripts/make_average_volume
--- a/scripts/make_average_volume
+++ b/scripts/make_average_volume
@@ -10,8 +10,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/01/03 19:48:52 $
-#    $Revision: 1.25 $
+#    $Date: 2008/01/03 20:01:54 $
+#    $Revision: 1.26 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -29,7 +29,7 @@
 # uncomment this to increase number of allowable open files to maximum:
 #limit descriptors unlimited
 
-set VERSION = '$Id: make_average_volume,v 1.25 2008/01/03 19:48:52 greve Exp $';
+set VERSION = '$Id: make_average_volume,v 1.26 2008/01/03 20:01:54 greve Exp $';
 
 set PrintHelp = 0;
 set transform_fname = talairach.xfm
@@ -200,7 +200,11 @@ if($DoASeg) then
       --mask $outdir/mri/brainmask.mgz --debug)
     echo $cmd | tee -a $LF
     $cmd  | tee -a $LF
-    if($status) exit 1;
+    if($status) then
+      echo "WARNING: could not create average segmentation for $seg ..." | tee -a $LF
+      echo "  ... but continuing" | tee -a $LF
+      continue;
+    endif
     # Extract Seg
     set aseg = $outdir/mri/$seg.mgz
     set cmd = (mri_convert $tmpdir/vote.mgz $aseg --frame 0)
@@ -212,10 +216,7 @@ if($DoASeg) then
     set cmd = (mri_convert $tmpdir/vote.mgz $pseg --frame 1)
     echo $cmd | tee -a $LF
     $cmd  | tee -a $LF
-    if($status) then
-      echo "WARNING: could not create average segmentation for $seg ..." | tee -a $LF
-      echo "  ... but continuing" | tee -a $LF
-    endif
+    if($status) exit 1;
 
  end # Loop over segs
 
