Now uses aparc by default, with options to use a2009s

diff --git a/scripts/make_cortex_label b/scripts/make_cortex_label
--- a/scripts/make_cortex_label
+++ b/scripts/make_cortex_label
@@ -12,8 +12,8 @@
 # Original Author: Douglas Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/12/06 04:57:20 $
-#    $Revision: 1.2 $
+#    $Date: 2010/03/18 21:13:21 $
+#    $Revision: 1.3 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -28,11 +28,19 @@
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION = '$Id: make_cortex_label,v 1.2 2007/12/06 04:57:20 greve Exp $';
+set VERSION = '$Id: make_cortex_label,v 1.3 2010/03/18 21:13:21 greve Exp $';
 set inputargs = ($argv);
 
 set subject   = ();
 set hemilist  = (lh rh)
+
+set parc = aparc;
+set NonCtxLabelList = (unknown corpuscallosum);
+                               
+set CtxLabel = cortex;
+
+#set parc = aparc.a2006s;
+#set NonCtxLabelList = (Medial_wall);
 
 set n = `echo $argv | grep -e -version | wc -l`
 if($n != 0) then
@@ -40,31 +48,14 @@ if($n != 0) then
   exit 0;
 endif
 if($#argv == 0) goto usage_exit;
-
 goto parse_args;
 parse_args_return:
-
 goto check_params;
 check_params_return:
 
-set sdir = $SUBJECTS_DIR/$subject
-if(! -e $sdir) then
-  echo "ERROR: cannto find $sdir"
-  exit 1;
-endif
-
-# Make sure $hemi.cortex.label does not exist
-foreach hemi ($hemilist)
-  set ctxlabel = $sdir/label/$hemi.cortex.label
-  if(-e $ctxlabel) then
-    echo "ERROR: $ctxlabel already exists"
-    exit 1;
-  endif
-end
-
 # Loop thru the hemis
 foreach hemi ($hemilist)
-  set annot = $sdir/label/$hemi.aparc.a2005s.annot
+  set annot = $sdir/label/$hemi.$parc.annot
   if(! -e $annot) then
     echo "ERROR: cannto find $annot"
     exit 1;
@@ -75,19 +66,21 @@ foreach hemi ($hemilist)
   rm -rf $tmpdir
   mkdir -p $tmpdir
 
-  # Unload all of Christophe's labels into tmpdir
+  # Unload all labels into tmpdir
   set cmd = (mri_annotation2label --subject $subject --hemi $hemi \
-    --outdir $tmpdir --annotation aparc.a2005s)
+    --outdir $tmpdir --annotation $parc)
   pwd
   echo $cmd 
   $cmd
   if($status) exit 1;
 
-  # Move medial wall to label dir
-  mv $tmpdir/$hemi.Medial_wall.label $sdir/label
+  # Delete medial wall label
+  foreach lbl ($NonCtxLabelList) 
+    rm -f $tmpdir/$hemi.$lbl.label
+  end
 
   # Create the cortex label with all the remaining labels
-  set ctxlabel = $sdir/label/$hemi.cortex.label
+  set ctxlabel = $sdir/label/$hemi.$CtxLabel.label
   set cmd = (mri_mergelabels -o $ctxlabel -d $tmpdir)
   echo $cmd 
   $cmd
@@ -113,13 +106,36 @@ while( $#argv != 0 )
   switch($flag)
 
     case "--s"
-      if($#argv == 0) goto arg1err;
+      if($#argv < 1) goto arg1err;
       set subject = $argv[1]; shift;
       breaksw
 
     case "--h"
-      if($#argv == 0) goto arg1err;
+      if($#argv < 1) goto arg1err;
       set hemilist = $argv[1]; shift;
+      breaksw
+
+    case "--lh"
+      set hemilist = (lh);
+      breaksw
+
+    case "--rh"
+      set hemilist = (rh);
+      breaksw
+
+    case "--a2009s"
+      set parc = aparc.a2009s;
+      set NonCtxLabelList = (Medial_wall);
+      breaksw
+
+    case "--a2005s"
+      set parc = aparc.a2005s;
+      set NonCtxLabelList = (Medial_wall);
+      breaksw
+
+    case "--o"
+      if($#argv < 1) goto arg2err;
+      set CtxLabel = $argv[1]; shift;
       breaksw
 
     case "--debug":
@@ -140,9 +156,13 @@ goto parse_args_return;
 
 ############--------------##################
 check_params:
-
   if($#subject == 0) then
     echo "ERROR: need subject"
+    exit 1;
+  endif
+  set sdir = $SUBJECTS_DIR/$subject
+  if(! -e $sdir) then
+    echo "ERROR: cannto find $sdir"
     exit 1;
   endif
 goto check_params_return;
@@ -153,7 +173,6 @@ arg1err:
   echo "ERROR: flag $flag requires one argument"
   exit 1
 ############--------------##################
-
 ############--------------##################
 usage_exit:
   echo ""
@@ -161,5 +180,7 @@ usage_exit:
   echo ""
   echo "   --s subject"
   echo "   --h hemi (default is both)"
+  echo "   --a2009s : use aparc.a2009 insteda of aparc"
+  echo "   --o outname : output will be ?h.outname.label (def is $CtxLabel)"
   echo ""
 exit 1;
