Changed so that does not try to access annotations when UseAnnot=0

diff --git a/scripts/make_average_surface b/scripts/make_average_surface
--- a/scripts/make_average_surface
+++ b/scripts/make_average_surface
@@ -10,8 +10,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2015/01/05 22:21:52 $
-#    $Revision: 1.60 $
+#    $Date: 2015/01/05 22:41:26 $
+#    $Revision: 1.61 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -28,7 +28,7 @@
 # uncomment this to increase number of allowable open files to maximum:
 #limit descriptors unlimited
 
-set VERSION = '$Id: make_average_surface,v 1.60 2015/01/05 22:21:52 greve Exp $';
+set VERSION = '$Id: make_average_surface,v 1.61 2015/01/05 22:41:26 greve Exp $';
 setenv FIX_VERTEX_AREA
 
 set PrintHelp = 0;
@@ -246,46 +246,48 @@ foreach hemi ($hemilist)
   cd $sdout/$average_subject
 
   # Create average annot
-  foreach annot (aparc aparc.a2009s)
-    set cmd = (annot2std --o label/$hemi.$annot.annot --$hemi \
-      --f $subjlistfile --t $average_subject --a $annot \
-      --srcsurfreg $sphere_reg --trgsurfreg sphere.reg)
-    if($DoXHemi) set cmd = ($cmd --xhemi)
-    echo $cmd | tee -a $LF
-    $cmd |& tee -a $LF
-    if($status) exit 1
-  end
+  if($UseAnnot) then
+    foreach annot (aparc aparc.a2009s)
+      set cmd = (annot2std --o label/$hemi.$annot.annot --$hemi \
+        --f $subjlistfile --t $average_subject --a $annot \
+        --srcsurfreg $sphere_reg --trgsurfreg sphere.reg)
+      if($DoXHemi) set cmd = ($cmd --xhemi)
+      echo $cmd | tee -a $LF
+      $cmd |& tee -a $LF
+      if($status) exit 1
+    end
 
-  # Create cortex label from Christophe's medial wall
-  set annot = $ddir/label/$hemi.aparc.a2009s.annot
-  if(! -e $annot) then
-    echo "ERROR: cannto find $annot" |& tee -a $LF
-    exit 1;
+    # Create cortex label from Christophe's medial wall
+    set annot = $ddir/label/$hemi.aparc.a2009s.annot
+    if(! -e $annot) then
+      echo "ERROR: cannto find $annot" |& tee -a $LF
+      exit 1;
+    endif
+    # Create tmpdir
+    set tmpdir = $ddir/make_cortex_label.tmp.$$
+    rm -rf $tmpdir
+    mkdir -p $tmpdir
+    # Unload all of Christophe's labels into tmpdir
+    set cmd = (mri_annotation2label --subject $average_subject \
+      --hemi $hemi --outdir $tmpdir --annotation aparc.a2009s)
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+    set MW = $tmpdir/$hemi.Unknown.label
+    if(! -e $MW) set MW = $tmpdir/$hemi.Medial_wall.label
+    if(! -e $MW) then
+      echo "ERROR: cannot find $hemi.Unknown.label or $hemi.Medial_wall.label"
+      exit 1;
+    endif
+    mv $MW $ddir/label/$hemi.Medial_wall.label # Move medial wall out of dir
+    # Create the cortex label with all the remaining labels
+    set ctxlabel = $ddir/label/$hemi.cortex.label
+    set cmd = (mri_mergelabels -o $ctxlabel -d $tmpdir)
+    echo $cmd |& tee -a $LF
+    $cmd |& tee -a $LF
+    if($status) exit 1;
+    rm -rf $tmpdir; # Cleanup
   endif
-  # Create tmpdir
-  set tmpdir = $ddir/make_cortex_label.tmp.$$
-  rm -rf $tmpdir
-  mkdir -p $tmpdir
-  # Unload all of Christophe's labels into tmpdir
-  set cmd = (mri_annotation2label --subject $average_subject \
-    --hemi $hemi --outdir $tmpdir --annotation aparc.a2009s)
-  echo $cmd |& tee -a $LF
-  $cmd |& tee -a $LF
-  if($status) exit 1;
-  set MW = $tmpdir/$hemi.Unknown.label
-  if(! -e $MW) set MW = $tmpdir/$hemi.Medial_wall.label
-  if(! -e $MW) then
-    echo "ERROR: cannot find $hemi.Unknown.label or $hemi.Medial_wall.label"
-    exit 1;
-  endif
-  mv $MW $ddir/label/$hemi.Medial_wall.label # Move medial wall out of dir
-  # Create the cortex label with all the remaining labels
-  set ctxlabel = $ddir/label/$hemi.cortex.label
-  set cmd = (mri_mergelabels -o $ctxlabel -d $tmpdir)
-  echo $cmd |& tee -a $LF
-  $cmd |& tee -a $LF
-  if($status) exit 1;
-  rm -rf $tmpdir; # Cleanup
 
   # Create average surface measures
   foreach meas ($measlist)
