Can now save output to a dir other than SUBJECTS_DIR and optionally link back

diff --git a/scripts/make_average_subject b/scripts/make_average_subject
--- a/scripts/make_average_subject
+++ b/scripts/make_average_subject
@@ -7,27 +7,15 @@
 # --help option will show usage
 #
 
-set VERSION = '$Id: make_average_subject,v 1.5 2006/01/11 18:04:29 greve Exp $'
-
+set VERSION = '$Id: make_average_subject,v 1.6 2006/01/25 23:53:06 greve Exp $'
 set PrintHelp = 0;
+set sdout = ();
+set average_subject = average;
+set DoLink = 1;
+set DoSurfaces = 1;
+set DoVolumes  = 1;
 
-if ( $?SUBJECTS) then
-    set SUBJECTS=($SUBJECTS)
-endif
-if ( $?SUBJECTS_DIR) then
-    set SUBJECTS_DIR=($SUBJECTS_DIR)
-endif
-
-set average_subject=average
-set ddir = ${SUBJECTS_DIR}/${average_subject}
-set transform_fname=""
-set XFORM_FLAG=""
-
-# note: SUBJECTS can be set by --subjects
-# SUBJECTS_DIR can be set by --sdir
-# average_subject can be set by --out
-# transform_fname can be set by --xform (default is no file specified)
-# XFORM_FLAG appends -X to transform_fname if --xform is specified
+set cmdargs = ($argv);
 
 if($#argv == 0) then
   # zero args is allowed only if SUBJECTS env var is declared
@@ -36,25 +24,146 @@ if($#argv == 0) then
   endif
 endif
 
-set flag = $argv[1]; 
-switch($flag)
-  case "--help":
-    set PrintHelp = 1;
-    goto usage_exit;
-    exit 0;
-  case "--version":
-    echo $VERSION
-    exit 0;
- endsw
+goto parse_args;
+parse_args_return:
 
-make_average_surface $argv
-if($status) exit 1;
+goto check_params;
+check_params_return:
 
-make_average_volume $argv
-if($status) exit 1;
+if($DoSurfaces) then
+  set cmd = (make_average_surface $cmdargs)
+  echo $cmd
+  $cmd
+  if($status) exit 1;
+endif
+
+if($DoVolumes) then
+  set cmd = (make_average_volume $cmdargs)
+  echo $cmd
+  $cmd
+  if($status) exit 1;
+endif
+
+if($DoLink) then
+  pushd $sdout > /dev/null
+  set sdoutfulldir = `pwd`;
+  pushd $SUBJECTS_DIR > /dev/null
+  ln -s $sdoutfulldir/$average_subject $average_subject
+  popd > /dev/null
+  popd > /dev/null
+endif
 
 exit 0
 #----------------------------------------------------------#
+############--------------##################
+parse_args:
+set cmdline = ($argv);
+
+while( $#argv != 0 )
+
+  set flag = $argv[1]; shift;
+
+  switch($flag)
+
+    case "--help":
+      set PrintHelp = 1;
+      goto usage_exit;
+      exit 0;
+      breaksw
+
+    case "--version":
+      echo $VERSION
+      exit 0;
+      breaksw
+
+    case "--sd":
+      if ( $#argv == 0) goto arg1err;
+      setenv SUBJECTS_DIR $argv[1]; shift;
+      breaksw
+
+    case "--out":
+      if($#argv < 1) goto arg1err;
+      set average_subject = $argv[1]; shift;
+      breaksw
+
+    case "--sd-out":
+      if ( $#argv == 0) goto arg1err;
+      set sdout = $argv[1]; shift;
+      breaksw
+
+    case "--no-link":
+      set DoLink = 0;
+      breaksw
+
+    case "--no-surf":
+      set DoSurfaces = 0;
+      breaksw
+
+    case "--no-vol":
+      set DoVolumes = 0;
+      breaksw
+
+   case "--debug": 
+   case "--echo":
+      set echo = 1;
+      set verbose = 1
+      breaksw
+
+    default:
+      breaksw
+  endsw
+
+end
+goto parse_args_return;
+
+############--------------##################
+arg1err:
+  echo "ERROR: flag $flag requires one argument"
+  exit 1
+############--------------##################
+
+############--------------##################
+check_params:
+  if (! $?SUBJECTS_DIR) then
+    echo "ERROR: SUBJECTS_DIR is not declared!"
+    echo "  Either set the SUBJECTS_DIR environment variable,"
+    echo "  or declare using --sdir argument, the root directory"
+    echo "  for subject data files."
+    exit 1
+  endif
+  if(! -e $SUBJECTS_DIR ) then
+    echo "ERROR: SUBJECTS_DIR $SUBJECTS_DIR does not exist."
+    exit 1;
+  endif
+  if(! $?FREESURFER_HOME ) then
+    echo "ERROR: environment variable FREESURFER_HOME not set."
+    exit 1;
+  endif
+  if(! -e $FREESURFER_HOME ) then
+    echo "ERROR: FREESURFER_HOME $FREESURFER_HOME does not exist."
+    exit 1;
+  endif
+  if($#sdout == 0) set sdout = $SUBJECTS_DIR
+  set outdir = $sdout/$average_subject
+  if(-e $outdir) then
+    echo "ERROR: $outdir already exists, select a new average subject name"
+    echo "       or delete and rerun" 
+    exit 1;
+  endif
+  if($sdout == $SUBJECTS_DIR) set DoLink = 0;
+  if($DoLink && -e $SUBJECTS_DIR/$average_subject) then
+    echo "ERROR: subject $average_subject already exists in $SUBJECTS_DIR."
+    echo "       Cannot create link. Select a different average subject name"
+    echo "       or delete and re-run."
+    exit 1;
+  endif
+  if(! $DoSurfaces && ! $DoVolumes) then
+    echo "ERROR: you have turned off computing both surfaces and volumes"
+    echo " Nothing to do!"
+    exit 1;
+  endif
+goto check_params_return;
+############--------------##################
 
 ############--------------##################
 usage_exit:
@@ -68,10 +177,12 @@ usage_exit:
   echo ""
   echo "Optional Arguments"
   echo "   --out <average subject name>    : default name is 'average'"
-  echo "   --topdir topdir : put data here and link to SUBJECTS_DIR"
+  echo "   --sd-out sdout : put output under sdout instead of SUBJECTS_DIR"
   echo "   --sdir <SUBJECTS_DIR to use instead of the one in the env>"
   echo "   --sd      : same as --sdir"
   echo "   --xform <transform_fname>       : filename of transform file"
+  echo "   --no-surf : do not make average surfaces"
+  echo "   --no-vol  : do not make average volumes"
   echo ""
   echo "   --help    : short descriptive help"
   echo "   --version : script version info"
