Now handles -ico

diff --git a/scripts/make_average_volume b/scripts/make_average_volume
--- a/scripts/make_average_volume
+++ b/scripts/make_average_volume
@@ -9,9 +9,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: nicks $
-#    $Date: 2008/09/04 20:31:45 $
-#    $Revision: 1.28 $
+#    $Author: greve $
+#    $Date: 2009/09/14 23:29:09 $
+#    $Revision: 1.29 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -29,7 +29,7 @@
 # uncomment this to increase number of allowable open files to maximum:
 #limit descriptors unlimited
 
-set VERSION = '$Id: make_average_volume,v 1.28 2008/09/04 20:31:45 nicks Exp $';
+set VERSION = '$Id: make_average_volume,v 1.29 2009/09/14 23:29:09 greve Exp $';
 
 set PrintHelp = 0;
 set transform_fname = talairach.xfm
@@ -38,6 +38,7 @@ set KeepAllOrig = 0;
 set sdout = ();
 set DoASeg = 1;
 set cleanup = 1;
+set DoXHemi = 0;
 
 set cmdargs = ($argv);
 if($#argv == 0) then
@@ -52,6 +53,19 @@ parse_args_return:
 
 goto check_params;
 check_params_return:
+
+# Include cross-hemi registration
+if($DoXHemi) then
+  set tmp = ();
+  foreach s ($SUBJECTS)
+    if(! -e $SUBJECTS_DIR/$s/xhemi) then
+      echo "ERROR: $s/xhemi does not exist"
+      exit 1;
+    endif
+    set tmp = ($tmp $s $s/xhemi)
+  end
+  set SUBJECTS = ($tmp);
+endif
 
 # This will put the data under $sdout (SUBJECTS_DIR by default)
 set outdir = $sdout/${average_subject}
@@ -68,10 +82,12 @@ set LF = $outdir/scripts/make_average_volume.log
 if(-e $LF) mv $LF $LF.bak
 
 echo Log file is $LF
-date | tee -a $LF
-pwd  | tee -a $LF
+echo ""
 echo $0  | tee -a $LF
 echo $cmdargs  | tee -a $LF
+echo ""
+date | tee -a $LF
+pwd  | tee -a $LF
 echo "setenv SUBJECTS_DIR $SUBJECTS_DIR"  | tee -a $LF
 echo "sdout $sdout" | tee -a $LF
 echo $SUBJECTS >> $LF
@@ -347,6 +363,7 @@ while( $#argv != 0 )
     case "--surfreg":
     case "--surf-reg":
     case "--surf_reg":
+    case "--ico":
       if ( $getting_subjects ) then
         set getting_subjects = 0;
         # got em all, from --subjects variable arg loop
@@ -373,6 +390,14 @@ while( $#argv != 0 )
 
     case "--no-aseg":
       set DoASeg = 0;
+      if ( $getting_subjects ) then
+        set getting_subjects = 0;
+        # got em all, from --subjects variable arg loop
+      endif
+      breaksw
+
+    case "--xhemi":
+      set DoXHemi = 1;
       if ( $getting_subjects ) then
         set getting_subjects = 0;
         # got em all, from --subjects variable arg loop
