Now creates annotations

diff --git a/scripts/make_average_surface b/scripts/make_average_surface
--- a/scripts/make_average_surface
+++ b/scripts/make_average_surface
@@ -8,7 +8,7 @@
 # --help option will show usage
 #
 
-set VERSION = '$Id: make_average_surface,v 1.24 2006/02/13 23:52:33 greve Exp $';
+set VERSION = '$Id: make_average_surface,v 1.25 2006/02/16 18:30:50 greve Exp $';
 
 set PrintHelp = 0;
 set sdout = ();
@@ -83,6 +83,35 @@ foreach hemi (rh lh)
   echo ""  | tee -a $LF
 
   cd $sdout/${average_subject}
+
+  #--------------------------------------------------------------
+  echo "#@# Making $hemi annotation ---------------------"  | tee -a $LF
+  date  | tee -a $LF
+  set GCS     = curvature.buckner40.filled.desikan_killiany.gcs
+  set CPAtlas = $hemi.$GCS
+  set annot = label/$hemi.aparc.annot
+  set cmd = (mris_ca_label -ml-annot $CPAtlas $ico_no $annot)
+  echo $cmd  | tee -a $LF
+  pwd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) then
+    echo "ERROR: mris_ca_label failed"  | tee -a $LF
+    exit 1;
+  endif
+
+  set GCS     = atlas2005_simple.gcs
+  set CPAtlas = $hemi.$GCS
+  set annot   = label/$hemi.aparc.a2005s.annot
+  set cmd = (mris_ca_label -ml-annot $CPAtlas $ico_no $annot)
+  echo $cmd  | tee -a $LF
+  pwd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) then
+    echo "ERROR: mris_ca_label failed"  | tee -a $LF
+    exit 1;
+  endif
+
+  #--------------------------------------------------------------
   foreach s (orig white pial inflated)
     echo "#@# Making average $hemi.$s surface ---------------------"  | tee -a $LF
     date  | tee -a $LF
@@ -107,6 +136,7 @@ foreach hemi (rh lh)
   echo "" | tee -a $LF
   echo "" | tee -a $LF
 
+  #--------------------------------------------------------------
   foreach c (sulc curv thickness)
     echo "#@# Making average $hemi.$c ----------------------" | tee -a $LF
     date
@@ -131,6 +161,7 @@ foreach hemi (rh lh)
   echo "" | tee -a $LF
   echo ""
 
+  #--------------------------------------------------------------
   echo "#@# Smoothing, inflating, etc $hemi ----------------" | tee -a $LF
   cd $sdout/${average_subject}/surf      
   echo "" | tee -a $LF
@@ -284,6 +315,7 @@ while( $#argv != 0 )
     case "--no-link":
     case "--no-surf":
     case "--no-vol":
+    case "--force":
       if ( $getting_subjects ) then
         set getting_subjects = 0;
         # got em all, from --subjects variable arg loop
