Better error msgs

diff --git a/scripts/make_average_subject b/scripts/make_average_subject
--- a/scripts/make_average_subject
+++ b/scripts/make_average_subject
@@ -7,7 +7,7 @@
 # --help option will show usage
 #
 
-set VERSION = '$Id: make_average_subject,v 1.7 2006/02/16 18:30:23 greve Exp $'
+set VERSION = '$Id: make_average_subject,v 1.8 2006/05/02 18:30:35 greve Exp $'
 set PrintHelp = 0;
 set sdout = ();
 set average_subject = average;
@@ -36,14 +36,20 @@ if($DoSurfaces) then
   set cmd = (make_average_surface $cmdargs)
   echo $cmd
   $cmd
-  if($status) exit 1;
+  if($status) then
+    echo "ERROR: make_average_surface"
+    exit 1;
+  endif
 endif
 
 if($DoVolumes) then
   set cmd = (make_average_volume $cmdargs)
   echo $cmd
   $cmd
-  if($status) exit 1;
+  if($status) then
+    echo "ERROR: make_average_volume"
+    exit 1;
+  endif
 endif
 
 if($DoLink) then
