Now makes cortex labels. Now explicilty uses ico7.

diff --git a/scripts/make_average_surface b/scripts/make_average_surface
--- a/scripts/make_average_surface
+++ b/scripts/make_average_surface
@@ -10,8 +10,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/08/13 17:31:47 $
-#    $Revision: 1.38 $
+#    $Date: 2007/08/13 20:54:29 $
+#    $Revision: 1.39 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -29,7 +29,7 @@
 # increase number of allowable open files to maximum:
 limit descriptors unlimited
 
-set VERSION = '$Id: make_average_surface,v 1.38 2007/08/13 17:31:47 greve Exp $';
+set VERSION = '$Id: make_average_surface,v 1.39 2007/08/13 20:54:29 greve Exp $';
 setenv FIX_VERTEX_AREA
 
 set PrintHelp = 0;
@@ -89,7 +89,7 @@ echo $VERSION | tee -a $LF
 date | tee -a $LF
 pwd | tee -a $LF
 echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
-echo "output sdir is $sdout" | tee -a $LF
+echo "output ddir is $sdout" | tee -a $LF
 id | tee -a $LF
 
 #
@@ -129,8 +129,6 @@ foreach hemi (lh rh)
   echo ""  | tee -a $LF
 
   cd $sdout/${average_subject}
-  cp ${FREESURFER_HOME}/average/surf/${hemi}.sphere.reg ./${hemi}.${sphere_reg}
-
 
   #--------------------------------------------------------------
   echo "#@# Making $hemi annotation ---------------------"  | tee -a $LF
@@ -179,6 +177,9 @@ foreach hemi (lh rh)
     echo ""  | tee -a $LF
     echo ""  | tee -a $LF
   end
+  # mris_make_average_surface creates its own sphere.reg, so copy over it with ico7
+  mv surf/${hemi}.${sphere_reg} surf/${hemi}.${sphere_reg}.avg
+  cp ${FREESURFER_HOME}/average/surf/${hemi}.sphere.reg surf/${hemi}.${sphere_reg}
   echo "---------------------------------------------------"  | tee -a $LF
   echo "" | tee -a $LF
   echo "" | tee -a $LF
@@ -235,15 +236,42 @@ foreach hemi (lh rh)
   echo "" | tee -a $LF
   if($UseSymLink) then
     ln -s -f ${hemi}.${sphere_reg} ${hemi}.sphere
-    ln -s -f ${hemi}.orig_avg ${hemi}.orig
+    ln -s -f ${hemi}.orig_avg  ${hemi}.orig
     ln -s -f ${hemi}.white_avg ${hemi}.white
-    ln -s -f ${hemi}.pial_avg ${hemi}.pial
+    ln -s -f ${hemi}.pial_avg  ${hemi}.pial
   else
     cp -f ${hemi}.${sphere_reg} ${hemi}.sphere
-    cp -f ${hemi}.orig_avg ${hemi}.orig
+    cp -f ${hemi}.orig_avg  ${hemi}.orig
     cp -f ${hemi}.white_avg ${hemi}.white
-    cp -f ${hemi}.pial_avg ${hemi}.pial
+    cp -f ${hemi}.pial_avg  ${hemi}.pial
   endif
+
+  # -----------------------------------------------------
+  # Create cortex label from Christophe's medial wall
+  set annot = $ddir/label/$hemi.aparc.a2005s.annot
+  if(! -e $annot) then
+    echo "ERROR: cannto find $annot" |& tee -a $LF
+    exit 1;
+  endif
+  # Create tmpdir
+  set tmpdir = $ddir/make_cortex_label.tmp.$$
+  rm -rf $tmpdir
+  mkdir -p $tmpdir
+  # Unload all of Christophe's labels into tmpdir
+  set cmd = (mri_annotation2label --subject $average_subject \
+    --hemi $hemi --outdir $tmpdir --annotation aparc.a2005s)
+  echo $cmd |& tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) exit 1;
+  mv $tmpdir/$hemi.Medial_wall.label $ddir/label; # Move medial wall
+  # Create the cortex label with all the remaining labels
+  set ctxlabel = $ddir/label/$hemi.cortex.label
+  set cmd = (mri_mergelabels -o $ctxlabel -d $tmpdir)
+  echo $cmd |& tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) exit 1;
+  rm -rf $tmpdir; # Cleanup
+  # -------- done creating cortex label -----------------
 
 end
 
