mideface. Added xopts, samseg json, fast samseeg, and ormask

diff --git a/scripts/mideface b/scripts/mideface
--- a/scripts/mideface
+++ b/scripts/mideface
@@ -27,7 +27,7 @@ set FillConstIn = ()
 set FillConstOut = ()
 set DoEars = 1;
 set DoForehead = 0;
-set DoBackOfHead = 1
+set DoBackOfHead = 0
 set DoPics = 0
 set SubjCode = ()
 set PicAnnot = ()
@@ -37,6 +37,10 @@ set RipplePeriod = 30
 set dwatermark = 5;
 set atlasdir = ()
 set imconvert = /usr/bin/convert
+set XOptsFile = ()
+set SamsegJson = ()
+set SamsegFast = 0
+set UseOrMask = 0
 
 set tmpdir = ();
 set cleanup = 1;
@@ -64,7 +68,6 @@ parse_args_return:
 goto check_params;
 check_params_return:
 
-if($#atlasdir == 0) set atlasdir = $FREESURFER/average/mideface-atlas
 set ctab = $atlasdir/deface.ctab
 set templatesurf = $atlasdir/average.head.dec44.us7.remesh3.ripple.surf
 set templatevol = $atlasdir/average.head.mgz
@@ -135,6 +138,8 @@ echo "UseXvfb $UseXvfb" | tee -a $LF
 set runxvfb = fsxvfb
 if(! $UseXvfb) set runxvfb = ()
 
+if($#XOptsFile) cp $XOptsFile $tmpdir
+
 #========================================================
 # Register to samseg atlas, maybe run samseg for xmask
 set samsegdir = $tmpdir/samseg
@@ -144,6 +149,8 @@ if($DoSamSegXMask == 0) then
   set ud = (`UpdateNeeded $samseglta $invol`)
   if($ud || $ForceUpdate) then
     set cmd = (run_samseg -i $invol -o $tmpdir/samseg --reg-only --threads $threads)
+    set xopts = `fsr-getxopts run_samseg $XOptsFile`;
+    set cmd = ($cmd $xopts);
     echo $cmd | tee -a $LF
     fs_time $cmd |& tee -a $LF
     if($status) goto error_exit
@@ -151,10 +158,14 @@ if($DoSamSegXMask == 0) then
 else
   # Running full samseg may require 14GB of mem and add ~20min to run time
   # In theory, samseg could be used instead of seghead
+  if($#SamsegJson) cp $SamsegJson $tmpdir
   set samseg = $samsegdir/seg.mgz
   set ud = (`UpdateNeeded $samseg $invol`)
   if($ud || $ForceUpdate) then
     set cmd = (samseg --i $invol --o $samsegdir --threads $threads --block-coordinate-descent)
+    if($#SamsegJson) set cmd = ($cmd --options $SamsegJson)
+    set xopts = `fsr-getxopts samseg $XOptsFile`;
+    set cmd = ($cmd $xopts);
     echo $cmd | tee -a $LF
     fs_time $cmd |& tee -a $LF
     if($status) goto error_exit
@@ -162,6 +173,9 @@ else
   set seg = $samseg
   set segidlist = (2 3 7 8 16 24 41 42 46 47 165) # 165=skull
   if($XEyeBalls) set segidlist = ($segidlist  259) # these are the eyeballs
+  # Add subcort because it can help in the 2nd mkheadsurf
+  set segidlist = ($segidlist  4  5 10 11 12 13 17 18 26 28 30 31 14 15 16 77 85)
+  set segidlist = ($segidlist 43 44 49 50 51 52 53 54 58 60 62 63)
 endif
 
 if($DoSynthSegXMask) then
@@ -171,6 +185,8 @@ if($DoSynthSegXMask) then
   set ud = (`UpdateNeeded $synthseg $invol`)
   if($ud || $ForceUpdate) then
     set cmd = (synthseg --i $invol --o $synthseg --threads $threads)
+    set xopts = `fsr-getxopts synthseg $XOptsFile`;
+    set cmd = ($cmd $xopts);
     echo $cmd | tee -a $LF
     fs_time $cmd |& tee -a $LF
     if($status) goto error_exit
@@ -182,15 +198,18 @@ if($DoSynthSegXMask) then
   endif
   set seg = $synthseg
   set segidlist = (2 3 7 8 16 41 42 46 47)
+  # Add subcort because it can help in the 2nd mkheadsurf
+  set segidlist = ($segidlist  4  5 10 11 12 13 17 18 26 28 30 31 14 15 16 77 85)
+  set segidlist = ($segidlist 43 44 49 50 51 52 53 54 58 60 62 63)
 endif
 
 if($DoSynthSegXMask || $DoSamSegXMask) then
+  set segdil = $tmpdir/seg.bin.dil.mgz
   # Binarize, and maybe dilate, the synthseg output. A subset of cerebral segids
   # are selected to assure that only cerebral structures are excluded. At 
   # the titme of writing, synthseg only produces cerebral structures, so it is
   # not an issue, but at some point it might start segmenting extracerebral.
   # Probably the only important seg is cortex, maybe skull and eyes.
-  set segdil = $tmpdir/seg.bin.dil.mgz
   set ud = (`UpdateNeeded $segdil $seg`)
   if($ud || $ForceUpdate) then
     set cmd = (mri_binarize --i $seg --match $segidlist --o $segdil)
@@ -237,6 +256,8 @@ if($DoBBR) then
       --no-cortex-label --label $bbrface --init-reg $input2atlaslta --tolf 1e-5 \
       --reg $bbrlta --no-pass1 --$BBRDoF --lh-only  --no-brute2 --include-zero-voxels \
       --surf $templatesurf --target-volume $templatevol)
+    set xopts = `fsr-getxopts bbregister $XOptsFile`;
+    set cmd = ($cmd $xopts);
     echo $cmd | tee -a $LF
     $cmd |& tee -a $LF
     if($status) goto error_exit
@@ -265,6 +286,11 @@ set ud = (`UpdateNeeded $headsurf $invol`)
 if($ud || $ForceUpdate) then
   set cmd = (mkheadsurf -i $invol -o $headmask -surf $headsurf \
     -rescale -no-inflate -fill-holes-islands -mc -no-curv)
+  # Adding samseg here makes the whole thing much more robust
+  # because samseg is bascially provides a head mask
+  if($UseOrMask && $DoSamSegXMask) set cmd = ($cmd -or-mask $samsegdir/seg.mgz)
+  set xopts = `fsr-getxopts mkheadsurf $XOptsFile`;
+  set cmd = ($cmd $xopts);
   echo $cmd | tee -a $LF
   fs_time $cmd |& tee -a $LF
   if($status) goto error_exit
@@ -291,8 +317,9 @@ if($ud || $ForceUpdate) then
   if($DoEars)       set cmd = ($cmd  --l $earleft  2 3 --l $earright 2 3)
   if($DoForehead)   set cmd = ($cmd  --l $forehead 2 3);
   if($DoBackOfHead) set cmd = ($cmd  --l $backofhead 2 3);
-
   if($#xmask) set cmd = ($cmd --xmask $xmask)
+  set xopts = `fsr-getxopts mri_defacer $XOptsFile`;
+  set cmd = ($cmd $xopts);
   echo $cmd | tee -a $LF
   fs_time $cmd |& tee -a $LF
   if($status) goto error_exit
@@ -319,7 +346,11 @@ set postheadsurf = $tmpdir/head.defaced.surf
 if($DoPostHeadSurf) then
   set ud = (`UpdateNeeded $posthead $outvol`)
   if($ud || $ForceUpdate) then
-    set cmd = (mkheadsurf -i $outvol -o $posthead -surf $postheadsurf -rescale -no-inflate -fill-holes-islands -mc -no-curv)
+    set xopts = `fsr-getxopts mkheadsurf $XOptsFile`;
+    set cmd = (mkheadsurf -i $outvol -o $posthead -surf $postheadsurf \
+      -rescale -no-inflate -fill-holes-islands -mc -no-curv $xopts)
+    # can't do samseg here, duh, but can use xmask if there
+    if($UseOrMask && $#xmask) set cmd = ($cmd -or-mask $xmask)
     echo $cmd | tee -a $LF
     fs_time $cmd |& tee -a $LF
     if($status) goto error_exit
@@ -327,13 +358,23 @@ if($DoPostHeadSurf) then
 endif
 
 # Take some pictures for QA
-set facepic = $tmpdir/face-before.png
-set postfacepic = $tmpdir/face-after.png
+if($#SubjCode == 0) then
+  set facepic = $tmpdir/face-before.png
+  set postfacepic = $tmpdir/face-after.png
+  set gif = $tmpdir/face-before+after.gif
+else
+  # Putting SubjCode in the name makes it easier for a slide show
+  set facepic = $tmpdir/$SubjCode.face-before.png
+  set postfacepic = $tmpdir/$SubjCode.face-after.png
+  set gif = $tmpdir/$SubjCode.face-before+after.gif
+endif
 if($DoPics) then
   set ud = `UpdateNeeded $facepic $headsurf $fmoverlay`
   if($ud || $ForceUpdate) then
     set cmd = (freeview -f ${headsurf}:affinexfm=${input2atlaslta}:overlay=${fmoverlay}:"overlay_threshold=.01,.011,.5"\
        --hide-3d-slices -viewport 3d -cam Azimuth -90 -ss $facepic --quit)
+    set xopts = `fsr-getxopts freeview-before $XOptsFile`;
+    set cmd = ($cmd $xopts);
     echo $cmd | tee -a $LF
     $runxvfb $cmd |& tee -a $LF
     if($status) goto error_exit
@@ -348,6 +389,8 @@ if($DoPics) then
     if($ud || $ForceUpdate) then
       set cmd = (freeview -f ${postheadsurf}:affinexfm=$input2atlaslta --hide-3d-slices \
         -viewport 3d -cam Azimuth -90 -ss $postfacepic --quit)
+      set xopts = `fsr-getxopts freeview-after $XOptsFile`;
+      set cmd = ($cmd $xopts);
       echo $cmd | tee -a $LF
       $runxvfb $cmd |& tee -a $LF
       if($status) goto error_exit
@@ -360,7 +403,6 @@ if($DoPics) then
   endif
   if(-e $facepic && -e $postfacepic && -e $imconvert) then
     # This is make an animation
-    set gif = $tmpdir/face-before+after.gif
     set ud = `UpdateNeeded $gif $facepic $postfacepic`
     if($ud || $ForceUpdate) then
       set cmd = ($imconvert -loop 0 -delay 60 $facepic $postfacepic $gif)
@@ -370,7 +412,6 @@ if($DoPics) then
     endif
   endif
 endif
-
 
 # Make a command line for viewing
 set cmd = (fsvglrun freeview $invol $outvol --hide-3d-slices -viewport 3d \
@@ -502,6 +543,22 @@ while( $#argv != 0 )
       set XEyeBalls = 0;
       breaksw
 
+    case "--samseg-json":
+      if( $#argv < 1) goto arg1err;
+      set SamsegJson = $argv[1]; shift;
+      breaksw
+    case "--no-samseg-json":
+      set SamsegJson = ()
+      breaksw
+    case "--samseg-fast":
+      set DoSamSegXMask = 1
+      set nSegDil = 1
+      set SamsegFast = 1;
+      breaksw
+    case "--no-samseg-fast":
+      set SamsegFast = 0;
+      breaksw
+
     case "--atlas":
       if($#argv < 1) goto arg1err;
       set atlasdir = $argv[1]; shift;
@@ -614,6 +671,21 @@ while( $#argv != 0 )
       set DoRipple = 0
       breaksw
 
+    case "--expert":
+      if( $#argv < 1) goto arg1err;
+      set XOptsFile = $argv[1]; shift;
+      fsr-checkxopts $XOptsFile
+      if($status) goto error_exit;
+      set XOptsFile = `getfullpath $XOptsFile`
+      breaksw
+
+    case "--or-mask"
+      set UseOrMask = 1;
+      breaksw
+    case "--no-or-mask"
+      set UseOrMask = 0;
+      breaksw
+
     case "--log":
       if($#argv < 1) goto arg1err;
       set LF = $argv[1]; shift;
@@ -668,6 +740,12 @@ if(! -e $invol) then
   exit 1;
 endif
 
+if($#atlasdir == 0) set atlasdir = $FREESURFER/average/mideface-atlas
+if(! -e $atlasdir) then
+  echo "ERROR: cannot find atlasdir $atlasdir"
+  exit 1
+endif
+
 if($#outdir) then
   if($#outvol == 0) set outvol = $outdir/defaced.mgz
   if($#tmpdir == 0) set tmpdir = $outdir
@@ -696,6 +774,12 @@ if($DoSynthSegXMask && $DoSamSegXMask) then
   exit 1
 endif
 
+if($SamsegFast && $#SamsegJson) then
+  echo "ERROR: cannot spec --samseg-fast and --samseg-json"
+  exit 1
+endif
+if($SamsegFast) set SamsegJson = $atlasdir/samseg-options.json
+
 goto check_params_return;
 ############--------------##################
 
@@ -722,12 +806,14 @@ usage_exit:
   echo " --facemask facemask"
   echo " --odir outputdir (turns on PostHeadSurf)"
   echo " --xmask xmask (exclusion mask)"
-  echo " --xmask-samseg ndilations : segment input using samseg (14GB, +~20min)"
+  echo " --xmask-samseg ndilations : segment input using samseg (14GB, +~20-40min)"
+  echo "   --samseg-json json: configure samseg"
+  echo " --samseg-fast : "
   echo " --xmask-synthseg ndilations : segment input using synthseg (35GB, +~20min)"
   echo " --fill-const constIn constOut"
   echo " --fill-zero"
   echo " --no-ears : do not include ears in the defacing"
-  echo " --no-back-of-head : do not include back of head in the defacing"
+  echo " --back-of-head : include back of head in the defacing"
   echo " --forehead : include forehead in the defacing (risks removing brain)"
   echo " --pics : take pics (--no-pics)"
   echo " --code codename : embed codename in pics"
@@ -736,6 +822,9 @@ usage_exit:
   echo " --threads nthreads"
   echo " --force : force reprocessing (not applicable if --odir has not been used)"
   echo " --atlas atlasdir"
+  echo " --expert xopts"
+  echo ""
+  echo "To apply midfacer output to a second volume"
   echo " --apply vol facemask reg output : apply to another volume (use regheader if no reg needed)"
   echo ""
 
