actually excludes properly now. also added more options for not tarring certain parts of the distro- see usage for info.

diff --git a/scripts/mkfsdist b/scripts/mkfsdist
--- a/scripts/mkfsdist
+++ b/scripts/mkfsdist
@@ -5,18 +5,22 @@
 # editing.
 #
 # mkfsdist
-# $Id: mkfsdist,v 1.10 2003/03/13 18:50:32 kteich Exp $
+# $Id: mkfsdist,v 1.11 2003/03/21 21:42:06 kteich Exp $
 #
 # Usage: mkfsdist targetdir
 #
 # Purpose: creates a FreeSurfer distribution in the directory 
 # specified on the command-line. The distribution can be installed 
-# by following the instructions in freesurfer_alpha/INSTALL.
+# by following the instructions in freesurfer/INSTALL.
+#
+# Note that the source directory can be any freesurfer installation,
+# but will probably be freesurfer_alpha or freesurfer_dev. Here we
+# will just use 'freesurfer' to refer to the destination directory.
 #
 # These files are created in the target directory:
-#  INSTALL -- installation instructions (copied from freesurfer_alpha);
-#  license.freesurfer -- license agreement (copied from freesurfer_alpha);
-#  fsa.tar.gz -- the freesurfer_alpha tree
+#  INSTALL -- installation instructions (copied from source dir);
+#  license.freesurfer -- license agreement (copied from source dir);
+#  FreeSurfer-PLATOFORM.tar.gz -- the freesurfer tree
 #  minc.tar.gz -- ~inverse/minc (for running functional autoreg)
 #  talairach.tar.gz -- $SUBJECTS_DIR/talairach (MNI 305)
 #  bert.001.tar.gz -- anatomical tutorial data, run 1
@@ -24,11 +28,11 @@
 #  bert.003.tar.gz -- anatomical tutorial data, run 3
 #  average7.tar.gz -- contains average labels for checking spherical morph
 #
-# Symbolic Links in freesurfer_alpha:
+# Symbolic Links in freesurfer:
 # 
 #  It does not follow symbolic links, so any symbolic link
-#  in freesurfer_alpha must have a pointer relative to someplace in the
-#  freesurfer_alpha tree.  
+#  in the source dir must have a pointer relative to someplace in the
+#  source dir tree.  
 #
 # Dynamic and Statically Linked Programs
 #
@@ -38,10 +42,10 @@
 #  with a .dynamic extension. The process that does this is fairly
 #  involved. See comments in the code for more detail.
 #
-# Excluding files and directories from freesurfer_alpha:
+# Excluding files and directories from freesurfer:
 # 
-#  Files and directories within the freesurfer_alpha tree can be targeted
-#  for exclusion by entering them into freesurfer_alpha/tar-exclude. This
+#  Files and directories within the freesurfer tree can be targeted
+#  for exclusion by entering them into freesurfer/tar-exclude. This
 #  is useful for excluding the license file (.license) as well as other
 #  files that just take up space. When adding items to the exclude file,
 #  put only one name on each line and make sure there are no trailing
@@ -50,7 +54,7 @@
 #  files found in tar-exclude-more and tar-exclude-gca.
 #
 # 
-set VERSION = '$Id: mkfsdist,v 1.10 2003/03/13 18:50:32 kteich Exp $';
+set VERSION = '$Id: mkfsdist,v 1.11 2003/03/21 21:42:06 kteich Exp $';
 
 # To include the autoseg in the distribution set environment varible
 # KEEPAUTOSEG to 1 before running mkfsdist (ie, setenv KEEPAUTOSEG 1)
@@ -71,14 +75,25 @@ set AVERAGE7_DIR = $SUBJECTS_DIR/average7
 set BERT_FUNC_DIR = /space/sake/5/tutorial/JUL01/bert-functional
 
 #------------------------------------------------------#
-if($#argv != 3) then
-  echo "USAGE: mkfsdist sourcedir targetdir platform=[Linux|Darwin]"
+if($#argv < 3) then
+  echo "USAGE: mkfsdist sourcedir targetdir platform=[Linux|Darwin] [options]"
   echo ""
   echo "   sourcedir: usually freesurfer_alpha or freesurfer_dev"
   echo "   targetdir: dir in which to create archive"
   echo "    platform: platform for whose binaries will be included"
   echo ""
-  echo "Ex: mkfsdist $FREESURFER_HOME ~/work Linux"
+  echo "   options include:"
+  echo "     --no-compress, --compress: create or don't create a gzipped tarfile (default yes)"
+  echo "   the following specify which components to include:"
+  echo "     --no-auto-seg, --auto-seg (default no)"
+  echo "     --no-average, --average (default yes)"
+  echo "     --no-minc, --minc (default yes)"
+  echo "     --no-talairach, --talairach (default yes)"
+  echo "     --no-bert-raw, --bert-raw (default yes)"
+  echo "     --no-bert-recon, --bert-recon (default yes)"
+  echo "     --no-bert-func, --bert-func (default yes)"
+  echo ""
+  echo "Ex: mkfsdist ~inverse/freesurfer_alpha ~/work Linux"
   echo ""
   exit 1;
 endif
@@ -86,6 +101,44 @@ endif
 set SOURCE_DIR = $argv[1];
 set TARGET_DIR = $argv[2];
 set PLATFORM = $argv[3];
+
+set COMPRESS   = 1
+set AUTO_SEG   = 0
+set AVERAGE    = 1
+set MINC       = 1
+set TALAIRACH  = 1
+set BERT_RAW   = 1
+set BERT_RECON = 1
+set BERT_FUNC  = 1
+foreach option ($argv)
+  switch ("$option")
+    case "--no-compress":
+      set COMPRESS = 0
+      breaksw
+    case "--auto-seg":
+      set AUTO_SEG = 1
+      breaksw
+    case "--no-average":
+      set AVERAGE = 0
+      breaksw
+    case "--no-minc":
+      set MINC = 0
+      breaksw
+    case "--no-talairach":
+      set TALAIRACH = 0
+      breaksw
+    case "--no-bert-raw":
+      set BERT_RAW = 0
+      breaksw
+    case "--no-bert-recon":
+      set BERT_RECON = 0
+      breaksw
+    case "--no-bert-func":
+      set BERT_FUNC = 0
+      breaksw
+  endsw
+end
+
 
 # Check the platform argument #
 if( "$PLATFORM" != "Linux" && "$PLATFORM" != "Darwin" ) then
@@ -105,44 +158,48 @@ if(! -e $SOURCE_DIR) then
 endif
 
 # Check that test subject runs are there #
-if(! -e $BERT_ANAT_DIR) then
+if( ( $BERT_RAW || $BERT_RECON ) && ! -e $BERT_ANAT_DIR) then
   echo "ERROR: cannot find $BERT_ANAT_DIR"
   exit 1;
 endif
-foreach run (1 2 3)
-  set rundir = `printf %s/%03d $BERT_ORIG_DIR $run`;
-  if( ! -e $rundir ) then
-    echo "ERROR: cannot find $rundir"
-    exit 1
-  endif
-end
 
-if(! -e $BERT_FUNC_DIR) then
+if( $BERT_RAW ) then
+  foreach run (1 2 3)
+    set rundir = `printf %s/%03d $BERT_ORIG_DIR $run`;
+    if( ! -e $rundir ) then
+      echo "ERROR: cannot find $rundir"
+      exit 1
+    endif
+  end
+endif
+
+if( $BERT_FUNC && ! -e $BERT_FUNC_DIR) then
   echo "ERROR: cannot find $BERT_FUNC_DIR"
   exit 1;
 endif
 
 # Check that the average7 is there #
-if(! -e $AVERAGE7_DIR) then
+if( $AVERAGE && ! -e $AVERAGE7_DIR) then
   echo "ERROR: cannot find $AVERAGE7_DIR"
   exit 1;
 endif
 
 # Check that the talairach subject is there #
-if(! -e $SUBJECTS_DIR/talairach) then
+if( $TALAIRACH && ! -e $SUBJECTS_DIR/talairach) then
   echo "ERROR: cannot find $$SUBJECTS_DIR/talairach"
   exit 1;
 endif
 
-echo " "
-echo "Creating FreeSurfer Distribution in $TARGET_DIR"
-echo " "
-
 # This is where the MNI stuff lives #
-if(! -e /space/lyon/9/pubsw) then
+if( $MINC && ! -e /space/lyon/9/pubsw) then
   echo "ERROR: cannot find /space/lyon/9/pubsw"
   exit 1;
 endif
+
+
+echo " "
+echo "Creating FreeSurfer Distribution in $TARGET_DIR"
+echo " "
 
 # Create the target directory #
 mkdir -p $TARGET_DIR
@@ -172,71 +229,94 @@ set LF = $TARGET_DIR/mkfsdist.log
 if(-e $LF) mv $LF $LF.old
 echo "Log file is $LF"
 
-echo "Log file for FreeSurfer (alpha) distribution creation" >> $LF
+echo "Log file for FreeSurfer distribution creation" >> $LF
 echo $VERSION  >> $LF
 echo "$0"    >> $LF
 echo "$argv" >> $LF
 date >> $LF
 
 #----- Tar up average7 --------#
-echo "--------------------------------------------" | tee -a $LF
-date | tee -a $LF  
-pushd $AVERAGE7_DIR > /dev/null
-cd ..
-echo "Tarring average7 data" | tee -a $LF
-set TF = $TARGET_DIR/average7.tar.gz
-rm -f $TF
-tar cvz -f $TF \
-  ./average7/mri \
-  ./average7/label/??-avg_*.label \
-  ./average7/surf/?h.avg_curv \
-  ./average7/surf/?h.avg_sulc \
-  ./average7/surf/?h.curv \
-  ./average7/surf/?h.inflated \
-  ./average7/surf/?h.orig \
-  ./average7/surf/?h.pial \
-  ./average7/surf/?h.smoothwm \
-  ./average7/surf/?h.sphere \
-  ./average7/surf/?h.sphere.reg \
-  ./average7/surf/lh.rh.sphere.reg \
-  ./average7/surf/?h.sulc >> $LF
-date | tee -a $LF  
+if ( $AVERAGE ) then
 
-# Create the exclude file. Basically we want to exclude
-# platform-specific binary and lib directories and any backup or temp
-# files (i.e. README~, tkmedit.031402)
-set EXCLUDE_FILE = /tmp/exclude
-rm -f $EXCLUDE_FILE
-if( "$PLATFORM" != "Linux" ) then
-  find $SOURCE_DIR | grep Linux >> $EXCLUDE_FILE
-endif
-if( "$PLATFORM" != "Darwin" ) then
-  find $SOURCE_DIR | grep Darwin >> $EXCLUDE_FILE
-endif
-find $SOURCE_DIR | grep IRIX >> $EXCLUDE_FILE
-find $SOURCE_DIR | grep SunOS >> $EXCLUDE_FILE
-find $SOURCE_DIR | grep Solaris >> $EXCLUDE_FILE
-find $SOURCE_DIR -name \*.\*03 >> $EXCLUDE_FILE
-find $SOURCE_DIR -name \*.~ >> $EXCLUDE_FILE
+  echo "--------------------------------------------" | tee -a $LF
+  date | tee -a $LF  
+  pushd $AVERAGE7_DIR > /dev/null
+  cd ..
+  echo "Tarring average7 data" | tee -a $LF
+  set TF = $TARGET_DIR/average7.tar.gz
+  rm -f $TF
+  tar cvz -f $TF \
+    ./average7/mri \
+    ./average7/label/??-avg_*.label \
+    ./average7/surf/?h.avg_curv \
+    ./average7/surf/?h.avg_sulc \
+    ./average7/surf/?h.curv \
+    ./average7/surf/?h.inflated \
+    ./average7/surf/?h.orig \
+    ./average7/surf/?h.pial \
+    ./average7/surf/?h.smoothwm \
+    ./average7/surf/?h.sphere \
+    ./average7/surf/?h.sphere.reg \
+    ./average7/surf/lh.rh.sphere.reg \
+    ./average7/surf/?h.sulc >> $LF
+  date | tee -a $LF  
+  
+endif 
 
 # ---- Tar up source dir ------- #
 pushd $SOURCE_DIR > /dev/null
 cd ..
+
+set SOURCE_DIR_REL = `basename $SOURCE_DIR`
+
+# Create the exclude file for the freesurfer source dir. Basically we
+# want to exclude platform-specific binary and lib directories and any
+# backup or temp files (i.e. README~, tkmedit.031402)
+set EXCLUDE_FILE = /tmp/exclude
+rm -f $EXCLUDE_FILE
+if( "$PLATFORM" != "Linux" ) then
+  find $SOURCE_DIR_REL | grep Linux >> $EXCLUDE_FILE
+endif
+if( "$PLATFORM" != "Darwin" ) then
+  find $SOURCE_DIR_REL | grep Darwin >> $EXCLUDE_FILE
+endif
+find $SOURCE_DIR_REL | grep Linux2 >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL | grep IRIX >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL | grep SunOS >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL | grep Solaris >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name \*.03\* >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name \*.02\* >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name \*.01\* >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name \*~ >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name \#\*\# >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name \*.bu >> $EXCLUDE_FILE
+find $SOURCE_DIR_REL -name tar-exclude-more >> $EXCLUDE_FILE
+
+
 echo "--------------------------------------------" | tee -a $LF
 echo "Tarring $SOURCE_DIR" | tee -a $LF
 date | tee -a $LF
 set TF = $TARGET_DIR/FreeSurfer-${PLATFORM}.tar
 rm -f $TF
-set tarcmd = ( tar cv -f $TF --exclude-from $SOURCE_DIR/tar-exclude \
-    --exclude-from $SOURCE_DIR/tar-exclude-more --exclude-from $EXCLUDE_FILE \
-    `basename $SOURCE_DIR` )
-if(! $KEEPAUTOSEG) set tarcmd = ($tarcmd --exclude-from $SOURCE_DIR/tar-exclude-gca)
+set tarcmd = ( tar cv -f $TF  $SOURCE_DIR_REL --exclude-from $EXCLUDE_FILE )
+if( -e $SOURCE_DIR/tar-exclude ) then
+  set tarcmd = ($tarcmd --exclude-from $SOURCE_DIR/tar-exclude)
+endif
+if( -e $SOURCE_DIR/tar-exclude-more ) then
+  set tarcmd = ($tarcmd --exclude-from $SOURCE_DIR/tar-exclude-more)
+endif
+if( -e $SOURCE_DIR/tar-exclude-gca && ! $KEEPAUTOSEG) then
+  set tarcmd = ($tarcmd --exclude-from $SOURCE_DIR/tar-exclude-gca)
+endif
 echo $tarcmd | tee -a $LF
 $tarcmd  >> $LF
 
-rm -f $EXCLUDE_FILE
+# rm -f $EXCLUDE_FILE
 
 date | tee -a $LF
+
+exit 1;
+
 
 #--- Special for tksurfer, tkmedit, and tkregister in freesurfer_alpha ---#
 # Note: static vs dynamic only applies to Linux.
@@ -270,80 +350,80 @@ date | tee -a $LF
 # .static files there).
 if( "`basename $SOURCE_DIR`" == "freesurfer_alpha" ) then
 
-echo "------------------------------------------" | tee -a $LF
-echo "Handling tkmedit, tksurfer, and tkregister" | tee -a $LF
-date | tee -a $LF
-pushd $TARGET_DIR > /dev/null
-set FSA_TMP_DIR = freesurfer_alpha;
-mkdir -p $FSA_TMP_DIR
-
-# Go through each OS - actually only applies to Linux #
-foreach OS (Linux)
-
-  # tkmedit and tkregister #
-  mkdir -p $FSA_TMP_DIR/bin/$OS
-  foreach binary (tkmedit tkregister)
-    # Copy dynamic #
-    set fdynamic = $SOURCE_DIR/bin/$OS/$binary
-    if(! -e $fdynamic) then
-      echo "ERROR: cannot find $fdynamic"| tee -a $LF
+  echo "------------------------------------------" | tee -a $LF
+  echo "Handling tkmedit, tksurfer, and tkregister" | tee -a $LF
+  date | tee -a $LF
+  pushd $TARGET_DIR > /dev/null
+  set FSA_TMP_DIR = freesurfer_alpha;
+  mkdir -p $FSA_TMP_DIR
+  
+  # Go through each OS - actually only applies to Linux #
+  foreach OS (Linux)
+  
+    # tkmedit and tkregister #
+    mkdir -p $FSA_TMP_DIR/bin/$OS
+    foreach binary (tkmedit tkregister)
+      # Copy dynamic #
+      set fdynamic = $SOURCE_DIR/bin/$OS/$binary
+      if(! -e $fdynamic) then
+        echo "ERROR: cannot find $fdynamic"| tee -a $LF
+        exit 1;
+      endif
+      cp $fdynamic $FSA_TMP_DIR/bin/$OS/$binary.dynamic
+      # Copy static #
+      set fstatic = $SOURCE_DIR/bin/$OS/$binary.static
+      if(! -e $fstatic) then
+        echo "ERROR: cannot find $fstatic"| tee -a $LF
+        exit 1;
+      endif
+      cp $fstatic  $FSA_TMP_DIR/bin/$OS/$binary
+    end # foreach binary (tkmedit tkregister)
+  
+  end#foreach OS
+  
+  # ----------- Handle tksurfer ----------------------#
+  foreach OS (Linux Solaris IRIX)
+    mkdir -p $FSA_TMP_DIR/bin/$OS
+  
+    # Get path to tksurfer.new
+    set tksurfernew = $SOURCE_DIR/bin/$OS/tksurfer.new
+    if(! -e $tksurfernew) then
+      echo "ERROR: cannot find $tksurfernew"| tee -a $LF
       exit 1;
     endif
-    cp $fdynamic $FSA_TMP_DIR/bin/$OS/$binary.dynamic
-    # Copy static #
-    set fstatic = $SOURCE_DIR/bin/$OS/$binary.static
-    if(! -e $fstatic) then
-      echo "ERROR: cannot find $fstatic"| tee -a $LF
-      exit 1;
+  
+    # Copy tksurfer.new to tksurfer (except Linux) #
+    if("$OS" != "Linux") then
+      # Solaris and IRIX
+      cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer
+      cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer.new
+    else
+      # Linux - must handle stat/dyn linked version #
+      cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer.dynamic
+      cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer.new.dynamic
+      # Copy tksurfer.new.static to tksurfer (Linux only)#
+      set tksurfernew_static = $SOURCE_DIR/bin/$OS/tksurfer.new.static
+      if(! -e $tksurfernew_static) then
+        echo "ERROR: cannot find $tksurfernew_static"| tee -a $LF
+        exit 1;
+      endif
+      cp $tksurfernew_static  $FSA_TMP_DIR/bin/$OS/tksurfer
+      cp $tksurfernew_static  $FSA_TMP_DIR/bin/$OS/tksurfer.new
     endif
-    cp $fstatic  $FSA_TMP_DIR/bin/$OS/$binary
-  end # foreach binary (tkmedit tkregister)
-
-end#foreach OS
-
-# ----------- Handle tksurfer ----------------------#
-foreach OS (Linux Solaris IRIX)
-  mkdir -p $FSA_TMP_DIR/bin/$OS
-
-  # Get path to tksurfer.new
-  set tksurfernew = $SOURCE_DIR/bin/$OS/tksurfer.new
-  if(! -e $tksurfernew) then
-    echo "ERROR: cannot find $tksurfernew"| tee -a $LF
-    exit 1;
-  endif
-
-  # Copy tksurfer.new to tksurfer (except Linux) #
-  if("$OS" != "Linux") then
-    # Solaris and IRIX
-    cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer
-    cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer.new
-  else
-    # Linux - must handle stat/dyn linked version #
-    cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer.dynamic
-    cp $tksurfernew $FSA_TMP_DIR/bin/$OS/tksurfer.new.dynamic
-    # Copy tksurfer.new.static to tksurfer (Linux only)#
-    set tksurfernew_static = $SOURCE_DIR/bin/$OS/tksurfer.new.static
-    if(! -e $tksurfernew_static) then
-      echo "ERROR: cannot find $tksurfernew_static"| tee -a $LF
-      exit 1;
-    endif
-    cp $tksurfernew_static  $FSA_TMP_DIR/bin/$OS/tksurfer
-    cp $tksurfernew_static  $FSA_TMP_DIR/bin/$OS/tksurfer.new
-  endif
-
-end#foreach OS
-
-echo "Appending temporary freesurfer_alpha to tar `date`"| tee -a $LF
-tar rv -f $TF ./$FSA_TMP_DIR >> $LF
-
-echo "Removing temporary directory `date`"| tee -a $LF
-rm -rf $FSA_TMP_DIR
+  
+  end #foreach OS
+  
+  echo "Appending temporary freesurfer_alpha to tar `date`"| tee -a $LF
+  tar rv -f $TF ./$FSA_TMP_DIR >> $LF
+  
+  echo "Removing temporary directory `date`"| tee -a $LF
+  rm -rf $FSA_TMP_DIR
 
 endif # specials for freesurfer_alpha #
 
-
 echo "Compressing tar file `date`"| tee -a $LF
 gzip $TF
+
 
 
 #-- Tar up the minc bin and libs -------#
