Fixed bugs

diff --git a/scripts/mksurfatlas b/scripts/mksurfatlas
--- a/scripts/mksurfatlas
+++ b/scripts/mksurfatlas
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # Creates an atlas to use for surface registration
 
-set VERSION = '$Id: mksurfatlas,v 1.2 2006/05/19 22:00:21 greve Exp $';
+set VERSION = '$Id: mksurfatlas,v 1.3 2006/05/22 18:25:57 greve Exp $';
 
 set atlas = ();
 set target = ();
@@ -41,8 +41,8 @@ check_params_return:
 if(-e $atlas && $force) rm -f $atlas
 
 set cmd = (mris_make_template -norot -annot aparc \
-            -overlay $surfval 10 $hemi $surfreg \
-            $subjects $atlas)
+            -overlay $surfval 10 -overlay-dir $surfvaldir \
+            $hemi $regsurf $subjects $atlas)
 echo $cmd
 $cmd
 if($status) exit(1);
@@ -63,7 +63,7 @@ while( $#argv != 0 )
   
   switch($flag)
 
-    case "--t":
+    case "--a":
       if($#argv < 1) goto arg1err;
       set atlas = $argv[1]; shift;
       breaksw
@@ -71,6 +71,17 @@ while( $#argv != 0 )
     case "--s":
       if($#argv < 1) goto arg1err;
       set subject = $argv[1]; shift;
+      set subjects = ($subjects $subject);
+      breaksw
+
+    case "--sf":
+      if($#argv < 1) goto arg1err;
+      set subjectfile = $argv[1]; shift;
+      if(! -e $subjectfile) then
+        echo "ERROR: cannot find $subjectfile"
+        exit 1;
+      endif
+      set subjects = ($subjects `cat $subjectfile`);
       breaksw
 
     case "--v":
@@ -90,12 +101,12 @@ while( $#argv != 0 )
       breaksw
 
     case "--r":
-      if ( $#argv == 0) goto arg1err;
+      if($#argv == 0) goto arg1err;
       set regsurf = $argv[1]; shift;
       breaksw
 
     case "--tmpdir":
-      if( $#argv < 1) goto arg1err;
+      if($#argv < 1) goto arg1err;
       set tmpdir = $argv[1]; shift;
       set cleanup = 0;
       breaksw
@@ -148,7 +159,7 @@ check_params:
       echo "ERROR: cannot find $SUBJECTS_DIR/$subject"
       exit 1;
     endif
-    set sr = $SUBJECTS_DIR/$subject/surf/$hemi.$surfreg
+    set sr = $SUBJECTS_DIR/$subject/surf/$hemi.$regsurf
     if(! -e $sr) then
       echo "ERROR: cannot find $sr"
       exit 1;
