Added -d option

diff --git a/scripts/mri_mergelabels b/scripts/mri_mergelabels
--- a/scripts/mri_mergelabels
+++ b/scripts/mri_mergelabels
@@ -7,9 +7,9 @@
 #
 # Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
 # CVS Revision Info:
-#    $Author: nicks $
-#    $Date: 2007/01/06 00:01:14 $
-#    $Revision: 1.3 $
+#    $Author: greve $
+#    $Date: 2007/08/10 20:01:57 $
+#    $Revision: 1.4 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -28,7 +28,7 @@
 # a functional data set by projecting out the eigenvectors
 # as computed from evfunc (fast_evfunc.m)
 #
-set VERSION = '$Id: mri_mergelabels,v 1.3 2007/01/06 00:01:14 nicks Exp $'
+set VERSION = '$Id: mri_mergelabels,v 1.4 2007/08/10 20:01:57 greve Exp $'
 set inputargs = ($argv);
 
 set PWDCMD = `getpwdcmd`;
@@ -99,6 +99,16 @@ while( $#argv != 0 )
       set inputlist = ($inputlist $input);
       breaksw
 
+    case "-d"
+      if ($#argv == 0) goto arg1err;
+      set d = $argv[1];shift;
+      if(! -e $d) then
+        echo "ERROR: $d does not exist"
+        exit 1;
+      endif
+      set inputlist = ($inputlist `ls $d/*.label`);
+      breaksw
+
     case "-verbose":
       set verbose = 1;
       breaksw
@@ -152,6 +162,7 @@ usage_exit:
   echo ""
   echo "   -i label1 -i label2 ..."
   echo "   -o outputlabel"
+  echo "   -d dir : all labels in directory dir"
   echo ""
   echo "This is a simple script that will merge two or more label"
   echo "files. It does this by catting the label files together"
