Added --diag-cluster

diff --git a/scripts/mri_glmfit-sim b/scripts/mri_glmfit-sim
--- a/scripts/mri_glmfit-sim
+++ b/scripts/mri_glmfit-sim
@@ -1,5 +1,5 @@
 #!/bin/tcsh -f
-set VERSION = '$Id: mri_glmfit-sim,v 1.10 2009/01/16 01:03:15 greve Exp $';
+set VERSION = '$Id: mri_glmfit-sim,v 1.11 2009/01/16 02:26:59 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -18,6 +18,7 @@ set fwhmOverride = ();
 set UseUniformPDF = 0;
 set UniformPDFMin = ();
 set UniformPDFMax = ();
+set DiagCluster = 0;
 
 set nJobs = 1;
 set DoBackground = 0;
@@ -221,7 +222,7 @@ if($DoSim) then
     if($anattype == surface) set cmd = ($cmd --surf $subject $hemi);
     if($#Seed) set cmd = ($cmd --seed $Seed);
     if($UseUniformPDF) set cmd = ($cmd --uniform $UniformPDFMin $UniformPDFMax);
-
+    if($DiagCluster) set cmd = ($cmd --diag-cluster)
     if($DoPoll) then
       set DoneFile = $glmdir/csd/done.$csdbase.$jpad
       rm -f $DoneFile
@@ -232,8 +233,37 @@ if($DoSim) then
     if(! $DoPoll) then
       # Run directly in shell
       $cmd | tee -a $LF
-      if($status) exit 1;
+      if($status && ! $DiagCluster) exit 1;
       date | tee -a $LF
+
+      # ----------------------------------------------------
+      if($DiagCluster)then
+        set conname = $conlist[1];
+        set sig = ./$conname-sig.mgh
+        set csd = $glmdir/csd/$csdbase.$jpad-$conname.csd
+        set sum = $glmdir/csd/$csdbase.$jpad-$conname.diag
+
+        if($anattype == surface) then
+          set cmd = (mri_surfcluster --subject $subject --hemi $hemi)
+          set c = 4;
+        endif
+        if($anattype == volume) then
+          set cmd = (mri_volcluster)
+          set c = 3;
+        endif
+        set cmd = ($cmd --in $sig --mask $mask \
+         --sum $sum --thmin $thresh --sign $simsign)
+        echo $cmd | tee -a $LF
+        $cmd | tee -a $LF
+        if($status) exit 1;
+
+        set maxclustB = `grep -v \# $csd | awk '{print $3}' | sort -nr | head -n 1`;
+        set maxclustA = `grep -v \# $sum | awk -v c=$c '{print $c}' | sort -nr | head -n 1`;
+        echo "MaxClusterSizeA $maxclustA"| tee -a $LF
+        echo "MaxClusterSizeB $maxclustB"| tee -a $LF
+        exit 1;
+      endif
+      # ----------------------------------------------------
     else
       if($DoBackground) then
         # Run in background
@@ -443,6 +473,10 @@ while( $#argv != 0 )
       set DoSim = 0;
       breaksw
 
+    case "--diag-cluster":
+      set DiagCluster = 1;
+      breaksw
+
     case "--debug":
       set verbose = 1;
       set echo = 1;
@@ -477,6 +511,18 @@ if($DoSim) then
   endif
 endif
 
+if($DiagCluster && $DoBackground) then
+  echo "ERROR: cannot background with --diag-cluster"
+  exit 1;
+endif
+if($DiagCluster && $DoPBSubmit) then
+  echo "ERROR: cannot pbsubmit with --diag-cluster"
+  exit 1;
+endif
+if($DiagCluster && $DoSim == 0) then
+  echo "ERROR: must simulate with --diag-cluster"
+  exit 1;
+endif
 
 goto check_params_return;
 ############--------------##################
