Better at finding y.mgh now

diff --git a/scripts/mri_glmfit-sim b/scripts/mri_glmfit-sim
--- a/scripts/mri_glmfit-sim
+++ b/scripts/mri_glmfit-sim
@@ -1,5 +1,5 @@
 #!/bin/tcsh -f
-set VERSION = '$Id: mri_glmfit-sim,v 1.3 2009/01/14 02:18:52 nicks Exp $';
+set VERSION = '$Id: mri_glmfit-sim,v 1.4 2009/01/14 03:22:13 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -81,10 +81,12 @@ while($#glmfitcmd)
     breaksw
   case "--y"
     set y = $glmfitcmd[1]; shift glmfitcmd;
-    #set y = $glmfitcwd/$y
     if(! -e $y) then
-      echo "ERROR: cannot find $y"
-      exit 1;
+      set y = $glmfitcwd/$y
+      if(! -e $y) then
+        echo "ERROR: cannot find $y"
+        exit 1;
+      endif
     endif
     breaksw
   default
