Added --bg and --pbsubmit

diff --git a/scripts/mri_glmfit-sim b/scripts/mri_glmfit-sim
--- a/scripts/mri_glmfit-sim
+++ b/scripts/mri_glmfit-sim
@@ -1,5 +1,5 @@
 #!/bin/tcsh -f
-set VERSION = '$Id: mri_glmfit-sim,v 1.4 2009/01/14 03:22:13 greve Exp $';
+set VERSION = '$Id: mri_glmfit-sim,v 1.5 2009/01/14 19:41:43 greve Exp $';
 
 set inputargs = ($argv);
 
@@ -11,6 +11,13 @@ set csdbase = ()
 set simsign = ()
 set Overwrite = 0;
 set LF = ();
+
+set nJobs = 1;
+set DoBackground = 0;
+set DoPBSubmit = 0;
+set DoPoll = 0;
+set tSleepSec = 10;
+
 set tmpdir = ();
 set CleanUp = 1;
 set PrintHelp = 0;
@@ -134,13 +141,17 @@ foreach c ($clist)
   endif
 
   # Make sure that csd is not there
-  set csd = $glmdir/$csdbase-$conname.csd
-  if(-e $csd && ! $Overwrite) then
-    echo "ERROR: $csd already exists"
-    echo "Delete it or run with --overwrite"
-    exit 1;
+  ls $glmdir/csd/$csdbase.j???-$conname.csd >& /dev/null
+  set csdexists = (! $status)
+  if($csdexists) then
+    set csdfiles = ($glmdir/csd/$csdbase.j???-$conname.csd)
+    if(! $Overwrite) then
+      echo "ERROR: $csdfiles already exists"
+      echo "Delete it or run with --overwrite"
+      exit 1;
+    endif
+    rm -f $csdfiles
   endif
-  rm -f $csd
 
 end
 
@@ -167,26 +178,80 @@ uname -a | tee -a $LF
 echo $user | tee -a $LF
 echo "setenv SUBJECTS_DIR $SUBJECTS_DIR" | tee -a $LF
 echo "FREESURFER_HOME $FREESURFER_HOME" | tee -a $LF
+echo "DoPoll = $DoPoll"| tee -a $LF
+
+
+# Number of sim iterations per job
+set nSimPerJob = `echo "$nsim/$nJobs" | bc`;
+echo "nSimPerJob = $nSimPerJob"| tee -a $LF
 
 # ----------------- Run glmfit simulation ----------------------
 # This may take a while
-date | tee -a $LF
-set cmd = (mri_glmfit --y $y $clist2)
-set cmd = ($cmd --sim $nulltype $nsim $thresh $glmdir/$csdbase)
-set cmd = ($cmd --sim-sign $simsign)
-if($#fsgd) set cmd = ($cmd --fsgd $fsgd)
-if($#X)    set cmd = ($cmd --X $X)
-if($nulltype != perm) set cmd = ($cmd --fwhm $fwhm)
-if($anattype == surface) set cmd = ($cmd --surf $subject $hemi);
+mkdir -p $glmdir/csd
+@ nthJob = 1
+while($nthJob <= $nJobs)
+  set jpad = `printf j%03d $nthJob`
+  echo "$nthJob/$nJobs `date`" | tee -a $LF
 
-echo $cmd | tee -a $LF
-$cmd | tee -a $LF
-if($status) exit 1;
-date | tee -a $LF
+  set cmd = (mri_glmfit --y $y $clist2)
+  set cmd = ($cmd --sim $nulltype $nSimPerJob $thresh $glmdir/csd/$csdbase.$jpad)
+  set cmd = ($cmd --sim-sign $simsign)
+  if($#fsgd) set cmd = ($cmd --fsgd $fsgd)
+  if($#X)    set cmd = ($cmd --X $X)
+  if($nulltype != perm) set cmd = ($cmd --fwhm $fwhm)
+  if($anattype == surface) set cmd = ($cmd --surf $subject $hemi);
+
+  set DoneFile = $glmdir/csd/$csdbase.$jpad.done
+  rm -f $DoneFile
+  set cmd = ($cmd --sim-done $DoneFile)
+
+  echo $cmd | tee -a $LF
+  if(! $DoPoll) then
+    $cmd | tee -a $LF
+    if($status) exit 1;
+    date | tee -a $LF
+  else
+    if($DoBackground) then
+      $cmd >& /dev/null &
+    endif
+    if($DoPBSubmit) then
+      pbsubmit -l nodes=1:opteron -c "$cmd"
+      sleep 10;
+    endif
+  endif
+  @ nthJob = $nthJob + 1
+end
+
+if($DoPoll) then
+  echo "Polling" | tee -a $LF
+  @ nthPoll = 0;
+  set Done = 0;
+  while(! $Done)
+    @ nthPoll = $nthPoll + 1;
+    echo "Poll $nthPoll `date`" | tee -a $LF
+    set Done = 1;
+    @ nthJob = 1
+    while($nthJob <= $nJobs)
+      set jpad = `printf j%03d $nthJob`
+      set DoneFile = $glmdir/csd/$csdbase.$jpad.done
+      if(! -e $DoneFile) then
+        set Done = 0;
+        break;
+      endif
+    @ nthJob = $nthJob + 1
+    end
+    sleep $tSleepSec 
+  end
+endif
 
 # -------------- now run mri_surfcluster -------------------- #
 foreach conname ($conlist)
-  set csd = $glmdir/$csdbase-$conname.csd
+  set csdfiles = ($glmdir/csd/$csdbase.j???-$conname.csd)
+  set csdlist = ();
+  foreach csd ($csdfiles)
+    set csdlist = ($csdlist --csd $csd);
+  end
+
   set sig = `stem2fname $glmdir/$conname/sig`
   set vwsig = $glmdir/$conname/$csdbase.sig.voxel.mgh
   set cwsig = $glmdir/$conname/$csdbase.sig.cluster.mgh
@@ -195,7 +260,7 @@ foreach conname ($conlist)
   set sum   = $glmdir/$conname/$csdbase.sig.cluster.summary
 
   if($anattype == surface) then
-    set cmd = (mri_surfcluster --in $sig --csd $csd --mask $mask \
+    set cmd = (mri_surfcluster --in $sig $csdlist --mask $mask \
       --cwsig $cwsig --vwsig $vwsig --sum $sum --ocn $ocn \
       --oannot $annot)
     echo $cmd | tee -a $LF
@@ -259,6 +324,36 @@ while( $#argv != 0 )
 
     case "--overwrite":
       set Overwrite = 1;
+      breaksw
+
+    case "--pbsubmit":
+      if($#argv < 1) goto arg1err;
+      set nJobs = $argv[1]; shift;
+      set DoPBSubmit = 1;
+      set DoPoll = 1;
+      set DoBackground = 0;
+      if(`hostname` != seychelles) then
+        echo "ERROR: must be on seychelles to pbsubmit"
+        exit 1;
+      endif
+      breaksw
+
+    case "--bg":
+      if($#argv < 1) goto arg1err;
+      set nJobs = $argv[1]; shift;
+      set DoBackground = 1;
+      set DoPoll = 1;
+      set DoPBSubmit = 0;
+      breaksw
+
+    case "--no-bg":
+      set DoBackground = 0;
+      set DoPoll = 0;
+      breaksw
+
+    case "--sleep":
+      if($#argv < 1) goto arg1err;
+      set tSleepSec = $argv[1]; shift;
       breaksw
 
     case "--debug":
