Can now cache out and in

diff --git a/scripts/mris_preproc b/scripts/mris_preproc
--- a/scripts/mris_preproc
+++ b/scripts/mris_preproc
@@ -2,7 +2,7 @@
 #
 setenv FIX_VERTEX_AREA
 
-set VERSION = '$Id: mris_preproc,v 1.16 2006/02/24 01:19:29 greve Exp $';
+set VERSION = '$Id: mris_preproc,v 1.17 2006/02/24 02:33:40 greve Exp $';
 
 set PrintHelp = 0;
 set subjlist = ();
@@ -38,6 +38,11 @@ set reshape = 0;
 set sval = ();
 set svalsurf = ();
 set jac = 0;
+set CacheOutFile = ();
+set CacheOutOnly = 0;
+set CacheIn = 0;
+set MeasIn  = 0;
+set outdir = ();
 
 set cmdargs = ($argv);
 if($#argv == 0)  goto usage_exit;
@@ -64,37 +69,39 @@ handle_fsfast_return:
 # Check the command-line arguments
 goto check_params;
 check_params_return:
-
-# Check for analyze and nifti output format
-isanalyze $outpath >& /dev/null
-if($status) then
-  if(! $reshape) then
-    set reshape = 1
-    echo "INFO: output detected as analyze, turning on reshaping"
-  endif
-endif
-isnifti $outpath >& /dev/null
-if($status) then
-  if(! $reshape) then
-    set reshape = 1
-    echo "INFO: output detected as nifti, turning on reshaping"
-  endif
-endif
-
 set nsubjects = $#subjlist;
 if($srcsurf) set geom = surface
 if($srcvol)  set geom = volume
 
-# Create the output directory
-set outdir = `dirname $outpath`;
-mkdir -p $outdir
-if($status) then
-  echo "ERROR: creating $outdir"
-  exit 1;
+if(! $CacheOutOnly) then
+  # Check for analyze and nifti output format
+  isanalyze $outpath >& /dev/null
+  if($status) then
+    if(! $reshape) then
+      set reshape = 1
+      echo "INFO: output detected as analyze, turning on reshaping"
+    endif
+  endif
+  isnifti $outpath >& /dev/null
+  if($status) then
+    if(! $reshape) then
+      set reshape = 1
+      echo "INFO: output detected as nifti, turning on reshaping"
+    endif
+  endif
+  # Create the output directory
+  set outdir = `dirname $outpath`;
+  mkdir -p $outdir
+  if($status) then
+    echo "ERROR: creating $outdir"
+    exit 1;
+  endif
 endif
 
 # Create the tmpdir
 if($#tmpdir == 0) set tmpdir = $outdir/tmp.mris_preproc.$$
+echo tmpdir is $tmpdir
+pwd
 mkdir -p $tmpdir
 if($status) then
   echo "ERROR: creating $tmpdir"
@@ -103,7 +110,8 @@ endif
 
 # Log file
 if($#LF == 0) then
-  set LF = $outdir/mris_preproc.$geom.$hemi.log
+  if(! $#CacheOutOnly) set LF = $outdir/mris_preproc.$geom.$hemi.log
+  if($#CacheOutOnly)   set LF = mris_preproc.$geom.$hemi.log
   if(-e $LF) mv $LF $LF.bak
 endif
 
@@ -123,48 +131,75 @@ foreach subj ($subjlist)
 
   set subjpath = $SUBJECTS_DIR/$subj
 
-  if($srcvol) then
-    # Source is a volume, run mri_vol2surf
-    set srcsurfpath = $tmpdir/subjsurfvals.mgh
-    set vol = $ivplist[$nthsubj];
-    set reg = $irplist[$nthsubj];
-    set cmd = (mri_vol2surf --src $vol --srcreg $reg --hemi $hemi)
-    set cmd = ($cmd --out $srcsurfpath)
-    if($#projfrac) set cmd = ($cmd --projfrac $projfrac)
-    if($synth)     set cmd = ($cmd --srcsynth -1) # Synth if desired
-    if(! $reshape) set cmd = ($cmd --noreshape);
+  if($CacheIn) then
+    # Input has been cached
+    set tval = $subjpath/surf/$hemi.$meas
+  else
+    # Input has NOT been cached, create
+    if($srcvol) then
+      # Source is a volume, run mri_vol2surf
+      set srcsurfpath = $tmpdir/subjsurfvals.mgh
+      set vol = $ivplist[$nthsubj];
+      set reg = $irplist[$nthsubj];
+      set cmd = (mri_vol2surf --src $vol --srcreg $reg --hemi $hemi)
+      set cmd = ($cmd --out $srcsurfpath)
+      if($#projfrac) set cmd = ($cmd --projfrac $projfrac)
+      if($synth)     set cmd = ($cmd --srcsynth -1) # Synth if desired
+      if(! $reshape) set cmd = ($cmd --noreshape);
+      echo "-----------------------"| tee -a $LF
+      echo $cmd | tee -a $LF
+      if($RunIt) $cmd |& tee -a $LF
+      if($status) exit 1;
+    else
+      # Source is already a surface
+      if($#meas || $#sval) then
+        set srcsurfpath = $subjpath/surf/$hemi.$meas
+        else
+        set srcsurfpath = $isplist[$nthsubj];
+      endif
+    endif
+
+    # Now srcsurfpath file exists, convert it to the target subject
+    set tval = $tmpdir/$subj.mgh
+    set cmd = (mri_surf2surf --hemi $hemi --srcsubject $subj)
+    if($#sval == 0) then
+       set cmd = ($cmd --sval $srcsurfpath)
+    else
+       set cmd = ($cmd --sval-$sval $svalsurf)
+    endif
+    if($jac) set cmd = ($cmd --jac)
+    if($#srcfmt) set cmd = ($cmd --sfmt curv)
+    set cmd = ($cmd --trgsubject $target --tval $tval)
+    if($synth && ! $srcvol) set cmd = ($cmd --synth) # Synth if desired, vol done above
+    if($#fwhmsrc)   set cmd = ($cmd --fwhm-src $fwhmsrc) # Smth in the targ space below
+    if($#niterssrc) set cmd = ($cmd --nsmooth-in $niterssrc) # Smth in the targ space below
+    if(! $reshape)  set cmd = ($cmd --noreshape);
     echo "-----------------------"| tee -a $LF
     echo $cmd | tee -a $LF
     if($RunIt) $cmd |& tee -a $LF
     if($status) exit 1;
-  else
-    # Source is already a surface
-    if($#meas || $#sval) then
-      set srcsurfpath = $subjpath/surf/$hemi.$meas
-    else
-      set srcsurfpath = $isplist[$nthsubj];
-    endif
-  endif
+  endif # if($CacheIn) then
 
-  # Now srcsurfpath file exists, convert it to the target subject
-  set tval = $tmpdir/$subj.mgh
-  set cmd = (mri_surf2surf --hemi $hemi --srcsubject $subj)
-  if($#sval == 0) then
-     set cmd = ($cmd --sval $srcsurfpath)
+  # Copy/smooth resampled data to CacheOutFile
+  if($#CacheOutFile) then
+    set tcache = $subjpath/surf/$hemi.$CacheOutFile
+    # Smooth in the target space
+    if($#fwhmtarg || $#niterstarg) then
+      set cmd = (mri_surf2surf --hemi $hemi --s $target )
+      set cmd = ($cmd --sval $tval)
+      set cmd = ($cmd --tval $tcache)
+      if($#fwhmtarg)   set cmd = ($cmd --fwhm-trg $fwhmtarg)
+      if($#niterstarg) set cmd = ($cmd --nsmooth-out $niterstarg)
+      if(! $reshape)   set cmd = ($cmd --noreshape);
+      echo "-----------------------"| tee -a $LF
+      echo $cmd | tee -a $LF
+      if($RunIt) $cmd |& tee -a $LF
+      if($status) exit 1;
+      echo "\n\n" | tee -a $LF
+    endif
   else
-     set cmd = ($cmd --sval-$sval $svalsurf)
+    cp $tval $subjpath/surf/$hemi.$CacheOutFile
   endif
-  if($jac) set cmd = ($cmd --jac)
-  if($#srcfmt) set cmd = ($cmd --sfmt curv)
-  set cmd = ($cmd --trgsubject $target --tval $tval)
-  if($synth && ! $srcvol) set cmd = ($cmd --synth) # Synth if desired, vol done above
-  if($#fwhmsrc)   set cmd = ($cmd --fwhm-src $fwhmsrc) # Smth in the targ space below
-  if($#niterssrc) set cmd = ($cmd --nsmooth-in $niterssrc) # Smth in the targ space below
-  if(! $reshape)  set cmd = ($cmd --noreshape);
-  echo "-----------------------"| tee -a $LF
-  echo $cmd | tee -a $LF
-  if($RunIt) $cmd |& tee -a $LF
-  if($status) exit 1;
 
   # Prepare to concatenate them
   set tvallist = ($tvallist $tval)
@@ -174,32 +209,34 @@ end
 
 echo "\n\n" | tee -a $LF
 
-# Now concatenate all the inputs together
-set cmd = (mri_concat $tvallist --o $outpath)
-if($paireddiff)      set cmd = ($cmd --paired-diff);
-if($paireddiffnorm)  set cmd = ($cmd --paired-diff-norm);
-if($paireddiffnorm1) set cmd = ($cmd --paired-diff-norm1);
-if($paireddiffnorm2) set cmd = ($cmd --paired-diff-norm2);
-if($catmean)    set cmd = ($cmd --mean);
-echo "-----------------------"| tee -a $LF
-echo $cmd | tee -a $LF
-if($RunIt) $cmd |& tee -a $LF
-if($status) exit 1;
-echo "\n\n" | tee -a $LF
-
-# Smooth in the target space
-if($#fwhmtarg || $#niterstarg) then
-  set cmd = (mri_surf2surf --hemi $hemi --s $target )
-  set cmd = ($cmd --sval $outpath)
-  set cmd = ($cmd --tval $outpath)
-  if($#fwhmtarg)   set cmd = ($cmd --fwhm-trg $fwhmtarg)
-  if($#niterstarg) set cmd = ($cmd --nsmooth-out $niterstarg)
-  if(! $reshape)   set cmd = ($cmd --noreshape);
+if(! $CacheOutOnly) then
+  # Now concatenate all the inputs together
+  set cmd = (mri_concat $tvallist --o $outpath)
+  if($paireddiff)      set cmd = ($cmd --paired-diff);
+  if($paireddiffnorm)  set cmd = ($cmd --paired-diff-norm);
+  if($paireddiffnorm1) set cmd = ($cmd --paired-diff-norm1);
+  if($paireddiffnorm2) set cmd = ($cmd --paired-diff-norm2);
+  if($catmean)    set cmd = ($cmd --mean);
   echo "-----------------------"| tee -a $LF
   echo $cmd | tee -a $LF
   if($RunIt) $cmd |& tee -a $LF
   if($status) exit 1;
   echo "\n\n" | tee -a $LF
+
+  # Smooth in the target space
+  if($#fwhmtarg || $#niterstarg) then
+    set cmd = (mri_surf2surf --hemi $hemi --s $target )
+    set cmd = ($cmd --sval $outpath)
+    set cmd = ($cmd --tval $outpath)
+    if($#fwhmtarg)   set cmd = ($cmd --fwhm-trg $fwhmtarg)
+    if($#niterstarg) set cmd = ($cmd --nsmooth-out $niterstarg)
+    if(! $reshape)   set cmd = ($cmd --noreshape);
+    echo "-----------------------"| tee -a $LF
+    echo $cmd | tee -a $LF
+    if($RunIt) $cmd |& tee -a $LF
+    if($status) exit 1;
+    echo "\n\n" | tee -a $LF
+  endif
 endif
 
 if($cleanup) then
@@ -259,6 +296,15 @@ while( $#argv != 0 )
       set meas = $argv[1]; shift;
       set srcsurf = 1;
       set srcfmt = curv;
+      set MeasIn = 1;
+      breaksw
+
+    case "--cache-in":
+      if($#argv < 1) goto arg1err;
+      set meas = $argv[1]; shift;
+      set srcsurf = 1;
+      set CacheIn = 1;
+      # dont set format
       breaksw
 
     case "--area":
@@ -365,9 +411,27 @@ while( $#argv != 0 )
       set FSFContrast = $argv[1]; shift;
       breaksw
 
+    case "--cache-out":
+      if ( $#argv == 0) goto arg1err;
+      set CacheOutFile = $argv[1]; shift;
+      breaksw
+
+    case "--cache-out-only":
+      if( $#argv < 1) goto arg1err;
+      set tmpdir = $argv[1]; shift;
+      set tmpdir = $tmpdir/tmp.mris_preproc.$$
+      echo tmpdir $tmpdir
+      set CacheOutOnly = 1;
+      breaksw
+
     case "--log":
       if ( $#argv == 0) goto arg1err;
       set LF = $argv[1]; shift;
+      breaksw
+
+    case "--tmpdir":
+      if ( $#argv == 0) goto arg1err;
+      set tmpdir = $argv[1]; shift;
       breaksw
 
     case "--mean":
@@ -512,7 +576,7 @@ if($#hemi == 0) then
   echo "ERROR: no hemi specified"
   exit 1;
 endif
-if($#outpath == 0) then
+if($#outpath == 0 && ! $CacheOutOnly) then
   echo "ERROR: no output specified"
   exit 1;
 endif
@@ -534,6 +598,10 @@ if($srcsurf && $#projfrac != 0) then
 endif
 if($#meas && $#isplist) then
   echo "ERROR: cannot specify both --meas and --is"
+  exit 1;
+endif
+if($MeasIn && $CacheIn) then
+  echo "ERROR: cannot specify both --meas and --cache-in"
   exit 1;
 endif
 if($#ivplist != 0) then
@@ -647,11 +715,13 @@ usage_exit:
   echo "  --paired-diff-norm1"
   echo "  --paired-diff-norm2"
   echo ""
+  echo "  --cache-out cachefile"
+  echo "  --cache-in  cachefile"
+  echo "  --cache-out-only tmpdir"
+  echo ""
   echo "  --mean : compute the mean of all inputs"
-  echo ""
-  echo "  --synth"
-  echo ""
   echo "  --reshape : reshape spatial dimensions"
+  echo "  --synth"
   echo "  --tmpdir dir : use tmpdir. Implies --nocleanup."
   echo "  --nocleanup  : do not delete tmpdir"
   echo "  --cleanup  : delete tmpdir (default)"
@@ -784,6 +854,27 @@ Same as --paired-diff, but normalizes by time point 1, ie,
 
 Same as --paired-diff, but normalizes by time point 2, ie,
 (Input1-Input2)/Input2.
+
+--cache-out cachefile
+--cache-in  cachefile
+--cache-out-only tmpdir
+
+Unless you are planning to do some type of semi-real-time processing,
+you can ignore caching. With --cache-out cachefile, mris_preproc will
+save the data for each subject, after resampling to the target and
+smoothing, in the subjects surf directory as hemi.cachefile. In a
+subsequent call to mris_preproc, you can specify --cache-in cachefile,
+and the precomputed data will be used. If you are going to smooth your
+data at some point, do it when caching out. If you want to cache
+without actually creating an output, then --cache-out-only. You must
+supply a tmpdir. The true tmpdir will be created under this. tmpdir
+itself will not be deleted. None of the paired diff options will
+affect caching.
+  mris_preproc --target average7 --hemi lh --s subj1 --s subj2 \
+    --meas thickness --fwhm 5 --cache-out thickness.avg7.sm5.mgh \
+    --cache-out-only tmp
+  mris_preproc --target average7 --hemi lh --s subj1 --s subj2 \
+    --cache-in thickness.avg7.sm5.mgh --out s12.thickness.avg7.sm5.mgh \
 
 --mean
 
