Added --SUBJECTS_DIR flag. -greve

diff --git a/scripts/mris_preproc b/scripts/mris_preproc
--- a/scripts/mris_preproc
+++ b/scripts/mris_preproc
@@ -10,9 +10,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: zkaufman $
-#    $Date: 2015/12/09 20:02:53 $
-#    $Revision: 1.76 $
+#    $Author: greve $
+#    $Date: 2016/08/12 17:08:16 $
+#    $Revision: 1.77 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -29,7 +29,7 @@
 #
 setenv FIX_VERTEX_AREA
 
-set VERSION = '$Id: mris_preproc,v 1.76 2015/12/09 20:02:53 zkaufman Exp $';
+set VERSION = '$Id: mris_preproc,v 1.77 2016/08/12 17:08:16 greve Exp $';
 
 set PrintHelp = 0;
 set subjlist = ();
@@ -608,6 +608,11 @@ while( $#argv != 0 )
       endif
       breaksw
 
+    case "--SUBJECTS_DIR":
+      if ( $#argv == 0) goto arg1err;
+      setenv SUBJECTS_DIR $argv[1]; shift;
+      breaksw
+
     case "--sf":
       if ( $#argv == 0) goto arg1err;
       set SessFile = $argv[1]; shift;
@@ -617,6 +622,10 @@ while( $#argv != 0 )
     case "--sd":
       if ( $#argv == 0) goto arg1err;
       set SessDirFile = $argv[1]; shift;
+      if(! -f $SessDirFile) then
+        echo "ERROR: cannot find SessDirFile $SessDirFile"
+        exit 1;
+      endif
       breaksw
 
     case "--analysis":
@@ -1083,6 +1092,7 @@ usage_exit:
   echo "  --reshape : reshape spatial dimensions"
   echo "  --surfreg SurfReg : default is sphere.reg"
   echo ""
+  echo "  --SUBJECTS_DIR SUBJECTS_DIR"
   echo "  --synth"
   echo "  --tmpdir dir : use tmpdir. Implies --nocleanup."
   echo "  --nocleanup  : do not delete tmpdir"
