Added fsfast support

diff --git a/scripts/mris_preproc b/scripts/mris_preproc
--- a/scripts/mris_preproc
+++ b/scripts/mris_preproc
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 #
 
-set VERSION = '$Id: mris_preproc,v 1.5 2006/01/19 22:55:33 greve Exp $';
+set VERSION = '$Id: mris_preproc,v 1.6 2006/01/31 05:41:26 greve Exp $';
 
 set PrintHelp = 0;
 set subjlist = ();
@@ -25,6 +25,10 @@ set srcvol  = 0;
 set tmpdir = ();
 set cleanup = 1;
 set RunIt = 1;
+set SessFile = ();
+set SessDirFile = ();
+set FSFAnalysis = ();
+set FSFContrast = ();
 set LF = ();
 
 if($#argv == 0)  goto usage_exit;
@@ -43,6 +47,10 @@ endif
 # Parse the command-line arguments
 goto parse_args;
 parse_args_return:
+
+# Handle FSFAST if needed
+goto handle_fsfast;
+handle_fsfast_return:
 
 # Check the command-line arguments
 goto check_params;
@@ -291,6 +299,27 @@ while( $#argv != 0 )
       set outpath = $argv[1]; shift;
       breaksw
 
+    case "--sf":
+      if ( $#argv == 0) goto arg1err;
+      set SessFile = $argv[1]; shift;
+      breaksw
+
+    case "--sd":
+      if ( $#argv == 0) goto arg1err;
+      set SessDirFile = $argv[1]; shift;
+      breaksw
+
+    case "--analysis":
+    case "--a":
+      if ( $#argv == 0) goto arg1err;
+      set FSFAnalysis = $argv[1]; shift;
+      breaksw
+
+    case "--c":
+      if ( $#argv == 0) goto arg1err;
+      set FSFContrast = $argv[1]; shift;
+      breaksw
+
     case "--log":
       if ( $#argv == 0) goto arg1err;
       set LF = $argv[1]; shift;
@@ -328,6 +357,87 @@ end
 
 goto parse_args_return;
 ############--------------##################
+
+############--------------##################
+handle_fsfast:
+
+if($#SessFile) then
+
+  # FS-Fast Session File
+  if($#FSFAnalysis == 0) then
+    echo "ERROR: need to specify --analysis with --sf"
+    exit 1;
+  endif
+  if($#FSFContrast == 0) then
+    echo "ERROR: need to specify --contrast with --sf"
+    exit 1;
+  endif
+
+  # Get the info file for the fsd
+  set infofile = $FSFAnalysis/analysis.info
+  if(! -e $infofile) then
+    echo "ERROR: cannot find $infofile" |& tee -a $LF
+    exit 1;
+  endif
+  set fsd = `cat $infofile | awk '{if($1 == "fsd") print $2}'`;
+
+  # Get the paths to the sessions
+  set cmd = (getsesspath -sf $SessFile);
+  if($#SessDirFile) set cmd = (getsesspath -df $SessDirFile);
+  set SessList = (`$cmd`)
+  if($status || $#SessList == 0) then
+    echo $cmd
+    echo "$SessList"
+    exit 1;
+  endif
+
+  # Go thru each session, get the input volume and register.dat
+  @ nthsess = 1;
+  set fsfsubjects = ();
+  set ivplist = ();
+  set irplist = ();
+  foreach sess ($SessList)
+    set ces = $sess/$fsd/$FSFAnalysis/$FSFContrast/ces.bhdr
+    if(! -e $ces) then
+      echo "ERROR: cannot find $ces"
+      exit 1;
+    endif
+    # should check that ces has only one frame
+    set reg = $sess/$fsd/register.dat
+    if(! -e $reg) then
+      echo "ERROR: cannot find $reg"
+      exit 1;
+    endif
+    set subject = `head -n 1 $reg`;
+    set fsfsubjects = ($fsfsubjects $subject)
+    set ivplist = ($ivplist $ces);
+    set irplist = ($irplist $reg);
+    @ nthsess = $nthsess + 1;
+  end
+
+  # Check subjlist against fsfast subjects
+  if($#subjlist == 0) set subjlist = ($fsfsubjects)
+  if($#subjlist != $#fsfsubjects) then
+    echo "ERROR: number of subjects does not equal the number"
+    echo "  of input fsfast sessions"
+    exit 1;
+  endif
+
+  @ nthsess = 1;
+  foreach subj ($subjlist)
+    set fsfsubj = $fsfsubjects[$nthsess]
+    if($subj != $fsfsubj) then
+      echo "ERROR: $nthsess mismatch: $subj vs $fsfsubj"
+      exit 1;
+    endif
+    @ nthsess = $nthsess + 1;
+  end
+
+  set srcvol = 1;
+endif
+
+goto handle_fsfast_return;
+
 
 ############--------------##################
 check_params:
@@ -458,6 +568,11 @@ usage_exit:
   echo ""
   echo "  --iv volmeasfile reg <--iv volmeasfile reg>"
   echo "  --projfrac frac : projection fraction for vol2surf"
+  echo ""
+  echo "  --sf sessfile        : fsfast session file"
+  echo "  --df sessdirfile     : fsfast session directory file"
+  echo "  --analysis analysis  : fsfast analysis"
+  echo "  --contrast constrast : fsfast contrast"
   echo ""
   echo "  --fwhm fwhm : smooth by fwhm mm on the target surface"
   echo "  --fwhm-src fwhmsrc : smooth by fwhm mm on the source surface"
