More dev

diff --git a/scripts/pctsurfcon b/scripts/pctsurfcon
--- a/scripts/pctsurfcon
+++ b/scripts/pctsurfcon
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/08/21 17:07:18 $
-#    $Revision: 1.2 $
+#    $Date: 2008/08/21 17:15:32 $
+#    $Revision: 1.3 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -23,12 +23,12 @@
 #
 
 #
-set VERSION = '$Id: pctsurfcon,v 1.2 2008/08/21 17:07:18 greve Exp $';
+set VERSION = '$Id: pctsurfcon,v 1.3 2008/08/21 17:15:32 greve Exp $';
 set inputargs = ($argv);
 
 set subject = ();
 set fsvol = rawavg;
-set movvol = ();
+set mov = ();
 set reg = ();
 
 set DoLH = 1;
@@ -38,6 +38,7 @@ set GMProjFrac = 0.5;
 set WMProjAbs = 2;
 set Interp = trilinear
 set OutBase = w-g.pct;
+set ConSign = +100;
 
 set debug = 0;
 set tmpdir = ();
@@ -97,8 +98,8 @@ foreach hemi ($hemilist)
   set cmd = (mri_vol2surf --mov $mov \
     --hemi $hemi --reshape --interp $Interp \
     --projdist -$WMProjAbs --o $wm)
-  if($#reg == 0) set cmd = (--regheader $subject);
-  if($#reg != 0) set cmd = (--reg $reg);
+  if($#reg == 0) set cmd = ($cmd --regheader $subject);
+  if($#reg != 0) set cmd = ($cmd --reg $reg);
   echo $cmd
   $cmd
   if($status) exit 1;
@@ -108,8 +109,8 @@ foreach hemi ($hemilist)
   set cmd = (mri_vol2surf --mov $mov \
     --hemi $hemi --reshape --interp $Interp \
     --projfrac $GMProjFrac --o $gm)
-  if($#reg == 0) set cmd = (--regheader $subject);
-  if($#reg != 0) set cmd = (--reg $reg);
+  if($#reg == 0) set cmd = ($cmd --regheader $subject);
+  if($#reg != 0) set cmd = ($cmd --reg $reg);
   echo $cmd
   $cmd
   if($status) exit 1;
@@ -117,7 +118,7 @@ foreach hemi ($hemilist)
   # Compute percent difference pct = 100*(w-g)/((w+g)/2)
   set out = $outdir/$hemi.$OutBase.mgh
   set cmd = (mri_concat $wm $gm --paired-diff-norm \
-    --mul 100 --o $out)
+    --mul $ConSign --o $out)
   echo $cmd 
   $cmd
   if($status) exit 1;
@@ -205,6 +206,14 @@ while( $#argv != 0 )
       set Interp = trilinear
       breaksw
 
+    case "--neg":
+      set ConSign = -100;
+      breaksw
+
+    case "--pos":
+      set ConSign = +100;
+      breaksw
+
     case "--tmp":
     case "--tmpdir":
       if ( $#argv < 1) goto arg1err;
@@ -249,7 +258,11 @@ check_params:
     exit 1;
   endif
 
-  if($#movvol == 0) set movvol = $SUBJECTS_DIR/$subject/mri/$fsvol.mgz
+  if($#mov == 0) set mov = $SUBJECTS_DIR/$subject/mri/$fsvol.mgz
+  if(! -e $mov) then
+    echo "ERROR: cannot find $mov"
+    exit 1;
+  endif
 
 goto check_params_return;
 ############--------------##################
@@ -283,6 +296,7 @@ usage_exit:
   echo "  --rh-only, --no-lh : compute rh only"
   echo "  --gm-proj-frac frac : GM projection fraction (default is $GMProjFrac)"
   echo "  --wm-proj-abs  dist : WM projection distance (default is $WMProjAbs mm)"
+  echo "  --neg : compute G-W instead of W-G"
   echo ""
   echo "Even more arguments"
   echo ""
