added -noaseg-inorm2 and -force flags

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -3,7 +3,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: recon-all,v 1.17 2006/02/27 18:45:26 greve Exp $';
+set VERSION = '$Id: recon-all,v 1.17.2.1 2006/03/22 18:19:15 nicks Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
@@ -22,6 +22,7 @@ set AppendLog    = 1;
 set AppendStatus = 1;
 set DoLegacy = 0;
 
+set Force = 0;
 set DoCleanTal   = 0;
 set DoCleanCP    = 0;
 set DoCleanSeed  = 0;
@@ -58,6 +59,8 @@ set FixDiagOnly = 0; # for topology fixer
 set RmNeckRadius = 25;  # used by mri_remove_neck
 set UseCAAlign = (-align); # not sure
 set UseAseg  = 1 # when set to 0 (using -noaseg), then aseg.mgz is not used
+set NoAsegInorm2 = 0 # when set to 1 (using -noaseg-inorm2), then aseg.mgz 
+                     # is not used during the 2nd mri_normalize step
 set UseNoNeg = 0 # if 1, add '-remove_negative 1' to mris_sphere,mris_register
 
 # For defacing, as found in:
@@ -786,7 +789,7 @@ if($DoNormalization2) then
   set cmd = (mri_normalize);
   if($UseControlPoints)   set cmd = ($cmd -f $ControlPointsFile)
   set cmd = ($cmd -mask brainmask.mgz)
-  if($UseAseg)            set cmd = ($cmd -aseg aseg.mgz)
+  if($UseAseg && ! $NoAsegInorm2) set cmd = ($cmd -aseg aseg.mgz)
   set cmd = ($cmd $xopts norm.mgz brain.mgz)
   $PWD |& tee -a $LF
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
@@ -1505,7 +1508,7 @@ while( $#argv != 0 )
 
     case "-subcortseg":
       set DoGCAReg         = 1;
-      set DoCARegInv      = 1;
+      set DoCARegInv       = 1;
       set DoRemoveNeck     = 1;
       set DoSkullLTA       = 1;
       set DoCANormalize    = 1;
@@ -1516,7 +1519,7 @@ while( $#argv != 0 )
 
     case "-nosubcortseg":
       set DoGCAReg         = 0;
-      set DoCARegInv      = 0;
+      set DoCARegInv       = 0;
       set DoRemoveNeck     = 0;
       set DoSkullLTA       = 0;
       set DoCANormalize    = 0;
@@ -1528,7 +1531,7 @@ while( $#argv != 0 )
     case "-noaseg":
       set UseAseg          = 0;
       set DoGCAReg         = 0;
-      set DoCARegInv      = 0;
+      set DoCARegInv       = 0;
       set DoRemoveNeck     = 0;
       set DoSkullLTA       = 0;
       set DoCANormalize    = 0;
@@ -1536,6 +1539,10 @@ while( $#argv != 0 )
       set DoCALabel        = 0;
       set DoSegStats       = 0;
       set DoAParc2ASeg     = 0;
+      breaksw
+
+    case "-noaseg-inorm2":
+      set NoAsegInorm2     = 1;
       breaksw
 
     case "-gca":
@@ -2043,6 +2050,10 @@ while( $#argv != 0 )
       limit coredumpsize unlimited
       breaksw
 
+    case "-force":
+      set Force = 1;
+      breaksw
+
     case "-verbose":
       set verbose = 1;
       breaksw
@@ -2213,8 +2224,15 @@ check_params:
       endif
     else
       if( -e $subjdir) then
-        echo "ERROR: $subjdir exists"
-        exit 1;
+        if(! $Force) then
+          echo "ERROR: $subjdir exists, delete or re-run with -force"
+          exit 1;
+        else
+          echo "INFO: $subjdir exists with -i, but -force specified."
+          echo "Deleting any previous source volumes"
+          rm -f $subjdir/src/[0-9][0-9][0-9].mgz >& /dev/null
+          rm -f $subjdir/mri/orig/[0-9][0-9][0-9].mgz >& /dev/null
+        endif
       endif
       mkdir -p $subjdir
     endif
@@ -2506,6 +2524,7 @@ usage_exit:
   echo "  -noappend     : start new log and status files instead of appending"
   echo ""
   echo " Other Arguments (Optional)"
+  echo "  -force          : with -i, allows pre-existing subjdir. Deletes source."
   echo "  -sd subjectsdir : specify subjects dir (default env SUBJECTS_DIR)"
   echo "  -mail username  : mail user when done"
   echo "  -umask umask    : set unix file permission mask (default 002)"
@@ -2542,7 +2561,9 @@ Basic usages:
 
 Creates analysis directory $SUBJECTS_DIR/subjectname, converts one or
 more input volumes to MGZ format in subjectname/mri/orig, and runs
-all processing steps.
+all processing steps. If subjectname exists, then an error is returned
+when -i is used; but this can be overridden with -force (in which 
+case any pre-existing source volumes are deleted).
 
 2. Manual conversion into mgz:
 
@@ -2768,6 +2789,10 @@ Skips subcortical segmentation steps (same as -nosubcortseg), and does
 not use aseg.mgz for inorm2, wm segmentation, or filling. Use this flag
 for brains that do not support usage of Freesurfers subcortical
 segmentation, such as baby brains, or non-human primates.
+
+-noaseg-inorm2
+
+Does not use aseg.mgz for the second mri_normalize step.
 
 
 EXPERT OPTIONS FILE
