Strip all references to longitudinal subfields.

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -238,9 +238,6 @@ set DoHippoSF_T1 = 0;  # if 1, run hippo subfield seg, exvivo atlas (only T1)
 set DoHippoSF_T1T2 = 0;# if 1, run hippo subfield seg, exvivo atlas (T1 and T2)
 set DoHippoSF_T2 = 0;  # if 1, run hippo subfield seg, exvivo atlas (only T2)
 set T2volHippoSF = ();
-set DoLongHippoSF_T1 = 0; # if 1, run longitudinal subfield segmentation (only T1)
-set BaseLongHippoSF = ();
-set TPlistLongHippoSF = (); # list of time points for longitudinal subfields
 
 # Brainstem substructures
 set DoBSsubst = 0;
@@ -5111,14 +5108,12 @@ endif # DoLabelExvivoEC
 ##-----------   -hippocampal-subfields-T1T2  -----------#
 ##-----------   -hippocampal-subfields-T2  -------------#
 #--------------                        -----------------#
-##-----------   -long-hippocampal-subfields-T1  --------#
-#--------------                        -----------------#
 #--------------  Brainstem Substructures ---------------#
 ##-----------   -brainstem-structures  -----------------#
 #--------------                        -----------------#
 
 # For substructure segmentation of hippocampus or brainstem: check if Matlab runtime is there
-if ($DoHippoSF_T1 || $DoHippoSF_T1T2 || $DoHippoSF_T2 || $DoBSsubst || $DoLongHippoSF_T1) then
+if ($DoHippoSF_T1 || $DoHippoSF_T1T2 || $DoHippoSF_T2 || $DoBSsubst) then
 
   if ( ! -e ${FREESURFER_HOME}/MCRv80/bin/glnxa64/libdctprocess.so \
     && ! -e ${FREESURFER_HOME}/MCRv80/bin/maci64/libdctprocess.jnilib  ) then
@@ -5182,42 +5177,6 @@ if ($DoHippoSF_T1 || $DoHippoSF_T1T2 || $DoHippoSF_T2) then
   else
     set hippohemilist=(left right)
   endif
-endif
-
-
-# longitudinal hippocampal subfields: make sure that required files are there,
-# and that there is at least one time point
-if ($DoLongHippoSF_T1 ) then
-
-  if( $#TPlistLongHippoSF < 1) then
-    echo "ERROR: at least one time point required for longitudinal hippocampal subfields."
-    goto error_exit;
-  endif
-
-  if (! -e ${SUBJECTS_DIR}/${BaseLongHippoSF}/mri/wmparc.mgz || \
-      ! -e ${SUBJECTS_DIR}/${BaseLongHippoSF}/mri/norm.mgz || \
-      ! -e ${SUBJECTS_DIR}/${BaseLongHippoSF}/mri/transforms/talairach.xfm ) then
-    echo "ERROR: cannot find wmparc.mgz or aseg.mgz or talairach.xfm for the base subject."
-    goto error_exit;
-  endif #checking of wmparc.mgz, norm.mgz and talairach.xfm of base
-
-  foreach item ($TPlistLongHippoSF)
-     if (! -e ${SUBJECTS_DIR}/${item}/mri/wmparc.mgz || \
-      ! -e ${SUBJECTS_DIR}/${item}/mri/norm.mgz || \
-      ! -e ${SUBJECTS_DIR}/${item}/mri/transforms/talairach.xfm ) then
-      echo "ERROR: cannot find wmparc.mgz or aseg.mgz or talairach.xfm for time point ${item}."
-      goto error_exit;
-    endif #checking of wmparc.mgz, norm.mgz and talairach.xfm of time points
-  end
-
-  # these tools assume 'left' and 'right' instead of our usual 'lh' and 'rh'
-  if($#hemilist == 1) then
-    if ("$hemilist" == "lh") set hippohemilist=(left)
-    if ("$hemilist" == "rh") set hippohemilist=(right)
-  else
-    set hippohemilist=(left right)
-  endif
-
 endif
 
 
@@ -5336,37 +5295,6 @@ if($DoHippoSF_T2) then
   end
   
   echo $cmd > $touchdir/hippo-subfields-T2.touch
-endif
-
-
-#--------------                        -----------------#
-##------------- -long-hippocampal-subfields-T1  --------#
-#--------------                        -----------------#
-if($DoLongHippoSF_T1) then 
-
-  set HSFLOG = ($subjdir/scripts/long-hippocampal-subfields-T1.log)
-  rm -f $HSFLOG
-  
-  # do hippocampal processing
-  foreach hemi ($hippohemilist)
-    echo "#--------------------------------------------" \
-      |& tee -a $LF |& tee -a $CF |& tee -a $HSFLOG
-    echo "#@# Longitudinal Hippocampal Subfields processing (T1) $hemi `date`" \
-      |& tee -a $SF |& tee -a $LF |& tee -a $CF |& tee -a $HSFLOG
-
-    set cmd = "${FREESURFER_HOME}/bin/segmentSF_T1_long.sh  ${FREESURFER_HOME}/MCRv80 $FREESURFER_HOME $SUBJECTS_DIR $hemi $BaseLongHippoSF"
-
-    foreach item ($TPlistLongHippoSF)
-      set cmd="$cmd $item"
-    end
-
-    echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
-    echo "See log file: $HSFLOG"|& tee -a $LF |& tee -a $CF
-    if($RunIt) $fs_time $cmd |& tee -a $HSFLOG
-    if($status) goto error_exit;
-  end
-  
-  echo $cmd > $touchdir/long-hippo-subfields-T1.touch 
 endif
 
 
@@ -7461,20 +7389,6 @@ while( $#argv != 0 )
       set DoHippoSF_T1 = 1;
       breaksw;
 
-    # longitudinal hippocampal subfield processing (ex vivo atlas, only T1)
-    case "-long-hippocampal-subfields-T1":
-      set DoLongHippoSF_T1 = 1;
-      if( $#argv < 1) goto arg1err;
-      set BaseLongHippoSF = "$argv[1]";  shift;
-      set subjid = "$BaseLongHippoSF";
-      breaksw;
-
-    # add a time point for the longitudinal hippocampal subfields
-    case "-hsfTP"
-      if( $#argv < 1) goto arg1err;
-      set TPlistLongHippoSF = ( $TPlistLongHippoSF $argv[1] ); shift;
-      breaksw;
-
     # hippocampal subfield processing (ex vivo atlas, multispectral)
     case "-hippocampal-subfields-T1T2":
       set DoHippoSF_T1T2 = 1;
@@ -7640,7 +7554,7 @@ check_params:
   endif
 
   if(! $DoVersionsOnly) then
-    if($#subjid != 1 &&  $DoLongHippoSF_T1 != 1) then
+    if($#subjid != 1) then
       echo "ERROR: must specify a subject id"
       exit 1;
     endif
@@ -7784,25 +7698,22 @@ check_params:
     endif
 
     # error if base subject is run as a regular subject:
-    if ( ! $DoCreateBaseSubj )  then
-      if ( ! $DoLongHippoSF_T1 )  then
-        if ( -e $subjdir/$BaseSubjsListFname ) then
-          echo ""
-          echo "ERROR: It appears that this subject ID is an existing"
-          echo "       base/template from longitudinal processing (-base):"
-          echo "       $subjid"
-          echo "       If you are trying to re-run a -base template you"
-          echo "       need to pass the -base and all -tp flags: "
-          echo ""
-          echo "       \' -base <templateid> -tp <tpNid> ... -all \'"
-          echo ""
-          echo "       (Instead of -all you can pass other flags, such"
-          echo "       as -autorecon2 -autorecon3 to run only parts.)"
-          exit 1;
-        endif
+    if ( ! $DoCreateBaseSubj  )  then
+      if ( -e $subjdir/$BaseSubjsListFname ) then
+        echo ""
+        echo "ERROR: It appears that this subject ID is an existing"
+        echo "       base/template from longitudinal processing (-base):"
+        echo "       $subjid"
+        echo "       If you are trying to re-run a -base template you"
+        echo "       need to pass the -base and all -tp flags: "
+        echo ""
+        echo "       \' -base <templateid> -tp <tpNid> ... -all \'"
+        echo ""
+        echo "       (Instead of -all you can pass other flags, such"
+        echo "       as -autorecon2 -autorecon3 to run only parts.)"
+        exit 1;
       endif
     endif
-
 
     # error if existing regular (cross run) is run as base
     if ( $DoCreateBaseSubj && -e $subjdir) then
@@ -7983,7 +7894,7 @@ check_params:
      ! $DoSurfVolume && ! $DoASegMerge && ! $DoCurvStats && ! $DoLabelV1 && \
      ! $DoCreateBaseSubj && ! $DoBaLabels && ! $DoShowEdits && \
      ! $DoLabelExvivoEC && ! $DoPialSurfs && \
-     ! $DoHippoSF_T1 && ! $DoLongHippoSF_T1 && ! $DoHippoSF_T1T2 && ! $DoHippoSF_T2 &&  ! $DoBSsubst && \
+     ! $DoHippoSF_T1 && ! $DoHippoSF_T1T2 && ! $DoHippoSF_T2 &&  ! $DoBSsubst && \
      ! $DoPctSurfCon && ! $DoT2pial && ! $DoFLAIRpial && \
      ! $DoConvertT2Input && ! $DoConvertFlairInput && ! $DoSuperClean &&\
      ! $DoCortParc3 && ! $DoParcStats3 && ! $DoAPas2ASeg ) then
@@ -8369,12 +8280,6 @@ different additional volumes are tried in this mode, in order to prevent files f
 This mode is very similar to the previous one, with the only difference that the main T1 and the 
 additional volumes are used simultaneously in the segmentation.
 
--long-hippocampal-subfields-T1 <baseID> -hsfTP <longTp1> -hsfTP <longTp2> ... -hsfTP <longTpN>
-
-This mode segments multiple time points of the same subject simultaneously with the algorithm 
-described in [19]. baseID is the subject ID of the base, whereas longTpX are the subject ID of 
-the longitudinally processed time points (i.e., running the main longitudinal recon-all stream 
-is thus a prerequisite of this module). 
 
 SEGMENTATION OF BRAINSTEM STRUCTURES
 
@@ -9111,28 +9016,6 @@ cross-sectional stream) to add as a new timepoint and upon which to run
 the longitudinal stream (creating <tpNsubjid>.long.<longbasesubjid>).
 
 
-LONGITUDINAL HIPPOCAMPAL SUBFIELDS
-
-FreeSurfer currently supports longitudinal segmentation of the hippocampal
-subfields on T1-weighted images. The only requirement is that the time points
-do not mix 1mm scans processed with the standard stream and higher resolution
-and scans processed with the -cm flag (conform to min voxel size for hi-res
-support).
-
-To use this module, you first need to run the FreeSurfer longitudinal stream 
-on your data, i.e., steps 1-3 in Section LONGITUDINAL PROCESSING above: cross-
-sectional processing; creation and processing of base; and longitudinal 
-processing.
-
-Then, you can run the following command to segment the subfields from all time
-points simultaneously using the method described in [19]:
-
- recon-all -long-hippocampal-subfields-T1 <baseSubject> -hsfTP <tp1Subject> ...
-           -hsfTP <tp2Subject> ... -hsfTP <tpNSubject>
-
-See further information, including how to visualize the results, at:
-http://surfer.nmr.mgh.harvard.edu/fswiki/LongitudinalHippocampalSubfields
-
 
 USING IMAGES FROM A 3T SCANNER 
 
@@ -9337,10 +9220,6 @@ Truran-Sacrey, D., Boxer, A., and Fischl, B., Bayesian segmentation of brainstem
 structures in MRI. Neuroimage 113, 2015, 184-195.
 http://dx.doi.org/10.1016/j.neuroimage.2015.02.065
 
-[19] Iglesias J.E., Van Leemput K., Augustinack J., Insausti R., Fischl B., and Reuter M.,
-Bayesian longitudinal segmentation of hippocampal substructures in brain MRI using 
-subject-specific atlases, Neuroimage, in press.
-http://dx.doi.org/10.1016/j.neuroimage.2016.07.020
 
 
 
