Fix for bug found by cmet (your friendly neighborhood corporate partner): bc doesn't exist on Googles Centos 6.7 instance, and its existence is not checked by freesurfer, so usage results in an empty var set, which happened to cause mris_calc to segfault.  checks for bc added to recon-all and mri_nu_correct.mni. -nicks

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -7,9 +7,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: greve $
-#    $Date: 2016/01/25 22:57:19 $
-#    $Revision: 1.563 $
+#    $Author: nicks $
+#    $Date: 2016/02/11 20:24:09 $
+#    $Revision: 1.564 $
 #
 # Copyright © 2011-2015 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -26,7 +26,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: recon-all,v 1.563 2016/01/25 22:57:19 greve Exp $';
+set VERSION = '$Id: recon-all,v 1.564 2016/02/11 20:24:09 nicks Exp $';
 set ProgName = `basename $0`;
 set inputargs = ($argv);
 set subjid = ();
@@ -562,6 +562,15 @@ endif
 if($?PBS_JOBID) then
   # If the job has been submitted to launchpad, get jobid
   echo "pbsjob $PBS_JOBID"  >> $LF
+endif
+
+# check for existence of bc (binary calculator)                                                                                               
+# some minimal installs of centos do not have it
+set cmd = (which bc)
+$cmd
+if($status) then
+  echo "ERROR: OS is missing bc (binary calculator) utility" |& tee -a $LF
+  exit 1;
 endif
 
 ## gather all versions here
