Moved the base initialization to rca-base-init

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -392,10 +392,11 @@ set DoneFile = ();
 setenv LANG C # Required by MNI tool
 
 # -------------------------------------------------- #
-set argv0 = ($argv); # make a copy
 set PWD = pwd;
 # better yet, make sure the real pwd is used:
 if ( -e /bin/pwd ) set PWD = /bin/pwd
+
+set argv0 = ($argv); # make a copy
 if($#argv == 0) goto usage_exit;
 set n = `echo $argv | egrep -e -help | wc -l`
 if($n != 0) then
@@ -1240,163 +1241,26 @@ endif
 #------------- Longitudinal 'base' subject input file creation ------------#
 ##------------                   -base                         ------------#
 #-------------                                                 ------------#
+# #DNG MoveToBaseScript
 if ($DoCreateBaseInput && $DoCreateBaseSubj) then
-  echo "#--------------------------------------------" \
-    |& tee -a $LF |& tee -a $CF
-  echo "#@# Longitudinal Base Subject Creation `date`" \
-    |& tee -a $SF |& tee -a $LF |& tee -a $CF
-  if ($#BaseSubjsList == 0) then
-    echo "ERROR: must specify subjects for base subject using -base-tp" \
-      |& tee -a $LF
-    goto error_exit;
-  endif
+  echo "#--------------------------------------------" |& tee -a $LF |& tee -a $CF
+  echo "#@# Longitudinal Base Subject Creation `date`" |& tee -a $SF |& tee -a $LF |& tee -a $CF
   cd $subjdir > /dev/null
   $PWD |& tee -a $LF
-  if($RunIt) rm -f ${BaseSubjsListFname};
-  set subjInVols=();
-  set normInVols=();
-  set ltaXforms=();
-  set lta1forms=();
-  set ltaAforms=();
-  set headInVols=();
-  set geodiff=0;
+  set cmd = (rca-base-init -base $subjid)
   foreach s ($BaseSubjsList)
-    if($RunIt) echo "${s}" >> ${BaseSubjsListFname};
-    set normInVols = ($normInVols ${SUBJECTS_DIR}/${s}/mri/norm.mgz)
-    set headInVols = ($headInVols ${SUBJECTS_DIR}/${s}/mri/T1.mgz)
-    set subjInVols = ($subjInVols ${SUBJECTS_DIR}/${s}/mri/${BaseSubjInvol})
-    set ltaname = ${s}_to_${subjid}.lta
-    set ltaXforms = ($ltaXforms ${subjdir}/mri/transforms/${ltaname})
-    set lta1forms = ($lta1forms ${subjdir}/mri/transforms/${s}_to_${subjid}_norm.lta)
-    set ltaAforms = ($ltaAforms ${subjdir}/mri/transforms/${s}_to_${subjid}_affine.lta)
-
-    # check if geometry differs across time
-    if ( "$s" != "$BaseSubjsList[1]" ) then
-      set cmd = (  mri_diff --notallow-pix --notallow-geo \
-                       ${SUBJECTS_DIR}/$s/mri/rawavg.mgz \
-                       ${SUBJECTS_DIR}/$BaseSubjsList[1]/mri/rawavg.mgz )
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) then
-        $fs_time $cmd |& tee -a $LF
-        if($status) set geodiff = 1;
-      endif
-    endif
+    set cmd = ($cmd -tp $s)
   end
-
-  if ( "$geodiff" == "1" ) then
-    echo "\n*******************************************************************************" |& tee -a $LF
-    echo "WARNING: Image parameters differ across time, maybe due to aquisition changes?" |& tee -a $LF
-    echo "         Consistent changes in, e.g., resolution can potentially bias a " |& tee -a $LF
-    echo "         longitudinal study! You can check image parameters by running mri_info" |& tee -a $LF
-    echo "         on each input image. Will continue in 10 seconds ..." |& tee -a $LF
-    echo "*******************************************************************************\n" |& tee -a $LF
-    sleep 10
+  set cmd = ($cmd -log $LF -cf $CF -sf $SF)
+  set xopts = `fsr-getxopts rca-base-init $XOptsFile`;
+  set cmd = ($cmd $xopts)
+  if($RunIt) then
+    # Don't use fs_time or capture output because it will be captured by rca-base-init
+    echo $cmd
+    $cmd 
+    if($status) goto error_exit
   endif
-
-  if ($#BaseSubjsList == 1) then
-    # if only a single time point, create fake 'base' by making the image upright
-    # this assures that also subjects with a single time point get processes as the other
-    # subjects in the longitudinal stream
-
-    # 1. make the norm upright (base space)
-    set cmd = ( make_upright $normInVols[1] \
-        ${subjdir}/mri/norm_template.mgz $ltaXforms[1] )
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-    if($RunIt) then
-      $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    endif
-
-    # 2. create the upright orig volume
-    set cmd = ( mri_convert -rt cubic \
-        -at $ltaXforms[1] $subjInVols[1] ${subjdir}/mri/orig.mgz )
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-    if($RunIt) then
-      $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    endif
-
-  else #more than 1 time point:
-
-    # create the 'mean/median' norm volume:
-    set cmd = (mri_robust_template --mov ${normInVols})
-    if ($DoAffineBase) then
-      # this is only initial rigid reg
-      set cmd = ($cmd --lta ${lta1forms})
-      set cmd = ($cmd --template ${subjdir}/mri/norm1_template.mgz)
-    else
-      # this is final rigid reg
-      set cmd = ($cmd --lta ${ltaXforms})
-      set cmd = ($cmd --template ${subjdir}/mri/norm_template.mgz)
-    endif
-    set cmd = ($cmd --average ${robust_template_avg_arg})
-    set cmd = ($cmd --sat 4.685 )
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-    if($RunIt) then
-      $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    endif
-
-    if ($DoAffineBase) then
-      # use registration on norm.mgz to initialize affine reg on full head imgs:
-      set cmd = (mri_robust_template --mov ${headInVols})
-      set cmd = ($cmd --lta ${ltaAforms})
-      set cmd = ($cmd --average ${robust_template_avg_arg})
-      set cmd = ($cmd --template ${subjdir}/mri/head_template.mgz)
-      set cmd = ($cmd --sat 4.685 )
-      set cmd = ($cmd --ixforms ${lta1forms})
-      set cmd = ($cmd --affine)
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) then
-        $fs_time $cmd |& tee -a $LF
-        if($status) goto error_exit;
-      endif
-      # use affine reg to init rigid reg on norm.mgz (fine tuning)
-      # not sure if it is really necessary
-      set cmd = (mri_robust_template --mov ${normInVols})
-      set cmd = ($cmd --lta ${ltaXforms})
-      set cmd = ($cmd --average ${robust_template_avg_arg})
-      set cmd = ($cmd --template ${subjdir}/mri/norm_template.mgz)
-      set cmd = ($cmd --sat 4.685 )
-      set cmd = ($cmd --ixforms ${ltaAforms})
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) then
-        $fs_time $cmd |& tee -a $LF
-        if($status) goto error_exit;
-      endif
-    endif
-
-    # create the 'mean/median' input (orig) volume:
-    set cmd = (mri_robust_template --mov ${subjInVols})
-    set cmd = ($cmd --average ${robust_template_avg_arg})
-    set cmd = ($cmd --ixforms ${ltaXforms})
-    set cmd = ($cmd --noit)
-    set cmd = ($cmd --template ${subjdir}/mri/orig.mgz)
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-    if($RunIt) then
-      $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    endif
-
-  endif # more than one time point
-
-  # now create the inverse transforms
-  cd $subjdir/mri/transforms > /dev/null
-  $PWD |& tee -a $LF
-  foreach s ($BaseSubjsList)
-    set cmd = (mri_concatenate_lta -invert1)
-    set cmd = ($cmd ${s}_to_${subjid}.lta)
-    set cmd = ($cmd identity.nofile)
-    set cmd = ($cmd ${subjid}_to_${s}.lta)
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-    if($RunIt) then
-      $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    endif
-  end
-  touch $touchdir/base.touch
 endif
-
 #-----------             -------------#
 ##---------- AUTORECON 1 -------------#
 #-----------             -------------#
@@ -2106,43 +1970,9 @@ skullstrip:
   # base subject stream:
   if($DoCreateBaseSubj) then
     set BMA = brainmask.auto.mgz
-    set BM  = brainmask.mgz  #used later
-    # create lists with all cross brainmasks and all ltas:
-    set bmInVols=""
-    set ltaXforms=""
-    foreach s ($BaseSubjsList)
-      set bmInVols = ($bmInVols ${SUBJECTS_DIR}/${s}/mri/brainmask.mgz)
-      set ltaname = ${s}_to_${subjid}.lta
-      set ltaXforms = ($ltaXforms ${subjdir}/mri/transforms/${ltaname})
-    end
-
-    if ($#bmInVols == 1) then
-      # only a single time point in base
-      set cmd = (mri_convert \
-        -at $ltaXforms[1] \
-        -rt nearest \
-        $bmInVols[1] brainmask_template.mgz )
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) then
-        $fs_time $cmd |& tee -a $LF
-        if($status) goto error_exit;
-      endif
-    else
-      # map all brainmask with nearest neighbor and average 0=mean=logicalOR:
-      set cmd = (mri_robust_template --mov ${bmInVols})
-      set cmd = ($cmd --average 0)
-      set cmd = ($cmd --ixforms ${ltaXforms})
-      set cmd = ($cmd --noit)
-      set cmd = ($cmd --finalnearest)
-      set cmd = ($cmd --template brainmask_template.mgz)
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) then
-        $fs_time $cmd |& tee -a $LF
-        if($status) goto error_exit;
-      endif
-    endif # more than 1 tp
-
-    # create brainmask.auto by applying brainmask_template to T1
+    set BM  = brainmask.mgz  #used later 
+    # Cannot move below to rca-base-init because of T1.mgz
+    # Create brainmask.auto by applying brainmask_template to T1
     # first apply mask and keep deletion edits (1)
     set cmd = (mri_mask -keep_mask_deletion_edits)
     set cmd = ($cmd T1.mgz brainmask_template.mgz $BMA)
@@ -2156,8 +1986,8 @@ skullstrip:
     echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
     if($RunIt) $fs_time $cmd |& tee -a $LF
     if($status) goto error_exit;
-    goto skipped_skullstrip;
-  endif
+    goto skipped_skullstrip; 
+  endif 
 
   # default stream...
   set xopts = `fsr-getxopts mri_watershed $XOptsFile $GlobXOptsFile`;
@@ -7701,6 +7531,12 @@ check_params:
       endif
     endif
 
+    if($DoCreateBaseSubj) then
+      if($#BaseSubjsList == 0) then
+        echo "ERROR: must specify subjects for base subject using -base-tp" 
+        exit 1;
+      endif
+    endif
 
     #---------------------------------------------------------#
     if($#InputList == 0) then
