recon-all. #NF added --samseg and --synthseg. --samseg will run samseg and samseg2recon, so it updates the norm, brainmask, etc. --synthseg only replaces ca_register and ca_label (no m3z is produced). #NF. Also made it so that only defects in cortex are reported

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -1513,7 +1513,55 @@ if($DoMotionCor) then
 
 endif # Motion Correction
 
+if($UseSamseg) then
+  # what to do if have T2, FLAIR, long, etc?
+  set origvol = $subjdir/mri/orig.mgz
+  set samsegdir = $subjdir/mri/samseg.rca
+  set ud = `UpdateNeeded $samsegdir/seg.mgz $origvol`
+  if($ud || $ForceUpdate) then
+    set xopts = `fsr-getxopts samseg $XOptsFile`;
+    set cmd = (samseg --t1w $origvol --refmode t1w --o $samsegdir --threads $OMP_NUM_THREADS $xopts)
+    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
+    if($RunIt) then
+      $fs_time $cmd |& tee -a $LF
+      if($status) goto error_exit;
+    endif
+  endif
+  # Fix hypos and vents
+  set xopts = `fsr-getxopts samseg2recon $XOptsFile`;
+  set cmd = (samseg2recon --s $subjid --samsegdir $samsegdir $xopts) # no update option
+  echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
+  if($RunIt) then
+    $fs_time $cmd |& tee -a $LF
+    if($status) goto error_exit;
+  endif
+endif
 
+if($DoCAReg && $DoCALabel && $UseSynthSeg) then
+  # Note: no m3z will be produced
+  set origvol  = $subjdir/mri/orig.mgz
+  set synthseg = $subjdir/mri/synthseg.rca.mgz
+  set ud = `UpdateNeeded $synthseg $origvol`
+  if($ud || $ForceUpdate) then
+    set xopts = `fsr-getxopts synthseg $XOptsFile`;
+    set cmd = (synthseg --i $origvol --o $synthseg --cpu --threads $OMP_NUM_THREADS $xopts)
+    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
+    if($RunIt) then
+      $fs_time $cmd |& tee -a $LF
+      if($status) goto error_exit;
+      pushd $subjdir/mri 
+      rm -f aseg.auto_noCCseg.mgz
+      ln -sf synthseg.rca.mgz aseg.auto_noCCseg.mgz
+      popd
+    endif
+    set cmd = (mri_convert $synthseg $synthseg --ctab $FREESURFER_HOME/FreeSurferColorLUT.txt)
+    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
+    if($RunIt) then
+      $fs_time $cmd |& tee -a $LF
+      if($status) goto error_exit;
+    endif
+  endif
+endif
 
 # MOD: this takes the externally supplied mask and resamples it into the
 # orig space so that it can be used with mri_em_register
@@ -2468,7 +2516,7 @@ endif # DoCANormalize
 #------------ Canonical Registration --------------#
 ##-----------        -careg          --------------#
 #------------                        --------------#
-if($DoCAReg) then
+if($DoCAReg && ! $UseSynthSeg) then
   echo "#--------------------------------------"|& tee -a $LF |& tee -a $CF
   echo "#@# CA Reg `date`" |& tee -a $SF |& tee -a $LF |& tee -a $CF
   cd $subjdir/mri > /dev/null
@@ -2569,7 +2617,7 @@ endif
 #-------------- SubCort Segmentation --------------#
 ##-------------        -calabel      --------------#
 #--------------                      --------------#
-if($DoCALabel) then
+if($DoCALabel  && ! $UseSynthSeg) then
   echo "#--------------------------------------"|& tee -a $LF |& tee -a $CF
   echo "#@# SubCort Seg `date`" |& tee -a $SF |& tee -a $LF |& tee -a $CF
   cd $subjdir/mri > /dev/null
@@ -7761,6 +7809,42 @@ check_params:
       echo "ERROR: previous calls to recon-all included -conf2hires but this one does not."
       echo "If you want to run without conf2hires, delete file $fname"
       exit 1;
+    endif
+
+    if($UseSamseg && $UseSynthSeg) then
+      echo "ERROR: cannot specify -samseg AND -synthseg"
+      exit 1
+    endif
+
+    if($UseSamseg) then
+      if($longitudinal || $LongSamseg) then
+        echo "ERROR: cannot use -samseg with long or longsamseg"
+        exit 1;
+      endif
+      set DoTalairach      = 0;
+      set DoTalCheck       = 0;
+      set DoNormalization  = 0;
+      set DoSkullStrip     = 0;
+      set DoNuIntensityCor = 0;
+      set DoGCAReg         = 0;
+      set DoRemoveNeck     = 0; # Should be 0 anyway
+      set DoSkullLTA       = 0; # Should be 0 anyway
+      set DoCANormalize    = 0;
+      set DoCAReg          = 0;
+      set DoCALabel        = 0;
+      set DoCCSeg          = 0;
+      set DoASegMerge      = 1;
+      set DoSamsegReg      = 0;
+    endif
+
+    if($UseSynthSeg) then
+      if($longitudinal || $LongSamseg) then
+        echo "ERROR: cannot use -synthseg with long or longsamseg"
+        exit 1;
+      endif
+      set DoCCSeg     = 1;
+      set DoASegMerge = 1;
+      set DoSamsegReg = 1
     endif
 
     # If not using emreg, then use an lta created from the talairach.xfm, get matching GCA
