Fix error message for hippocampal subfield processing.

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -7,9 +7,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: mreuter $
-#    $Date: 2015/10/19 21:17:06 $
-#    $Revision: 1.548 $
+#    $Author: zkaufman $
+#    $Date: 2015/10/23 16:06:50 $
+#    $Revision: 1.549 $
 #
 # Copyright © 2011-2015 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -26,7 +26,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: recon-all,v 1.548 2015/10/19 21:17:06 mreuter Exp $';
+set VERSION = '$Id: recon-all,v 1.549 2015/10/23 16:06:50 zkaufman Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
@@ -7278,13 +7278,13 @@ while( $#argv != 0 )
     # hippocampal subfield processing (ex vivo atlas, multispectral)
     case "-hippocampal-subfields-T1T2":
       set DoHippoSF_T1T2 = 1;
-      if( $#argv < 2) goto arg1err;
+      if( $#argv < 2) goto arg2err;
       set T2volHippoSF = "$argv[1]"; shift;
       set UserSuffix = "$argv[1]"; shift;
       breaksw;
     case "-hippocampal-subfields-T2":
       set DoHippoSF_T2 = 1;
-      if( $#argv < 2) goto arg1err;
+      if( $#argv < 2) goto arg2err;
       set T2volHippoSF = "$argv[1]"; shift;
       set UserSuffix = "$argv[1]"; shift;
       breaksw;
@@ -7374,6 +7374,12 @@ goto parse_args_return;
 arg1err:
 #-------------------------------------------------#
   echo "ERROR: flag $flag requires one argument"
+  exit 1
+
+#-------------------------------------------------#
+arg2err:
+#-------------------------------------------------#
+  echo "ERROR: flag $flag requires two argument"
   exit 1
 
 #-------------------------------------------------#
