Sync from cvs.

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -8,8 +8,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: iglesias $
-#    $Date: 2015/08/03 11:27:01 $
-#    $Revision: 1.542 $
+#    $Date: 2015/08/21 10:57:29 $
+#    $Revision: 1.543 $
 #
 # Copyright © 2011-2015 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -26,7 +26,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: recon-all,v 1.542 2015/08/03 11:27:01 iglesias Exp $';
+set VERSION = '$Id: recon-all,v 1.543 2015/08/21 10:57:29 iglesias Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
@@ -7278,13 +7278,13 @@ while( $#argv != 0 )
     # hippocampal subfield processing (ex vivo atlas, multispectral)
     case "-hippocampal-subfields-T1T2":
       set DoHippoSF_T1T2 = 1;
-      if( $#argv < 2) goto arg1err;
+      if( $#argv < 2) goto arg2err;
       set T2volHippoSF = "$argv[1]"; shift;
       set UserSuffix = "$argv[1]"; shift;
       breaksw;
     case "-hippocampal-subfields-T2":
       set DoHippoSF_T2 = 1;
-      if( $#argv < 2) goto arg1err;
+      if( $#argv < 2) goto arg2err;
       set T2volHippoSF = "$argv[1]"; shift;
       set UserSuffix = "$argv[1]"; shift;
       breaksw;
@@ -7369,6 +7369,12 @@ goto parse_args_return;
 
 #-------------------------------------------------#
 arg1err:
+#-------------------------------------------------#
+  echo "ERROR: flag $flag requires one argument"
+  exit 1
+
+#-------------------------------------------------#
+arg2err:
 #-------------------------------------------------#
   echo "ERROR: flag $flag requires one argument"
   exit 1
