Added ability to use conf2hires. Now calls longmc; this allowed me to remove a lot of the long code from recon-all

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -45,7 +45,7 @@ set CF = ();
 set CF_DEFAULT_NAME = recon-all.cmd;
 set AppendLog    = 1;
 set AppendStatus = 1;
-set DoTime = 0;
+set DoTime = 1;
 if($?SET_FS_CMD_TIMING) set DoTime = 1;
 set fs_time = "";
 set ErrorFile = /dev/null
@@ -130,6 +130,7 @@ set NuIterations = 2;   # Number of iterations for nu intensity correction
 set ConformMin = 0;     # 1=conformed to min dimension
 set ConformKeepDC = 0;  # Keep volume direction cosines when conforming
 set HiRes = 0;          # 1=hires option (conformed to min dimension)
+set DoConf2Hires = 0;
 set Norm3dIters = ();   # passed as -n to *both* mri_normalize runs
 set NormMaxGrad = 1;    # passed as -g to *both* mri_normalize runs
 set Norm1_b = ();       # passed as -b to the *first* mri_normalize only
@@ -1390,187 +1391,25 @@ if($DoMotionCor) then
     |& tee -a $LF |& tee -a $CF
   echo "#@# MotionCor `date`" |& tee -a $SF |& tee -a $LF |& tee -a $CF
 
-  if ($longitudinal) then
-    # longitudinal processing to create orig.mgz:
+  set origvol = $subjdir/mri/orig.mgz
 
-    # in order to create orig.mgz in LONG we need at least 001.mgz in CROSS:
-    if ( ! -e ${SUBJECTS_DIR}/${tpNid}/mri/orig/001.mgz ) then
-      echo "ERROR: no CROSS run data found in ${SUBJECTS_DIR}/${tpNid}/mri/orig/. Make sure to" \
-        |& tee -a $LF
-      echo "have a volume called 001.mgz there." |& tee -a $LF
-      echo "If you have a second run of data call it 002.mgz, etc." \
-        |& tee -a $LF
-      echo "See also: http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Conversion" \
-        |& tee -a $LF
-      goto error_exit;
-    endif
-
-    # use orig/00?.mgz from cross:
-    set CrossList = `ls ${SUBJECTS_DIR}/${tpNid}/mri/orig/[0-9][0-9][0-9].mgz`;
-    set origvol = $subjdir/mri/orig.mgz
-    set rawvol  = $subjdir/mri/rawavg.mgz
-
-    if($#CrossList == 1) then
-      # if only single input, directly resample to base space
-      set cmd = (mri_convert -at $tpNtobase_regfile -odt uchar)
-      set cmd = ($cmd -rt cubic)
-      set cmd = ($cmd ${SUBJECTS_DIR}/${tpNid}/mri/orig/001.mgz)
-      set cmd = ($cmd ${origvol})
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-      # also create rawavg (usually float) image
-      set cmd = (mri_convert -at $tpNtobase_regfile )
-      set cmd = ($cmd -rt cubic)
-      set cmd = ($cmd ${SUBJECTS_DIR}/${tpNid}/mri/orig/001.mgz)
-      set cmd = ($cmd ${rawvol})
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-      goto motioncor_post_process
-    endif
-
-    # if ltas and iscales exist in cross, copy them over
-    set CrossLtas = `ls ${SUBJECTS_DIR}/${tpNid}/mri/orig/[0-9][0-9][0-9].lta`;
-    set CrossIscales = `ls ${SUBJECTS_DIR}/${tpNid}/mri/orig/[0-9][0-9][0-9]-iscale.txt`;
-    if ( $#CrossLtas > 0 ) then
-      # check if one lta for each mgz:
-      # here we could better check if really each 00?.mgz has its own 00?.lta in future
-      if ( $#CrossList != $#CrossLtas ) then
-        echo "ERROR: Orig 00?.mgz runs and number of 00?.lta files must agree in" \
-         |& tee -a $LF
-        echo "${SUBJECTS_DIR}/${tpNid}/mri/orig/" \
-         |& tee -a $LF
-        goto error_exit;
-      endif
-      #copy ltas:
-      cd $subjdir/mri/
-      set cmd = (cp -vf ${CrossLtas})
-      set cmd = ($cmd orig/)
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-      #copy iscales if available:
-      if ($#CrossIscales > 0) then
-        # here we could better check if really each 00?.mgz has its own iscale file in future
-        if ( $#CrossList != $#CrossIscales ) then
-          echo "ERROR: Orig 00?.mgz runs and number of 00?-iscale.txt files must agree in" \
-            |& tee -a $LF
-          echo "${SUBJECTS_DIR}/${tpNid}/mri/orig/" \
-            |& tee -a $LF
-          goto error_exit;
-        endif
-        cd $subjdir/mri/
-        set cmd = (cp -vf ${CrossIscales})
-        set cmd = ($cmd orig/)
-        echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-        if($RunIt) $fs_time $cmd |& tee -a $LF
-        if($status) goto error_exit;
-      endif
-    else
-      # else the ltas don't exist (maybe because 5.0 or fsl was used,
-      # they are created by 5.1+ in cross sectional stream)
-      # if more than one input, re-receate the ltas:
-      if($#CrossList > 1) then
-        # set output names for ltas and iscales in long dir
-        set LongLtas = ""
-        set LongIscales = ""
-        foreach nthid ($CrossList)
-          set nthname=`basename $nthid .mgz`
-          set nthdir=$subjdir/mri/orig
-          set nthlta=${nthdir}/${nthname}.lta
-          set LongLtas=($LongLtas $nthlta)
-          set LongIscales=($LongIscales $nthdir/${nthname}-iscale.txt)
-        end
-        # perform motion correction again to obtain the ltas (but in long dir, don't touch cross):
-        set rawavg  = $subjdir/mri/rawavg.mgz
-        # the output rawavg in long will be ignored and not used for anything
-        # except maybe debugging, we only need the ltas and iscales!
-        set cmd = (mri_robust_template)
-        set cmd = ($cmd --mov ${CrossList})
-        set cmd = ($cmd --average 1)
-        set cmd = ($cmd --template ${rawavg})
-        set cmd = ($cmd --satit)
-        set cmd = ($cmd --inittp 1)
-        set cmd = ($cmd --fixtp)
-        set cmd = ($cmd --noit)
-        set cmd = ($cmd --iscale)
-        set cmd = ($cmd --iscaleout $LongIscales)
-        set cmd = ($cmd --subsample 200)
-        set cmd = ($cmd --lta $LongLtas)
-        echo "#-----------------------------------------------"
-        $PWD |& tee -a $LF
-        echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-        if($RunIt) then
-          $fs_time $cmd |& tee -a $LF
-          if($status) goto error_exit;
-        endif
-        # better get rid of rawavg to avoid confusion
-        # as it is not in the base/long space, but in 001.mgz space
-        set cmd = (rm -f $rawavg )
-        echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-        if($RunIt) then
-          $fs_time $cmd |& tee -a $LF
-          if($status) goto error_exit;
-        endif
-
-      else
-        # we should never get here, this case hase been dealt with above
-        echo Only single run - should not get here
-        goto error_exit;
-      endif
-    endif
-
-    # now we have the ltas in long (current tp : subjdir)
-    set LongLtas = `ls $subjdir/mri/orig/[0-9][0-9][0-9].lta`;
-    set LongIscales = `ls $subjdir/mri/orig/[0-9][0-9][0-9]-iscale.txt`;
-
-    # concat ltas (e.g. 002 -> 001 -> base/orig.mgz)
-    set ConcatLtas = ""
-    foreach nthlta ($LongLtas)
-      set nthname=`basename $nthlta .lta`
-      set nthdir=$subjdir/mri/orig
-      set concatlta=${nthdir}/${nthname}-long.lta
-      set ConcatLtas=($ConcatLtas $nthdir/${nthname}-long.lta)
-      set cmd = (mri_concatenate_lta $nthlta $tpNtobase_regfile $concatlta)
-      echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-      if($RunIt) $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    end
-
-    # use mri_robust_template just to create the average in base orig space:
-    set cmd = (mri_robust_template)
-    set cmd = ($cmd --mov ${CrossList})
-    set cmd = ($cmd --average 1)
-    set cmd = ($cmd --ixforms ${ConcatLtas})
-    if ($#LongIscales > 0) then
-      set cmd = ($cmd --iscalein ${LongIscales})
-    endif
-    set cmd = ($cmd --noit)
-    set cmd = ($cmd --template ${rawvol})
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
+  if($longitudinal) then
+    set cmd = (longmc -long $tpNid $longbaseid)
+    if($DoConf2Hires) set cmd = ($cmd -conf2hires)
+    set xopts = `fsr-getxopts longmc $XOptsFile`;
+    set cmd = ($cmd $xopts)
     if($RunIt) then
       $fs_time $cmd |& tee -a $LF
       if($status) goto error_exit;
+      echo $cmd > $touchdir/longmc.touch
     endif
-
-    # make sure orig is uchar:
-    set cmd = (mri_convert -odt uchar ${rawvol} ${origvol})
-    echo "\n $cmd \n" |& tee -a $LF |& tee -a $CF
-    if($RunIt) then
-      $fs_time $cmd |& tee -a $LF
-      if($status) goto error_exit;
-    endif
-
     goto motioncor_post_process
-
-  endif #longitudinal
+  endif 
 
   # base processing (we do not need to do anything,
   #   as orig should be there, rawavg is not there, due to difficulties of
   #   averaging different image geometries across time)
-  if ($DoCreateBaseSubj) then
-    set origvol = $subjdir/mri/orig.mgz
+  if($DoCreateBaseSubj) then
     goto motioncor_post_process
   endif
 
@@ -4204,11 +4043,30 @@ if($DoCortParc) then
   endif
 endif
 
+if($DoConf2Hires) then
+  # This places the surfaces on the highres T1 (and T2)
+  set cmd = (conf2hires --threads $OMP_NUM_THREADS)
+  if($DoT2pial == 0)    set cmd = ($cmd --no-T2)
+  if($DoT2pial == 1)    set cmd = ($cmd --T2)
+  if($DoFLAIRpial == 1) set cmd = ($cmd --FLAIR)
+  if($longitudinal) then
+    set cmd = ($cmd --longitudinal $tpNid $longbaseid)
+  else
+    set cmd = ($cmd --s $subjid)
+  endif
+  if($UseCubic == 1) set cmd = ($cmd --cubic)
+  if($UseCubic == 0) set cmd = ($cmd --trilin)
+  echo $cmd | tee -a $LF
+  if($RunIt) $fs_time $cmd |& tee -a $LF
+  if($status) goto error_exit;
+  echo $cmd > $touchdir/conf2hires
+endif
+
 #----------------                    -------------------#
 #---------------- Make Pial Surfaces -------------------#
 ##---------------       -pial        -------------------#
 #----------------                    -------------------#
-if($DoPialSurfs) then
+if($DoPialSurfs && ! $DoConf2Hires) then
   set CMDFS = () # see earlier notes on -parallel implementation
   foreach hemi ($hemilist)
     echo "#--------------------------------------------" \
@@ -4284,7 +4142,7 @@ endif
 ##---------------     -T2pial  and  -FLAIRpial        ----------------#
 #----------------                                     ----------------#
 # note: the registration portion requires existence of both surfaces
-if($DoT2pial || $DoFLAIRpial) then
+if(($DoT2pial || $DoFLAIRpial) && ! $DoConf2Hires) then
   echo "#--------------------------------------------" \
     |& tee -a $LF |& tee -a $CF
   echo "#@# Refine Pial Surfs w/ T2/FLAIR `date`" \
@@ -7335,6 +7193,20 @@ while( $#argv != 0 )
       # means aseg.mgz can be created with hi-res data).
       breaksw
 
+    case "-conf2hires":
+      set DoConf2Hires = 1;
+      set DoSurfVolume = 1;
+      set HiRes = 0;
+      set ConformMin = 0;
+      set UseCubic = 0; # The conformed should be generated with trilin interp
+      set DoPialSurfs = 0; # will be done in conf2hires
+      which conf2hires >& /dev/null
+      if($status) then
+        echo "ERROR: cannot find conf2hires"
+        exit 1;
+      endif
+      breaksw
+
     case "-use-aseg":
       set UseAseg = 1;
       breaksw
@@ -7710,6 +7582,29 @@ check_params:
     if($TH3Flag)   set TH3Opt = "-th3"
     if(! $TH3Flag) set TH3Opt = "-no-th3"
 
+    if($DoConf2Hires) then
+      set DoPialSurfs = 0;
+      if($HiRes) then
+        echo "ERROR: cannot use -hires with -conf2hires"
+        exit 1;
+      endif
+      if($ConformMin) then
+        echo "ERROR: cannot use -cm with -conf2hires"
+        exit 1;
+      endif
+      if($DoCreateBaseSubj) then
+        echo "ERROR: do not use -conf2hires with -base (it is unneeded)"
+        exit 1;
+      endif
+    endif
+
+    set fname = $subjdir/scripts/DoConf2Hires
+    if(-e $fname && ! $DoConf2Hires && ($DoPialSurfs || $DoT2pial)) then
+      echo "ERROR: previous calls to recon-all included -conf2hires but this one does not."
+      echo "If you want to run without conf2hires, delete file $fname"
+      exit 1;
+    endif
+
     #------------ Longitudinal ---------------#
     if($longitudinal) then
 
@@ -7999,6 +7894,10 @@ check_params:
     set GlobXOptsFile = ()
   endif
 
+  if($DoConf2Hires) then
+    touch $subjdir/scripts/DoConf2Hires
+  endif
+
   if($#NotifyFile != 0) then
     rm -f $NotifyFile;
     set tmpdir = `dirname $NotifyFile`;
@@ -8038,7 +7937,7 @@ check_params:
      ! $DoMakefile && ! $DoParallel && ! $DoRelabelHypos && ! $DoCurvHK && \
      ! $DoSurfVolume && ! $DoASegMerge && ! $DoCCSeg && ! $DoCurvStats && ! $DoLabelV1 && \
      ! $DoCreateBaseSubj && ! $DoBaLabels && ! $DoShowEdits && \
-     ! $DoLabelExvivoEC && ! $DoPialSurfs && \
+     ! $DoLabelExvivoEC && ! $DoPialSurfs && ! $DoConf2Hires && \
      ! $DoSubfields  && \
      ! $DoPctSurfCon && ! $DoT2pial && ! $DoFLAIRpial && \
      ! $DoConvertT2Input && ! $DoConvertFlairInput && ! $DoSuperClean &&\
