enhanced -tal-check to include QA checking of Avis talairach_avi.log file: z-score must be greater than -5

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -7,9 +7,9 @@
 #
 # Original Author: Doug Greve
 # CVS Revision Info:
-#    $Author: greve $
-#    $Date: 2007/11/28 01:21:06 $
-#    $Revision: 1.148 $
+#    $Author: nicks $
+#    $Date: 2007/12/04 00:28:47 $
+#    $Revision: 1.149 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -27,7 +27,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: recon-all,v 1.148 2007/11/28 01:21:06 greve Exp $';
+set VERSION = '$Id: recon-all,v 1.149 2007/12/04 00:28:47 nicks Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
@@ -845,6 +845,7 @@ if($DoTalCheck) then
   echo "#@# Talairach Failure Detection `date`" \
     |& tee -a $SF |& tee -a $LF |& tee -a $CF
   cd $subjdir/mri > /dev/null
+  # first run Laurence's AFD tool:
   set xopts = `fsr-getxopts talairach_afd $XOptsFile`;
   set xfm = transforms/talairach.xfm
   set cmd = (talairach_afd -T 0.005 -xfm $xfm $xopts)
@@ -853,6 +854,27 @@ if($DoTalCheck) then
   if($RunIt) then
     $fs_time $cmd |& tee -a $LF
     if($status) goto error_exit;
+  endif
+  # now run Avi's QA check on the results found in talairach_avi.log
+  set cmd = (awk -f $FREESURFER_HOME/bin/extract_talairach_avi_QA.awk)
+  set cmd = ($cmd $subjdir/mri/transforms/talairach_avi.log)
+  set qalog = ($subjdir/mri/transforms/talairach_avi_QA.log)
+  echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
+  if($RunIt) then
+    $fs_time $cmd |& tee -a $LF >& $qalog
+    if($status) goto error_exit;
+    set talAviQA=`grep "TalAviQA" $qalog | awk '{print $2}'`
+    echo "TalAviQA: ${talAviQA}" |& tee -a $LF
+    set mean=(0.9787) # buckner40 mean TalAviQA
+    set std=(0.0046)  # buckner40 std TalAviQA
+    set zscore=`echo "scale=0;(${talAviQA} - ${mean}) / ${std}" | bc`
+    echo "z-score: $zscore"
+    set zscoreThreshold=(-5) # conservative value, but catches M.Harms subj.
+    if ($zscore < $zscoreThreshold) then
+        echo "ERROR: Talairach QA check failed!"
+        echo "       z-score = ${zscore} < ${zscoreThreshold} = threshold"
+        goto error_exit;
+    endif
   endif
 endif
 
@@ -2469,18 +2491,20 @@ error_exit:
       mail -s "$subjid ERROR `date`" $mailuser
   endif
   # Create an error file with date, cmd, etc of error
-  echo "------------------------------" > $ErrorFile
-  echo "SUBJECT $subjid" >> $ErrorFile
-  echo "DATE `date`"     >> $ErrorFile
-  echo "USER $user"      >> $ErrorFile
-  echo "HOST `hostname`" >> $ErrorFile
-  echo "PROCESSOR `uname -m`" >> $ErrorFile
-  echo "OS `uname -s`"       >> $ErrorFile
-  uname -a         >> $ErrorFile
-  echo $VERSION    >> $ErrorFile
-  echo $0          >> $ErrorFile
-  echo "PWD `pwd`" >> $ErrorFile
-  echo "CMD $cmd"  >> $ErrorFile
+  if ( $?ErrorFile ) then
+    echo "------------------------------" > $ErrorFile
+    echo "SUBJECT $subjid" >> $ErrorFile
+    echo "DATE `date`"     >> $ErrorFile
+    echo "USER $user"      >> $ErrorFile
+    echo "HOST `hostname`" >> $ErrorFile
+    echo "PROCESSOR `uname -m`" >> $ErrorFile
+    echo "OS `uname -s`"       >> $ErrorFile
+    uname -a         >> $ErrorFile
+    echo $VERSION    >> $ErrorFile
+    echo $0          >> $ErrorFile
+    echo "PWD `pwd`" >> $ErrorFile
+    echo "CMD $cmd"  >> $ErrorFile
+  endif
   # Finally exit
   exit 1;
 endif
