Added more support. Copied from dev.

diff --git a/scripts/reg-feat2anat b/scripts/reg-feat2anat
--- a/scripts/reg-feat2anat
+++ b/scripts/reg-feat2anat
@@ -2,7 +2,7 @@
 # reg-feat2anat
 # Registers example func to freesurfer using fsl
 
-set VERSION = '$Id: reg-feat2anat,v 1.14.2.5 2006/03/25 00:34:51 greve Exp $'
+set VERSION = '$Id: reg-feat2anat,v 1.14.2.6 2006/05/23 22:39:03 greve Exp $'
 set FeatDir = ();
 set subject = ();
 set anatvol = brain;
@@ -22,12 +22,12 @@ set PrintHelp = 0;
 
 set cmdargs = ($argv);
 if($#argv == 0)  goto usage_exit;
-set n = `echo $argv | grep -e --version | wc -l` 
+set n = `echo $argv | egrep -e --version | wc -l` 
 if($n != 0) then
   echo $VERSION
   exit 1;
 endif
-set n = `echo $argv | grep -e --help | wc -l` 
+set n = `echo $argv | egrep -e --help | wc -l` 
 if($n != 0) then
   set PrintHelp = 1;
   goto usage_exit;
@@ -456,9 +456,18 @@ if(! -e $FeatDir) then
   echo "ERROR: cannot find feat dir $FeatDir"
   exit 1;
 endif
-if($#subject == 0) then
-  echo "ERROR: must specify a FreeSurfer subject"
-  exit 1;
+if(! $manual) then
+  if($#subject == 0) then
+    echo "ERROR: must specify a FreeSurfer subject"
+    exit 1;
+  endif
+else
+  set anat2exf_regdat = $FeatDir/reg/freesurfer/anat2exf.register.dat
+  if(! -e $anat2exf_regdat) then
+    echo "ERROR: cannot find $anat2exf_regdat"
+    exit 1;
+  endif
+  set subject = `cat $anat2exf_regdat | head -1`;
 endif
 if($?SUBJECTS_DIR == 0) then
   echo "ERROR: FreeSurfer environment variable SUBJECTS_DIR not defined"
