Now uses bbr by default

diff --git a/scripts/reg-feat2anat b/scripts/reg-feat2anat
--- a/scripts/reg-feat2anat
+++ b/scripts/reg-feat2anat
@@ -8,8 +8,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/08/27 19:12:48 $
-#    $Revision: 1.31 $
+#    $Date: 2008/12/17 21:26:59 $
+#    $Revision: 1.32 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -25,7 +25,7 @@
 #
 
 
-set VERSION = '$Id: reg-feat2anat,v 1.31 2008/08/27 19:12:48 greve Exp $'
+set VERSION = '$Id: reg-feat2anat,v 1.32 2008/12/17 21:26:59 greve Exp $'
 set FeatDir = ();
 set subject = ();
 set anatvol = brainmask;
@@ -42,7 +42,7 @@ set manxfm = func2anat;
 set DoBETFunc = 0; # Not with FSL 4.0
 set title = ();
 set UseSPM = 0;
-set DoSegReg = 0;
+set DoBBR = 1; # On by default
 
 set PrintHelp = 0;
 
@@ -266,16 +266,28 @@ if(! $UseSPM) then
     --maxangle $maxangle  --initfslmat $exf2anat_init_fslmat \
     --tmp $FeatDir/reg/freesurfer/tmp --out $outvol.$fslext)
   if($DoBETFunc) set cmd = ($cmd --betfunc) # Not with FSL 4.0
-  if($DoSegReg) set cmd = ($cmd --segreg $segregdat)
+  echo "" | tee -a $LF
   echo $cmd | tee -a $LF
   $cmd | tee -a $LF
   if($status) exit 1;
+
+  if($DoBBR) then
+    cp $anat2exf_regdat $anat2exf_regdat.bbr.init
+    set cmd = (bbregister --mov $tempvol --bold \
+      --init-reg $anat2exf_regdat --reg $anat2exf_regdat)
+    echo "" | tee -a $LF
+    echo $cmd | tee -a $LF
+    $cmd | tee -a $LF
+    if($status) exit 1;
+  endif
+
 else
   # Or use SPM2 or SPM5 (but don't tell Steve)
   # This will probably only work on x32 machines
   set cmd = (spmregister --s $subject --reg $anat2exf_regdat \
     --mov $tempvol  --fsvol $anatvol \
     --tmp $FeatDir/reg/freesurfer/tmp )
+  echo "" | tee -a $LF
   echo $cmd | tee -a $LF
   $cmd | tee -a $LF
   if($status) exit 1;
@@ -295,6 +307,7 @@ set cmd = ($TKR --targ $stdbrain \
             --mov $FeatDir/example_func.$fslext \
             --fslreg $FeatDir/reg/example_func2standard.mat \
             --reg $std2exf_regdat --noedit)
+echo "" | tee -a $LF
 echo $cmd | tee -a $LF
 $cmd |& tee -a $LF
 if($status) then
@@ -307,6 +320,7 @@ set cmd = ($MM -fsl \
   -im $FeatDir/reg/freesurfer/exf2anat.fsl.mat \
   -iim $FeatDir/reg/example_func2standard.mat \
   -om $FeatDir/reg/freesurfer/std2anat.fsl.mat)
+echo "" | tee -a $LF
 echo $cmd | tee -a $LF
 $cmd |& tee -a $LF
 if($status) then
@@ -333,7 +347,8 @@ set cmd = ($cmd --fslreg $exf2anat_fslmat)
 set cmd = ($cmd --surf orig);  # for visual inspection
 echo ""
 echo "To visually check your results, run:" | tee -a $LF
-echo $cmd --tag | tee -a $LF
+echo $cmd --tag | sed 's/_cmdl//g' | tee -a $LF
+# note: the sed will remove the _cmdl from the tkregister2 cmd
 echo ""
 echo ""
 
@@ -432,8 +447,13 @@ while( $#argv != 0 )
       set UseSPM = 1;
       breaksw
 
+    case "--bbr":
     case "--segreg":
-      set DoSegReg = 1;
+      set DoBBR = 1;
+      breaksw
+
+    case "--no-bbr":
+      set DoBBR = 0;
       breaksw
 
     case "--debug":
@@ -477,6 +497,20 @@ goto parse_args_return;
 
 ############--------------##################
 check_params:
+
+if($DoBBR) then
+  which bbregister > /dev/null
+  if($status) then
+    echo ""
+    echo "ERROR: reg-feat2anat is currently configured to run bbregister."
+    echo "However, it cannot be found in your path. Make sure it is"
+    echo "in your path and then rerun reg-feat2anat. Alternatively, you"
+    echo "can run reg-feat2anat with --no-bbr, but the results might not"
+    echo "be as accurate"
+    echo ""
+    exit 1;
+  endif
+endif
 
 if($#FeatDir == 0) then
   echo "ERROR: must specify feat dir"
@@ -546,6 +580,7 @@ usage_exit:
   echo " --bet            : run betfunc on example_func (not with FSL 4.0)"
   echo " "
   echo " --title        : title for tkregister window"
+  echo " --no-bbr       : do not use boundary-based registration"
   echo " --spm          : use SPM instead of flirt, 6 dof only"
   echo " --version      : print version and exit"
   echo " --help         : print help and exit"
