Now exits with a message to use tkregister2

diff --git a/scripts/spmmat2register b/scripts/spmmat2register
--- a/scripts/spmmat2register
+++ b/scripts/spmmat2register
@@ -1,6 +1,13 @@
 #!/bin/csh -f
 
-set SPMMAT2REGISTER_VER = '$Id: spmmat2register,v 1.9 2000/08/28 20:40:40 greve Exp $';
+echo ""
+echo "ERROR: spmmat2register is obsolete. Use tkregister2."
+echo "Run tkregister2 with --help for extensive documentation."
+echo "In particular, look at the section called USING WITH FSL and SPM"
+echo ""
+exit 1;
+
+set SPMMAT2REGISTER_VER = '$Id: spmmat2register,v 1.10 2004/11/17 22:50:58 greve Exp $';
 
 set OutStream = /dev/null;
 set funcvol   = ();
