Better error checking

diff --git a/scripts/spmregister b/scripts/spmregister
--- a/scripts/spmregister
+++ b/scripts/spmregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2008/06/05 22:18:16 $
-#    $Revision: 1.34 $
+#    $Date: 2008/07/07 13:53:10 $
+#    $Revision: 1.35 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -23,7 +23,7 @@
 #
 
 #
-set VERSION = '$Id: spmregister,v 1.34 2008/06/05 22:18:16 greve Exp $';
+set VERSION = '$Id: spmregister,v 1.35 2008/07/07 13:53:10 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
@@ -558,6 +558,10 @@ check_params:
 
   if($#subjid == 0) then
     echo "ERROR: must spec a subject id"
+    exit 1;
+  endif
+  if(! -e $SUBJECTS_DIR/$subjid) then
+    echo "ERROR: cannot find $subjid in $SUBJECTS_DIR"
     exit 1;
   endif
 
