Now autodetects mgz

diff --git a/scripts/spmregister b/scripts/spmregister
--- a/scripts/spmregister
+++ b/scripts/spmregister
@@ -1,7 +1,7 @@
 #!/bin/csh -f
 # 
-# $Id: spmregister,v 1.9 2005/05/20 21:31:31 greve Exp $
-set VERSION = '$Id: spmregister,v 1.9 2005/05/20 21:31:31 greve Exp $';
+# $Id: spmregister,v 1.10 2005/08/24 20:39:40 greve Exp $
+set VERSION = '$Id: spmregister,v 1.10 2005/08/24 20:39:40 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
@@ -16,6 +16,7 @@ set MLF = ();
 set PrintHelp = 0;
 set zero_center = 1; 
 set frame = 0;
+set MGZ = ();
 # zero_center forces mri_convert to set the coordinate
 # of the center to zero. This allows spm to register
 # two volumes when they do not overlap in the native
@@ -59,9 +60,13 @@ set DateString = "`date '+%y%m%d%H%M'`"
 
 # Convert reference to analyze
 set refvol = $SUBJECTS_DIR/$subjid/mri/$fsvol
-if(! -e $refvol) then
-  echo "ERROR: $refvol not found"
-  exit 1;
+if(! -e $refvol/COR-.info) then
+  set MGZ = .mgz
+  set refvol = $SUBJECTS_DIR/$subjid/mri/$fsvol$MGZ
+  if(! -e $refvol) then
+    echo "ERROR: $refvol not found in either COR or MGZ formats"
+    exit 1;
+  endif
 endif
 set refvolbase = $tmpdir/refvol.spmregister
 set refvolimg  = $refvolbase.img
@@ -189,6 +194,7 @@ set TKR2 = tkregister2
 set cmd = ($TKR2 --s $subjid --mov $movvolimg \
            --regheader --noedit --reg $regfile \
            --targ $refvolimg );
+if($#MGZ) set cmd = ($cmd --mgz);
 echo "--------------------------------------------------" |& tee -a $LF
 pwd        |& tee -a $LF
 echo $cmd  |& tee -a $LF
@@ -274,6 +280,10 @@ while( $#argv != 0 )
 
     case "--zero-nocenter":
       set zero_center = 0;
+      breaksw
+
+    case "--mgz":
+      set MGZ = .mgz;
       breaksw
 
     case "--verbose":
