Added ability to do bbr

diff --git a/scripts/spmregister b/scripts/spmregister
--- a/scripts/spmregister
+++ b/scripts/spmregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/11/06 02:41:54 $
-#    $Revision: 1.24 $
+#    $Date: 2008/02/07 22:57:04 $
+#    $Revision: 1.25 $
 #
 # Copyright (C) 2002-2007,
 # The General Hospital Corporation (Boston, MA).
@@ -23,7 +23,7 @@
 #
 
 #
-set VERSION = '$Id: spmregister,v 1.24 2007/11/06 02:41:54 greve Exp $';
+set VERSION = '$Id: spmregister,v 1.25 2008/02/07 22:57:04 greve Exp $';
 set inputargs = ($argv);
 
 set subjid = ();
@@ -43,6 +43,7 @@ set templateout = ();
 set MGZ = ();
 set nolog = 0;
 set matlab = matlab
+set DoSegReg = 0;
 
 if($?FS_SPMREG_MATLAB) then
   set matlab = $FS_SPMREG_MATLAB
@@ -270,6 +271,17 @@ if($LeftRightReverse) then
   echo ""
 endif
 
+if($DoSegReg) then
+  set cmd = (mri_segreg --reg $regfile --mov $movvol \
+     --out-reg $segregfile --cost $segregfile.segreg.cost)
+  echo $cmd | tee -a $LF
+  $cmd |& tee -a $LF
+  if($status) then
+    echo "ERROR: mri_segreg failed" | tee -a $LF
+    exit 1;
+  endif
+endif
+
 # Cleanup
 if($cleanup) then
   echo "Cleaning up" |& tee -a $LF
@@ -342,6 +354,12 @@ while( $#argv != 0 )
     case "--reg":
       if ( $#argv < 1) goto arg1err;
       set regfile = $argv[1]; shift;
+      breaksw
+
+    case "--segreg":
+      if ( $#argv < 1) goto arg1err;
+      set segregfile = $argv[1]; shift;
+      set DoSegReg = 1;
       breaksw
 
     case "--tmp":
