Copied from dev. Now checks for multiple formats. Now looks for nii.gz before nii if FSF_OUTPUT_FORMAT is nii.gz

diff --git a/scripts/stem2fname b/scripts/stem2fname
--- a/scripts/stem2fname
+++ b/scripts/stem2fname
@@ -12,20 +12,19 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2007/09/21 23:29:20 $
-#    $Revision: 1.2 $
+#    $Date: 2011/10/05 22:12:45 $
+#    $Revision: 1.3.2.1 $
 #
-# Copyright (C) 2002-2007,
-# The General Hospital Corporation (Boston, MA). 
-# All rights reserved.
+# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
-# Distribution, usage and copying of this software is covered under the
-# terms found in the License Agreement file named 'COPYING' found in the
-# FreeSurfer source code root directory, and duplicated here:
-# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
+# Terms and conditions for use, reproduction, distribution and contribution
+# are found in the 'FreeSurfer Software License Agreement' contained
+# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
 #
-# General inquiries: freesurfer@nmr.mgh.harvard.edu
-# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
+# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
+#
+# Reporting: freesurfer@nmr.mgh.harvard.edu
+#
 #
 
 
@@ -39,14 +38,41 @@ endif
 
 set stem = $argv[1];
 
-foreach fmt (mgh mgz nii nii.gz bhdr img w)
-  set testfile = $stem.$fmt
-  if(-e $testfile) then
-    echo $testfile
-    exit 0;
+set fmtlist = (mgh mgz nii nii.gz bhdr img w)
+if($?FSF_OUTPUT_FORMAT) then
+  if($FSF_OUTPUT_FORMAT == nii.gz) then
+    set fmtlist = (mgh mgz nii.gz nii bhdr img w)
   endif
+endif
+
+
+# Make sure that the desired FSF OUTPUT format is first
+#if($?FSF_OUTPUT_FORMAT) then
+#  set fmtlist = ($FSF_OUTPUT_FORMAT $fmtlist)
+#endif
+
+@ n = 0;
+set tstlist = ();
+foreach fmt ($fmtlist)
+  set testfile = $stem.$fmt
+  if(-e $testfile) set tstlist = ($tstlist $testfile);
 end
 
-echo "ERROR: could not determine file for $stem"
+if($#tstlist == 0) then
+  echo "ERROR: could not determine file for $stem"
+  exit 1;
+endif
+
+echo "$tstlist[1]"
+if($#tstlist == 1) exit 0;
+
+# only option
+if($#tstlist > 1) then
+  echo "WARNING: multiple formats found for $stem" > /dev/stderr
+  echo "  USING: $tstlist[1]" > /dev/stderr
+  exit 1;
+endif
+
+
 exit 1;
 ##########################################
