surfreg. #NF. Added ability to set number of threads. Added ability to init with an LTA. Now runs xhemireg with one hemi if only one is specified.

diff --git a/scripts/surfreg b/scripts/surfreg
--- a/scripts/surfreg
+++ b/scripts/surfreg
@@ -13,6 +13,8 @@ set cleanup = 1;
 set OutSurf = ();
 set InitSurf = ();
 set annot = aparc.annot;
+set InitLTA = ()
+set threads = 1
 set LF = ();
 
 set LF = ();
@@ -63,6 +65,7 @@ if($DoXHemi) then
   if(! -e $sd/lrrev.register.dat) then
     echo "xhemi does not exist for $subject, running now"
     set cmd = (xhemireg --s $subject)
+    if($#hemilist == 1) set cmd = ($cmd --$hemilist)
     echo $cmd | tee -a $LF
     $cmd | tee -a $LF
     if($status) exit 1;
@@ -81,7 +84,8 @@ foreach hemi ($hemilist)
   endif
   set outreg = $sd/surf/$hemi.$OutSurf
   set InitSurfPath = $sd/surf/$hemi.$InitSurf
-  set cmd = (mris_register -curv)
+  set cmd = (mris_register -curv -threads $threads)
+  if($#InitLTA) set cmd = ($cmd -reg $InitLTA) # consider -norot as well
   if($#annot) set cmd = ($cmd -annot $annot)
   if($UseNoNeg) set cmd = ($cmd -remove_negative 1)
   set cmd = ($cmd $InitSurfPath $AvgTif $outreg)
@@ -123,10 +127,6 @@ while( $#argv != 0 )
     case "--t":
       if($#argv < 1) goto arg1err;
       set target = $argv[1]; shift;
-      if(! -e $SUBJECTS_DIR/$target) then
-        echo "ERROR: cannot find $target in $SUBJECTS_DIR"
-        exit 1;
-      endif
       breaksw
 
     case "--o":
@@ -143,6 +143,15 @@ while( $#argv != 0 )
     case "--log":
       if($#argv < 1) goto arg1err;
       set LF = $argv[1]; shift;
+      breaksw
+
+    case "--lta":
+      if($#argv < 1) goto arg1err;
+      set InitLTA = $argv[1]; shift;
+      if(! -e $InitLTA) then
+        echo "ERROR: cannot find $InitLTA"
+        exit 1
+      endif
       breaksw
 
     case "--lh":
@@ -168,6 +177,11 @@ while( $#argv != 0 )
 
     case "--no-annot":
       set annot = ();
+      breaksw
+
+    case "--threads":
+      if($#argv < 1) goto arg1err;
+      set threads = $argv[1]; shift;
       breaksw
 
     case "--noneg":
@@ -212,6 +226,16 @@ if(! -e $sd) then
   exit 1;
 endif
 if($DoXHemi) set sd = $SUBJECTS_DIR/$subject/xhemi
+if(! -e $SUBJECTS_DIR/$target) then
+   if($target == fsaverage_sym) then
+      pushd $SUBJECTS_DIR
+      ln -s $FREESURFER_HOME/subjects/fsaverage_sym
+      popd
+   else
+     echo "ERROR: cannot find $target in $SUBJECTS_DIR"
+     exit 1;
+   endif
+endif
 
 if($#OutSurf == 0) then
   if($target == fsaverage) set OutSurf = sphere.reg
@@ -274,8 +298,10 @@ usage_exit:
   echo "  --aparc : sets annotname to aparc.annot (default)"
   echo "  --noneg "
   echo "  --init-reg initregname : default is sphere (do not include hemi)"
+  echo "  --lta reg.lta : apply rotational components of affine reg"
   echo "  --o outsurfname : default is target.sphere.reg (do not include hemi)"
   echo "      If target is fsaverage, then default is sphere.reg"
+  echo "  --threads threads : run in parallel"
   echo ""
 
   if(! $PrintHelp) exit 1;
