Added ability to spec an annot to rip medial wall

diff --git a/scripts/surfreg b/scripts/surfreg
--- a/scripts/surfreg
+++ b/scripts/surfreg
@@ -1,16 +1,19 @@
 #!/bin/tcsh -f
 # thalseg
 
-set VERSION = '$Id: surfreg,v 1.7 2011/12/22 00:52:02 greve Exp $';
+set VERSION = '$Id: surfreg,v 1.8 2012/01/02 23:34:24 greve Exp $';
 
 set subject = ();
 set hemilist  = ();
 set target = ();
 set DoXHemi = 0;
 set UseNoNeg = 0;
-set MkSphere = 0;
 set tmpdir = ();
 set cleanup = 1;
+set OutSurf = ();
+set InitSurf = ();
+set annot = ();
+set LF = ();
 
 set LF = ();
 
@@ -39,8 +42,10 @@ set sd = $SUBJECTS_DIR/$subject
 if($DoXHemi) set sd = $SUBJECTS_DIR/$subject/xhemi
 mkdir -p $sd/scripts
 
-if($#hemilist == 2) set LF = $sd/scripts/surfreg.$target.log
-if($#hemilist == 1) set LF = $sd/scripts/surfreg.$target.$hemilist.log
+if($#LF == 0) then
+  if($#hemilist == 2) set LF = $sd/scripts/surfreg.$target.log
+  if($#hemilist == 1) set LF = $sd/scripts/surfreg.$target.$hemilist.log
+endif
 rm -f $LF
 echo "Log file for surfreg" >> $LF
 date  | tee -a $LF
@@ -64,20 +69,21 @@ endif
 
 foreach hemi ($hemilist)
   echo "#@# $hemi `date`" | tee -a $LF
-
-  set sph = $sd/surf/$hemi.sphere
-  if($MkSphere) then
-    echo "Re-creating sphere" |& tee -a $LF
-    set inf = $sd/surf/$hemi.inflated
-    set cmd = (mris_sphere -seed 1234 $inf $sph)
-    echo "#CMD# $cmd"|& tee -a $LF
-    $cmd |& tee -a $LF
-    if($status) exit 1;
+  if($target == fsaverage) then
+    set AvgCurvTifPath = "${FREESURFER_HOME}/average"
+    set AvgCurvTif = average.curvature.filled.buckner40.tif
+    set AvgTif = ${AvgCurvTifPath}/$hemi.${AvgCurvTif}
+    if($DoXHemi)  set outreg = $sd/xhemi/surf/$hemi.sphere.reg
+  else
+    set AvgTif = $SUBJECTS_DIR/$target/$hemi.reg.template.tif
+    if($DoXHemi)  set outreg = $sd/xhemi/surf/$hemi.$target.sphere.reg
   endif
-
-  set cmd = (mris_register -curv $sph)
+  set outreg = $sd/surf/$hemi.$OutSurf
+  set InitSurfPath = $sd/surf/$hemi.$InitSurf
+  set cmd = (mris_register -curv)
+  if($#annot) set cmd = ($cmd -annot $annot)
   if($UseNoNeg) set cmd = ($cmd -remove_negative 1)
-  set cmd = ($cmd $AvgTif $outreg)
+  set cmd = ($cmd $InitSurfPath $AvgTif $outreg)
   echo "#CMD# $cmd"|& tee -a $LF
   $cmd |& tee -a $LF
   if($status) exit 1;
@@ -120,6 +126,22 @@ while( $#argv != 0 )
       endif
       breaksw
 
+    case "--o":
+      if($#argv < 1) goto arg1err;
+      set OutSurf = $argv[1]; shift;
+      breaksw
+
+    case "--init-reg":
+    case "--init-surf":
+      if($#argv < 1) goto arg1err;
+      set InitSurf = $argv[1]; shift;
+      breaksw
+
+    case "--log":
+      if($#argv < 1) goto arg1err;
+      set LF = $argv[1]; shift;
+      breaksw
+
     case "--lh":
       set hemilist = (lh);
       breaksw
@@ -132,16 +154,20 @@ while( $#argv != 0 )
       set hemilist = (lh rh);
       breaksw
 
+    case "--aparc":
+      set annot = aparc.annot;
+      breaksw
+
+    case "--annot":
+      set annot = $argv[1]; shift;
+      breaksw
+
     case "--noneg":
       set UseNoNeg = 1;
       breaksw
 
     case "--xhemi":
       set DoXHemi = 1;
-      breaksw
-
-    case "--sphere":
-      set MkSphere = 1;
       breaksw
 
     case "--debug":
@@ -177,6 +203,11 @@ if(! -e $sd) then
   echo "ERROR: cannot find $subject in $SUBJECTS_DIR"
   exit 1;
 endif
+if($#OutSurf == 0) then
+  if($target == fsaverage) set InitSurf = sphere.reg
+  if($target != fsaverage) set InitSurf = $target.sphere.reg  
+endif
+if($#InitSurf == 0) set InitSurf = sphere
 
 if($#hemilist == 0 && ! $DoXHemi) set hemilist = (lh rh)
 if($#hemilist == 0 && $DoXHemi)   set hemilist = (lh)
@@ -186,20 +217,23 @@ foreach hemi ($hemilist)
     set AvgCurvTifPath = "${FREESURFER_HOME}/average"
     set AvgCurvTif = average.curvature.filled.buckner40.tif
     set AvgTif = ${AvgCurvTifPath}/$hemi.${AvgCurvTif}
-    set outreg = $sd/surf/$hemi.sphere.reg    
     if($DoXHemi)  set outreg = $sd/xhemi/surf/$hemi.sphere.reg
   else
     set AvgTif = $SUBJECTS_DIR/$target/$hemi.reg.template.tif
-    set outreg = $sd/surf/$hemi.$target.sphere.reg
     if($DoXHemi)  set outreg = $sd/xhemi/surf/$hemi.$target.sphere.reg
   endif
-
   if(! -e $AvgTif) then
     echo "ERROR: cannot find $AvgTif"
     exit 1;
   endif
+  set outreg = $sd/surf/$hemi.$OutSurf
   if(-e $outreg) then
     echo "ERROR: output already exists $outreg"
+    exit 1;
+  endif
+  set InitSurfPath = $sd/surf/$hemi.$InitSurf
+  if(! -e $InitSurfPath) then
+    echo "ERROR: cannot find $InitSurfPath"
     exit 1;
   endif
 end
@@ -225,8 +259,12 @@ usage_exit:
   echo "  --lh : only reg lh (default for --xhemi)"
   echo "  --rh : only reg rh"
   echo "  --lhrh : reg both lh and rh (default when not using --xhemi)"
+  echo "  --annot annotname : uses label/hemi.annotname (rips medial)"
+  echo "  --aparc : sets annotname to aparc.annot"
   echo "  --noneg "
-  echo "  --sphere : re-generate sphere from inflated "
+  echo "  --init-reg initregname : default is sphere (do not include hemi)"
+  echo "  --o outsurfname : default is target.sphere.reg (do not include hemi)"
+  echo "      If target is fsaverage, then default is sphere.reg"
   echo ""
 
   if(! $PrintHelp) exit 1;
@@ -243,11 +281,15 @@ BEGINHELP
 
 Performs surface registration (mris_register) between a subject and a
 target average subject based on the hemi.reg.template.tif atlas in the
-average subject. The source surface is subject/surf/hemi.sphere.
-Creates hemi.target.sphere.reg in the subject/surf dir. If --xhemi is
-used, then the subject name is replaced with subject/xhemi. If this
-directrory is not there, then xhemireg is run on the subject. If
---xhemi is NOT used, then both hemispheres are registered by default.
-If --xhemi IS used, then only the left hemispheres is registered by
-default. If the output already exists, then it throws an error.
+average subject. The source surface is subject/surf/hemi.sphere
+unless changed with --init-reg. 
+
+Creates hemi.target.sphere.reg (unless changed with --o) in the
+subject/surf dir. If --xhemi is used, then the subject name is
+replaced with subject/xhemi. If this directrory is not there, then
+xhemireg is run on the subject. If --xhemi is NOT used, then both
+hemispheres are registered by default.  If --xhemi IS used, then only
+the left hemispheres is registered by default (can be changed by
+adding --rh or --lhrh AFTER --xhemi). If the output already exists,
+then it throws an error.
 
