Added ability to set cursor and zoom

diff --git a/scripts/tkmeditfv b/scripts/tkmeditfv
--- a/scripts/tkmeditfv
+++ b/scripts/tkmeditfv
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # tkmeditfv
 
-set VERSION = '$Id: tkmeditfv,v 1.14 2014/11/17 20:12:16 greve Exp $';
+set VERSION = '$Id: tkmeditfv,v 1.15 2015/07/02 16:14:53 greve Exp $';
 
 set subject = ();
 set overlay = ();
@@ -32,6 +32,9 @@ set fmax    = 5;
 set label = ();
 set UseTkMedit = 0;
 set vollist0 = ();
+set CursorCRS = ();
+set CenterCursor = 0;
+set Zoom = ();
 
 set tmpdir = ();
 set cleanup = 1;
@@ -88,6 +91,9 @@ if(! $UseTkMedit) then
     @ nth = $nth + 1;
     set cmd = ($cmd --surface $surf":"edgecolor=$surfcolor[$nth])
   end
+  if($#CursorCRS) set cmd = ($cmd -slice $CursorCRS)
+  if($CenterCursor) set cmd = ($cmd -cc)
+  if($#Zoom) set cmd = ($cmd -zoom $Zoom)
 else
   ### tkmedit ####----------------------------------------------
   set cmd = tkmedit
@@ -275,6 +281,18 @@ while( $#argv != 0 )
       set surfcolor = ($surfcolor yellow red yellow red);
       breaksw
 
+    case "-crs":
+      if($#argv < 3) goto arg3err;
+      set CursorCRS = ($argv[1-3]);
+      shift;shift;shift;
+      set CenterCursor = 1;
+      breaksw
+
+    case "-zoom":
+      if($#argv < 1) goto arg1err;
+      set Zoom = $argv[1]; shift;
+      breaksw
+
     case "-tkmedit":
     case "-tkm":
       set UseTkMedit = 1;
@@ -451,6 +469,10 @@ arg2err:
   echo "ERROR: flag $flag requires two arguments"
   exit 1
 ############--------------##################
+arg3err:
+  echo "ERROR: flag $flag requires three arguments"
+  exit 1
+############--------------##################
 
 ############--------------##################
 usage_exit:
@@ -467,6 +489,8 @@ usage_exit:
   echo "-surfs  : load lh and rh white and pial"
   echo "-surf /path/to/surface <color> : load surface with optional color (eg, blue)"
   echo "-vol volume1 <-vol volume2> : load extra volumes "
+  echo "-crs col row slice : place cursor at given location and center FoV"
+  echo "-zoom Zoom : set zoom level"
   echo ""
   if(! $PrintHelp) exit 1;
   echo $VERSION
