Now uses reg2subject to get the subjectname from a registration file (allows for LTA)

diff --git a/scripts/tkmeditfv b/scripts/tkmeditfv
--- a/scripts/tkmeditfv
+++ b/scripts/tkmeditfv
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # tkmeditfv
 
-set VERSION = '$Id: tkmeditfv,v 1.9 2014/10/01 21:08:18 greve Exp $';
+set VERSION = '$Id: tkmeditfv,v 1.10 2014/10/27 16:18:12 greve Exp $';
 
 set subject = ();
 set overlay = ();
@@ -305,7 +305,12 @@ if($#subject) then
       echo "ERROR: must supply regfile with getreg"
       exit 1;
     endif
-    set subject = `head -n 1 $overlayreg`
+    if(! -e $overlayreg ) then
+      echo "ERROR: cannot find $overlayreg"
+      exit 1;
+    endif
+    #set subject = `head -n 1 $overlayreg`
+    set subject = `reg2subject --r $overlayreg`;
   endif
   if(! -e $SUBJECTS_DIR/$subject) then
     echo "ERROR: cannot find $subject"
