Added -vol

diff --git a/scripts/tkmeditfv b/scripts/tkmeditfv
--- a/scripts/tkmeditfv
+++ b/scripts/tkmeditfv
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # tkmeditfv
 
-set VERSION = '$Id: tkmeditfv,v 1.13 2014/11/06 18:03:12 greve Exp $';
+set VERSION = '$Id: tkmeditfv,v 1.14 2014/11/17 20:12:16 greve Exp $';
 
 set subject = ();
 set overlay = ();
@@ -31,6 +31,7 @@ set fthresh = 2;
 set fmax    = 5;
 set label = ();
 set UseTkMedit = 0;
+set vollist0 = ();
 
 set tmpdir = ();
 set cleanup = 1;
@@ -79,6 +80,9 @@ if(! $UseTkMedit) then
     if($#twfreg) set fvopt = ($fvopt":"reg=$twfreg)
     set cmd = ($cmd -v $fvopt)
   endif
+  foreach vol ($vollist)
+    set cmd = ($cmd -v $vol)
+  end
   @ nth = 0;
   foreach surf ($surflist)
     @ nth = $nth + 1;
@@ -167,6 +171,12 @@ while( $#argv != 0 )
 
     case "-aparc+aseg":
       set segvol0 = aparc+aseg.mgz
+      breaksw
+
+    case "-vol":
+      if($#argv < 1) goto arg1err;
+      set vol = $argv[1];
+      set vollist0 = ($vollist0 $vol); shift;
       breaksw
 
     case "-op":
@@ -413,6 +423,22 @@ if($#label) then
   endif
 endif
 
+set vollist = ()
+foreach vol0 ($vollist0)
+  set vol = ();
+  if(-e $vol0) set vol = $vol0;
+  else 
+    set voltry = $SUBJECTS_DIR/$subject/mri/$vol0
+    if(-e $vol0) then
+      set vol = $voltry
+    else 
+      echo "ERROR: cannot find $vol0"
+      exit 1;
+    endif
+  endif
+  set vollist = ($vollist $vol) 
+end
+
 goto check_params_return;
 ############--------------##################
 
@@ -440,6 +466,7 @@ usage_exit:
   echo "-aparc+aseg"
   echo "-surfs  : load lh and rh white and pial"
   echo "-surf /path/to/surface <color> : load surface with optional color (eg, blue)"
+  echo "-vol volume1 <-vol volume2> : load extra volumes "
   echo ""
   if(! $PrintHelp) exit 1;
   echo $VERSION
