tkregisterfv. #NF. Added ability to read the mov or targ from the reg.lta (ie, allows user to spec the mov or targ and read the other from the reg

diff --git a/scripts/tkregisterfv b/scripts/tkregisterfv
--- a/scripts/tkregisterfv
+++ b/scripts/tkregisterfv
@@ -526,23 +526,6 @@ if($DoTal) then
   set movvol = $SUBJECTS_DIR/$subject/mri/orig.mgz
 endif
 
-if($#movvol == 0 && $#targ == 0 && $#reg != 0) then
-  set tmp = (`grep filename $reg | awk '{print $3}'`)
-  if($#tmp != 2) then
-    echo "ERROR: cannot get filenames from $reg"
-    exit 1
-  endif
-  set movvol = $tmp[1];
-  set targ   = $tmp[2];
-  echo "Setting mov  to $movvol"
-  echo "Setting targ to $targ"
-endif
-
-if($#movvol == 0) then
-  echo "ERROR: must spec a moveable volume"
-  exit 1;
-endif
-
 if($#targ == 0) then
   if($#subject == 0 && $#reg == 0) then
     echo "ERROR: must spec either subject or reg or targ"
@@ -555,15 +538,39 @@ if($#targ == 0) then
     endif
     set subject = `reg2subject --r $reg`
   endif
-  if(! -e $SUBJECTS_DIR/$subject) then
-    echo "ERROR: cannot find $subject"
-    exit 1;
+  if(-e $SUBJECTS_DIR/$subject) then
+    set targ = $SUBJECTS_DIR/$subject/mri/$fstarg
+    if(! -e $targ) then
+      echo "ERROR: cannot find $targ"
+      exit 1;
+    endif
+  else if($#reg != 0) then
+    set tmp = (`grep filename $reg | awk '{print $3}'`)
+    if($#tmp != 2) then
+      echo "ERROR: cannot get filenames from $reg"
+      exit 1
+    endif
+    set targ   = $tmp[2];
   endif
-  set targ = $SUBJECTS_DIR/$subject/mri/$fstarg
-  if(! -e $targ) then
-    echo "ERROR: cannot find $targ"
-    exit 1;
+  echo "Setting targ to $targ"
+endif
+
+endif
+
+if($#movvol == 0 && $#reg != 0) then
+  set tmp = (`grep filename $reg | awk '{print $3}'`)
+  if($#tmp != 2) then
+    echo "ERROR: cannot get filenames from $reg"
+    exit 1
   endif
+  set movvol = $tmp[1];
+  echo "Setting mov  to $movvol"
+endif
+
+
+if($#movvol == 0) then
+  echo "ERROR: must spec a moveable volume"
+  exit 1;
 endif
 
 if($#segvol0) then
@@ -649,8 +656,9 @@ usage_exit:
   echo "tkregisterfv --mov mov --targ targ --reg reg.lta --s subject "
   echo "  --aux vol1 reg1 --aux vol2 reg2 ..."
   echo "  Note: you can run it like "
-  echo "   tkregisterfv --reg reg.lta "
-  echo "   and it will rad the mov and targ volumes from the lta"
+  echo "   tkregisterfv --reg reg.lta             and it will read the mov and targ volumes from the lta"
+  echo "   tkregisterfv --reg reg.lta --mov mov   and it will read the targ volume from the lta"
+  echo "   tkregisterfv --reg reg.lta --targ targ and it will read the mov  volume from the lta"
   echo ""
   echo "  --fstarg volume : spec volume instead of $fstarg"
   echo "  --sd SUBJECTS_DIR"  
