Added support for multiple diffusion scans per session and pre-processing with topup and/or eddy

diff --git a/scripts/trac-all b/scripts/trac-all
--- a/scripts/trac-all
+++ b/scripts/trac-all
@@ -34,10 +34,7 @@ if ($?PBS_JOBID && `domainname` == nmr.mgh.harvard.edu) then
 endif
 
 set onpbs = 0
-set hname = `hostname -s`
-if ($hname == tensor || $hname == launchpad) then
-  set onpbs = 1
-endif
+if (`where pbsubmit` != "") set onpbs = 1
 
 setenv FSLOUTPUTTYPE NIFTI_GZ
 setenv LANG en_US.UTF-8
@@ -108,12 +105,17 @@ set bveclist = ()
 set bvecfile = ()
 set bvallist = ()
 set bvalfile = ()
+set bmax = ()
+set bshell = ()
 set nb0 = ()
 set dob0 = 0
 set b0mlist = ()
 set b0plist = ()
 set echospacing = ()
-set doeddy = 1
+set epifactor = ()
+set pedir = ()
+set dTE = ()
+set doeddy = 2
 set dorotbvecs = 1
 set thrbet = 0.3
 set doregflt = 0
@@ -219,30 +221,60 @@ if ($#umaskid) set cmdopts = ($cmdopts -umask $umaskid)
 if ($#groupid) set cmdopts = ($cmdopts -grp $groupid)
 if ($allowcore) set cmdopts = ($cmdopts -allowcoredump)
 
+# Select a subset of scans to process
+set cmd = `printf "%dp;" $runlist`
+set subjlist = `printf '%s\n' $subjlist | sed -n "$cmd"`
+set dcmlist  = `printf '%s\n' $dcmlist  | sed -n "$cmd"`
+if ($#bveclist) set bveclist = `printf '%s\n' $bveclist | sed -n "$cmd"`
+if ($#bvallist) set bvallist = `printf '%s\n' $bvallist | sed -n "$cmd"`
+if ($#b0mlist)  set b0mlist  = `printf '%s\n' $b0mlist  | sed -n "$cmd"`
+if ($#b0plist)  set b0plist  = `printf '%s\n' $b0plist  | sed -n "$cmd"`
+if ($#baselist) set baselist = `printf '%s\n' $baselist | sed -n "$cmd"`
+
+# Find unique subject IDs
+set subjids = `printf '%s\n' $subjlist | sort --unique`
+if ($#baselist) set baseids = `printf '%s\n' $baselist | sort --unique`
+
 #------------ Loop over subjects ------------------------------------------#
 set subjdirs = ()
 set basedirs = ()
 
 if ($#baselist == 0) then	#--->>> A single time point for each subject
-  foreach isubj ($runlist)
-    set subj = $subjlist[$isubj]
+  foreach subj ($subjids)
+    # Find this subject's scans
+    set scanlist = `printf '%s\n' $subjlist \
+                    | awk -v subj=$subj '{if ($1==subj) print NR}'`
 
-    if ($do1out) then
-      set dtdir = $subj
-      set dtroot = `dirname $dtdir`
-      set subj = `basename $dtdir`
+    set cmd = `printf "%dp;" $scanlist`
+    set my_dcmlist = `printf '%s\n' $dcmlist | sed -n "$cmd"`
+    if ($#bveclist) set my_bveclist = `printf '%s\n' $bveclist | sed -n "$cmd"`
+    if ($#bvallist) set my_bvallist = `printf '%s\n' $bvallist | sed -n "$cmd"`
+    if ($#b0mlist)  set my_b0mlist  = `printf '%s\n' $b0mlist  | sed -n "$cmd"`
+    if ($#b0plist)  set my_b0plist  = `printf '%s\n' $b0plist  | sed -n "$cmd"`
+    if ($#echospacing > 1) \
+      set my_echospacing  = `printf '%s\n' $echospacing  | sed -n "$cmd"`
+    if ($#epifactor > 1) \
+      set my_epifactor    = `printf '%s\n' $epifactor    | sed -n "$cmd"`
+    if ($#pedir > 1) \
+      set my_pedir        = `printf '%s\n' $pedir        | sed -n "$cmd"`
 
-      if (-e $trainfile) then
-        set trainsubjlist = `cat $trainfile | sed -n "$isubj p"`
-        shift trainsubjlist
-      endif
-    else
-      set dtdir = $dtroot/$subj
+    if (-e $trainfile) then
+      if ($do1out) then
+        foreach k (`awk '{print NR}' $trainfile`)
+          set slist = `sed -n "$k p" $trainfile`
 
-      if (-e $trainfile) then
+          if (`basename $slist[1]` == $subj) then
+            set dtroot = `dirname $slist[1]`
+            shift slist
+            set trainsubjlist = ($slist)
+          endif
+        end
+      else
         set trainsubjlist = `cat $trainfile`
       endif
     endif
+
+    set dtdir = $dtroot/$subj
 
     set subjdirs = ($subjdirs $dtdir)
 
@@ -427,30 +459,47 @@ if ($#baselist == 0) then	#--->>> A single time point for each subject
     echo "# Options for image corrections and tensor fit"	 	>> $RCF
     echo "#"							 	>> $RCF
     echo "set dcmroot = ($dcmroot)"					>> $RCF
-    echo "set dcmfile = ($dcmlist[$isubj])"				>> $RCF
+    echo "set dcmfile = ($my_dcmlist)"					>> $RCF
     if ($#bveclist) then
-      echo "set bvecfile = ($bveclist[$isubj])"				>> $RCF
+      echo "set bvecfile = ($my_bveclist)"				>> $RCF
     else
       echo "set bvecfile = ($bvecfile)"					>> $RCF
     endif
     if ($#bvallist) then
-      echo "set bvalfile = ($bvallist[$isubj])"				>> $RCF
+      echo "set bvalfile = ($my_bvallist)"				>> $RCF
     else
       echo "set bvalfile = ($bvalfile)"					>> $RCF
     endif
+    echo "set bmax = ($bmax)"						>> $RCF
+    echo "set bshell = ($bshell)"					>> $RCF
     echo "set nb0 = ($nb0)"						>> $RCF
     echo "set dob0 = ($dob0)"						>> $RCF
     if ($#b0mlist) then
-      echo "set b0mfile = ($b0mlist[$isubj])"				>> $RCF
+      echo "set b0mfile = ($my_b0mlist)"				>> $RCF
     else
       echo "set b0mfile = ()"						>> $RCF
     endif
     if ($#b0plist) then
-      echo "set b0pfile = ($b0plist[$isubj])"				>> $RCF
+      echo "set b0pfile = ($my_b0plist)"				>> $RCF
     else
       echo "set b0pfile = ()"						>> $RCF
     endif
-    echo "set echospacing = ($echospacing)"				>> $RCF
+    if ($#echospacing > 1) then
+      echo "set echospacing = ($my_echospacing)"			>> $RCF
+    else
+      echo "set echospacing = ($echospacing)"				>> $RCF
+    endif
+    if ($#epifactor > 1) then
+      echo "set epifactor = ($my_epifactor)"				>> $RCF
+    else
+      echo "set epifactor = ($epifactor)"				>> $RCF
+    endif
+    if ($#pedir > 1) then
+      echo "set pedir = ($my_pedir)"					>> $RCF
+    else
+      echo "set pedir = ($pedir)"					>> $RCF
+    endif
+    echo "set dTE = ($dTE)"						>> $RCF
     echo "set doeddy = ($doeddy)"					>> $RCF
     echo "set dorotbvecs = ($dorotbvecs)"				>> $RCF
     echo "set thrbet = ($thrbet)"					>> $RCF
@@ -553,55 +602,35 @@ if ($#baselist == 0) then	#--->>> A single time point for each subject
     endif
   end
 else				#--->>> Multiple time points for each subject
-  if (! $do1out) then
-    # Find which base subjects will be processed
-    set bsubjlist = ()
-
-    foreach isubj ($runlist)
-      if ($#baselist > 0) then
-        set bsubjlist = ($bsubjlist $baselist[$isubj])
-      endif
-    end
-
-    set bsubjlist = `printf '%s\n' $bsubjlist | sort --unique`
-  endif
-
   # Loop over base subjects
-  @ ibsubj = 1
-  while ($ibsubj <= $#bsubjlist)
-    set bsubj = $bsubjlist[$ibsubj]
+  foreach bsubj ($baseids)
+    # Find this subject's time points
+    set scanlist = `printf '%s\n' $baselist \
+                    | awk -v base=$bsubj '{if ($1==base) print NR}'`
 
-    if ($do1out) then
-      set dtdir = $bsubj
-      set dtroot = `dirname $dtdir`
-      set bsubj = `basename $dtdir`
+    set cmd = `printf "%dp;" $scanlist`
+    set tplist = `printf '%s\n' $subjlist | sed -n "$cmd" | sort --unique`
+    set tplist = `printf "%s.long.$bsubj " $tplist`
 
-      if (-e $trainfile) then
-        set trainsubjlist = `cat $trainfile | sed -n "$ibsubj p"`
-        shift trainsubjlist
-      endif
-    else
-      set dtdir = $dtroot/$bsubj
+    if (-e $trainfile) then
+      if ($do1out) then
+        foreach k (`awk '{print NR}' $trainfile`)
+          set slist = `sed -n "$k p" $trainfile`
 
-      if (-e $trainfile) then
+          if (`basename $slist[1]` == $bsubj) then
+            set dtroot = `dirname $slist[1]`
+            shift slist
+            set trainsubjlist = ($slist)
+          endif
+        end
+      else
         set trainsubjlist = `cat $trainfile`
       endif
     endif
 
-    # Find which time points will be processed for this base subject
-    set itps = ()
-    set tplist = ()
+    set dtdir = $dtroot/$bsubj
 
-    foreach isubj ($runlist)
-      if ($baselist[$isubj] == $bsubj) then
-        set itps = ($itps $isubj)
-        set tplist = ($tplist $subjlist[$isubj])
-      endif
-    end
-
-    set tplist = `printf "%s.long.$bsubj " $tplist`
-
-    # Depending on which step of the analysis I am preforming,
+    # Depending on which step of the analysis I am performing,
     # I may need to process the time points, the base, or all of the above
     set proclist = ()
 
@@ -624,6 +653,28 @@ else				#--->>> Multiple time points for each subject
       set dtdir = $dtroot/$subj
 
       if ($subj != $bsubj) then
+        # Find this time point's scans
+        set scanlist = `printf '%s\n' $subjlist \
+                        | awk -v subj=$subj -v bsubj=$bsubj \
+                              '{if ($1".long."bsubj == subj) print NR}'`
+
+        set cmd = `printf "%dp;" $scanlist`
+        set my_dcmlist = `printf '%s\n' $dcmlist | sed -n "$cmd"`
+        if ($#bveclist) \
+          set my_bveclist     = `printf '%s\n' $bveclist     | sed -n "$cmd"`
+        if ($#bvallist) \
+          set my_bvallist     = `printf '%s\n' $bvallist     | sed -n "$cmd"`
+        if ($#b0mlist)  \
+          set my_b0mlist      = `printf '%s\n' $b0mlist      | sed -n "$cmd"`
+        if ($#b0plist)  \
+          set my_b0plist      = `printf '%s\n' $b0plist      | sed -n "$cmd"`
+        if ($#echospacing > 1) \
+          set my_echospacing  = `printf '%s\n' $echospacing  | sed -n "$cmd"`
+        if ($#epifactor > 1) \
+          set my_epifactor    = `printf '%s\n' $epifactor    | sed -n "$cmd"`
+        if ($#pedir > 1) \
+          set my_pedir        = `printf '%s\n' $pedir        | sed -n "$cmd"`
+
         set subjdirs = ($subjdirs $dtdir)
         set basedirs = ($basedirs $dtroot/$bsubj)
       endif
@@ -830,33 +881,50 @@ else				#--->>> Multiple time points for each subject
       echo "#"							 	>> $RCF
       echo "set dcmroot = ($dcmroot)"					>> $RCF
       if ($subj != $bsubj) then
-        echo "set dcmfile = ($dcmlist[$itps[$iproc]])"			>> $RCF
+        echo "set dcmfile = ($my_dcmlist)"				>> $RCF
       else
         echo "set dcmfile = ()"						>> $RCF
       endif
       if ($#bveclist && $subj != $bsubj) then
-        echo "set bvecfile = ($bveclist[$itps[$iproc]])"		>> $RCF
+        echo "set bvecfile = ($my_bveclist)"				>> $RCF
       else
         echo "set bvecfile = ($bvecfile)"				>> $RCF
       endif
       if ($#bvallist && $subj != $bsubj) then
-        echo "set bvalfile = ($bvallist[$itps[$iproc]])"		>> $RCF
+        echo "set bvalfile = ($my_bvallist)"				>> $RCF
       else
         echo "set bvalfile = ($bvalfile)"				>> $RCF
       endif
+      echo "set bmax = ($bmax)"						>> $RCF
+      echo "set bshell = ($bshell)"					>> $RCF
       echo "set nb0 = ($nb0)"						>> $RCF
       echo "set dob0 = ($dob0)"						>> $RCF
       if ($subj != $bsubj && $#b0mlist) then
-        echo "set b0mfile = ($b0mlist[$itps[$iproc]])"			>> $RCF
+        echo "set b0mfile = ($my_b0mlist)"				>> $RCF
       else
         echo "set b0mfile = ()"						>> $RCF
       endif
       if ($subj != $bsubj && $#b0plist) then
-        echo "set b0pfile = ($b0plist[$itps[$iproc]])"			>> $RCF
+        echo "set b0pfile = ($my_b0plist)"				>> $RCF
       else
         echo "set b0pfile = ()"						>> $RCF
       endif
-      echo "set echospacing = ($echospacing)"				>> $RCF
+      if ($#echospacing > 1) then
+        echo "set echospacing = ($my_echospacing)"			>> $RCF
+      else
+        echo "set echospacing = ($echospacing)"				>> $RCF
+      endif
+      if ($#epifactor > 1) then
+        echo "set epifactor = ($my_epifactor)"				>> $RCF
+      else
+        echo "set epifactor = ($epifactor)"				>> $RCF
+      endif
+      if ($#pedir > 1) then
+        echo "set pedir = ($my_pedir)"					>> $RCF
+      else
+        echo "set pedir = ($pedir)"					>> $RCF
+      endif
+      echo "set dTE = ($dTE)"						>> $RCF
       echo "set doeddy = ($doeddy)"					>> $RCF
       echo "set dorotbvecs = ($dorotbvecs)"				>> $RCF
       echo "set thrbet = ($thrbet)"					>> $RCF
@@ -974,8 +1042,6 @@ else				#--->>> Multiple time points for each subject
         if ($status) exit 1
       endif
     endif
-
-    @ ibsubj = $ibsubj + 1
   end
 endif
 
@@ -1435,15 +1501,28 @@ check_params:
         # Leave-one-out training file:
         # The first subject of each line is the test subject,
         # the remaining subjects of the line are the training subjects
-        if ($#baselist == 0) then	# A single time point for each subject
-          set subjlist = `cat $trainfile | awk '{print $1}'`
+        set dlist = `cat $trainfile | awk '{print $1}'`
+        set slist = ()
+        foreach dname ($dlist)
+          set slist = ($slist `basename $dname`)
+        end
 
-          set runlist = 1
-          while ($runlist[$#runlist] < $#subjlist)
-            set runlist = ($runlist `echo $runlist[$#runlist] + 1 | bc`)
+        if ($#baselist == 0) then	# A single time point for each subject
+          set subjids = ($slist)
+
+          set runlist = ()
+          foreach subj ($subjids)
+            set runlist = ($runlist `printf '%s\n' $subjlist \
+                           | awk -v subj=$subj '{if ($1==subj) print NR}'`)
           end
         else				# Multiple time points for each subject
-          set bsubjlist = `cat $trainfile | awk '{print $1}'`
+          set baseids = ($slist)
+
+          set runlist = ()
+          foreach base ($baseids)
+            set runlist = ($runlist `printf '%s\n' $baselist \
+                           | awk -v base=$base '{if ($1==base) print NR}'`)
+          end
         endif
 
         if (! $#ntrainlist) then
@@ -1470,14 +1549,11 @@ check_params:
     endif
 
     if ($#runlist == 0) then			# Process all subjects
-      set runlist = 1
-      while ($runlist[$#runlist] < $#subjlist)
-        set runlist = ($runlist `echo $runlist[$#runlist] + 1 | bc`)
-      end
+      set runlist = `printf '%s\n' $subjlist | awk '{print NR}'`
     else
-      foreach isubj ($runlist)
-        if ($isubj > $#subjlist) then
-          echo "ERROR: $isubj is in run list but have only $#subjlist subjects"
+      foreach iscan ($runlist)
+        if ($iscan > $#subjlist) then
+          echo "ERROR: $iscan is in run list but have only $#subjlist scans"
           exit 1
         endif
       end
@@ -1518,39 +1594,79 @@ check_params:
     end
 
     if ($#runlist > $#subjlist) then
-      echo "ERROR: run list is longer than subject list"
+      echo "ERROR: run list is longer than subject ID list"
       exit 1
     endif
 
     if ($docorr) then
       if ($#dcmlist != $#subjlist) then
-        echo "ERROR: must specify as many DWI dicoms as subjects"
+        echo "ERROR: must specify as many subject IDs as DWI scans"
         exit 1
       endif
 
       if ($#bveclist > 0 && $#bveclist != $#subjlist) then
-        echo "ERROR: must specify as many gradient vector tables as subjects"
+        echo "ERROR: must specify as many gradient vector tables as DWI scans"
         exit 1
       endif
 
       if ($#bvallist > 0 && $#bvallist != $#subjlist) then
-        echo "ERROR: must specify as many b-value tables as subjects"
+        echo "ERROR: must specify as many b-value tables as DWI scans"
         exit 1
       endif
 
-      if ($#b0mlist > 0 && $#b0mlist != $#subjlist) then
-        echo "ERROR: must specify as many fieldmap magnitude dicoms as subjects"
-        exit 1
+      if ($dob0) then
+        if (! $#echospacing) then
+          echo "ERROR: for B0 distortion correction, must specify echo spacing"
+          exit 1
+        else if ($#echospacing > 1 && $#echospacing != $#subjlist) then
+          echo "ERROR: must specify one echo spacing or one for each DWI scan"
+          exit 1
+        endif
       endif
 
-      if ($#b0plist > 0 && $#b0plist != $#subjlist) then
-        echo "ERROR: must specify as many fieldmap phase dicoms as subjects"
-        exit 1
+      if ($dob0 == 1) then
+        if ($#b0mlist != $#subjlist) then
+          echo "ERROR: for B0 distortion correction with field maps,"
+          echo "ERROR: must specify as many magnitude maps as DWI scans"
+          exit 1
+        endif
+
+        if ($#b0plist != $#subjlist) then
+          echo "ERROR: for B0 distortion correction with field maps,"
+          echo "ERROR: must specify as many phase maps as DWI scans"
+          exit 1
+        endif
+      endif
+
+      if ($dob0 > 1 || $doeddy > 1) then
+        if (! $#pedir) then
+          echo "ERROR: for B0 distortion correction with reverse-polarity DWIs"
+          echo "ERROR: or for model-based eddy-current distortion correction,"
+          echo "ERROR: must specify PE direction"
+          exit 1
+        else if ($#pedir > 1 && $#pedir != $#subjlist) then
+          echo "ERROR: for B0 distortion correction with reverse-polarity DWIs"
+          echo "ERROR: or for model-based eddy-current distortion correction,"
+          echo "ERROR: must specify one PE direction or one for each DWI scan"
+          exit 1
+        endif
+
+        if (! $#epifactor) then
+          echo "ERROR: for B0 distortion correction with reverse-polarity DWIs"
+          echo "ERROR: or for model-based eddy-current distortion correction,"
+          echo "ERROR: must specify EPI factor"
+          exit 1
+        else if ($#epifactor > 1 && $#epifactor != $#subjlist) then
+          echo "ERROR: for B0 distortion correction with reverse-polarity DWIs"
+          echo "ERROR: or for model-based eddy-current distortion correction,"
+          echo "ERROR: must specify one EPI factor or one for each DWI scan"
+          exit 1
+        endif
       endif
     endif
 
     if ($#baselist > 0 && $#baselist != $#subjlist) then
-      echo "ERROR: must specify a base template name for every time point name"
+      echo "ERROR: must specify a base template name for every DWI scan"
       exit 1
     endif
   endif
