Now checks that the input is there

diff --git a/scripts/vsm-smooth b/scripts/vsm-smooth
--- a/scripts/vsm-smooth
+++ b/scripts/vsm-smooth
@@ -1,7 +1,7 @@
 #!/bin/tcsh -f
 # vsm-smooth
 
-set VERSION = '$Id: vsm-smooth,v 1.1 2011/08/09 15:48:45 greve Exp $';
+set VERSION = '$Id: vsm-smooth,v 1.2 2013/05/03 20:19:21 greve Exp $';
 
 set vsm = ();
 set vsmout = ();
@@ -164,6 +164,10 @@ check_params:
 
 if($#vsm == 0) then
   echo "ERROR: must spec vsm"
+  exit 1;
+endif
+if(! -e $vsm) then
+  echo "ERROR: cannot find $vsm"
   exit 1;
 endif
 if($#vsmout == 0) then
