Start testing the new code

diff --git a/mris_make_surfaces/test_mris_make_surfaces b/mris_make_surfaces/test_mris_make_surfaces
--- a/mris_make_surfaces/test_mris_make_surfaces
+++ b/mris_make_surfaces/test_mris_make_surfaces
@@ -6,8 +6,9 @@ if ( $?SKIP_MRIS_MAKE_SURFACES_TEST ) then
   exit 0
 endif
 
+set passed = 1
 
-foreach threads ( 8 )
+foreach threads ( 4 )
 
   # extract testing data
 
@@ -36,23 +37,24 @@ foreach threads ( 8 )
   $cmd
   if ($status != 0) then
     echo "mris_make_surfaces FAILED"
-    exit 1
+    set passed = 0
+  else
+    # compare expected results with actual (produced) results
+
+    set TST = subject/surf/lh.white.preaparc
+    set REF = ${TST}.REF
+    set cmd=(../../mris_diff/mris_diff --debug $REF $TST );
+
+    echo ""
+    echo $cmd
+    #$cmd
+    set diff_status=$status
+    if ($diff_status != 0) then
+      echo "$cmd FAILED (exit status=$diff_status)"
+      set passed = 0
+    endif
   endif
 
-  # compare expected results with actual (produced) results
-
-  set TST = subject/surf/lh.white.preaparc
-  set REF = ${TST}.REF
-  set cmd=(../../mris_diff/mris_diff --debug $REF $TST );
-
-  echo ""
-  echo $cmd
-  #$cmd
-  set diff_status=$status
-  if ($diff_status != 0) then
-    echo "$cmd FAILED (exit status=$diff_status)"
-    exit 1
-  endif
 
 
   # ---- TEST 2 ----
@@ -69,27 +71,27 @@ foreach threads ( 8 )
   $cmd
   if ($status != 0) then
     echo "mris_make_surfaces FAILED"
-    exit 1
+    set passed = 0
+  else
+    # compare expected results with actual (produced) results
+
+    foreach surface ( white pial )
+
+      set TST = subject/surf/lh.$surface
+      set REF = ${TST}.REF
+      set cmd=(../../mris_diff/mris_diff --debug $REF $TST );
+
+      echo ""
+      echo $cmd
+      $cmd
+      set diff_status=$status
+      if ($diff_status != 0) then
+        echo "$cmd FAILED (exit status=$diff_status)"
+        set passed = 0
+      endif
+
+    end
   endif
-
-  # compare expected results with actual (produced) results
-
-  foreach surface ( white pial )
-
-    set TST = subject/surf/lh.$surface
-    set REF = ${TST}.REF
-    set cmd=(../../mris_diff/mris_diff --debug $REF $TST );
-
-    echo ""
-    echo $cmd
-    $cmd
-    set diff_status=$status
-    if ($diff_status != 0) then
-      echo "$cmd FAILED (exit status=$diff_status)"
-      exit 1
-    endif
-
-  end
 
   echo ""
   echo ""
@@ -101,8 +103,14 @@ foreach threads ( 8 )
   cd ..
   rm -rf testdata
 
-  end
+end
 
-echo ""
-echo "test_mris_make_surfaces passed all tests"
-exit 0
+if ($passed != 0) then
+  echo ""
+  echo "test_mris_make_surfaces passed all tests"
+  exit 0
+else
+  echo ""
+  echo "test_mris_make_surfaces failed some tests"
+  exit 1
+endif
