fixed problem where lta_diff was failing (lta_convert now used to create .lta from .xfm and the .lta is compared)

diff --git a/talairach_avi/test_talairach_avi b/talairach_avi/test_talairach_avi
--- a/talairach_avi/test_talairach_avi
+++ b/talairach_avi/test_talairach_avi
@@ -7,11 +7,11 @@
 #
 # Original Author: Nick Schmansky
 # CVS Revision Info:
-#    $Author: zkaufman $
-#    $Date: 2012/12/05 18:52:42 $
-#    $Revision: 1.9 $
+#    $Author: nicks $
+#    $Date: 2015/01/13 01:40:40 $
+#    $Revision: 1.10 $
 #
-# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
+# Copyright © 2011-2015 The General Hospital Corporation (Boston, MA) "MGH"
 #
 # Terms and conditions for use, reproduction, distribution and contribution
 # are found in the 'FreeSurfer Software License Agreement' contained
@@ -22,7 +22,7 @@
 # Reporting: freesurfer@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_talairach_avi,v 1.9 2012/12/05 18:52:42 zkaufman Exp $'
+set VERSION='$Id: test_talairach_avi,v 1.10 2015/01/13 01:40:40 nicks Exp $'
 
 umask 002
 
@@ -46,10 +46,21 @@ if ($status != 0) then
 endif
 
 #
+# convert .xfm to .lta since lta_diff no longer handles .xfm files
+#
+set cmd=(../lta_convert/lta_convert --inmni tal.xfm --outlta tal.lta \
+    --src nu.mgz --trg mni305.cor.mgz)
+$cmd >& test_talairach_avi.log
+if ($status != 0) then
+  echo "$cmd FAILED"
+  exit 1
+endif
+
+#
 # compare expected results with actual (produced) results
 # use lta_diff, since there will be small variations between platforms
 #
-set cmd=(../mri_robust_register/lta_diff tal.xfm reference-tal.xfm)
+set cmd=(../mri_robust_register/lta_diff tal.lta reference-tal.lta)
 echo ""
 echo $cmd
 set diffVal=(`$cmd`)  
