added test for building against gfortran shared libs

diff --git a/talairach_avi/test_libg2c b/talairach_avi/test_libg2c
--- a/talairach_avi/test_libg2c
+++ b/talairach_avi/test_libg2c
@@ -3,6 +3,8 @@
 # the talairach_avi utils must not build against the shared libg2c, as that
 # lib is not found on most installations (and there is no reason to distribute
 # it if we can avoid it).
+# On the mac, ditto for libquadmath.0.dylib, which is one of the shared libs
+# found in gfortran, which we dont want to be dependent upon.
 
 # check for an enviro var to skip
 if ( $?SKIP_LIBG2C_TEST ) exit 77
@@ -23,5 +25,15 @@ endif
 
 if ( ! $grepstatus ) then
   echo "ERROR: gauss_4dfp built against shared libg2c!"
+  exit 1
+endif
+
+if ("$OS" == "Darwin") then
+  otool -L ./gauss_4dfp | grep libquadmath
+  set grepstatus=$status
+endif
+
+if ( ! $grepstatus ) then
+  echo "ERROR: gauss_4dfp built against shared gfortran libs!"
   exit 1
 endif
