Finish the deterministic test of mris_curvature

diff --git a/mris_curvature/test_mris_curvature b/mris_curvature/test_mris_curvature
--- a/mris_curvature/test_mris_curvature
+++ b/mris_curvature/test_mris_curvature
@@ -31,7 +31,7 @@ setenv SUBJECTS_DIR ""
 setenv OMP_NUM_THREADS 8
 
 # modified (shortened) usage in recon-all: 
-set cmd=(../mris_curvature \
+set cmd=(../mris_curvature -seed 1234 \
     -thresh .999 -n -a 5 -w -distances 10 10 \
     lh.inflated)
 
@@ -49,6 +49,24 @@ endif
 
 set REF_VOL = ref_lh.inflated.H
 set TST_VOL = lh.inflated.H
+
+#hd -s 96 -n 550000 < $REF_VOL > ${REF_VOL}.hd.txt
+#hd -s 96 -n 550000 < $TST_VOL > ${TST_VOL}.hd.txt
+hd < $REF_VOL > ${REF_VOL}.hd.txt
+hd < $TST_VOL > ${TST_VOL}.hd.txt
+
+set cmd=(diff -q ${REF_VOL}.hd.txt ${TST_VOL}.hd.txt );
+echo ""
+echo $cmd
+$cmd
+set diff_status=$status
+if ($diff_status != 0) then
+  echo "$cmd FAILED (exit status=$diff_status)"
+  exit 1
+endif
+
+set REF_VOL = ref_lh.inflated.K
+set TST_VOL = lh.inflated.K
 
 #hd -s 96 -n 550000 < $REF_VOL > ${REF_VOL}.hd.txt
 #hd -s 96 -n 550000 < $TST_VOL > ${TST_VOL}.hd.txt
