Minor tweaks and added CUDA test.

diff --git a/mri_ca_register/test_mri_ca_register b/mri_ca_register/test_mri_ca_register
--- a/mri_ca_register/test_mri_ca_register
+++ b/mri_ca_register/test_mri_ca_register
@@ -8,8 +8,8 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: zkaufman $
-#    $Date: 2016/02/04 20:23:04 $
-#    $Revision: 1.3 $
+#    $Date: 2016/03/11 21:02:55 $
+#    $Revision: 1.4 $
 #
 # Copyright © 2015 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -24,7 +24,7 @@
 # General inquiries: freesurfer@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mri_ca_register,v 1.3 2016/02/04 20:23:04 zkaufman Exp $'
+set VERSION='$Id: test_mri_ca_register,v 1.4 2016/03/11 21:02:55 zkaufman Exp $'
 
 umask 002
 
@@ -42,33 +42,25 @@ cd testdata
 setenv FREESURFER_HOME ../../distribution
 setenv SUBJECTS_DIR ""
 
-# test data was created with 1 thread, but we're testing with 4 because
-# the results should be the same
-setenv OMP_NUM_THREADS 8
+setenv OMP_NUM_THREADS 4
 
 # usage in recon-all: 
-
-set profile=""
-##set profile="valgrind --tool=callgrind"
-set cmd=($profile ../mri_ca_register_cuda \
+set cmd=(../mri_ca_register \
     -nobigventricles \
     -T talairach.lta \
     -align-after \
     -mask brainmask.mgz \
     norm.mgz \
-    $FREESURFER_HOME/average/RB_all_2008-03-26.gca \
+    $FREESURFER_HOME/average/RB_all_2016-02-11.gca \
     talairach.m3z)
 
 echo ""
+echo $cmd
 $cmd
 if ($status != 0) then
   echo "mri_ca_register FAILED"
   exit 1
 endif
-
-echo ""
-echo ""
-echo ""
 
 #
 # compare expected results with actual (produced) results
@@ -91,6 +83,54 @@ if ($diff_status != 0) then
   echo "$cmd FAILED (exit status=$diff_status)"
   exit 1
 endif
+
+if (-e ../mri_ca_register_cuda && -e TEST_CUDA) then
+  
+  # Source cuda setup file which set the path
+  source ../../scripts/cuda_setup
+
+  set cmd=(../mri_ca_register_cuda \
+    -nobigventricles \
+    -T talairach.lta \
+    -align-after \
+    -mask brainmask.mgz \
+    norm.mgz \
+    $FREESURFER_HOME/average/RB_all_2016-02-11.gca \
+    talairach_cuda.m3z)
+
+  echo ""
+  echo $cmd
+  $cmd
+  if ($status != 0) then
+    echo "mri_ca_register_cuda FAILED"
+    exit 1
+  endif
+
+  if (-e talairach_cuda.m3z) then 
+    set OS=`uname -s`
+    if ("$OS" == "Darwin") then
+      set REF_VOL = ref_talairach_osx_cuda.m3z
+    else
+      set REF_VOL = ref_talairach_cuda.m3z
+    endif
+    set TST_VOL = talairach_cuda.m3z
+    set cmd=(../../mri_diff/mri_diff --debug \
+            $REF_VOL $TST_VOL );
+    echo ""
+    echo $cmd
+    #$cmd
+    set diff_status=$status
+    if ($diff_status != 0) then
+      echo "$cmd FAILED (exit status=$diff_status)"
+      exit 1
+    endif
+  endif
+
+endif
+
+echo ""
+echo ""
+echo ""
 
 #
 # cleanup
