FIX: license header update

diff --git a/mri_concatenate_lta/test_mri_concatenate_lta b/mri_concatenate_lta/test_mri_concatenate_lta
--- a/mri_concatenate_lta/test_mri_concatenate_lta
+++ b/mri_concatenate_lta/test_mri_concatenate_lta
@@ -8,23 +8,24 @@
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2009/06/10 18:35:45 $
-#    $Revision: 1.3 $
+#    $Date: 2011/05/02 21:09:56 $
+#    $Revision: 1.4.2.1 $
 #
-# Copyright (C) 2009
-# The General Hospital Corporation (Boston, MA). 
-# All rights reserved.
+# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
-# Distribution, usage and copying of this software is covered under the
-# terms found in the License Agreement file named 'COPYING' found in the
-# FreeSurfer source code root directory, and duplicated here:
-# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
+# Terms and conditions for use, reproduction, distribution and contribution
+# are found in the 'FreeSurfer Software License Agreement' contained
+# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
+#
+# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
+#
+# Reporting: freesurfer@nmr.mgh.harvard.edu
 #
 # General inquiries: freesurfer@nmr.mgh.harvard.edu
 # Bug reports: analysis-bugs@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mri_concatenate_lta,v 1.3 2009/06/10 18:35:45 nicks Exp $'
+set VERSION='$Id: test_mri_concatenate_lta,v 1.4.2.1 2011/05/02 21:09:56 nicks Exp $'
 
 umask 002
 
@@ -34,7 +35,7 @@ umask 002
 gunzip -c testdata.tar.gz | tar xvf -
 
 #
-# run command
+# run command1
 #
 set cmd=(./mri_concatenate_lta -invert1 \
   nick13_to_nickbase.lta \
@@ -44,7 +45,7 @@ echo ""
 echo $cmd
 $cmd
 if ($status != 0) then
-  echo "mri_concatenate_lta FAILED"
+  echo "mri_concatenate_lta test1 FAILED"
   exit 1
 endif
 
@@ -52,6 +53,33 @@ endif
 # look for differences
 #
 set cmd=(diff nickbase_to_nick13.lta reference-nickbase_to_nick13.lta)
+echo ""
+echo $cmd
+$cmd
+set diff_status=$status
+if ($diff_status != 0) then
+  echo "$cmd FAILED (exit status=$diff_status)"
+  exit 1
+endif
+
+#
+# run command2
+#
+set cmd=(./mri_concatenate_lta 002.lta \
+  tp_to_base.lta \
+  002-long.lta)
+echo ""
+echo $cmd
+$cmd
+if ($status != 0) then
+  echo "mri_concatenate_lta test2 FAILED"
+  exit 1
+endif
+
+#
+# look for differences
+#
+set cmd=(diff 002-long.lta reference-002-long.lta)
 echo ""
 echo $cmd
 $cmd
diff --git a/mri_convert/test_mri_convert b/mri_convert/test_mri_convert
--- a/mri_convert/test_mri_convert
+++ b/mri_convert/test_mri_convert
@@ -4,26 +4,28 @@
 # test_mri_convert
 #
 # execute mri_convert and check results against expected results
+# (and test mri_make_uchar while we're at it)
 #
 # Original Author: Nick Schmansky
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2010/03/01 21:06:30 $
-#    $Revision: 1.6 $
+#    $Date: 2011/05/02 21:09:56 $
+#    $Revision: 1.7.2.1 $
 #
-# Copyright (C) 2002-2010
-# The General Hospital Corporation (Boston, MA). 
-# All rights reserved.
+# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
-# Distribution, usage and copying of this software is covered under the
-# terms found in the License Agreement file named 'COPYING' found in the
-# FreeSurfer source code root directory, and duplicated here:
-# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
+# Terms and conditions for use, reproduction, distribution and contribution
+# are found in the 'FreeSurfer Software License Agreement' contained
+# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
+#
+# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
+#
+# Reporting: freesurfer@nmr.mgh.harvard.edu
 #
 # General inquiries: freesurfer@nmr.mgh.harvard.edu
 #
 
-set VERSION='$Id: test_mri_convert,v 1.6 2010/03/01 21:06:30 nicks Exp $'
+set VERSION='$Id: test_mri_convert,v 1.7.2.1 2011/05/02 21:09:56 nicks Exp $'
 
 umask 002
 
@@ -74,6 +76,24 @@ if ($status != 0) then
   exit 1
 endif
 
+
+
+# mri_make_uchar test
+# data (nu.mgz) is from ADNI subj 0030_m12, which was problematic because
+# mri_nu_correct.mni float thing would mess with the histogramming stuff
+# in mri_normalize.  mri_make_uchar was introduced to fix that, so this is
+# a regression test of sorts.
+set cmd=(../mri_make_uchar nu.mgz talairach.xfm nuuc.mgz)
+echo ""
+echo $cmd
+$cmd
+if ($status != 0) then
+  echo "mri_make_uchar FAILED"
+  exit 1
+endif
+
+
+
 echo ""
 echo ""
 echo ""
@@ -82,13 +102,16 @@ echo ""
 # compare expected results with actual (produced) results
 #
 
-set TEST_FILES=( orig.mgz dicom.mgz nifti.mgz analyze.mgz )
+set TEST_FILES=( orig.mgz dicom.mgz nifti.mgz analyze.mgz nuuc.mgz )
 foreach tstvol ($TEST_FILES)
   # now compare expected with observed data
   set REF_VOL  = freesurfer.mgz
   if ( "x$tstvol" == "xorig.mgz" ) then
     set REF_VOL = ref_orig.mgz
     if ( "`uname -p`" == "powerpc" ) set REF_VOL = ref_powerpc_orig.mgz
+  endif
+  if ( "x$tstvol" == "xnuuc.mgz" ) then
+    set REF_VOL = nuuc_ref.mgz
   endif
   set TST_VOL  = $tstvol
   set DIFF_VOL = $PWD/mri_diff-$tstvol
